### ISSUE TITLE
Banking app crash on start

### ISSUE THREAD

**Issue by HupHum** [microg/android_packages_apps_GmsCore#1043]
java.lang.RuntimeException: Unable to start activity ComponentInfo{ua.privatbank.ap24/ua.privatbank.ap24v6.MainActivity}: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.d0.h.a@b4f5fe5, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6394)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.d0.h.a@b4f5fe5, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
	at okhttp3.d0.h.f.a()
	at okhttp3.w$b.a()
	at ua.privatbank.core.network.OkhttpNetworkConfiguration.a()
	at ua.privatbank.core.network.OkhttpNetworkConfiguration.a()
	at ua.privatbank.core.network.OkhttpNetworkConfiguration.a()
	at ua.privatbank.ap24v6.repositories.CurrencyExchangeRepositoryImpl.a()
	at ua.privatbank.ap24v6.repositories.CurrencyExchangeRepositoryImpl.i()
	at ua.privatbank.ap24v6.repositories.CurrencyExchangeRepositoryImpl.g()
	at ua.privatbank.ap24v6.repositories.CurrencyExchangeRepositoryImpl.d()
	at ua.privatbank.ap24v6.repositories.CurrencyExchangeRepositoryImpl.<init>()
	at ua.privatbank.ap24v6.w.a.a.a$b$a.invoke()
	at ua.privatbank.ap24v6.w.a.a.a$b$a.invoke()
	at l.a.c.o.a()
	at l.a.c.e.c()
	at ua.privatbank.ap24v6.repositories.f$a.invoke()
	at kotlin.l.getValue()
	at ua.privatbank.ap24v6.repositories.f.f()
	at ua.privatbank.ap24v6.services.home.HomeViewModel.<init>()
	at java.lang.Class.newInstance(Native Method)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create()
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create()
	at androidx.lifecycle.ViewModelProvider.get()
	at androidx.lifecycle.ViewModelProvider.get()
	at ua.privatbank.core.base.d.B0()
	at ua.privatbank.core.base.d.a()
	at ua.privatbank.core.base.d.onCreate()
	at androidx.fragment.app.Fragment.performCreate()
	at androidx.fragment.app.i.a()
	at androidx.fragment.app.n.a()
	at androidx.fragment.app.n.a()
	at androidx.fragment.app.n.a()
	at androidx.fragment.app.i.b()
	at androidx.fragment.app.i.c()
	at androidx.fragment.app.i.u()
	at androidx.fragment.app.i.e()
	at androidx.fragment.app.i.j()
	at androidx.fragment.app.Fragment.performActivityCreated()
	at androidx.fragment.app.i.a()
	at androidx.fragment.app.i.m()
	at androidx.fragment.app.i.a()
	at androidx.fragment.app.a.f()
	at androidx.fragment.app.i.a()
	at androidx.fragment.app.i.b()
	at androidx.fragment.app.i.c()
	at androidx.fragment.app.i.u()
	at androidx.fragment.app.i.e()
	at androidx.fragment.app.i.j()
	at androidx.fragment.app.e.a()
	at androidx.fragment.app.c.onStart()
	at androidx.appcompat.app.c.onStart()
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6891)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2721)
	... 10 more

Hello.
Half of year used app Privat24 with ver. MicroG 0.2.8.... It work good. 
In early March updated the app Privat24, so it stopped starting.
Updated the app "microG SerCore" to Ver. 0.2.10..., but it didn't give positive results.
As a result if searches, I used the prompt and rolled back to the ver. 0.2.6. App Privat24 work restored.
Will there be more complete support for the functionality of banking apps in new versions microG?

**Comment by michalens** [comment]
Same here. 
This app worked fine on normal LineageOS (no Gapps)

**Comment by token0** [comment]
@HupHum 
Do you have magisk or xposed installed?  Or both?

Try this patched version https://4pda.ru/forum/index.php?showtopic=226055&view=findpost&p=93331275

Though QR code recognition does not work for me.

**Comment by jesse-git** [comment]
Looks like same as #1241
