### ISSUE TITLE
fr.banquepopulaire.cyberplus auth crash when using GmsCore

### ISSUE THREAD

**Issue by loupianche** [microg/android_packages_apps_GmsCore#1045]
```
4-16 16:58:33.410  4657  4657 W OAuth2Manager: no default authorization set.
04-16 16:58:33.421  4753  4753 W A4SService: Service is already initialized
04-16 16:58:33.422  4657  4657 E         : 💣 Error ! ERROR-ValidationUnit(uuid=a00c36cb-27b1-47c6-801f-0e04f1722270, factors=[PasswordFactor(id=e11fe150-17e1-4c85-99be-414ad287d5de, keyboardConfig=null, scope=CTX_DACS_NUM, minSize=1, maxSize=null, password=null)])
04-16 16:58:33.422  4657  4657 E         : java.lang.IllegalStateException: Unable to extract the trust manager on AndroidPlatform, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
04-16 16:58:33.422  4657  4657 E         : 	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(SourceFile:182)
04-16 16:58:33.422  4657  4657 E         : 	at okhttp3.OkHttpClient$Builder.sslSocketFactory(SourceFile:768)
04-16 16:58:33.422  4657  4657 E         : 	at bgj.a(SourceFile:141)
04-16 16:58:33.422  4657  4657 E         : 	at akl.a(SourceFile:272)
04-16 16:58:33.422  4657  4657 E         : 	at alg.a(SourceFile:33)
04-16 16:58:33.422  4657  4657 E         : 	at alg.get(SourceFile:11)
04-16 16:58:33.422  4657  4657 E         : 	at beo.get(SourceFile:47)
04-16 16:58:33.422  4657  4657 E         : 	at alb.a(SourceFile:33)
04-16 16:58:33.422  4657  4657 E         : 	at alb.get(SourceFile:11)
04-16 16:58:33.422  4657  4657 E         : 	at beo.get(SourceFile:47)
04-16 16:58:33.422  4657  4657 E         : 	at fr.banquepopulaire.afi.managers.impl.l.a(SourceFile:43)
04-16 16:58:33.422  4657  4657 E         : 	at fr.banquepopulaire.afi.managers.impl.l.get(SourceFile:9)
04-16 16:58:33.422  4657  4657 E         : 	at beo.get(SourceFile:47)
04-16 16:58:33.422  4657  4657 E         : 	at com.ibp.androidapp.cloudcard.ac.a(SourceFile:27)
04-16 16:58:33.422  4657  4657 E         : 	at com.ibp.androidapp.cloudcard.ac.get(SourceFile:10)
04-16 16:58:33.422  4657  4657 E         : 	at ahm.d(SourceFile:3449)
04-16 16:58:33.422  4657  4657 E         : 	at aol$ac.a(SourceFile:823)
04-16 16:58:33.422  4657  4657 E         : 	at aol$ac.apply(SourceFile:100)
04-16 16:58:33.422  4657  4657 E         : 	at cmz$a.a_(SourceFile:102)
04-16 16:58:33.422  4657  4657 E         : 	at cpy.b(SourceFile:56)
04-16 16:58:33.422  4657  4657 E         : 	at cje.a(SourceFile:3603)
04-16 16:58:33.422  4657  4657 E         : 	at cmz.a(SourceFile:49)
04-16 16:58:33.422  4657  4657 E         : 	at ciy.c(SourceFile:12267)
04-16 16:58:33.422  4657  4657 E         : 	at cng$a.d(SourceFile:475)
04-16 16:58:33.422  4657  4657 E         : 	at cng$a$a.c(SourceFile:527)
04-16 16:58:33.422  4657  4657 E         : 	at clx$a.c(SourceFile:52)
04-16 16:58:33.422  4657  4657 E         : 	at cln$a.a_(SourceFile:51)
04-16 16:58:33.422  4657  4657 E         : 	at cps$a.a_(SourceFile:60)
04-16 16:58:33.422  4657  4657 E         : 	at cqb$a.run(SourceFile:81)
04-16 16:58:33.422  4657  4657 E         : 	at cjl$b.run(SourceFile:124)
04-16 16:58:33.422  4657  4657 E         : 	at android.os.Handler.handleCallback(Handler.java:883)
04-16 16:58:33.422  4657  4657 E         : 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-16 16:58:33.422  4657  4657 E         : 	at android.os.Looper.loop(Looper.java:214)
04-16 16:58:33.422  4657  4657 E         : 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-16 16:58:33.422  4657  4657 E         : 	at java.lang.reflect.Method.invoke(Native Method)
04-16 16:58:33.422  4657  4657 E         : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-16 16:58:33.422  4657  4657 E         : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-16 16:58:33.423  4657  4657 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
```

**Comment by farfromrefug** [comment]
@loupianche i cant get banque pop to work her either.
Though i am not sure if this error is due to microg:
```
04-16 16:58:33.422  4657  4657 E         : java.lang.IllegalStateException: Unable to extract the trust manager on AndroidPlatform, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
```
can you confirm it works with gapps?
Also does it crash on start or when you try to login?
For me it is when i try to login. It always fails telling me "service indisponible".

**Comment by loupianche** [comment]
Was working on stock CRdroid ROM. Failed after MicroG installation.

My guess is that on stock ROM, app detects missing API for fingerprint auth and don't crash (and don't ask for fingerprint)

With MicroG, app tries to get fingerprint auth but crash.

Was working one year ago with MicroG.

With gapps, it just asks to configure fingerprint auth just after first password connexion.

**Comment by bellegarde-c** [comment]
Does not crash since last app update.

**Comment by farfromrefug** [comment]
I still cant connect. It always brings me back to the main screen

**Comment by bellegarde-c** [comment]
Using Magisk Hide, it works, with Doidguard crashing but works.

**Comment by farfromrefug** [comment]
Indeed magisk hide did the trick ! Thanks ...

**Comment by bellegarde-c** [comment]
No idea why, because without, I got this error:
05-27 14:28:44.038  7922  8003 W FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
05-27 14:28:44.040  7922  8059 W FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.

**Comment by JulTux** [comment]
Hi
"I still cant connect. It always brings me back to the main screen".
Same issue here, with AEX ans microg. For me, Magisk hide doesn't the trick, crash again...
Any new information about this ?
Thanks

**Comment by farfromrefug** [comment]
@JulTux Funny just got the issue while reinstalling the app. Had your issue. I enabled magisk hide and it worked !
What s your magisk version?

**Comment by JulTux** [comment]
Thanks for tour reply
> What s your magisk version?

Up to date:
Magisk 20.4
Magisk Manager 7.5.1

What are your Magisk's settings pls ?
