### ISSUE TITLE
jelbi crashes with nonpublic method in PolylineImplementation

### ISSUE THREAD

**Issue by thrillfall** [microg/android_packages_apps_GmsCore#1087]
app: com.trafi.whitelabel.bvg (v3.13.0)
microg: 0.2.10.19420-dirty-vtm (fcm registryfix cherry-picked)

the app crashes after a few seconds (every time) before any map and/or markers are displayed

trace
```
07-14 13:53:03.594  6151  7167 D GmsMeasureSvcImpl: onTransact [unknown]: 6, android.os.Parcel@6f19100, 16
07-14 13:53:03.682 21912 22038 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
07-14 13:53:03.690  6151  7167 D GmsClearcutLogSvcImpl: log: LogEventParcelable[1, PlayLoggerContext[1, package=com.trafi.whitelabel.bvg, packageVersionCode=3130450, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=false, logSourceName=FIREPERF, isAnonymous=true, qosTier=0], LogEventBytes: CMWfr+m0LjKPAgpvCicxOjUxNjQ1NDg5NjQyMTphbmRyb2lkOmI1ZWU0MDNkOWQyYTg3YTcSFmY4d19HdFVnU05PbVVtd1I4bEdSYjkaKgoYY29tLnRyYWZpLndoaXRlbGFiZWwuYnZnEgYxOS4wLjcaBjMuMTMuMCgBGpsBCj9odHRwczovL3doaXRlbGFiZWwtYXBwLWFwaS13bC5idmcudHJhZmkuY29tL3YxL2hvbWUvbWFwL29iamVjdHMQAxhdKMgBMh9hcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04OODk6ZfXzOoCUMCnpAFqIgogM2M5YTU5ODE5ZTg3NDhiNmI0NDRkNjk4OWUzMDM2MDl4wHCIAdOB5mo=, AddPhenotypeExperimentTokens: true]
07-14 13:53:03.802   741 22115 E ResolverController: No valid NAT64 prefix (116, <unspecified>/0)
07-14 13:53:03.862 21912 21912 D SafeParcel: Unknown field num 8 in com.google.android.gms.maps.model.PolylineOptions, skipping.
07-14 13:53:03.862 21912 21912 D SafeParcel: Unknown field num 9 in com.google.android.gms.maps.model.PolylineOptions, skipping.
07-14 13:53:03.862 21912 21912 D SafeParcel: Unknown field num 10 in com.google.android.gms.maps.model.PolylineOptions, skipping.
07-14 13:53:03.862 21912 21912 D SafeParcel: Unknown field num 11 in com.google.android.gms.maps.model.PolylineOptions, skipping.
07-14 13:53:03.865 21912 21912 D AndroidRuntime: Shutting down VM
07-14 13:53:03.866 21912 21912 E AndroidRuntime: FATAL EXCEPTION: main
07-14 13:53:03.866 21912 21912 E AndroidRuntime: Process: com.trafi.whitelabel.bvg, PID: 21912
07-14 13:53:03.866 21912 21912 E AndroidRuntime: java.lang.IllegalAccessError: Method 'java.lang.Object java.lang.Object.clone()' implementing interface method 'java.lang.Object b.c.a.b.d.clone()' is not public (declaration of 'b.c.a.b.c0.c' appears in /system/priv-app/GmsCore/GmsCore.apk)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at e.b.d.h.d.c.<clinit>(Unknown Source:0)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at org.microg.gms.maps.vtm.markup.PolylineImpl.getDrawable(Unknown Source:61)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at org.microg.gms.maps.vtm.BackendMap.updateDrawableLayer(Unknown Source:34)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at org.microg.gms.maps.vtm.BackendMap.add(Unknown Source:21)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at org.microg.gms.maps.vtm.GoogleMapImpl.addPolyline(Unknown Source:11)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(Unknown Source:987)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at org.microg.gms.maps.vtm.GoogleMapImpl.onTransact(Unknown Source:0)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:914)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.google.android.gms.internal.maps.zza.zza(SourceFile:4)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.google.android.gms.maps.internal.zzg.addPolyline(SourceFile:3)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.google.android.gms.maps.GoogleMap.addPolyline(SourceFile:1)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.google.GoogleMapProvider.updateAnnotations(SourceFile:15)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.MapView.updateAnnotations(SourceFile:1)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.AnnotationManager.d(SourceFile:28)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.AnnotationManager.access$mergeNewAnnotationsWithIcons(SourceFile:1)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.AnnotationManager$a.a(SourceFile:1)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.AnnotationManager$a.invoke(SourceFile:1)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.trafi.map.AnnotationIconFactory$a$a.run(SourceFile:1)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-14 13:53:03.866 21912 21912 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
07-14 13:53:04.062 21912 22037 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
07-14 13:53:04.071  6151  7167 D GmsClearcutLogSvcImpl: log: LogEventParcelable[1, PlayLoggerContext[1, package=com.trafi.whitelabel.bvg, packageVersionCode=3130450, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=false, logSourceName=FIREPERF, isAnonymous=true, qosTier=0], LogEventBytes: CMSir+m0LjKGAgpvCicxOjUxNjQ1NDg5NjQyMTphbmRyb2lkOmI1ZWU0MDNkOWQyYTg3YTcSFmY4d19HdFVnU05PbVVtd1I4bEdSYjkaKgoYY29tLnRyYWZpLndoaXRlbGFiZWwuYnZnEgYxOS4wLjcaBjMuMTMuMCgBGpIBCjlodHRwczovL3doaXRlbGFiZWwtYXBwLWFwaS13bC5idmcudHJhZmkuY29tL3YxL2FwcC9jb25maWcQASjIATIfYXBwbGljYXRpb24vanNvbjsgY2hhcnNldD11dGYtODjIiYeZ18zqAlC+kh5qIgogM2M5YTU5ODE5ZTg3NDhiNmI0NDRkNjk4OWUzMDM2MDl4wHCIAdKE5mo=, AddPhenotypeExperimentTokens: true]

```

**Comment by mar-v-in** [comment]
Does this still happen with 0.2.11-202414 release?

**Comment by thrillfall** [comment]
your latest release fixed that issue! Thank you so much
