### ISSUE TITLE
Google Earth crashes at start-up due to failed FCM registration

### ISSUE THREAD

**Issue by Fs00** [microg/android_packages_apps_GmsCore#1113]
Using the latest version of MicroG (0.2.11.202414), Google Earth crashes at the loading screen. The logcat for the crash is the following:

```
08-02 19:23:04.180 28222 28279 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-02 19:23:04.180 28222 28279 E AndroidRuntime: Process: com.google.earth, PID: 28222
08-02 19:23:04.180 28222 28279 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1468)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at android.app.ContextImpl.bindService(ContextImpl.java:1422)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at dvy.a(PG:17)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at dvy.a(PG:3)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at gfx.a(PG:14)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at ggd.a(PG:7)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at gfk.run(Unknown Source)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at dwn.run(PG:2)
08-02 19:23:04.180 28222 28279 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
```

It seems to be the same error as #918.

**Comment by Fs00** [comment]
I did some research and the cause of the issue seems to be [this line of the play-services-core manifest](https://github.com/microg/android_packages_apps_GmsCore/blob/ab69fa1ee0721cd22570070d14b939b9206c67ed/play-services-core/src/main/AndroidManifest.xml#L216).
MicroG requires apps to request `com.google.android.c2dm.permission.RECEIVE` permission in their manifest in order to register to GCM/FCM, but it seems that it is not required anymore for FCM (the official FCM guide [doesn't say anything about that permission](https://firebase.google.com/docs/cloud-messaging/android/client?hl=en#manifest), and furthermore [this unofficial migration guide from GCM to FCM](https://developer.ibm.com/customer-engagement/tutorials/migrating-google-cloud-messaging-gcm-firebase-cloud-messaging-fcm/) advises to remove such permission from the manifest.)
In fact, Google Earth doesn't request that permission in its manifest.
