### ISSUE TITLE
Corona-Warn-App problems with MicroG (Exposure Notification API)

### ISSUE THREAD

**Issue by Romern** [microg/android_packages_apps_GmsCore#1115]
When activating the Expore Logging in the Corona-Warn-App, microG crashes:
```
08-03 21:33:58.744 13117 13117 E AndroidRuntime: FATAL EXCEPTION: main
08-03 21:33:58.744 13117 13117 E AndroidRuntime: Process: com.google.android.gms, PID: 13117
08-03 21:33:58.744 13117 13117 E AndroidRuntime: java.lang.ClassCastException: org.microg.gms.nearby.exposurenotification.ExposureDatabase cannot be cast to java.lang.AutoCloseable
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$start$1.invoke(ExposureNotificationServiceImpl.kt:62)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$start$1.invoke(ExposureNotificationServiceImpl.kt:29)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$confirm$1.onReceiveResult(ExposureNotificationServiceImpl.kt:38)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-03 21:33:58.744 13117 13117 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
The app stays open, but after microG starts up again, I get the notification to Turn off the Exposure Notifiactions, and microG crashes again after clicking both options and the app closes (without error).  
I somehow got into the app anyway after tapping alot of buttons, but while downloading the exposure data, microG crashes again. The error is always the same as in the logcat above.  

I built microG at commit 5f70d943.  
Corona-Warn-App is at version 1.1.1.34.  
I run LineageOS 15.1 (Build date 25.06) on a Moto G4 Plus.

EDIT:  
> Note: the AutoCloseable interface was first added in the Build.VERSION_CODES.Q release.

From https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper

EDIT²:
After manually adding the use function (from https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jdk7/src/kotlin/AutoCloseable.kt ), I now get this error while downloading the exporure data inside the app:
```
08-04 00:26:18.764 10986 12728 W ExposureNotification: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.google.android.gms/databases/exposure.db
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1516)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at org.microg.gms.nearby.exposurenotification.ExposureDatabase.storeDiagnosisKey(ExposureDatabase.kt:127)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl.storeDiagnosisKeyExport(ExposureNotificationServiceImpl.kt:134)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl.access$storeDiagnosisKeyExport(ExposureNotificationServiceImpl.kt:29)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1.run(ExposureNotificationServiceImpl.kt:163)
08-04 00:26:18.764 10986 12728 W ExposureNotification:  at java.lang.Thread.run(Thread.java:764)
```
This only happens after a while, and the startup of the app functions properly, except the window appearing which asks for exposure api to be turned off again, which can be ignored.

**Comment by Romern** [comment]
Now on commit https://github.com/microg/android_packages_apps_GmsCore/commit/ee176c42cc8390d0c2116382f633cbc129f7fbce , but database errors still occur after a while, during the downloading and checking inside the Corona-Warn app.
```
08-05 00:38:34.021  9820  9820 D AndroidRuntime: Shutting down VM
08-05 00:38:34.022  9820  9820 E AndroidRuntime: FATAL EXCEPTION: main
08-05 00:38:34.022  9820  9820 E AndroidRuntime: Process: com.google.android.gms, PID: 9820
08-05 00:38:34.022  9820  9820 E AndroidRuntime: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at org.microg.gms.nearby.exposurenotification.ExposureDatabase.noteAdvertisement(ExposureDatabase.kt:80)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at org.microg.gms.nearby.exposurenotification.ExposureDatabase.noteAdvertisement$default(ExposureDatabase.kt:71)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at org.microg.gms.nearby.exposurenotification.ScannerService$callback$1.onScanResult(ScannerService.kt:23)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:478)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-05 00:38:34.022  9820  9820 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Romern** [comment]
Nice, the newest commit fixed the crashes!

**Comment by mar-v-in** [comment]
Great that it worked. Please let me know should you notice any issues while using CWA (except for the TODOs mentioned in #1057).

**Comment by celle1234** [comment]
With the new CWA (1.2.0) the app does not work. It says, that I need to update the Google Play Services.

**Comment by mar-v-in** [comment]
@celle1234 It should work again with latest commit df5ad9f3de16d33c0bc3c88713c8b167c5aba223

**Comment by Romern** [comment]
Can confirm that the latest commit fixed it.

**Comment by Romern** [comment]
The main window shows "Exposure logginw as active for 0 of the past 14 days" for a few days now, I think something broke, as before the update it counted the days. This could potentially have an impact on the risk calculation. The only relevant logcat lines are these:
```
08-15 21:01:13.704  3936  7158 I ActivityManager: START u0 {cmp=de.rki.coronawarnapp/.ui.main.MainActivity} from uid 10192
08-15 21:01:13.841  3936  5772 E LocSvc_eng: E/Calling gnss_sv_status_cb
08-15 21:01:14.131 30352 30367 D ChimeraServiceProvider: serviceIntentCall: com.google.android.gms.nearby.exposurenotification.START -> Intent { act=com.google.android.gms.nearby.exposurenotification.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.nearby.exposurenotification.ExposureNotificationService }
08-15 21:01:14.175 30352 30352 D ExposureNotification: onBind: Intent { act=com.google.android.gms.nearby.exposurenotification.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.nearby.exposurenotification.ExposureNotificationService }
08-15 21:01:14.416 30352 31220 D SafeParcel: Unknown field id 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 21:01:14.416 30352 31220 D SafeParcel: Unknown field id 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 21:01:14.416 30352 31220 D SafeParcel: Unknown field id 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 21:01:14.417 30352 31220 D SafeParcel: Unknown field id 13 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 21:01:14.417 30352 31220 D ExposureNotification: bound by: GetServiceRequest{serviceId=NEARBY_EXPOSURE, gmsVersion=12451000, packageName='de.rki.coronawarnapp', extras=Bundle[{}]}
08-15 21:01:14.425 30352 31220 D ExposureNotification: handleServiceRequest: de.rki.coronawarnapp
08-15 21:01:14.457  3936  4192 I ActivityManager: Displayed de.rki.coronawarnapp/.ui.main.MainActivity: +712ms
```

**Comment by mar-v-in** [comment]
I can confirm that day counting in CWA is apparently not working as expected. I don't think it affects risk calculation though, as that happens in microG.

The day counting is a feature completely implemented inside CWA and not a feature of EN API. I'm not sure what it's supposed to actually display:
A) Number of days in last 14 days where EN was enabled at all
B) Number of days in last 14 days where EN was disabled at all
C) Total time EN was enabled in last 14 days, rounded to full days.
For A, it would show 14/14 days as soon as it's enabled a minute every day, for B it would show 0/14 if you put your phone in airplane mode overnight, for C it would not reach more than 10/14 if you put your phone to airplane mode overnight. None of those three really makes sense. So either it's not actually measuring affective EN enabled time, it's doing something completely different, or it's pretty useless.

**Comment by celle1234** [comment]
For me it seems to work. Did you see the Exposure Notifications in microg?

**Comment by Romern** [comment]
@celle1234 Which version of microg and cwa are you using?

**Comment by celle1234** [comment]
I use version 1.2.1 of the cwa and master branch from 11.08., which is head at the moment. 
First I had trouble to upgrade from prebuild binaries to the build of myself. The problem was, that I get no exposure notifications in microg itself. But after I fixed this (delete old gms from /data/data/...) it works.location has to be enabled and microg needs to have the background location permission.

**Comment by Romern** [comment]
And the app displays the amount of days correctly? That's strange.

**Comment by celle1234** [comment]
Yes I am on day 6 of 14. I reinstalled the CWA after I upgraded microg to the installed version, so I have a clean start.

**Comment by Romern** [comment]
The app now times out while checking for the keys:
```
08-24 19:08:53.886  3806 14082 D ExposureNotification: de.rki.coronawarnapp/9c5427cf-abae-4676-9582-c846f0f10def provided 0 keys
08-24 19:08:54.164 13054 13054 W System.err: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 60000 ms
08-24 19:08:54.164 13054 13054 W System.err:    at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:2)
08-24 19:08:54.164 13054 13054 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
08-24 19:08:54.164 13054 13054 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 19:08:54.164 13054 13054 W System.err:    at android.os.Looper.loop(Looper.java:164)
08-24 19:08:54.164 13054 13054 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
08-24 19:08:54.164 13054 13054 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
08-24 19:08:54.164 13054 13054 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-24 19:08:54.165 13054 13054 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
Afterwards this error occurs:
"CAUSE: 9002 Something went wrong. Job was cancelled":
```
08-24 19:10:59.911  3806 14209 D ExposureNotification: de.rki.coronawarnapp/2001cce8-2465-4ce9-970a-494cac354ccd provided 0 keys
08-24 19:11:00.046 13054 13054 W System.err: de.rki.coronawarnapp.exception.RollbackException: An error occurred during rollback of transaction 6ceb0813-ce34-4626-9c25-97319b8b00ab, State API_SUBMISSION
08-24 19:11:00.047 13054 13054 W System.err:    at de.rki.coronawarnapp.transaction.Transaction.handleRollbackError(Transaction.kt:4)
08-24 19:11:00.047 13054 13054 W System.err:    at de.rki.coronawarnapp.transaction.RetrieveDiagnosisKeysTransaction.rollback(RetrieveDiagnosisKeysTransaction.kt:16)
08-24 19:11:00.047 13054 13054 W System.err:    at de.rki.coronawarnapp.transaction.Transaction.handleTransactionError$suspendImpl(Transaction.kt:5)
08-24 19:11:00.047 13054 13054 W System.err:    at de.rki.coronawarnapp.transaction.Transaction.lockAndExecute(Transaction.kt:32)
08-24 19:11:00.047 13054 13054 W System.err:    at de.rki.coronawarnapp.transaction.Transaction$lockAndExecute$2.invokeSuspend(Unknown Source:13)
08-24 19:11:00.047 13054 13054 W System.err:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
08-24 19:11:00.047 13054 13054 W System.err:    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
08-24 19:11:00.047 13054 13054 W System.err:    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
08-24 19:11:00.047 13054 13054 W System.err:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:8)
08-24 19:11:00.047 13054 13054 W System.err:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
08-24 19:11:00.047 13054 13054 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
08-24 19:11:00.047 13054 13054 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 19:11:00.047 13054 13054 W System.err:    at android.os.Looper.loop(Looper.java:164)
08-24 19:11:00.047 13054 13054 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
08-24 19:11:00.047 13054 13054 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
08-24 19:11:00.047 13054 13054 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-24 19:11:00.047 13054 13054 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-24 19:11:00.047 13054 13054 W System.err: Caused by: java.lang.IllegalStateException: the state before the transaction state could not be restored.
08-24 19:11:00.047 13054 13054 W System.err:    ... 17 more
08-24 19:11:00.048 13054 13054 W System.err: Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@b88075e
08-24 19:11:00.049 13054 13054 W System.err: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@b88075e

```
This could be because the database is getting pretty large:
```
973M -rw-rw---- 1 u0_a40 u0_a40 1.8G 2020-08-24 19:14 /data/data/com.google.android.gms/databases/exposure.db
```
And this is with 4455 IDs collected in 5 days.

**Comment by celle1234** [comment]
My database is only 109mb big with 3700 IDs. In the advertisment table are round about 4k rows. The diagnosis table has 600k rows and tek_check 70k rows.

**Comment by Romern** [comment]
Ok, my diagnosis table has 11.114.702 entries.

**Comment by mar-v-in** [comment]
Deletion of historic data is not implemented yet, as mentioned in https://github.com/microg/android_packages_apps_GmsCore/issues/1057#issuecomment-668276901.
Probably once the database gets large, this is becoming a problem. I'm currently working on exactly that, so hopefully will see solution today.

**Comment by mar-v-in** [comment]
Just so you understand a bit more what's happening here:
- `tek_check` contains the keys that have been provided by CWA as diagnosed positive
- `diagnosis` contains the information associated with each key in each single diagnosis check run. CWA does this every day and processes something like 40k-50k keys on each run, so this table gets about 50k new entries per day.
- `advertisement` is the table containing your collected IDs
- `Processed 0 keys` is not an issue. This happens when CWA presents keys to the service it already knows about. I'll change the log to specifically say `0 new keys` to avoid confusion.
- UNIQUE constraint errors can happen when the CWA is running two diagnosis checks in parallel. This should not have any impact on the results though.
