### ISSUE TITLE
Maps.me crash when opening

### ISSUE THREAD

**Issue by Pollockwar** [microg/android_packages_apps_GmsCore#1135]
Maps.me crash when opening.
I'm using latest Crdroid (Android 10) on a OnePlus 5T.
Also, Google Maps can find my location only when I previously run the app "GPS Locker".

Log :
time: 1596715966071 msg: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission. stacktrace: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission. at android.os.Parcel.createException(Parcel.java:2071) at android.os.Parcel.readException(Parcel.java:2039) at android.os.Parcel.readException(Parcel.java:1987) at com.google.android.gms.internal.location.zza.transactAndReadExceptionReturnVoid(Unknown Source:10) at com.google.android.gms.internal.location.zzap.zza(Unknown Source:9) at com.google.android.gms.internal.location.zzas.zza(Unknown Source:43) at com.google.android.gms.internal.location.zzaz.zza(Unknown Source:5) at com.google.android.gms.internal.location.zzr.doExecute(Unknown Source:25) at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.run(Unknown Source:19) at com.google.android.gms.common.api.internal.zaah.execute(Unknown Source:20) at com.google.android.gms.common.api.internal.zabe.execute(Unknown Source:23) at com.google.android.gms.common.api.internal.zaaw.execute(Unknown Source:74) at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source:14) at com.mapswithme.maps.location.GoogleFusedLocationProvider.requestLocationUpdates(GoogleFusedLocationProvider.java:134) at com.mapswithme.maps.location.GoogleFusedLocationProvider.access$200(GoogleFusedLocationProvider.java:19) at com.mapswithme.maps.location.GoogleFusedLocationProvider$1.onResult(GoogleFusedLocationProvider.java:114) at com.mapswithme.maps.location.GoogleFusedLocationProvider$1.onResult(GoogleFusedLocationProvider.java:91) at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(Unknown Source:10) at android.os.Handler.dispatchMessage(Handler.java:107) at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:8) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by drrossum** [comment]
This was reported before.  Check #1100

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version.
Please retest and report back.
