### ISSUE TITLE
DownDog app crashes on startup

### ISSUE THREAD

**Issue by anjanoelle** [microg/android_packages_apps_GmsCore#1159]
The app DownDog used to work in version 0.2.19420 of MicroG, but doesn't work anymore since 0.2.11.202414.

I'm running lineage-17.1-20200821-microG-starlte, but also tried it on /e/ with Android 8.1 and only updating microg from 0.2.19420 to 0.2.11.202414. The app works fine on 0.2.19420 but doesn't work anymore after the update to 0.2.11.202414.

Steps to reproduce:

1. Download DownDog
2. Try to start the app - It will freeze and shortly after close.

Here is the logcat from startint the app up to the first Java error it produces:

> 09-06 11:34:19.997 12052 12092 I FA      :   adb shell setprop debug.firebase.analytics.app com.downdogapp
09-06 11:34:19.998 12052 12100 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-06 11:34:20.002 12052 12115 W ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
09-06 11:34:20.016  5939  5939 V AvrcpMediaPlayerList: onActiveSessionsChanged: number of controllers: 1
09-06 11:34:20.016 12052 12102 W ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
09-06 11:34:20.016  5939  5939 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.mozilla.fennec_fdroid
09-06 11:34:20.016  5939  5939 D AvrcpMediaPlayerList: Already have a controller for the player: org.mozilla.fennec_fdroid, updating instead
09-06 11:34:20.018  5939  5939 V AvrcpMediaPlayerList: onActiveSessionsChanged: number of controllers: 2
09-06 11:34:20.018  5939  5939 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: org.mozilla.fennec_fdroid
09-06 11:34:20.018  5939  5939 D AvrcpMediaPlayerList: Already have a controller for the player: org.mozilla.fennec_fdroid, updating instead
09-06 11:34:20.019  5939  5939 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: com.downdogapp
09-06 11:34:20.019  5939  5939 D AvrcpMediaPlayerList: Already have a controller for the player: com.downdogapp, updating instead
09-06 11:34:20.021  7713  7713 D GmsMeasureBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
09-06 11:34:20.027 12052 12127 W ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
09-06 11:34:20.034 12052 12118 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
09-06 11:34:20.034 12052 12052 V MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-06 11:34:20.036 12052 12052 I MediaRouter: Found default route: MediaRouter.RouteInfo{ uniqueId=android/d.m.c.t:DEFAULT_ROUTE, name=Phone, description=null, iconUri=null, enabled=true, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=1, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
09-06 11:34:20.036 12052 12052 I MediaRouter: Unselecting the current route because it is no longer selectable: null
09-06 11:34:20.037 12052 12052 W DynamiteModule: IDynamite loader version < 2, falling back to getModuleVersion2
09-06 11:34:20.037 12052 12052 D GmsDynamiteLoaderImpl: returning temp fix module version for com.google.android.gms.cast.framework.dynamite. Cast API wil not be functional!
09-06 11:34:20.037 12052 12052 I DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:1
09-06 11:34:20.037 12052 12052 I DynamiteModule: Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 1
09-06 11:34:20.037 12052 12052 W DynamiteModule: Dynamite loader version < 2, falling back to createModuleContext
09-06 11:34:20.037 12052 12052 D GmsDynamiteLoaderImpl: unimplemented Method: createModuleContext for com.google.android.gms.cast.framework.dynamite at version 1, returning gms context
09-06 11:34:20.040 12052 12052 D SafeParcel: Unknown field id 4 in com.google.android.gms.cast.LaunchOptions, skipping.
09-06 11:34:20.041 12052 12052 W SafeParcel: Error reading field: 2 in com.google.android.gms.cast.framework.media.NotificationOptions, skipping.
09-06 11:34:20.041 12052 12052 W SafeParcel: java.lang.RuntimeException: Parcel android.os.Parcel@28542a8: Unmarshalling unknown type code 60 at offset 484
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.os.Parcel.readValue(Parcel.java:2945)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.os.Parcel.readListInternal(Parcel.java:3307)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.os.Parcel.readArrayList(Parcel.java:2450)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelReader.readList(SafeParcelReader.java:139)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.readField(SafeParcelUtil.java:316)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.readObject(SafeParcelUtil.java:95)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.createObject(SafeParcelUtil.java:37)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(AutoSafeParcelable.java:33)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(AutoSafeParcelable.java:23)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelReader.readParcelable(SafeParcelReader.java:129)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.readField(SafeParcelUtil.java:290)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.readObject(SafeParcelUtil.java:95)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.createObject(SafeParcelUtil.java:37)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(AutoSafeParcelable.java:33)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(AutoSafeParcelable.java:23)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelReader.readParcelable(SafeParcelReader.java:129)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.readField(SafeParcelUtil.java:290)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.readObject(SafeParcelUtil.java:95)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.SafeParcelUtil.createObject(SafeParcelUtil.java:37)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(AutoSafeParcelable.java:33)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at org.microg.safeparcel.AutoSafeParcelable$AutoCreator.createFromParcel(AutoSafeParcelable.java:23)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.google.android.gms.cast.framework.internal.ICastDynamiteModule$Stub.onTransact(ICastDynamiteModule.java:84)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.os.Binder.transact(Binder.java:914)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.google.android.gms.internal.cast.t.a(com.google.android.gms:play-services-cast@@18.1.0:4)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.google.android.gms.internal.cast.k.a(com.google.android.gms:play-services-cast-framework@@18.1.0:6)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.google.android.gms.internal.cast.f.a(com.google.android.gms:play-services-cast-framework@@18.1.0:3)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.google.android.gms.cast.framework.b.<init>(com.google.android.gms:play-services-cast-framework@@18.1.0:23)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.google.android.gms.cast.framework.b.a(com.google.android.gms:play-services-cast-framework@@18.1.0:15)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.downdogapp.client.singleton.CastHelper.<clinit>(CastHelper.kt:2)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.downdogapp.AppActivity.onCreate(AppActivity.kt:14)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.Activity.performCreate(Activity.java:7824)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.Activity.performCreate(Activity.java:7813)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.os.Looper.loop(Looper.java:214)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-06 11:34:20.041 12052 12052 W SafeParcel: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
09-06 11:34:20.042 12052 12052 W SafeParcel: Error reading field: 5 in com.google.android.gms.cast.framework.media.CastMediaOptions, skipping.
09-06 11:34:20.042 12052 12052 W SafeParcel: java.lang.RuntimeException: Can't construct object

**Comment by anjanoelle** [comment]
From reading other issues, I think this might be a duplicate to #1111, therefore I'll close this issue.
