### ISSUE TITLE
Corona Warn App "Fehler bei der Kommunikation mit der Google Schnittstelle"

### ISSUE THREAD

**Issue by hubbty** [microg/android_packages_apps_GmsCore#1171]
I don't know if this does really matter, but I report here just in case. Please see the screenshots of the details given by Corona Warn App: [https://share-your-photo.com/img/e00e70e75b.png](url)

My system:
lineage-16.0-20200816-microG-cheeseburger
microG Services Core 0.2.12.203315 from F-Droid
de.rki.coronawarnapp_v37 from Aurora store (in app information "Version: 1.3.0")
Please let me know if you need further information.

**Comment by Nanolx** [comment]
Delete the app data of `Corona Warn App` and re-setup, that should do the trick. Additionally, you may need to have Fake Store installed.

**Comment by hubbty** [comment]
Fake Store had already been installed when this error occurred (I think it comes with LineageOS for microG).

I deleted app data and did the re-setup, as you have suggested. There was no error message this time. But I should add to my previous post, that this error had not arrised immediately after installation and first start of the app, but only after I had force-stopped it and started it again later.

**Comment by Nanolx** [comment]
I see, in case it happens again a logcat from the error message would be helpful, to see the full error log.

**Comment by Nanolx** [comment]
I had the message appear aswell today, but got rid of it by tapping on the "Risikostatus" tile to load detail view and then it correctly synced with RKI and the message was gone and everything fine.

Will collect a logcat with the message pops up again.

**Comment by Tentos** [comment]
The error message has appeared several times in the last days, unfortunately. However, checking the exposure notification keys seems to have worked after several retries.

My logcat with the error notification:
```
09-23 07:48:26.433 26614 26619 I art     : Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
09-23 07:48:26.555 26614 26614 W System.err: com.google.android.gms.common.api.ApiException: 8: 
09-23 07:48:26.557 26614 26614 W System.err: 	at android.support.v4.media.MediaDescriptionCompatApi21$Builder.setResultOrApiException(MediaDescriptionCompatApi21.java:3)
09-23 07:48:26.557 26614 26614 W System.err: 	at com.google.android.gms.internal.nearby.zzah.zza(com.google.android.gms:play-services-nearby@@18.0.3-eap:1)
09-23 07:48:26.557 26614 26614 W System.err: 	at com.google.android.gms.internal.nearby.zzbl.zza(com.google.android.gms:play-services-nearby@@18.0.3-eap:3)
09-23 07:48:26.557 26614 26614 W System.err: 	at com.google.android.gms.internal.nearby.zza.onTransact(com.google.android.gms:play-services-nearby@@18.0.3-eap:3)
09-23 07:48:26.557 26614 26614 W System.err: 	at android.os.Binder.execTransact(Binder.java:565)
```
There seem to be related messages in the logcat. This seems to be a successful check of exposure notification keys:
```
09-23 07:48:11.069 30382 26493 D ExposureNotification: de.rki.coronawarnapp/<key removed> provided 6885 keys in 4.986s -> 1380.866 keys/s
09-23 07:48:11.159 30382 26493 D ExposureNotification: Processed 0 new keys in 0.079s -> 0.0 keys/s
09-23 07:48:11.258 30382 26493 D ExposureNotification: Sending Intent { act=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND pkg=de.rki.coronawarnapp (has extras) }
09-23 07:48:11.278 30382 26532 D ExposureNotification: Importing keys from file Sun Sep 13 02:00:00 GMT+02:00 2020 to Mon Sep 14 02:00:00 GMT+02:00 2020
```
On the other hand, an error happened here:
```
09-23 07:48:14.641 30382 26532 D ExposureNotification: Processed 0 new keys in 0.255s -> 0.0 keys/s
09-23 07:48:14.727 30382 26532 D ExposureNotification: Sending Intent { act=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND pkg=de.rki.coronawarnapp (has extras) }
09-23 07:48:14.758 30382 26569 D ExposureNotification: Importing keys from file Wed Sep 16 02:00:00 GMT+02:00 2020 to Thu Sep 17 02:00:00 GMT+02:00 2020
...
09-23 07:48:20.825 30382 26569 D ExposureNotification: de.rki.coronawarnapp/<key removed> provided 10235 keys in 6.169s -> 1659.102 keys/s
09-23 07:48:20.996 30382 26569 D ExposureNotification: Processed 0 new keys in 0.163s -> 0.0 keys/s
09-23 07:48:21.070 30382 30382 W ExposureNotification: Callback failed
09-23 07:48:21.070 30382 30382 W ExposureNotification: android.os.DeadObjectException
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at android.os.BinderProxy.transactNative(Native Method)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at android.os.BinderProxy.transact(Binder.java:617)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at com.google.android.gms.common.api.internal.IStatusCallback$Stub$Proxy.onResult(IStatusCallback.java:104)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at org.microg.gms.nearby.exposurenotification.ExposureNotificationServiceImpl$provideDiagnosisKeys$1$1$4.run(ExposureNotificationServiceImpl.kt:196)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at android.os.Handler.handleCallback(Handler.java:751)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at android.os.Looper.loop(Looper.java:154)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at android.app.ActivityThread.main(ActivityThread.java:6128)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-23 07:48:21.070 30382 30382 W ExposureNotification: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-23 07:48:21.162 30382 26569 D ExposureNotification: Sending Intent { act=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND pkg=de.rki.coronawarnapp (has extras) }
```

**Comment by jw243** [comment]
I have a similar problem with Corona Warn App. At first, it seemed to work well. But after a few days, the app refused to connect to the servers to download exposure tokens from people that have been tested positive. It produced the error messages in the attached screen shots.

I tried to delete the app data and even deleted and reinstalled the app, but none of that helped. The app refused to work right from the beginning after reinstallation. I even deleted all my captured tokens in MicroG, but that didn't help, either.

Have you already identified the problem causing this behaviour? I would be extremely happy, if a solution would be found.

Thanks for your effort!


![Screenshot-1 1](https://user-images.githubusercontent.com/13139555/94027021-b4f63480-fdba-11ea-96e4-c7c12376f3f2.png)
![Screenshot-2 1](https://user-images.githubusercontent.com/13139555/94027082-c2132380-fdba-11ea-9db8-123b98854152.png)
![Screenshot-3 1](https://user-images.githubusercontent.com/13139555/94027144-d2c39980-fdba-11ea-8957-f5626e84cf69.png)

**Comment by qoheniac** [comment]
I have the same problem as @hubbty.

- Fairphone Open 19.12.1-beta1 (Android 7.1.2)
- microG Services Core 0.2.12.203315 (microG F-Droid repo)
- Corona Warn-App 1.3.0 (Aurora Store)

Exposure notifications were active for 14 days without problems when this happend.

**Comment by dueringa** [comment]
I also face the same problem (API error 8).

After deleting the CWA app data, it's back to "unknown risk", but according to `adb logcat`, ExpoureNotification is still checking old keys, e.g.

```
09-28 20:34:30.788 13212 15316 D ExposureNotification: Importing keys from file Mon Sep 14 02:00:00 GMT+02:00 2020 to Tue Sep 15 02:00:00 GMT+02:00 2020
```

Logcat of API error 8, which occurred after starting and quitting app several times (doesn't always occur):

```
09-28 20:37:28.862 13212 14669 D SafeParcel: Unknown field id 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-28 20:37:28.862 13212 14669 D SafeParcel: Unknown field id 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-28 20:37:28.862 13212 14669 D SafeParcel: Unknown field id 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-28 20:37:28.862 13212 14669 D SafeParcel: Unknown field id 13 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
09-28 20:37:28.862 13212 14669 D ExposureNotification: bound by: GetServiceRequest{serviceId=NEARBY_EXPOSURE, gmsVersion=12451000, packageName='de.rki.coronawarnapp', extras=Bundle[{}]}
09-28 20:37:28.882 13212 14669 D ExposureNotification: handleServiceRequest: de.rki.coronawarnapp
09-28 20:37:28.899  1286  2120 I ActivityManager: Displayed de.rki.coronawarnapp/.ui.LauncherActivity: +1s68ms
09-28 20:37:28.933  1286 10739 I ActivityManager: START u0 {cmp=de.rki.coronawarnapp/.ui.main.MainActivity} from uid 10154
09-28 20:37:28.963 16324 16324 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1573623
09-28 20:37:29.048   372  3545 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen de.rki.coronawarnapp#0
09-28 20:37:29.048   372  3545 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen de.rki.coronawarnapp#0
09-28 20:37:29.145  1286  2895 D CountryDetector: The first listener is added
09-28 20:37:29.352 16324 16324 W System.err: com.google.android.gms.common.api.ApiException: 8: 
09-28 20:37:29.354 16324 16324 W System.err: 	at android.support.v4.media.MediaDescriptionCompatApi21$Builder.setResultOrApiException(MediaDescriptionCompatApi21.java:3)
09-28 20:37:29.354 16324 16324 W System.err: 	at com.google.android.gms.internal.nearby.zzah.zza(com.google.android.gms:play-services-nearby@@18.0.3-eap:1)
09-28 20:37:29.354 16324 16324 W System.err: 	at com.google.android.gms.internal.nearby.zzbl.zza(com.google.android.gms:play-services-nearby@@18.0.3-eap:3)
09-28 20:37:29.354 16324 16324 W System.err: 	at com.google.android.gms.internal.nearby.zza.onTransact(com.google.android.gms:play-services-nearby@@18.0.3-eap:3)
09-28 20:37:29.354 16324 16324 W System.err: 	at android.os.Binder.execTransact(Binder.java:731)
```

Maybe something to do with the unknown fields?

For me, the errors also occurred after 14 days of use.

- microg 0.2.12.203315
- Fairphone FP2
- microg-LineageOS 16, self-built, 20200814
- CWA 1.3.1

**Comment by nidico** [comment]
In the corresponding issue in the official German android app repo, @kbobrowski [asks](https://github.com/corona-warn-app/cwa-app-android/issues/1187#issuecomment-696970088) asks whether "ApiException: 8" has the same meaning in the MicroG EN implementation as in the Google implementation.

Does anybody have a clue? @mar-v-in?

**Comment by mar-v-in** [comment]
IIRC, this error code is emitted by the client library, thus it doesn't matter which service is used. 8 means `INTERNAL_ERROR`.
