### ISSUE TITLE
App crash with new mapbox

### ISSUE THREAD

**Issue by ildar** [microg/android_packages_apps_GmsCore#1176]
https://play.google.com/store/apps/details?id=citybus.guidejet.com , map fails to show.

```
09-11 08:58:14.931 29246 29246 D AndroidRuntime: Shutting down VM
09-11 08:58:14.934 29246 29246 E AndroidRuntime: FATAL EXCEPTION: main
09-11 08:58:14.934 29246 29246 E AndroidRuntime: Process: citybus.guidejet.com, PID: 29246
09-11 08:58:14.934 29246 29246 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {citybus.guidejet.com/citybus.guidejet.com.SchemeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3753)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3719)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3693)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3667)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6130)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at citybus.guidejet.com.ApplicationState.o(Unknown Source)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at citybus.guidejet.com.SchemeActivity.onPause(Unknown Source)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:6863)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1323)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3742)
09-11 08:58:14.934 29246 29246 E AndroidRuntime: 	... 12 more
09-11 08:58:14.971 29246 29246 I Process : Sending signal. PID: 29246 SIG: 9
```

**Comment by Pokemetti** [comment]
Crashes here too

**Comment by mar-v-in** [comment]
Can you describe in detail how you reached this crash? I am not seeing any crashes with CityBus 1.6.3 and microG mapbox 0.2.12.

**Comment by ildar** [comment]
App, Tracking, menu, Map

Android 7

**Comment by Pokemetti** [comment]
The only apps I have that use mapbox crashed, so WhatsApp and eBay Kleinanzeigen, but I had the old Nanodroid version but the microg update installed, which is kind of dirty (generally nanodroid is dirty). I will make a "clean" install soon.

**Comment by Nanolx** [comment]
> generally nanodroid is dirty

I know this is going off-topic, but: if there's anything that should/can be improved in ND feel free to open a bug report over at https://gitlab.com/Nanolx/NanoDroid :]

In general ND 22.7/22.8 fixed several bugs in regards to Android 10, maybe the old version is the root cause.

**Comment by Pokemetti** [comment]
Well, take what I said with a grain of salt. It is not about any specific issues, it is just a lot of small patches I don't know all of. Did a clean install of newest Nanodroid (Couldn't just update because twrp was broken) and now more stuff (like DroidGuard) seems to work, though the mapbox issue still exists, as it seems to be related to microg/mapbox. I am on Android 8.0 Samsung Experience (devdexed with vdexextractor and patched with newest nanodroid-patcher) btw

**Comment by fareszr** [comment]
idk know if this related
but after the new update(v0.2.12.203315)
every navigation app crashes
and mozilla location services is crshing when in micro G too.
i run untrusted(closed source) apps in a work profile and when deleting microG from the profile navigation works normally.

i had to revert to the old version to get location working again.

device:
S10+ using modpunk's LOS 17.1

**Comment by ildar** [comment]
On Mon, Sep 14, 2020 at 1:47 AM Ildar wrote:

> App, Tracking, menu, Map
>
> Android 7
>

@marv-i-n I'm sorry, did you manage to reproduce?

**Comment by ildar** [comment]
unfortunately the bug persists :-(
The exception is the same.

**Comment by fareszr** [comment]
Google maps still crashes with the new update

**Comment by fareszr** [comment]
this seems to be fixed by doing clean install, all my issues were fixed by reflashing the OS and reinstalling microg(from f-droid or flashing it)

so i advice anyone to do a clean install, it seems 0.2.12+ have some big changes under the hood?

**Comment by fareszr** [comment]
Great, the issue is back again and maps is always crashing.

**Comment by mar-v-in** [comment]
@fareszr I guess your issue is totally unrelated to the one by @ildar. Can you please open a new issue and provide a logcat as otherwise it's impossible to find what the issue is.

**Comment by pcercuei** [comment]
This is what I get when opening a whatsapp conversation after a contact sent me his/her location:
https://gist.github.com/pcercuei/8323d1c03741b47ea167c76d7364198d

Just opening the conversation is enough to trigger the crash - which means that I now have to delete the entire conversation otherwise I can't talk to that person anymore.

I'm pretty new to debugging Android apps, please tell me if I can provide a better crash report.

**Comment by ntfc** [comment]
> Just opening the conversation is enough to trigger the crash - which means that I now have to delete the entire conversation otherwise I can't talk to that person anymore.

@pcercuei If you disable the microg app then you can open WhatsApp and delete the location message. Re-enable microg once the messages are deleted.

Surely not a fix for the issue but at least I could open the conversation again without losing history.

**Comment by pcercuei** [comment]
@ntfc great, thanks!

**Comment by mrtndwrd** [comment]
I just reinstalled lineageos + microg and can confirm that that fixed the problem I had with applications that used mapbox. I can also confirm that I have now a problem with the UnifiedNlp location backend crashing every now and then, but am 90% sure it is not related (at least I can see mapbox in the apps that crashed before).

**Comment by pcercuei** [comment]
Well, I did reinstall lineageos + microg (using the latest nightly build from https://download.lineage.microg.org/), and I still have the bug.
