### ISSUE TITLE
EN: Occasional crash with `IllegalStateException: Tried to open writable database from secondary instance`

### ISSUE THREAD

**Issue by cgrigis** [microg/android_packages_apps_GmsCore#1200]
While running SwissCovid with microG as a library on a stock LineageOS device (see #1179), the application occasionally crashes with the following exception:

```
IllegalStateException: Tried to open writable database from secondary instance
```

Not sure yet whether it comes from the app or microG, opening an issue in case someone else has seen this as well.

**Comment by cgrigis** [comment]
Stack trace:

```
2020-09-29 19:31:22.448 21743-21743/ch.admin.bag.dp3t.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.admin.bag.dp3t.dev, PID: 21743
    java.lang.IllegalStateException: Tried to open writable database from secondary instance
        at org.microg.gms.nearby.exposurenotification.ExposureDatabase.getWritableDatabase(ExposureDatabase.kt:535)
        at org.microg.gms.nearby.exposurenotification.ExposureDatabase.noteAdvertisement(ExposureDatabase.kt:111)
        at org.microg.gms.nearby.exposurenotification.ExposureDatabase.noteAdvertisement$default(ExposureDatabase.kt:111)
        at org.microg.gms.nearby.exposurenotification.ScannerService.onScanResult(ScannerService.kt:78)
        at org.microg.gms.nearby.exposurenotification.ScannerService$callback$1.onScanResult(ScannerService.kt:35)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:498)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```
