### ISSUE TITLE
MySudo Won't Start

### ISSUE THREAD

**Issue by ExFathead** [microg/android_packages_apps_GmsCore#1202]
MySudo is some kind of communications/privacy app.  (com.anonyome.mysudo)

Install the app, give it all requested permissions, run it:  It fails to start with "Oops.  Something Went Wrong"  message

Android Version:  9
OS Version: LineageOS for MicroG 16.0-20200927
MicroG Services Core Version: 0.2.12.203315
No Google account registered.
Google device registration ON.
App in question is registered with GCM.
Reproduced with cheeseburger, gts210vewifi

**Comment by Nanolx** [comment]
Please provide a logcat from the crash.

If you don't know how you can check this XDA guide: https://www.xda-developers.com/how-to-take-logs-in-android/

**Comment by ExFathead** [comment]
Log attached, hope it is useful.
[MySudoLog.txt](https://github.com/microg/android_packages_apps_GmsCore/files/5320653/MySudoLog.txt)

**Comment by DevPre24** [comment]
Same issue, here's my full log: 
[logcat.log](https://github.com/microg/android_packages_apps_GmsCore/files/5397345/logcat.log)


Taking a quick unexperienced look at it there are a couple of exceptions:

- `io.fabric.sdk.android.services.network.HttpRequest$HttpRequestException: java.net.ConnectException: Failed to connect to settings.crashlytics.com/127.0.0.1:443` This is due to Adway, doesn't seem to be blocking
- ```10-18 12:13:03.656 D/GmsSafetyNetClientSvc( 5825): onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
10-18 12:13:03.660 I/netd    ( 4048): firewallSetUidRule(2, 10141, 1) <3.63ms>
10-18 12:13:03.665 I/netd    ( 4048): firewallSetUidRule(2, 10133, 1) <3.74ms>
10-18 12:13:03.679 I/anonyome.mysud(10528): NativeAlloc concurrent copying GC freed 2577361(73MB) AllocSpace objects, 22(592KB) LOS objects, 66% free, 24MB/72MB, paused 109us total 333.533ms
10-18 12:13:03.680 D/SafeParcel( 5825): Unknown field id 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
10-18 12:13:03.680 D/SafeParcel( 5825): Unknown field id 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
10-18 12:13:03.680 D/SafeParcel( 5825): Unknown field id 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
10-18 12:13:03.680 D/GmsSafetyNetClientSvc( 5825): bound by: GetServiceRequest{serviceId=SAFETY_NET_CLIENT, gmsVersion=12451000, packageName='com.anonyome.mysudo', extras=Bundle[{}]}
10-18 12:13:03.838 I/netd    ( 4048): firewallSetUidRule(2, 10152, 1) <3.42ms>
10-18 12:13:03.841 D/GmsDroidGuardHelper(10270): -- Request --
10-18 12:13:03.841 D/GmsDroidGuardHelper(10270): DGRequest{usage=DGUsage{type=attest, packageName=com.google.android.gms}, info=[KeyValuePair{key=BOARD, val=sdm660}, KeyValuePair{key=BOOTLOADER, val=<private info omitted>}, KeyValuePair{key=BRAND, val=Xiaomi}, KeyValuePair{key=CPU_ABI, val=arm64-v8a}, KeyValuePair{key=CPU_ABI2, val=}, KeyValuePair{key=SUPPORTED_ABIS, val=arm64-v8a,armeabi-v7a,armeabi}, KeyValuePair{key=DEVICE, val=whyred}, KeyValuePair{key=DISPLAY, val=QQ3A.200805.001}, KeyValuePair{key=FINGERPRINT, val=google/coral/coral:10/QQ3A.200805.001/6578210:user/release-keys}, KeyValuePair{key=HARDWARE, val=qcom}, KeyValuePair{key=HOST, val=build-vm-test}, KeyValuePair{key=ID, val=QQ3A.200805.001}, KeyValuePair{key=MANUFACTURER, val=Xiaomi}, KeyValuePair{key=MODEL, val=Redmi Note 5}, KeyValuePair{key=PRODUCT, val=whyred}, KeyValuePair{key=RADIO, val=660_GEN_PACK-1.209285.1.210383.1,660_GEN_PACK-1.209285.1.210383.1}, KeyValuePair{key=SERIAL, val=<private info omitted>}, KeyValuePair{key=TAGS, val=release-keys}, KeyValuePair{key=TIME, val=1597669895000}, KeyValuePair{key=TYPE, val=user}, KeyValuePair{key=USER, val=ruturaj_kadam99}, KeyValuePair{key=CODENAME, val=REL}, KeyValuePair{key=INCREMENTAL, val=eng.rutura.20200817.131213}, KeyValuePair{key=RELEASE, val=10}, KeyValuePair{key=SDK, val=29}, KeyValuePair{key=SDK_INT, val=29}], versionNamePrefix=20.33.15 (040400-{{cl}}), isGoogleCn=false, enableInlineVm=true, cached=[ByteString[size=20 md5=89c3855244e634fc5b4e9f0ab753c22d], ByteString[size=20 md5=c642f19b9ec9eea01065f33b699dc048], ByteString[size=20 md5=97b60d4be6f4ae45efbe5fac3a8faf04], ByteString[size=20 md5=d38cb609270e4c9f022e2c0c62b9594d]], currentVersion=3, arch=aarch64}
10-18 12:13:03.990 D/GmsDroidGuardHelper(10270): Using cached file from /data/user/0/org.microg.gms.droidguard/app_dg_cache/8d432dc1a4801262b6e1d30cde10f1ceee66d535/the.apk
10-18 12:13:04.126 E/BatteryExternalStatsWorker( 4395): no controller energy info supplied for bluetooth
10-18 12:13:04.126 D/GmsDroidGuardHelper(10270): b -> <private info omitted>9470
10-18 12:13:04.147 I/netd    ( 4048): tetherGetStats() <2.20ms>
10-18 12:13:04.208 I/anonyome.mysud(10528): NativeAlloc concurrent copying GC freed 806277(20MB) AllocSpace objects, 0(0B) LOS objects, 66% free, 21MB/64MB, paused 76us total 165.436ms
10-18 12:13:04.306 D/GmsDroidGuardHelper(10270): c -> com.google.android.gms
10-18 12:13:04.315 D/GmsSafetyNetClientImpl( 5825): Status: 0, error:null
10-18 12:13:04.324 I/netd    ( 4048): firewallSetUidRule(2, 10152, 2) <5.56ms>
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): 
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): java.io.IOException: {
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):   "error": {
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):     "code": 403,
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):     "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):     "errors": [
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):       {
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):         "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):         "domain": "global",
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):         "reason": "forbidden"
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):       }
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):     ],
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):     "status": "PERMISSION_DENIED"
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825):   }
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): }
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): 
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): 	at org.microg.gms.snet.Attestation.attest(Attestation.java:176)
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): 	at org.microg.gms.snet.Attestation.attest(Attestation.java:146)
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): 	at org.microg.gms.snet.SafetyNetClientServiceImpl$1.run(SafetyNetClientServiceImpl.java:87)
10-18 12:13:04.577 W/GmsSafetyNetClientImpl( 5825): 	at java.lang.Thread.run(Thread.java:919)
10-18 12:13:04.582 E/null    (10528): register failed
10-18 12:13:04.582 E/null    (10528): com.anonyome.user.core.entities.user.UserService$RegisterException$SafetyNetAttestationException: java.io.InterruptedIOException: SafetyNet API request was cancelled or interrupted.
10-18 12:13:04.582 E/null    (10528): 	at com.anonyome.user.core.data.anonyomebackend.user.ABUserService.k(SourceFile:42)
10-18 12:13:04.582 E/null    (10528): 	at com.anonyome.user.core.data.anonyomebackend.user.ABUserService$registerActual$1.u(Unknown Source:11)
10-18 12:13:04.582 E/null    (10528): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:2)
10-18 12:13:04.582 E/null    (10528): 	at q0.a.k0.run(SourceFile:14)
10-18 12:13:04.582 E/null    (10528): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.u(SourceFile:1)
10-18 12:13:04.582 E/null    (10528): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$a.run(SourceFile:13)
10-18 12:13:04.582 E/null    (10528): Caused by: java.io.InterruptedIOException: SafetyNet API request was cancelled or interrupted.
10-18 12:13:04.582 E/null    (10528): 	at b.a.g.p4.a$a.d(SourceFile:7)
10-18 12:13:04.582 E/null    (10528): 	at b.l.a.c.k.p.run(SourceFile:11)
10-18 12:13:04.582 E/null    (10528): 	at android.os.Handler.handleCallback(Handler.java:883)
10-18 12:13:04.582 E/null    (10528): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-18 12:13:04.582 E/null    (10528): 	at android.os.Looper.loop(Looper.java:214)
10-18 12:13:04.582 E/null    (10528): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-18 12:13:04.582 E/null    (10528): 	at java.lang.reflect.Method.invoke(Native Method)
10-18 12:13:04.582 E/null    (10528): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
10-18 12:13:04.582 E/null    (10528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-18 12:13:04.585 E/null    (10528): Sign in error
10-18 12:13:04.585 E/null    (10528): com.anonyome.user.core.entities.user.UserService$RegisterException$SafetyNetAttestationException: java.io.InterruptedIOException: SafetyNet API request was cancelled or interrupted.
10-18 12:13:04.585 E/null    (10528): 	at com.anonyome.user.core.data.anonyomebackend.user.ABUserService.k(SourceFile:42)
10-18 12:13:04.585 E/null    (10528): 	at com.anonyome.user.core.data.anonyomebackend.user.ABUserService$registerActual$1.u(Unknown Source:11)
10-18 12:13:04.585 E/null    (10528): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.g(SourceFile:2)
10-18 12:13:04.585 E/null    (10528): 	at q0.a.k0.run(SourceFile:14)
10-18 12:13:04.585 E/null    (10528): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.u(SourceFile:1)
10-18 12:13:04.585 E/null    (10528): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$a.run(SourceFile:13)
10-18 12:13:04.585 E/null    (10528): Caused by: java.io.InterruptedIOException: SafetyNet API request was cancelled or interrupted.
10-18 12:13:04.585 E/null    (10528): 	at b.a.g.p4.a$a.d(SourceFile:7)
10-18 12:13:04.585 E/null    (10528): 	at b.l.a.c.k.p.run(SourceFile:11)
10-18 12:13:04.585 E/null    (10528): 	at android.os.Handler.handleCallback(Handler.java:883)
10-18 12:13:04.585 E/null    (10528): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-18 12:13:04.585 E/null    (10528): 	at android.os.Looper.loop(Looper.java:214)
10-18 12:13:04.585 E/null    (10528): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-18 12:13:04.585 E/null    (10528): 	at java.lang.reflect.Method.invoke(Native Method)
10-18 12:13:04.585 E/null    (10528): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
10-18 12:13:04.585 E/null    (10528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
10-18 12:13:05.084 I/anonyome.mysud(10528): NativeAlloc concurrent copying GC freed 1399365(37MB) AllocSpace objects, 2(104KB) LOS objects, 63% free, 27MB/75MB, paused 111us total 227.731ms``` A safety net issue

**Comment by ale5000-git** [comment]
Could you please retry with the latest microG GmsCore?

**Comment by zdat** [comment]
Tried with the latest microG Services Core (I assume they're the same?) and still shows same error. Did anyone get this app to work?
