### ISSUE TITLE
Java lang VerifyError

### ISSUE THREAD

**Issue by Phyks** [microg/android_packages_apps_GmsCore#121]
Hi,

I installed GmsCore and so on (from the f-droid repo) to be able to use apps that require Google services to be installed on the phone. It seems to be working very well (self check is ok, geolocation using wifi is ok as well, and some apps which used to crash are working, such as Uber).

I wanted to test how much apps that could not be used before were now usable. I tried "Duel quiz" (https://play.google.com/store/apps/details?id=se.feomedia.quizkampen.fr.lite&hl=fr), latest version (2.2.0).

However, when launching it, I get some "This app encountered a problem and crashed" error message. I am not 100% sure it has a link to micro-g, but I suspect the issue to be caused by the loading of advertisements displayed in the app.

Here is the traceback I had using `logcat`:

```
E/AndroidRuntime(18468): FATAL EXCEPTION: main
E/AndroidRuntime(18468): java.lang.VerifyError: o/र$if
E/AndroidRuntime(18468): 	at o.र.ˊ(Unknown Source)
E/AndroidRuntime(18468): 	at o.т.ˊ(Unknown Source)
E/AndroidRuntime(18468): 	at o.т.ˊ(Unknown Source)
E/AndroidRuntime(18468): 	at o.ᴛ.ˎ(Unknown Source)
E/AndroidRuntime(18468): 	at o.ᴛ.ˋ(Unknown Source)
E/AndroidRuntime(18468): 	at o.ᴛ.ˊ(Unknown Source)
E/AndroidRuntime(18468): 	at com.mopub.mobileads.GooglePlayServicesBanner.loadBanner(SourceFile:4000)
E/AndroidRuntime(18468): 	at com.mopub.mobileads.CustomEventBannerAdapter.loadAd(SourceFile:92)
E/AndroidRuntime(18468): 	at com.mopub.mobileads.MoPubView.loadCustomEvent(SourceFile:173)
E/AndroidRuntime(18468): 	at com.mopub.mobileads.AdLoader$CustomEventAdLoader.load(SourceFile:64)
E/AndroidRuntime(18468): 	at com.mopub.mobileads.AdViewController.onAdLoadSuccess(SourceFile:147)
E/AndroidRuntime(18468): 	at com.mopub.mobileads.AdViewController$1.onSuccess(SourceFile:115)
E/AndroidRuntime(18468): 	at o.ki.ˊ(SourceFile:44246)
E/AndroidRuntime(18468): 	at o.kG.run(SourceFile:99)
E/AndroidRuntime(18468): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(18468): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(18468): 	at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(18468): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(18468): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18468): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(18468): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/AndroidRuntime(18468): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(18468): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(18468): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  597):   Force finishing activity se.feomedia.quizkampen.fr.lite/o.tM
```

Which references `GooglePlayServicesBanner`, which is in agreement with the issue being cause by advertisements, I think, and made me think it could also be linked to microg.

Using adblock plus, everything works fine, which confirms the issue with ads.

Thanks

**Comment by mar-v-in** [comment]
Very interesting:

The actual stacktrace gives no trace to Play Services. This means that even if ads through play services are used, they are implemented using a custom library. Or the obfuscation causes problems here.

VerifyError is not thrown by play services, or atleast I did not see something like that before. Again it could be that the obfuscation is causing problems here. As with all exceptions, VerifyError can be thrown by application code. However, if the system throws it, it will be because a class could not be loaded. There is a class name mentioned with the exception, so it's likely that problem.

Adblock blocks network traffic on Android, which means that not the code itself is changed, its just not able to download ads. This can cause problems, but does not in most cases (you could just be offline). However you mentioned that when using adblock, you do not have problems, which is kind of weird, because this would mean that network traffic from the app itself causes it to throw an error.

If you combine the information above, the only idea what can cause the problem would be that some code to show ads is loaded from the internet (which is not possible when using adblock) and the class verification of this code fails. Looking at the stack trace, I guess that it's more likely that Xposed causes problems here.

**Comment by Phyks** [comment]
I dig a bit further, and saw that Mopub is used and may be loading ads. Maybe we can try to replicate the problem with an opensource app (then not obfuscated and in debug mode) using mopub as well?

In my `logcat`, I saw some issues with invalid certificates, but I was not 100% sure it was linked to this issue, and did not give much extra info, so I did not copy/paste them.

I am really new to android development, and may not be able to dig much further for this issue. Still, I will happily provide any log sample or try things if it can be useful.

Thanks
