### ISSUE TITLE
F-Droid repo error

### ISSUE THREAD

**Issue by pejakm** [microg/android_packages_apps_GmsCore#122]
Something is wrong with https://microg.org/fdroid/repo, F-Droid reports error (it can't refresh apps).

**Comment by mar-v-in** [comment]
It does work for me, can you provide details (logcat, error message)

**Comment by zoff99** [comment]
+1 error getting index file

also what is this repo: https://fdroid.o9i.de ??

http://fdroid.o9i.de/repo/index.xml

**Comment by mar-v-in** [comment]
@zoff99 That's the repo from thy guy that wrote this tutorial: https://o9i.de/2015/10/23/howto-gmscore.html

I don't have problems opening the index file ( https://microg.org/fdroid/repo/index.xml ) on my devices. Can you provide a logcat?

**Comment by pejakm** [comment]
```
E/UpdateService(26980): Error updating repository https://microg.org/fdroid/repo
E/UpdateService(26980): org.fdroid.fdroid.RepoUpdater$UpdateException: Error getting index file
E/UpdateService(26980):         at org.fdroid.fdroid.RepoUpdater.downloadIndex(RepoUpdater.java:115)
E/UpdateService(26980):         at org.fdroid.fdroid.RepoUpdater.update(RepoUpdater.java:132)
E/UpdateService(26980):         at org.fdroid.fdroid.UpdateService.onHandleIntent(UpdateService.java:377)
E/UpdateService(26980):         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/UpdateService(26980):         at android.os.Handler.dispatchMessage(Handler.java:102)
E/UpdateService(26980):         at android.os.Looper.loop(Looper.java:136)
E/UpdateService(26980):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/UpdateService(26980): Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x60fca3c0: Failure in SSL library, usually a protocol error
E/UpdateService(26980): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x52156f88:0x00000000)
E/UpdateService(26980):         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
E/UpdateService(26980):         at info.guardianproject.netcipher.client.TlsOnlySocketFactory$DelegateSSLSocket.startHandshake(TlsOnlySocketFactory.java:256)
E/UpdateService(26980):         at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
E/UpdateService(26980):         at com.android.okhttp.Connection.connect(Connection.java:107)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
E/UpdateService(26980):         at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
E/UpdateService(26980):         at org.fdroid.fdroid.net.HttpDownloader.download(HttpDownloader.java:89)
E/UpdateService(26980):         at org.fdroid.fdroid.RepoUpdater.downloadIndex(RepoUpdater.java:100)
E/UpdateService(26980):         ... 6 more
E/UpdateService(26980): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x60fca3c0: Failure in SSL library, usually a protocol error
E/UpdateService(26980): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x52156f88:0x00000000)
E/UpdateService(26980):         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/UpdateService(26980):         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
E/UpdateService(26980):         ... 18 more
I/UpdateService(26980): Updating repo(s) complete, took 1 seconds to complete.
```

**Comment by mar-v-in** [comment]
What Android version are you running?

**Comment by pejakm** [comment]
4.4.4 ([MahdiRom](http://forum.xda-developers.com/optimus-4x-hd/development/rom-mahdi-rom-2-7-unofficial-beta-t2867590)).

**Comment by mar-v-in** [comment]
Just to make sure: Latest F-Droid version?

**Comment by mar-v-in** [comment]
Filed as https://gitlab.com/fdroid/fdroidclient/issues/629, closing here.

**Comment by pejakm** [comment]
@mar-v-in Yes, latest FDroid. Thanks for clarifying and reporting this to upstream!
