### ISSUE TITLE
Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.AskPushPermission

### ISSUE THREAD

**Issue by jesse-git** [microg/android_packages_apps_GmsCore#1225]
OS: Android 9
What is supposed to happen: Start Sprint IP relay app>White screen>Logo appears>Login screen>Logged in

(Behavior changes after Sprint IP relay app version 60.30.5. The newer versions crash with a okhttp error.)

Sprint IP relay app version 60.30.5 and before: I get to the login screen, but when trying to login, microg crashes:

```
java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.ButtonBarLayout" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-Q-bMnMr4UQ8M_1XpvD5m7w==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-Q-bMnMr4UQ8M_1XpvD5m7w==/lib/arm64, /data/app/com.google.android.gms-Q-bMnMr4UQ8M_1XpvD5m7w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.AskPushPermission}: android.view.InflateException: Binary XML file line #79: Binary XML file line #79: Error inflating class android.support.v7.widget.ButtonBarLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2948)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3083)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6672)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: android.view.InflateException: Binary XML file line #79: Binary XML file line #79: Error inflating class android.support.v7.widget.ButtonBarLayout
Caused by: android.view.InflateException: Binary XML file line #79: Error inflating class android.support.v7.widget.ButtonBarLayout
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.ButtonBarLayout" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-Q-bMnMr4UQ8M_1XpvD5m7w==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-Q-bMnMr4UQ8M_1XpvD5m7w==/lib/arm64, /data/app/com.google.android.gms-Q-bMnMr4UQ8M_1XpvD5m7w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:421)
	at android.app.Activity.setContentView(Activity.java:2772)
	at org.microg.gms.ui.AskPushPermission.onCreate(AskPushPermission.java:53)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3083)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6672)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

**Comment by mar-v-in** [comment]
This was fixed in 26f2e859b8d424f20f42f3c2ec3736817f39b6e2
