### ISSUE TITLE
Blank permission request dialog shown (GmsGcmRegister java.lang.RuntimeException: Push permission not granted to app)

### ISSUE THREAD

**Issue by runejuhl** [microg/android_packages_apps_GmsCore#1240]
Since upgrading UnifiedNlp yesterday I've gotten a few weird permission popups:

![signal-2020-10-20-162453](https://user-images.githubusercontent.com/626791/96600787-9ddf2f80-12f1-11eb-92a2-0b67a02bd042.png)

Looking at Logcat they seem to be associated with this error:

~~~
java.lang.RuntimeException: Push permission not granted to app
	at org.microg.gms.gcm.PushRegisterServiceKt.ensureAppRegistrationAllowed(PushRegisterService.kt:73)
	at org.microg.gms.gcm.PushRegisterServiceKt$ensureAppRegistrationAllowed$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:76)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:106)
	at androidx.lifecycle.DispatchQueue.access$enqueue(DispatchQueue.kt:32)
	at androidx.lifecycle.DispatchQueue$runOrEnqueue$$inlined$with$lambda$1.run(DispatchQueue.kt:93)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
~~~

I haven't found a pattern in when the popup is shown yet. If I dismiss it it seems to come back at random, sometimes within a few seconds and sometimes after some hours.

Please let me know if I can assist in debugging -- and thank you for your work on microg!

**Comment by jesse-git** [comment]
It is because of dark mode. Works fine otherwise

**Comment by runejuhl** [comment]
> It is because of dark mode. Works fine otherwise

Not sure I understand -- do apps require a new permission to be able to work under dark mode? I've looked through the list of all permissions, but can't see anything that seems to have anything to do with dark mode.

**Comment by jesse-git** [comment]
No, the GCM authorization prompt for apps is controlled under micro G > GCM > menu > advanced. Alternate solution is 2 disable dark mode in order 2 see the prompt text.

**Comment by runejuhl** [comment]
Thank you @jesse-git, that makes sense.
