### ISSUE TITLE
Google Maps crashes

### ISSUE THREAD

**Issue by julienschmidt** [microg/android_packages_apps_GmsCore#127]
* CM 13
* Signature patching via Xposed
* Maps 9.25.1

Google Maps crashes immediately after start:

```
05-06 13:46:27.176  5039  5122 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
05-06 13:46:27.185  5039  5039 D AndroidRuntime: Shutting down VM
05-06 13:46:27.186  5039  5039 W System.err: java.lang.IllegalArgumentException: No such column: sync_me_to_contacts
05-06 13:46:27.189  5039  5039 W System.err: 	at com.google.android.gms.common.data.DataHolder.a(Unknown Source)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.google.android.gms.common.data.j.c(Unknown Source)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.google.android.gms.people.internal.i.s(Unknown Source)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.google.android.apps.gmm.x.g.<init>(PG:123)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.google.android.apps.gmm.layers.ai.a(PG:5021)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.google.android.gms.common.api.a.k.handleMessage(Unknown Source)
05-06 13:46:27.189  5039  5039 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 13:46:27.189  5039  5039 W System.err: 	at android.os.Looper.loop(Looper.java:148)
05-06 13:46:27.189  5039  5039 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
05-06 13:46:27.189  5039  5039 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-06 13:46:27.189  5039  5039 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-06 13:46:27.189  5039  5039 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-06 13:46:27.190  7356 30803 D SafeParcel: Unknown field num 1 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
05-06 13:46:27.190  7356 30803 D SafeParcel: Unknown field num 2 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
05-06 13:46:27.190  7356 30803 D SafeParcel: Unknown field num 3 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
05-06 13:46:27.190  7356 30803 D GmsClearcutLogSvcImpl: log: com.google.android.gms.clearcut.LogEventParcelable@f658e14
05-06 13:46:27.190  5039  5039 E AndroidRuntime: FATAL EXCEPTION: main
05-06 13:46:27.190  5039  5039 E AndroidRuntime: Process: com.google.android.apps.maps, PID: 5039
05-06 13:46:27.190  5039  5039 E AndroidRuntime: Theme: themes:{}
05-06 13:46:27.190  5039  5039 E AndroidRuntime: java.lang.IllegalArgumentException: No such column: sync_me_to_contacts
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.google.android.gms.common.data.DataHolder.a(Unknown Source)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.google.android.gms.common.data.j.c(Unknown Source)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.google.android.gms.people.internal.i.s(Unknown Source)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.google.android.apps.gmm.x.g.<init>(PG:123)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.google.android.apps.gmm.layers.ai.a(PG:5021)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.google.android.gms.common.api.a.k.handleMessage(Unknown Source)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-06 13:46:27.190  5039  5039 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-06 13:46:27.192  5904 14372 W ActivityManager:   Force finishing activity com.google.android.apps.maps/com.google.android.maps.MapsActivity
```

**Comment by Catfriend1** [comment]
happens on my device too..updaten maps From play store.

**Comment by Catfriend1** [comment]
note: restoted maps 9.23 with titanium backup ... maps is working again.

**Comment by art1fa** [comment]
Cannot reproduce with Maps 9.25.1 on OmniROM 6 with mircoG components integrated in build process.

**Comment by Catfriend1** [comment]
microg 0.2.2-5
cm  13 20160412
gcm setup
xposed 80-arm final

**Comment by ibleedbinari** [comment]
Can confirm the crash. Looks like it is related to the new contacts on the map feature. Downgrading fixes the issue.

**Comment by Catfriend1** [comment]
I still have  the Problem with microg fdroid Version b9 0.2.2.
05-15 14:02:02.566 E/AndroidRuntime(11498): java.lang.IllegalArgumentException: No such column: sync_me_to_contacts
after updating maps to newest play store Version.
will downgrade maps again.

**Comment by mar-v-in** [comment]
@Catfriend1 are you sure you are on the latest version (Check in microG Settings->About, it should show "Version 0.2.2-9-g4ae10d9")

**Comment by Catfriend1** [comment]
checked. it shows 0.2.2. fdroid die Install the stable build. upgraded to -9 build.
