### ISSUE TITLE
Severe Weather App - map tile click and default centered location problem

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#141]
SevereWeather App "Unwetter" from Michael Diener opens and centers the screen on the wrong Position. If i move the screen right down it shows my GPS marker on the Google map. With Googles gms , the marker was always in the center of the screen after App open without manually moving right down. 

Further difference. When using microg gms instead of Googles gms, i cannot click coloured tiles of the map (these should display weather warnings Form DWD if the Tile is coloured , a Warning is present and can be clicked. ).

Sometimes i can work around the microg bug by zooming a little bit in and out or moving the map so the spot of my location dies no longer fit in the screen center.

Here is some logcat. Rarely App crashes, so i only geht this error on crash. Above symptoms always occur. Cm13 on Lg h815. Nightly 29.05.2016, fakesig and xposed 85 arm64.

06-04 10:39:16.679 E/AndroidRuntime(7571): FATAL EXCEPTION: VtmAsyncExecutor
06-04 10:39:16.679 E/AndroidRuntime(7571): Process: de.mdiener.unwetter.gm, PID: 7571
06-04 10:39:16.679 E/AndroidRuntime(7571): java.lang.NullPointerException: Attempt to read from field 'java.lang.Object org.oscim.utils.quadtree.TreeNode.item' on a null object reference
(More oscim errors follow)

All those problems do not occur when using Google gms.

**Comment by Catfriend1** [comment]
As an intermediate fix, I replaced the App via some own lua script pushing gcm notifications to my phone. So this is low-priority now.

**Comment by Catfriend1** [comment]
06-04 10:39:16.679 E/AndroidRuntime(7571): FATAL EXCEPTION: VtmAsyncExecutor
06-04 10:39:16.679 E/AndroidRuntime(7571): Process: de.mdiener.unwetter.gm, PID: 7571
06-04 10:39:16.679 E/AndroidRuntime(7571): Theme: themes:{default=overlay:system, iconPack:com.thomassafca.tw, com.android.systemui=overlay:com.thomassafca.tw, com.android.systemui.navbar=overlay:com.thomassafca.tw}
06-04 10:39:16.679 E/AndroidRuntime(7571): java.lang.NullPointerException: Attempt to read from field 'java.lang.Object org.oscim.utils.quadtree.TreeNode.item' on a null object reference
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at org.oscim.utils.quadtree.BoxTree.search(BoxTree.java:208)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at org.oscim.utils.QuadTree.search(QuadTree.java:69)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at org.oscim.layers.vector.VectorLayer.processFeatures(VectorLayer.java:184)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at org.oscim.layers.vector.AbstractVectorLayer$Worker.doWork(AbstractVectorLayer.java:114)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at org.oscim.layers.vector.AbstractVectorLayer$Worker.doWork(AbstractVectorLayer.java:67)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at org.oscim.utils.async.SimpleWorker.run(SimpleWorker.java:67)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-04 10:39:16.679 E/AndroidRuntime(7571): 	at java.lang.Thread.run(Thread.java:818)

**Comment by mar-v-in** [comment]
Regarding crashes, see #147. The marker/map position thing is probably related to #148

**Comment by ghost** [comment]
please delete issue
