### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by pejakm** [microg/android_packages_apps_GmsCore#16]
Hi! I have Omnirom 4.4.4, I removed ugUnifiedNlp, restarted, installed this GmsCore, installed it as a system app (using TitaniumBackup), restarted again, enabled GCM from ug settings. Network location part is working, but applications which require GCM to work aren't working (for example I'm trying out TextSecure - it refuses to register me claiming I don't have Google Play services installed). Am I missing a crucial information here? Just to note, I do have xposed installed.

Edit: I used apk from http://files.brnmod.rocks/apps/GmsCore/Latest/

**Comment by pejakm** [comment]
Some logcat output:

```
u0_a69@p880:/ $ su
root@p880:/ # logcat | grep gms
W/PackageManager(  539): Not granting permission android.permission.INSTALL_LOCATION_PROVIDER to package com.google.android.gms (protectionLevel=18 flags=0x88be45)
W/PackageManager(  539): Unknown permission android.permission.ACCESS_COARSE_UPDATES in package com.google.android.gms
W/PackageManager(  539): Not granting permission android.permission.INSTALL_LOCATION_PROVIDER to package com.google.android.gms (protectionLevel=18 flags=0x88be45)
W/PackageManager(  539): Unknown permission android.permission.ACCESS_COARSE_UPDATES in package com.google.android.gms
I/ActivityManager(  539): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.gms/org.microg.gms.ui.SettingsActivity} from pid 1441
I/ActivityManager(  539): Killing 752:com.google.android.gms/u0a30 (adj 1): remove task
W/ActivityManager(  539): Scheduling restart of crashed service com.google.android.gms/org.microg.nlp.location.LocationServiceV2 in 1000ms
W/ActivityManager(  539): Scheduling restart of crashed service com.google.android.gms/org.microg.nlp.geocode.GeocodeServiceV1 in 11000ms
I/ActivityManager(  539): Start proc com.google.android.gms for service com.google.android.gms/org.microg.nlp.location.LocationServiceV2: pid=5404 uid=10030 gids={50030, 3003}
I/ActivityManager(  539): START u0 {cmp=com.google.android.gms/org.microg.nlp.ui.SettingsActivity} from pid 3920
I/ActivityManager(  539): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.gms/org.microg.gms.ui.SettingsActivity} from pid 1441
I/ActivityManager(  539): Killing 5404:com.google.android.gms/u0a30 (adj 1): remove task
W/ActivityManager(  539): Scheduling restart of crashed service com.google.android.gms/org.microg.nlp.location.LocationServiceV2 in 1000ms
W/ActivityManager(  539): Scheduling restart of crashed service com.google.android.gms/org.microg.nlp.geocode.GeocodeServiceV1 in 10999ms
I/ActivityManager(  539): Start proc com.google.android.gms for service com.google.android.gms/org.microg.nlp.location.LocationServiceV2: pid=6625 uid=10030 gids={50030, 3003}
W/ActivityManager(  539): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=972, uid=10022 requires com.google.android.c2dm.permission.RECEIVE
^C
130|root@p880:/ #
```

**Comment by pejakm** [comment]
Well, yeah, I installed FakeStore, too, and now apps "see" GCM but still refuse to work. For example, TextSecure allows me to start registering process, but it cannot finish it, telling me there is no network connection (no firewall). Application "Heavens-above" crashes (it can work without play-services, but it notifies about them missing). Don't know how else to test.

**Comment by mar-v-in** [comment]
You need to reinstall applications after you installed GmsCore so they can be granted the required permission.
There seem to be issues with the device checkin implementation. Can you please start "logcat | grep GmsCheckin" and then open the dialer and dial "*#*#CHECKIN#*#*". If you see a message like "W/GmsCheckinSvc( 5853): java.io.IOException: Internal server error." you're affected by the problem and a lot of Google services will not work probably or might stop working in the future. I am working on a fix.

**Comment by pejakm** [comment]
I even installed real PlayStore, and I managed to sign-in. But it wont refresh applications, says: no internet connection.

Here's the output of checking test:

```
u0_a69@p880:/ $ su
root@p880:/ # logcat | grep GmsCheckin
V/tinyclipboardmanager( 1810): modifyClip(null, logcat | grep GmsCheckin, 0)
D/GmsCheckinTrigger(  752): Trigger checkin: Intent { act=android.provider.Telephony.SECRET_CODE dat=android_secret_code://2432546 flg=0x10 cmp=com.google.android.gms/org.microg.gms.checkin.TriggerReceiver }
D/GmsCheckinClient(  752): -- Request --
D/GmsCheckinClient(  752): CheckinRequest{androidId=0, digest=1-da39a3ee5e6b4b0d3255bfef95601890afd80709, checkin=Checkin{build=Build{fingerprint=LG/omni_p880/p880:4.4.4/KTU84P/560:userdebug/test-keys, hardware=x3, brand=LG, radio=LGP880AT-00-V20b-EUR-XXX-JUL-17-2013, bootloader=unknown, time=1432136615, packageVersionCode=7099448, device=p880, sdkVersion=19, model=LG-P880, manufacturer=LGE, product=omni_p880, otaInstalled=false}, lastCheckinMs=0, event=[], stat=[], requestedGroup=[]}, macAddress=[], accountCookie=[[pejakm@gmail.com], DQAAAAsBAADcnfcKTLt72ZbbKPYct07z0tU8YSV9iXAG1CfEQDPynspdkbykXj5Gg0V_57U1JwuQGl1OtXO8KCCf8tLtp-FresOTa9jnQl6RfeG7PKKQkEMj6rOHxqtGhKdTp9C3vOTFG3BrNGbzMSY14f_NYQpBnCJVVGW2ygYQS3HfSxWOd9tIn25KNvtDYW9IKWFBbojaVHj-np5FOeKhejyBuHaNkEoAG2FF8CPtbH59rp0Ljr0dhlyjFa69yyVpds-l5LTqnBqvF3jdKGkNGyJDOIxtgq-qA8tjk5oXeO0IEXxGHzk52UnP2AUmRpg1LziiPqKYPdVlEwH2nC25NuSASDQgt_PFeJ3Tv8ZP8TnC-BWIPQ], version=3, otaCert=[], deviceConfiguration=DeviceConfig{touchScreen=3, keyboardType=1, navigation=1, screenLayout=268435554, hasHardKeyboard=false, hasFiveWayNavigation=false, densityDpi=320, glEsVersion=131072, sharedLibrary=[android.test.runner, javax.obex, com.android.nfc_extras, com.android.future.usb.accessory, com.android.location.provider, com.android.media.remotedisplay], availableFeature=[android.hardware.wifi, android.hardware.location.network, android.hardware.nfc, android.hardware.bluetooth_le, android.hardware.location, android.software.input_methods, android.hardware.sensor.gyroscope, android.hardware.screen.landscape, android.hardware.screen.portrait, android.hardware.wifi.direct, android.hardware.usb.accessory, android.hardware.camera.any, android.hardware.bluetooth, android.hardware.touchscreen.multitouch.distinct, android.hardware.microphone, android.hardware.sensor.light, android.hardware.camera.autofocus, android.software.live_wallpaper, android.software.app_widgets, android.hardware.camera.flash, android.hardware.telephony, android.software.sip, android.hardware.touchscreen.multitouch.jazzhand, android.hardware.touchscreen.multitouch, android.hardware.sensor.compass, android.hardware.faketouch, android.hardware.camera, android.software.home_screen, android.software.sip.voip, android.hardware.sensor.proximity, android.hardware.location.gps, android.hardware.telephony.gsm, android.software.device_admin, android.hardware.nfc.hce, android.hardware.camera.front, android.hardware.sensor.accelerometer, com.nxp.mifare, android.hardware.touchscreen], nativePlatform=[armeabi-v7a, armeabi], widthPixels=720, heightPixels=1280, locale=[, ca, da, fa, ja, ka, nb, de, ne, af, bg, th, fi, hi, si, vi, sk, uk, el, nl, pl, sl, tl, am, km, rm, in, mn, ko, lo, ro, ar, fr, hr, sr, tr, cs, es, ms, et, it, lt, pt, hu, ru, zu, lv, sv, iw, sw, hy, az, en_CA, fr_CA, lo_LA, uk_UA, en_GB, in_ID, et_EE, ka_GE, ar_EG, en_SG, km_KH, th_TH, fi_FI, sl_SI, zh_HK, si_LK, sk_SK, hy_AM, zh_CN, hi_IN, en_IN, mn_MN, vi_VN, ro_RO, ne_NP, hr_HR, sr_RS, en_US, es_US, lt_LT, pt_PT, en_AU, hu_HU, lv_LV, zh_TW, ms_MY, az_AZ, en_NZ, af_ZA, zu_ZA, nl_BE, fr_BE, de_DE, sv_SE, bg_BG, de_CH, rm_CH, fr_CH, it_CH, tl_PH, de_LI, da_DK, iw_IL, nl_NL, pl_PL, nb_NO, ja_JP, pt_BR, fr_FR, el_GR, fa_IR, ko_KR, tr_TR, ca_ES, es_ES, de_AT, am_ET, it_IT, ru_RU, cs_CZ, sw_TZ, en, bn_BD, ky_KG, mk_MK, ur_PK, my_MM, ta_IN, te_IN, ml_IN, kn_IN, mr_IN, gl_ES, eu_ES, is_IS, kk_KZ, uz_UZ], glExtension=[GL_EXT_bgra, GL_EXT_texture_compression_dxt1, GL_EXT_texture_compression_s3tc, GL_EXT_texture_format_BGRA8888, GL_EXT_unpack_subimage, GL_EXT_debug_marker, GL_EXT_debug_label, GL_NV_texture_npot_2D_mipmap, GL_OES_byte_coordinates, GL_OES_compressed_ETC1_RGB8_texture, GL_OES_compressed_paletted_texture, GL_OES_draw_texture, GL_OES_extended_matrix_palette, GL_OES_EGL_image, GL_OES_EGL_image_external, GL_OES_EGL_sync, GL_OES_fbo_render_mipmap, GL_OES_fixed_point, GL_OES_framebuffer_object, GL_OES_matrix_get, GL_OES_matrix_palette, GL_OES_point_size_array, GL_OES_point_sprite, GL_OES_query_matrix, GL_OES_read_format, GL_OES_rgb8_rgba8, GL_OES_single_
W/GmsCheckinSvc(  752): java.io.IOException: Internal server error.
W/GmsCheckinSvc(  752):         at org.microg.gms.checkin.CheckinClient.request(CheckinClient.java:57)
W/GmsCheckinSvc(  752):         at org.microg.gms.checkin.CheckinManager.checkin(CheckinManager.java:55)
W/GmsCheckinSvc(  752):         at org.microg.gms.checkin.CheckinService.onHandleIntent(CheckinService.java:50)
W/GmsCheckinSvc(  752):         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
W/GmsCheckinSvc(  752):         at android.os.Handler.dispatchMessage(Handler.java:102)
W/GmsCheckinSvc(  752):         at android.os.Looper.loop(Looper.java:136)
W/GmsCheckinSvc(  752):         at android.os.HandlerThread.run(HandlerThread.java:61)
^C
130|root@p880:/ #
```

**Comment by pejakm** [comment]
So I guess I'm affected by this bug. :(

**Comment by mar-v-in** [comment]
Yes, Google changed something in their servers I need to adopt, all µg users will be affected as well sooner or later.

**Comment by pejakm** [comment]
If I can help somehow, please, let me know.

**Comment by mar-v-in** [comment]
This should be fixed in the latest version. Can you please try again with the latest build from http://files.brnmod.rocks/apps/GmsCore/Latest/ ?

**Comment by pejakm** [comment]
Right away, will report back soon.

**Comment by pejakm** [comment]
Whatever I try, I only get "This app requires Google Play services installed".

**Comment by mar-v-in** [comment]
Can you update again? And remember to reboot after updating

**Comment by dajoe** [comment]
Since commit https://github.com/microg/android_packages_apps_GmsCore/commit/cd9d38b70b39ccd3b7f739be04602188b6cf3fe7, gcm works just fine. TextSecure works like a charm on two CM 12.1 devices, one patched, one with the xposed module by thermatk.

**Comment by mar-v-in** [comment]
Awesome. I'll close this one then.

**Comment by pejakm** [comment]
After @dajoe's comment I realized that my current rom is not patched. I'm gonna try with the Xposed module and report back.

**Comment by pejakm** [comment]
Sorry, can't use Xposed. Where can I find required patch?

**Comment by nu11point3r** [comment]
It is in the root of the repo. https://github.com/microg/android_packages_apps_GmsCore/blob/master/android_frameworks_base%2BFAKE_PACKAGE_SIGNATURE.patch

**Comment by pejakm** [comment]
Thanks!

**Comment by pejakm** [comment]
@mar-v-in I finally got my hands on a [patched rom](http://forum.xda-developers.com/showpost.php?p=62200262&postcount=1222), and I cannot get this to work. Checkin does not report revious error, I have installed FakeStore, installed microgravity to root, but can't get TextSecure to work. Registration to server succeeds, but after that it wont start claiming there is no network connection. I'm not sure how to test other apps, Viber and WhatsApp seems to work like they used to (i reinstalled them).

**Comment by bonanza123** [comment]
@pejakm can you provide some logs? Have you tried following the instructions at https://github.com/thermatk/FakeGApps/blob/master/README.md?

**Comment by dajoe** [comment]
From my experience, if registration with the Textsecure Server works, this is an indication that gcm is setup correctly. Maybe this is an issue with Textsecure itself. 

I use the app Push Notification Tester from play store to test gcm functionality.

**Comment by pejakm** [comment]
@bonanza123 Like I've said, patched rom, no need for Xposed modules. Compiled and installed FakeStore from microg repo, but I didn't try placing it in system partition.

@dajoe Thanks, I'm gonna try with that.

I'll post logs as soon as I "catch" anything usefull.

**Comment by pejakm** [comment]
The second try with TextSecure was succesfull. :) I upgraded it, and now works! This is awesome!

**Comment by pejakm** [comment]
I added my gmail account and installed YouTube app, and everything works!
