### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find "libvtm-jni.so"

### ISSUE THREAD

**Issue by julienschmidt** [microg/android_packages_apps_GmsCore#19]
I'm running CM 12.1 BACON nightlies with Xposed and https://github.com/thermatk/FakeGApps for signature faking. I'm using the builds from http://files.brnmod.rocks/apps/GmsCore/Latest/.

[This App](https://play.google.com/store/apps/details?id=com.valuephone.vpmarktkauf) crashes when it tries to show a map, with `java.lang.UnsatisfiedLinkError` since `libvtm-jni.so` can not be found.

```
W/ResourcesManager( 9647): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
D/MapFragmentImpl( 9647): onInflate
D/MapFragmentImpl( 9647): onCreate
D/AndroidRuntime( 9647): Shutting down VM
E/AndroidRuntime( 9647): FATAL EXCEPTION: main
E/AndroidRuntime( 9647): Process: com.valuephone.vpmarktkauf, PID: 9647
E/AndroidRuntime( 9647): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/app/play-services-core-debug.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libvtm-jni.so"
E/AndroidRuntime( 9647): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime( 9647): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 9647): 	at org.oscim.android.MapView.<clinit>(MapView.java:52)
E/AndroidRuntime( 9647): 	at org.microg.gms.maps.BackendMap.<init>(BackendMap.java:61)
E/AndroidRuntime( 9647): 	at org.microg.gms.maps.GoogleMapImpl.<init>(GoogleMapImpl.java:87)
E/AndroidRuntime( 9647): 	at org.microg.gms.maps.MapFragmentImpl.onCreateView(MapFragmentImpl.java:74)
E/AndroidRuntime( 9647): 	at com.google.android.gms.maps.internal.IMapFragmentDelegate$Stub.onTransact(IMapFragmentDelegate.java:104)
E/AndroidRuntime( 9647): 	at android.os.Binder.transact(Binder.java:380)
E/AndroidRuntime( 9647): 	at com.google.android.gms.maps.a.l.a(Unknown Source)
E/AndroidRuntime( 9647): 	at com.google.android.gms.maps.k.a(Unknown Source)
E/AndroidRuntime( 9647): 	at com.google.android.gms.a.f.b(Unknown Source)
E/AndroidRuntime( 9647): 	at com.google.android.gms.a.b.a(Unknown Source)
E/AndroidRuntime( 9647): 	at com.google.android.gms.a.b.a(Unknown Source)
E/AndroidRuntime( 9647): 	at com.google.android.gms.maps.SupportMapFragment.onCreateView(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.Fragment.performCreateView(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.addFragment(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentActivity.onCreateView(Unknown Source)
E/AndroidRuntime( 9647): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
E/AndroidRuntime( 9647): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 9647): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 9647): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime( 9647): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:650)
E/AndroidRuntime( 9647): 	at android.view.LayoutInflater.inflate(<Xposed>)
E/AndroidRuntime( 9647): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 9647): 	at com.valuephone.stores.ui.ac.onCreateView(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.Fragment.performCreateView(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source)
E/AndroidRuntime( 9647): 	at android.support.v4.app.FragmentActivity.onStart(Unknown Source)
E/AndroidRuntime( 9647): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
E/AndroidRuntime( 9647): 	at android.app.Activity.performStart(Activity.java:6006)
E/AndroidRuntime( 9647): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)
E/AndroidRuntime( 9647): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
E/AndroidRuntime( 9647): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 9647): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 9647): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9647): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 9647): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 9647): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9647): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9647): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 9647): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 9647): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```
Is this a bug or does one need to install more files than just the APK?

**Comment by julienschmidt** [comment]
It seems to work after I copied https://github.com/hjanetzek/vtm-ext-libs/blob/master/vtm-android/armeabi-v7a/libvtm-jni.so to /system/lib

**Comment by mar-v-in** [comment]
This happens once you install the gmscore apk to /system/app. Libs in apks in /system/app need to be extracted to /system/lib. If you install the apk as a normal application, this problem should not occur.

**Comment by julienschmidt** [comment]
Now I installed µg as a normal app. But now the Location provider settings are gone. I guess for the same reason as stated here: http://forum.xda-developers.com/showpost.php?p=61510899&postcount=1060

I'm using Cyanogen Mod instead of Omnirom. So I guess my options are a) no settings b) install in /system/app and manually install libs?

**Comment by julienschmidt** [comment]
How about making the Location Settings also available from the Settings App?

**Comment by mar-v-in** [comment]
Running `am start com.google.android.gms/org.microg.nlp.ui.SettingsActivity` is a work-around until its fixed. It will be part of the Settings App in the next build.

**Comment by julienschmidt** [comment]
Thanks!
