### ISSUE TITLE
Shazam crashes

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#213]
I have CM13 without GApps and use FakeGapps via XPosed. Shazam crashes immediately after I start it:

```
10-08 00:47:44.406   948  1573 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.shazam.android/.activities.SplashActivity bnds=[1190,1083][1425,1409] (has extras)} from uid 10029 on display 0
10-08 00:47:44.474   948 10862 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x4000000 cmp=com.shazam.android/.activities.MainActivity (has extras)} from uid 10101 on display 0
10-08 00:47:44.578   948   959 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.579   948  2028 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.579   948  1756 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.581 30958 30958 E AdColony: Null App ID - disabling AdColony.
10-08 00:47:44.584   948  1189 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.584   948 11025 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.585   948  7866 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.585   948   960 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.606   948  2028 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.621   948 21593 D NetlinkSocketObserver: NeighborEvent{elapsedMs=355930899, fe80::f6f2:6dff:fe55:2698, [F4F26D552698], RTM_NEWNEIGH, NUD_REACHABLE}
10-08 00:47:44.629   948  1639 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=30958, uid=10101 requires com.google.android.c2dm.permission.RECEIVE
10-08 00:47:44.667 30958 31133 I FA      : Tag Manager is not found and thus will not be used
--------- beginning of crash
10-08 00:47:44.672 30958 30988 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
10-08 00:47:44.672 30958 30988 E AndroidRuntime: Process: com.shazam.android, PID: 30958
10-08 00:47:44.672 30958 30988 E AndroidRuntime: Theme: themes:{}
10-08 00:47:44.672 30958 30988 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1255)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1232)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:587)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at com.google.android.gms.b.a.a(Unknown Source)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at com.google.android.gms.b.a.a(Unknown Source)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at com.shazam.android.service.gcm.c$a.a(SourceFile:67)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at com.shazam.android.service.gcm.c$a.doInBackground(SourceFile:52)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-08 00:47:44.672 30958 30988 E AndroidRuntime: 	... 4 more
10-08 00:47:44.675   948  7866 W ActivityManager:   Force finishing activity com.shazam.android/.activities.MainActivity
10-08 00:47:44.701 30958 31142 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
10-08 00:47:44.707   948  1756 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.710   948 11025 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.711   948   960 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.735   948 21230 I OpenGLRenderer: Initialized EGL, version 1.4
10-08 00:47:44.754 30958 31007 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
10-08 00:47:44.757  2679 31151 I Thermal-Lib: Thermal-Lib-Client: Client request sent
10-08 00:47:44.757   280   363 I ThermalEngine: Thermal-Server: Thermal received msg from  override
10-08 00:47:44.823 31134 31134 W LongWork-0: type=1400 audit(0.0:313005): avc: denied { ioctl } for path="socket:[2235622]" dev="sockfs" ino=2235622 ioctlcmd=8927 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=tcp_socket permissive=0
10-08 00:47:44.881   948  1189 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.881   948  1210 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.882   948  1639 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:44.992   948 11025 W ActivityManager: Unable to start service Intent { act=com.shazam.android pkg=com.shazam.android } U=0: not found
10-08 00:47:44.992 30958 31007 I c*.g*.i*.p*.e: Proxmity Service started by com.shazam.android
10-08 00:47:45.100   948   962 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{84312c7 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{6ee56e1 30958 com.shazam.android/10101/u0 remote:8d97848}: process crashing
10-08 00:47:45.135   948 10065 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:45.136   948  1573 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:45.137   948 10862 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:45.138 30958 30958 I WebViewFactory: Loading com.android.webview version 51.0.2704.106 (code 1)
10-08 00:47:45.182 30958 30958 W System  : ClassLoader referenced unknown path: /system/app/webview/lib/arm
10-08 00:47:45.194 30958 30958 I cr_LibraryLoader: Time to load native libraries: 3 ms (timestamps 4363-4366)
10-08 00:47:45.195 30958 30958 I cr_LibraryLoader: Expected native library version number "51.0.2704.106", actual native library version number "51.0.2704.106"
10-08 00:47:45.206 30958 30958 V WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {9273d85}
10-08 00:47:45.206 30958 30958 I cr_LibraryLoader: Expected native library version number "51.0.2704.106", actual native library version number "51.0.2704.106"
10-08 00:47:45.206 30958 30958 I chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
10-08 00:47:45.220 30958 30958 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
10-08 00:47:45.228 30958 30958 E ApkAssets: Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
10-08 00:47:45.228 30958 30958 E ApkAssets: Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
10-08 00:47:45.239 30958 30958 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
10-08 00:47:45.239 30958 30958 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
10-08 00:47:45.239 30958 30958 I Adreno-EGL: Build Date: 11/17/15 Tue
10-08 00:47:45.239 30958 30958 I Adreno-EGL: Local Branch: mybranch16463693
10-08 00:47:45.239 30958 30958 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.4
10-08 00:47:45.239 30958 30958 I Adreno-EGL: Local Patches: NONE
10-08 00:47:45.239 30958 30958 I Adreno-EGL: Reconstruct Branch: NOTHING
10-08 00:47:45.287 30958 30958 I cr_DRP  : No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
10-08 00:47:45.289   948   967 D BluetoothManagerService: Message: 20
10-08 00:47:45.290   948   967 D BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@673c442:true
10-08 00:47:45.295   948   962 W BroadcastQueue: Skipping deliver [foreground] BroadcastRecord{f3b9e45 u-1 android.media.ACTION_SCO_AUDIO_STATE_UPDATED} to ReceiverList{9f4eaaf 30958 com.shazam.android/10101/u0 remote:7fde28e}: process crashing
10-08 00:47:45.309   948   962 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{66b8043 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{f3c50fd 30958 com.shazam.android/10101/u0 remote:a70d954}: process crashing
10-08 00:47:45.311   948  2028 D ConnectivityService: listenForNetwork for Listen from uid/pid:10101/30958 for NetworkRequest [ id=120, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
10-08 00:47:45.321 30958 30958 D cr_Ime  : [InputMethodManagerWrapper.java:30] Constructor
10-08 00:47:45.329 30958 30958 W cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
10-08 00:47:45.331 30958 30958 D cr_Ime  : [InputMethodManagerWrapper.java:59] isActive: false
10-08 00:47:45.336   948   962 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{83b9d4a u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{c7dfeec 30958 com.shazam.android/10101/u0 remote:3bbdd9f}: process crashing
10-08 00:47:45.370 30958 30958 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-08 00:47:45.372   948   962 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{69acff0 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{9b28ba2 30958 com.shazam.android/10101/u0 remote:a28736d}: process crashing
10-08 00:47:45.422  1733  1978 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-08 00:47:45.422  1733  1978 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-08 00:47:45.467   948  7942 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:45.468   948   960 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:45.472   948  1742 I Xposed  : FakeGApps: returning fake signature to com.shazam.android
10-08 00:47:45.501   948   962 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{7c64ca1 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{dce42ab 30958 com.shazam.android/10101/u0 remote:d9decfa}: process crashing
10-08 00:47:45.502   948  1619 D ConnectivityService: listenForNetwork for Listen from uid/pid:10101/30958 for NetworkRequest [ id=121, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
10-08 00:47:45.643 15719 31185 D com.gsamlabs.bbm.lib.NotifyingService: ===:59:3937:25.3:2
10-08 00:47:45.958   280   363 I ThermalEngine: Thermal-Server: Thermal received msg from  override
10-08 00:47:45.959  2679 31189 I Thermal-Lib: Thermal-Lib-Client: Client request sent
```

It works fine if I disable FakeGapps in XPosed and reboot.

**Comment by mar-v-in** [comment]
Did you install Shazam before or after microG Services Core. If first, please try to reinstall Shazam.

**Comment by Torvin** [comment]
Thanks, that helped.
