### ISSUE TITLE
maps/location API crashes on 4.1.2, 4.2, 4.4.2

### ISSUE THREAD

**Issue by axydavid** [microg/android_packages_apps_GmsCore#219]
Hi, after I install the gsmscore app, all apps requiring the maps API just crash.
removing gmscore makes those apps work again
Possibly related to #203 but not sure

**Comment by ale5000-git** [comment]
Hi, I suggest to post a logcat, a report so generic isn't useful.

**Comment by axydavid** [comment]
So I thiught it was just a rom, but I have experienced the same error on different roms based on differend CM.
Here's a logcat that is related to the error:
`
[ 11-02 02:21:10.415  2633: 2648 E/AndroidRuntime ]

FATAL EXCEPTION: Thread-155

Process: de.hafas.android.rejseplanen, PID: 2633

java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } without permission com.google.android.c2dm.permission.RECEIVE

	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1534)

	at android.app.ContextImpl.startService(ContextImpl.java:1511)

	at android.content.ContextWrapper.startService(ContextWrapper.java:494)

	at com.google.android.c2dm.a.a(ProGuard:73)

	at de.hafas.main.HafasApp.e(ProGuard:362)

	at de.hafas.app.ae.run(ProGuard:3462)

	at java.lang.Thread.run(Thread.java:841)`

**Comment by axydavid** [comment]
As far as I see this is a permission issue, I wonder if it has something to do with the declarations in the XML file?

**Comment by axydavid** [comment]
Here is the logcat when the application starts, without the gmscore installed 

> [ 11-02 14:19:53.131  2494: 2553 W/ContextImpl ]
Implicit intents with startService are not safe: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } android.content.ContextWrapper.startService:494 com.google.android.c2dm.a.a:73 de.hafas.main.HafasApp.e:362

[ 11-02 14:19:53.141   653:  664 W/ActivityManager ]
Unable to start service Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } U=0: not found

**Comment by mar-v-in** [comment]
The logcat you provided suggests that the DB app was installed before microG Services Core. if this is the case, reinstall the DB app (don't need to uninstall it, just install the same apk again)

**Comment by axydavid** [comment]
I did try to reinstall the app, uninstalling then reinstalling, same error.

**Comment by mar-v-in** [comment]
Sorry if it was unclear before, I meant you to reinstall the rejseplanen app, not the microG app. rejseplanen app does work well for me including the maps part of it (map is a bit buggy, but that is the case for all apps using maps right now) on latest microG preview release (0.2.4-27).

**Comment by axydavid** [comment]
Yes' of course, I understood you man, no problem :)
No, on some roms it works, on others it doesn't, I don't understand it why.
Yet on the same roms that this doesn't work, google play services work.
So I am confused.
As I said in my initial post, it is not related to the Rejseplannen itself, but most apps using the services will crash.

**Comment by axydavid** [comment]
```
[ 11-16 03:17:34.013   947: 1287 I/ActivityManager ]
Start proc de.hafas.android.rejseplanen for activity de.hafas.android.rejseplanen/de.hafas.main.HafasApp: pid=12872 uid=10105 gids={50105, 3003, 1015, 1028}

[ 11-16 03:17:34.033   947:12871 I/UsageStats ]
Deleting usage file : usage-20161110

[ 11-16 03:17:34.203 12872:12872 W/Trace    ]
error opening trace file: No such file or directory (2)

[ 11-16 03:17:34.564 12872:12874 D/dalvikvm ]
JIT code cache reset in 0 ms (0 bytes 4/0)

[ 11-16 03:17:34.934 12872:12872 I/dalvikvm ]
DexOpt: illegal method access (call Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V from Landroid/content/res/XResources$XTypedArray;)

[ 11-16 03:17:34.934 12872:12872 I/dalvikvm ]
Could not find method android.content.res.TypedArray.<init>, referenced from method android.content.res.XResources$XTypedArray.<init>

[ 11-16 03:17:34.934 12872:12872 W/dalvikvm ]
VFY: unable to resolve direct method 82: Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V

[ 11-16 03:17:34.934 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x70 at 0x0002

[ 11-16 03:17:35.585 12872:12872 I/dalvikvm ]
Could not find method android.view.ViewGroup.onNestedScrollAccepted, referenced from method android.support.v7.internal.widget.ActionBarOverlayLayout.onNestedScrollAccepted

[ 11-16 03:17:35.595 12872:12872 W/dalvikvm ]
VFY: unable to resolve virtual method 12070: Landroid/view/ViewGroup;.onNestedScrollAccepted (Landroid/view/View;Landroid/view/View;I)V

[ 11-16 03:17:35.595 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x6f at 0x0000

[ 11-16 03:17:35.595 12872:12872 I/dalvikvm ]
Could not find method android.view.ViewGroup.onStopNestedScroll, referenced from method android.support.v7.internal.widget.ActionBarOverlayLayout.onStopNestedScroll

[ 11-16 03:17:35.595 12872:12872 W/dalvikvm ]
VFY: unable to resolve virtual method 12076: Landroid/view/ViewGroup;.onStopNestedScroll (Landroid/view/View;)V

[ 11-16 03:17:35.595 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x6f at 0x0000

[ 11-16 03:17:35.595 12872:12872 I/dalvikvm ]
Could not find method android.support.v7.internal.widget.ActionBarOverlayLayout.stopNestedScroll, referenced from method android.support.v7.internal.widget.ActionBarOverlayLayout.setHideOnContentScrollEnabled

[ 11-16 03:17:35.595 12872:12872 W/dalvikvm ]
VFY: unable to resolve virtual method 9416: Landroid/support/v7/internal/widget/ActionBarOverlayLayout;.stopNestedScroll ()V

[ 11-16 03:17:35.595 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x6e at 0x000e

[ 11-16 03:17:35.615 12872:12872 I/dalvikvm ]
Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations

[ 11-16 03:17:35.615 12872:12872 W/dalvikvm ]
VFY: unable to resolve virtual method 511: Landroid/content/res/TypedArray;.getChangingConfigurations ()I

[ 11-16 03:17:35.615 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x6e at 0x0002

[ 11-16 03:17:35.625 12872:12872 I/dalvikvm ]
Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType

[ 11-16 03:17:35.625 12872:12872 W/dalvikvm ]
VFY: unable to resolve virtual method 533: Landroid/content/res/TypedArray;.getType (I)I

[ 11-16 03:17:35.625 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x6e at 0x0002

[ 11-16 03:17:35.945   947: 1598 I/Xposed   ]
FakeGApps: returning fake signature to de.hafas.android.rejseplanen

[ 11-16 03:17:35.955   947: 1575 I/Xposed   ]
FakeGApps: returning fake signature to de.hafas.android.rejseplanen

[ 11-16 03:17:36.185   947: 1576 I/Xposed   ]
FakeGApps: returning fake signature to de.hafas.android.rejseplanen

[ 11-16 03:17:36.185   947:  947 I/Xposed   ]
FakeGApps: returning fake signature to de.hafas.android.rejseplanen

[ 11-16 03:17:36.225  9103: 9103 D/GmsLocManagerSvc ]
onBind: Intent { act=com.google.android.location.internal.GoogleLocationManagerService.START pkg=com.google.android.gms }

[ 11-16 03:17:36.826 12872:12872 I/Choreographer ]
Skipped 41 frames!  The application may be doing too much work on its main thread.

[ 11-16 03:17:36.926 12872:12872 D/libEGL   ]
loaded /system/lib/egl/libEGL_adreno200.so

[ 11-16 03:17:36.926 12872:12872 D/libEGL   ]
loaded /system/lib/egl/libGLESv1_CM_adreno200.so

[ 11-16 03:17:36.946 12872:12872 D/libEGL   ]
loaded /system/lib/egl/libGLESv2_adreno200.so

[ 11-16 03:17:36.966 12872:12872 I/Adreno200-EGL ]
<qeglDrvAPI_eglInitialize:294>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB.04.01.01.00.036_msm8960_JB_CL2644550_release_AU (CL2644550)
Build Date: 07/31/12 Tue
Local Branch:
Remote Branch: quic/master
Local Patches: NONE
Reconstruct Branch: AU_LINUX_ANDROID_JB.04.01.01.00.036 +  NOTHING

[ 11-16 03:17:37.106 12872:12872 D/OpenGLRenderer ]
Enabling debug mode 0

[ 11-16 03:17:37.106  9103: 9117 D/GmsLocManagerSvc ]
bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=6587000, packageName='de.hafas.android.rejseplanen', extras=Bundle[{client_name=locationServices}]}

[ 11-16 03:17:37.747 12872:12872 I/Choreographer ]
Skipped 59 frames!  The application may be doing too much work on its main thread.

[ 11-16 03:17:37.857   947:  980 I/ActivityManager ]
Displayed de.hafas.android.rejseplanen/de.hafas.main.HafasApp: +3s879ms

[ 11-16 03:17:38.237 12872:12872 I/dalvikvm ]
Could not find method android.widget.TabHost.<init>, referenced from method de.hafas.ui.view.TabHostView.<init>

[ 11-16 03:17:38.237 12872:12872 W/dalvikvm ]
VFY: unable to resolve direct method 12997: Landroid/widget/TabHost;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;I)V

[ 11-16 03:17:38.237 12872:12872 D/dalvikvm ]
VFY: replacing opcode 0x70 at 0x0000

[ 11-16 03:17:41.070  9103: 9115 D/GmsLocManagerSvcImpl ]
getLastLocationWithPackage: de.hafas.android.rejseplanen

[ 11-16 03:17:41.080  9103: 9115 D/GmsLocProviderReal ]
uh-ok: last location for network is null!

[ 11-16 03:17:41.090  9103: 9115 D/GmsLocProviderReal ]
uh-ok: last location for gps is null!

[ 11-16 03:17:41.090 12872:12872 I/Choreographer ]
Skipped 205 frames!  The application may be doing too much work on its main thread.

[ 11-16 03:17:41.100  9103: 9103 D/GmsAnalyticsSvc ]
onBind: Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) }

[ 11-16 03:17:41.570  9103: 9700 D/GmsLocManagerSvcImpl ]
requestLocationUpdatesWithListener: LocationRequest{priority=100, interval=5000, fastestInterval=5000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}

[ 11-16 03:17:41.570  9103: 9700 D/GmsLocProviderReal ]
gps: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=100, interval=5000, fastestInterval=5000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}

[ 11-16 03:17:41.580  9103: 9700 D/GmsLocProviderReal ]
gps: requesting location updates. minTime=5000 minDistance=0.0

[ 11-16 03:17:41.580  9103: 9700 D/GmsLocProviderReal ]
network: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=100, interval=5000, fastestInterval=5000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}

[ 11-16 03:17:41.590  9103: 9700 D/GmsLocProviderReal ]
network: requesting location updates. minTime=5000 minDistance=0.0

[ 11-16 03:17:41.671 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.671 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.691 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.691 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.701 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.701 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.721 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=15, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.721 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x2-x0>=280, x1-x0>=28, x2-x0<=100 are inconsistent; permanently removing: x2-x0<=100.

[ 11-16 03:17:41.731 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.731 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.741 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.741 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.751 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.761 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.771 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.781 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.791 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x1-x0>=28, x2-x1>=0, x2-x0<=0 are inconsistent; permanently removing: x2-x0<=0.

[ 11-16 03:17:41.801 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=0, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.811 12872:12872 D/android.support.v7.widget.GridLayout ]
vertical constraints: y2-y1>=17, y3-y2>=17, y4-y3>=15, y3-y1<=28, y1-y0<=0 are inconsistent; permanently removing: y3-y1<=28.

[ 11-16 03:17:41.821 12872:12872 D/android.support.v7.widget.GridLayout ]
horizontal constraints: x2-x0>=280, x1-x0>=28, x2-x0<=100 are inconsistent; permanently removing: x2-x0<=100.

[ 11-16 03:17:42.091 12872:12872 D/webviewglue ]
nativeDestroy view: 0x52be1de0
```
A huge logcat when the app starts with microG on a rom that works.

**Comment by axydavid** [comment]
> `java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } without permission com.google.android.c2dm.permission.RECEIVE`
I'm thinking it might have something to do with proguard revoking the permission on this specific intent, but I do not know the ins and outs of android, but it surelly looks like a permission issue

**Comment by axydavid** [comment]
OK, downloaded lastest nightliy gms build:
```
FATAL EXCEPTION: main
java.lang.IllegalArgumentException: requested provider network doesn't exisit
        at android.os.Parcel.readException(Parcel.java:1429)
        at android.os.Parcel.readException(Parcel.java:1379)
        at com.google.android.gms.internal.bi.a(Unknown Source)
        at com.google.android.gms.internal.bj.a(Unknown Source)
        at com.google.android.gms.internal.bm.a(Unknown Source)
        at com.google.android.gms.internal.az.a(Unknown Source)
        at com.google.android.gms.internal.az.b(Unknown Source)
        at com.google.android.gms.common.api.k.a(Unknown Source)
        at com.google.android.gms.common.api.w.a(Unknown Source)
        at com.google.android.gms.common.api.w.a(Unknown Source)
        at com.google.android.gms.internal.ay.a(Unknown Source)
        at de.hafas.e.f.run(ProGuard:146)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4931)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by axydavid** [comment]
A small update, I tested it with some of the roms that the stable version didn't work with and I'm glad o say that it has better compability with different roms :)
Some of them still dont work like the error above, but some of them do now, keep the awesome work bro.

**Comment by mar-v-in** [comment]
the error above should be fixed by a reboot (always take a look at the self-check in microG)

**Comment by axydavid** [comment]
Well I think the issue has indeed been solved by upgrading to the nightly release, finally I can use my favourite rom + open source GMS :) many thanks!
