### ISSUE TITLE
SQL crash (no such function: printf)

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#264]
SQL crash (no such function: printf).

Log:
```
[ 01-08 20:02:00.258  1896: 1913 I/ActivityManager ]
Waited long enough for: ServiceRecord{41e6b698 u0 com.android.vending/com.google.android.finsky.wear.WearSupportService}

[ 01-08 20:02:02.773  3157: 3174 D/SafeParcel ]
Unknown field num 9 in com.google.android.gms.common.internal.GetServiceRequest, skipping.

[ 01-08 20:02:02.773  3157: 3174 D/GmsWearSvc ]
bound by: GetServiceRequest{serviceId=WEARABLE, gmsVersion=9683000, packageName='com.android.vending', extras=Bundle[{}]}

[ 01-08 20:02:02.781  3157: 3168 D/GmsWearSvcImpl ]
getDataItemsByUri: wear:/device_configuration

[ 01-08 20:02:02.914  3157: 3157 E/SQLiteLog ]
(1) no such function: printf

[ 01-08 20:02:02.914  3157: 3157 D/AndroidRuntime ]
Shutting down VM

[ 01-08 20:02:02.914  3157: 3157 W/dalvikvm ]
threadid=1: thread exiting with uncaught exception (group=0x415d7c20)

[ 01-08 20:02:02.914  3157: 3157 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 3157
android.database.sqlite.SQLiteException: no such function: printf (code 1): , while compiling: SELECT null AS host,printf("wear://%s%s",host,path) AS path,data AS data,'' AS tags,assetname AS asset_key,assets_digest AS asset_id FROM dataItemsAndAssets WHERE packageName = ? AND signatureDigest = ? AND path LIKE ? AND deleted=0 AND assetsPresent !=0
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
	at org.microg.gms.wearable.NodeDatabaseHelper.getDataItemsForDataHolderByHostAndPath(NodeDatabaseHelper.java:91)
	at org.microg.gms.wearable.WearableImpl.getDataItemsByUriAsHolder(WearableImpl.java:461)
	at org.microg.gms.wearable.WearableServiceImpl$9.run(WearableServiceImpl.java:187)
	at org.microg.gms.wearable.WearableServiceImpl$CallbackRunnable.run(WearableServiceImpl.java:498)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5179)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)

[ 01-08 20:02:03.016  3157: 3174 D/SafeParcel ]
Unknown field num 9 in com.google.android.gms.common.internal.GetServiceRequest, skipping.

[ 01-08 20:02:03.016  3157: 3174 D/GmsWearSvc ]
bound by: GetServiceRequest{serviceId=WEARABLE, gmsVersion=9683000, packageName='com.android.vending', extras=Bundle[{}]}
```

**Comment by mar-v-in** [comment]
Thanks, no idea how this made it into release

**Comment by ale5000-git** [comment]
@mar-v-in: Why it report "gmsVersion=9683000"?

Ref: #273

**Comment by mar-v-in** [comment]
That's the minimum gms version required by the app accessing the service (in this case the Play Store).
