### ISSUE TITLE
Official Play store crashed

### ISSUE THREAD

**Issue by acsway878787** [microg/android_packages_apps_GmsCore#269]
Phone: Sony XPERIA TX with Android 4.3
microG Services Core: 0.2.4-39

>01-15 16:51:10.289 I/Finsky  (9189): [1] com.google.android.finsky.utils.dm.a(70): Connection with LocationServices established
01-15 16:51:10.299 D/GmsLocManagerSvcImpl(8831): getLastLocationWithPackage: com.android.vending
01-15 16:51:10.299 D/GmsLocProviderReal(8831): uh-ok: last location for network is null!
01-15 16:51:10.299 D/GmsLocProviderReal(8831): uh-ok: last location for gps is null!
01-15 16:51:10.309 I/Finsky  (9189): [1] com.google.android.finsky.utils.dm.a(97): Requesting Location Updates; Interval: 300000
01-15 16:51:10.319 D/SafeParcel(8831): Unknown field num 8 in com.google.android.gms.location.internal.LocationRequestInternal, skipping.
01-15 16:51:10.319 D/GmsLocManagerSvcImpl(8831): updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=102, interval=300000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=false, triggerUpdate=true, clients=[], tag='null', hideFromAppOps=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@427c3138, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@427c32b0}
01-15 16:51:10.319 D/GmsLocProviderReal(8831): network: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=300000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
01-15 16:51:10.319 D/AndroidRuntime(9189): Shutting down VM
01-15 16:51:10.319 W/dalvikvm(9189): threadid=1: thread exiting with uncaught exception (group=0x415a7658)
01-15 16:51:10.329 E/AndroidRuntime(9189): FATAL EXCEPTION: main
01-15 16:51:10.329 E/AndroidRuntime(9189): java.lang.IllegalArgumentException: provider doesn't exisit: null
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at android.os.Parcel.readException(Parcel.java:1448)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at android.os.Parcel.readException(Parcel.java:1395)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.location.internal.s.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.location.internal.e.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.ls.b(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.mm.b(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.mh.b(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.location.internal.d.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.finsky.utils.dm.a(SourceFile:98)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.finsky.utils.dm.a(SourceFile:71)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.mh.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.lv.g(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.lv.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.mm.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.internal.lm.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.common.internal.ah.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.common.internal.v.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.common.internal.m.a(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.google.android.gms.common.internal.p.handleMessage(Unknown Source)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at android.os.Looper.loop(Looper.java:213)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at android.app.ActivityThread.main(ActivityThread.java:5225)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at java.lang.reflect.Method.invoke(Method.java:525)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
01-15 16:51:10.329 E/AndroidRuntime(9189): 	at dalvik.system.NativeStart.main(Native Method)
01-15 16:51:10.339 I/Xposed  (1170): FakeGApps: returning fake signature to com.android.vending
01-15 16:51:10.339 W/ActivityManager(1170):   Force finishing activity com.android.vending/com.google.android.finsky.activities.MainActivity

**Comment by acsway878787** [comment]
@mar-v-in Can you help me with this?
Thank you very much!

**Comment by mar-v-in** [comment]
@acsway878787 Please install UnifiedNlp legacy (from F-Droid), reboot and try again.
