### ISSUE TITLE
Crash on search with Google Play Store 5.4.12

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#277]
Sorry if it isn't microG fault.

Sincerely I'm not sure if it is an incompatibility with microG or a general bug in the Google Play Store apk but when searching I get this:
```
[ 01-20 14:41:26.956  5630: 5630 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.vending, PID: 5630
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.google.android.finsky.protos.SearchSuggest$NavSuggestion.docId' on a null object reference
	at com.google.android.finsky.providers.SearchSuggestionFetcherLegacy.getIconUri(SearchSuggestionFetcherLegacy.java:90)
	at com.google.android.finsky.providers.SearchSuggestionFetcherLegacy.access$200(SearchSuggestionFetcherLegacy.java:34)
	at com.google.android.finsky.providers.SearchSuggestionFetcherLegacy$2.onResponse(SearchSuggestionFetcherLegacy.java:170)
	at com.google.android.finsky.providers.SearchSuggestionFetcherLegacy$2.onResponse(SearchSuggestionFetcherLegacy.java:153)
	at com.google.android.finsky.api.DfeRequest.deliverResponse(DfeRequest.java:597)
	at com.google.android.finsky.api.DfeRequest.deliverResponse(DfeRequest.java:56)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6126)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by 1337sup3rh4x0r** [comment]
I don't have a log of that event, but that happened to me after I didn't allow the Play Store receive Cloud Messages. Do you have that covered?

**Comment by ale5000-git** [comment]
It is registered in GCM and all permissions are granted.

**Comment by be-neth** [comment]
@ale5000-git I had the same error, when using your exact version of the playstore. (Coming from you micro Installer)

I use another one now, for arm64, coming from https://opengapps.org, and it's working fine. (But the version appears to be the same, but Ui is not.)

**Comment by ale5000-git** [comment]
@be-neth: I used Play Store from apkmirror that should be the original version (and pass signature check), the one from GApps are modified I think.

If you have time can you please try the crashing version (from apkmirror) with GApps?
So I can know if the problem is in microG compatibility or in the Play Store itself.

**Comment by be-neth** [comment]
> If you have time can you please try the crashing version (from apkmirror) with GApps?

Sure, but what do you mean by : > with GApps ?
From what I remember the error was the same.

I don't know which key OpenGapps team use to sign Phonesky apk. But I confirm this is working with testkeys ROM build. (Default keys from build/target/product/security/)

**Comment by ale5000-git** [comment]
I mean with official Google Play Service.
If the same error happen with official Google Play Service then it has nothing to do with microG.

I will close this issue, in case someone verify that it works with official Google Play Service, add a comment here.
