### ISSUE TITLE
Cannot install Öffi app with maps support: Some maps pieces missing?

### ISSUE THREAD

**Issue by RalfJung** [microg/android_packages_apps_GmsCore#30]
When I install the "full" version of <http://oeffi.schildbach.de/download.html>, installation fails and the following appears in logcat:

```
W/PackageManager(  890): Package couldn't be installed in /data/app/de.schildbach.oeffi-1
W/PackageManager(  890): com.android.server.pm.PackageManagerException: Package de.schildbach.oeffi requires unavailable shared library com.google.android.maps; failing!
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService.updateSharedLibrariesLPw(PackageManagerService.java:5451)
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:5812)
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5543)
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10966)
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11511)
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService.access$2500(PackageManagerService.java:273)
W/PackageManager(  890):        at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:9410)
W/PackageManager(  890):        at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager(  890):        at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager(  890):        at android.os.Looper.loop(Looper.java:135)
W/PackageManager(  890):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager(  890):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by mar-v-in** [comment]
> https://github.com/mar-v-in/MapsAPI
