### ISSUE TITLE
NullPointerException in GoogleMapsImpl

### ISSUE THREAD

**Issue by YtvwlD** [microg/android_packages_apps_GmsCore#340]
I'm using an app to track workouts and with a current update it crashes on certain screens (the core functionality is still usable).

The logcat I got is this:

```
E/AndroidRuntime(29365): java.lang.NullPointerException
E/AndroidRuntime(29365):        at org.microg.gms.maps.GoogleMapImpl$2.run(GoogleMapImpl.java:553)
E/AndroidRuntime(29365):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(29365):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(29365):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(29365):        at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(29365):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29365):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(29365):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(29365):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(29365):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(29365):        at dalvik.system.NativeStart.main(Native Method)
```

So, apparently it doesn't pass a `callback` to this method:

```
    @Override
    public void setOnMapLoadedCallback(final IOnMapLoadedCallback callback) throws RemoteException {
        Log.d(TAG, "setOnMapLoadedCallback");
        new Handler(context.getMainLooper()).postDelayed(new Runnable() {
            @Override
            public void run() {
                Log.d(TAG, "Announce map loaded");
                try {
                    callback.onMapLoaded();
                } catch (RemoteException e) {
                    Log.w(TAG, e);
                }
            }
        }, 5000);
    }
```

I experience #322 and #179 with this app, too, but they do not lead to crashes.

**Comment by 5005007** [comment]
Confirmed. The same log.

**Comment by pomarec** [comment]
Same log with uber (small cab business) app when map finish loading

**Comment by pomarec** [comment]
I replaced
```java
callback.onMapLoaded();
```
with 
```java
if (callback != nil) {
    callback.onMapLoaded();
}
```
It works but map sometimes does not show properly. Idk if it's the proper fix.

**Comment by alinefr** [comment]
As @pomarec did, by checking if `callback` is `nil` the latest uber release is working now. I did it this way:
```
diff --git a/play-services-core/src/main/java/org/microg/gms/maps/GoogleMapImpl.java b/play-services-core/src/main/java/org/microg/gms/maps/GoogleMapImpl.java
index 11aa616..060ed7e 100644
--- a/play-services-core/src/main/java/org/microg/gms/maps/GoogleMapImpl.java
+++ b/play-services-core/src/main/java/org/microg/gms/maps/GoogleMapImpl.java
@@ -545,10 +545,12 @@ public class GoogleMapImpl extends IGoogleMapDelegate.Stub
             @Override
             public void run() {
                 Log.d(TAG, "Announce map loaded");
-                try {
-                    callback.onMapLoaded();
-                } catch (RemoteException e) {
-                    Log.w(TAG, e);
+                if (callback != null) {
+                    try {
+                        callback.onMapLoaded();
+                    } catch (RemoteException e) {
+                        Log.w(TAG, e);
+                    }
                 }
             }
         }, 5000);
```

**Comment by ale5000-git** [comment]
@alinefr: It would be nice if you submit a pull request.
