### ISSUE TITLE
Device does not have package com.google.android.gsf

### ISSUE THREAD

**Issue by julienschmidt** [microg/android_packages_apps_GmsCore#36]
I'm running µg with the xposed signature faker module. Most apps work fine so far :+1: 

But the German McDonalds app keeps crashing (new install, first run):
```
E/AndroidRuntime(21416): FATAL EXCEPTION: IntentService[GCMRegistrationService]
E/AndroidRuntime(21416): Process: de.mcdonalds.mcdonaldsinfoapp, PID: 21416
E/AndroidRuntime(21416): java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
E/AndroidRuntime(21416): 	at com.google.android.gcm.GCMRegistrar.checkDevice(GCMRegistrar.java:98)
E/AndroidRuntime(21416): 	at de.mcdonalds.mcdonaldsinfoapp.service.gcm.GCMRegistrationService.onHandleIntent(GCMRegistrationService.java:29)
E/AndroidRuntime(21416): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime(21416): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21416): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21416): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```
Any idea what could be the reason and how it could be fixed? As I understand it, µg should be a replacement for com.google.android.gsf, therefore it should be available, or not?

**Comment by bonanza123** [comment]
I guess you need https://github.com/microg/android_packages_apps_GsfProxy
you can build it using gradle

**Comment by bonanza123** [comment]
I made a (untested) build:
http://d-h.st/wGoX

**Comment by julienschmidt** [comment]
Seems to work! Thanks!
