### ISSUE TITLE
Can't log in to google account already added in system settings.

### ISSUE THREAD

**Issue by UnicodeAlt255** [microg/android_packages_apps_GmsCore#363]
Apps such as chrome and calendar try to log me in, but if I put in my credentials it will say that the account is already on the device, and there is no option to select an account already on the device.

**Comment by mar-v-in** [comment]
You need to grant contacts permission manually to Google apps (via system settings) so that they can see the account.

**Comment by UnicodeAlt255** [comment]
Already granted all permissions to AOSP calendar and Etar, no change

**Comment by mar-v-in** [comment]
Ah. microG does not provide contact/calendar data to the relevant system services. If you want to use your Google calendar/contacts, read about it in #222, if you want to use offline or CalDAV calendars, there are separate apps for this in F-Droid.

**Comment by UnicodeAlt255** [comment]
Ok thanks. Where can I get the GoogleContactsSyncAdapter.apk?

**Comment by ale5000-git** [comment]
Here: http://www.apkmirror.com/apk/google-inc/google-contacts-sync/

**Comment by mirh** [comment]
> http://www.apkmirror.com/apk/google-inc/google-contacts-sync/

4.0.4 version crashes for me on sync, complaining about 

````
W/AccountManagerService( 1877):   caller uid 10047 lacks any of android.permission.GET_ACCOUNTS
W/dalvikvm( 2930): threadid=13: thread exiting with uncaught exception (group=0x40a6c1f8)
E/AndroidRuntime( 2930): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime( 2930): java.lang.SecurityException: caller uid 10047 lacks any of android.permission.GET_ACCOUNTS
E/AndroidRuntime( 2930):        at android.os.Parcel.readException(Parcel.java:1327)
E/AndroidRuntime( 2930):        at android.os.Parcel.readException(Parcel.java:1281)
E/AndroidRuntime( 2930):        at android.accounts.IAccountManager$Stub$Proxy.getAccounts(IAccountManager.java:475)
E/AndroidRuntime( 2930):        at android.accounts.AccountManager.getAccountsByType(AccountManager.java:400)
E/AndroidRuntime( 2930):        at com.google.android.syncadapters.contacts.ContactsSyncAdapter.innerPerformSync(ContactsSyncAdapter.java:236)
E/AndroidRuntime( 2930):        at com.google.android.syncadapters.contacts.ContactsSyncAdapter.onPerformLoggedSync(ContactsSyncAdapter.java:180)
E/AndroidRuntime( 2930):        at com.google.android.common.LoggingThreadedSyncAdapter.onPerformSync(LoggingThreadedSyncAdapter.java:33)
E/AndroidRuntime( 2930):        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)

**Comment by ale5000-git** [comment]
@mirh: You could try to use [my installers](https://forum.xda-developers.com/showthread.php?t=3432360) (microG unofficial installer and Google Sync Add-on) that setup everything automatically.

**Comment by mirh** [comment]
Microg self-check gave me ok to everything but unifiednlp (fairly since I hadn't installed it)
Then, I guess like google sync add-on could help in this regard, but it definitively isn't going to work on ics.

**Comment by ale5000-git** [comment]
Unfortunately now I can't try ICS (because I don't have any device with it) but if I find an emulator with it then I can discover the problem and fix it.

**Comment by AzzyC** [comment]
I had this exact problem and I had fixed it by pushing a contacts-calenderssync.xml file (you may find a similar file) and pushing it to system/etc/permissions
