### ISSUE TITLE
Feature request: Add dummy com.google.android.gms.googlecertificates

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#373]
Please add dummy googlecertificates to avoid these problems:

```
[ 05-13 23:13:18.613  4998: 6837 W/DynamiteModule ]
Local module descriptor class for com.google.android.gms.googlecertificates not found.

[ 05-13 23:13:18.614  4998: 6837 D/GmsDynamiteLoaderImpl ]
unimplemented Method: getModuleVersion for com.google.android.gms.googlecertificates

[ 05-13 23:13:18.614  4998: 6837 I/DynamiteModule ]
Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:0

[ 05-13 23:13:18.615  4998: 6837 E/GoogleCertificates ]
Failed to load com.google.android.gms.googlecertificates
com.google.android.gms.dynamite.i: No acceptable module found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source)
	at com.google.android.gms.common.o.bsy(Unknown Source)
	at com.google.android.gms.common.o.a(Unknown Source)
	at com.google.android.gms.common.i.b(Unknown Source)
	at com.google.android.gms.common.i.a(Unknown Source)
	at com.google.android.gms.common.i.oI(Unknown Source)
	at com.google.android.libraries.f.d.c.h.e(SourceFile:13)
	at com.google.android.apps.gsa.search.core.v.bZ(SourceFile:114)
	at com.google.android.apps.gsa.search.core.v.i(SourceFile:111)
	at com.google.android.apps.gsa.assistant.settings.a.run(SourceFile:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at com.google.android.apps.gsa.shared.util.concurrent.a.ax.run(SourceFile:14)
	at com.google.android.apps.gsa.shared.util.concurrent.a.bl.run(SourceFile:4)
	at com.google.android.apps.gsa.shared.util.concurrent.a.bl.run(SourceFile:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
	at com.google.android.apps.gsa.shared.util.concurrent.a.ai.run(SourceFile:6)

[ 05-13 23:13:18.615  4998: 6837 D/GoogleSignatureVerifier ]
Cert not in list. atk=false
```

**Comment by ale5000-git** [comment]
Seems to be implemented here: bf88e7c8bd5968b880bd4ba617c91b83587c8a2c

I have no time to test it currently, but I will reopen it in case it isn't fixed.
