### ISSUE TITLE
App crashing after installing GMS on CM11

### ISSUE THREAD

**Issue by axydavid** [microg/android_packages_apps_GmsCore#377]
Hi, so my apps are crashing, it's relying on the gms, on some ROMS it's  working, on others it's crashing, I'm using CM11 right now and it's crashing, here's the logcat, I have the latest nightly edition of GMS:
`
W/dalvikvm( 1474): threadid=11: thread exiting with uncaught exception (group=0x418e3ce0)
W/ActivityManager(  419): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=1474, uid=10063 requires com.google.android.c2dm.permission.RECEIVE
D/GmsAnalyticsSvc(  587): onBind: Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) }
E/AndroidRuntime( 1474): FATAL EXCEPTION: Thread-112
E/AndroidRuntime( 1474): Process: de.hafas.android.rejseplanen, PID: 1474
E/AndroidRuntime( 1474): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime( 1474):        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1567)
E/AndroidRuntime( 1474):        at android.app.ContextImpl.startService(ContextImpl.java:1544)
E/AndroidRuntime( 1474):        at android.content.ContextWrapper.startService(ContextWrapper.java:494)
E/AndroidRuntime( 1474):        at com.google.android.c2dm.a.a(ProGuard:73)
E/AndroidRuntime( 1474):        at de.hafas.main.HafasApp.e(ProGuard:362)
E/AndroidRuntime( 1474):        at de.hafas.app.ae.run(ProGuard:3462)
E/AndroidRuntime( 1474):        at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  419):   Force finishing activity de.hafas.android.rejseplanen/de.hafas.main.HafasApp
W/chromium( 1474): [WARNING:proxy_service.cc(890)] PAC support disabled because there is no system implementation`

**Comment by axydavid** [comment]
Nevermind, I researched deeper, seems I innstalled my app before GMS
