### ISSUE TITLE
OWS Signal 4.6.0 declines to use microG Services Core 0.2.4-92-g3669bab, says version is too low

### ISSUE THREAD

**Issue by miketv-s** [microg/android_packages_apps_GmsCore#386]
I'm having issues using Signal with microG.
Problems match those described in https://github.com/WhisperSystems/Signal-Android/issues/6392

moxie0 comments on the issue there:
>[the problems started when OWS updated the version of GMS used in Signal, so] I assume microG isn't properly reporting that it is API compatible with the updated version.

That hypothesis is supported on my device (i9300, Replicant 6.0) by the Signal debug log, which includes:
```
3593  3610 W GcmRefreshJob: Reregistering GCM...
3593  3610 W GooglePlayServicesUtil: Google Play services out of date.  Requires 9683000 but found 9258259
```

MicroG in itself appears to install well. Installed via F-Droid. The self tests are OK.

From a user perspective it seems like the easiest way out of this problem would be if microG reported a higher version. While looking for a solution I saw some comments about other programs complaining about outdated services as well.
Could you make this change? Could I myself work around the issue somehow?

**Comment by n76** [comment]
Hmmm. I am running Signal 4.6.1 with microG with no issues. Are you running the latest 0.2.4-92-g3669bab version of microG? If not, that is probably your problem.

**Comment by miketv-s** [comment]
Thanks for your quick reply n76.

The microG  version is 0.2.4-92-g3669bab, yes, installed through F-Droid via the microG repository.
I probably should add that strictly speaking I am now using LibreSignal 4.6.0 from the Eutopia repository, and that is what the log excerpt is from. But the error messages and lack of response to attempts to fix it are effectively indistinguishable from my attempts with the standalone APK from Open Whisper Systems about 10 days ago (same version as is listed there now, Signal 4.5.3).

What's amazing is that as I'm making another attempt now, "Google Cloud Messaging", in the microG settings application, suddenly reports LibreSignal as registered, it does not give the complaint message about "communication failure" on system reboot, and the debug log does now not have the second line I posted. This state looks much more promising for working.

I've spent several days over the last few weeks trying to fix this and must have been though half a dozen or so installations of microG alone. Little seems different from the last few times, and nothing seems different from the very latest time (I had only disabled microG and the signature spoofing, not uninstalled it). I very much regret that I don't have a good explanation for the difference. 

I will get someone to help me test the functionality and report back here.

**Comment by n76** [comment]
For apps to properly register for push messaging they need to be installed after microG gmscore. Maybe that was your issue.

**Comment by ale5000-git** [comment]
@miketv-s: Probably you think you have got the latest version but it isn't.
The log message clearly demonstrate that you haven't the latest version.

**Comment by miketv-s** [comment]
> For apps to properly register for push messaging they need to be installed after microG gmscore. Maybe that was your issue.
Important point, but also one that's very clear from the installation instructions, and I've been considering that throughout the attempts.
The only difference I've come to think of is that this time I also re-registered with the Signal server.

Anyway, using Signal still doesn't fully work, but now my issue is that the program crashes when trying to make a call, and I don't see anything specific to indicate that this is a microG problem.

**Comment by miketv-s** [comment]
@ale5000-git , that could make sense as an explanation actually.
I enabled "unstable updates" in F-Droid at some point recently and it's still active. So maybe one reason it's suddenly working now is that it was now able to pull down the preview builds as well, but hadn't done it yet when I made the attempts that go with the log. 
I'm fairly sure I enabled it precisely to try with latest microG and would have thought I did that right away at the time, but I honestly can't say for sure, and there's always the possibility I did but something else went wrong.

I think it's fair to say that invalidates this issue report as it stands, but maybe it would be good to add a remark about this in the installation instructions so new users getting burned by the same issue can get out of the fire easier.

**Comment by n76** [comment]
> Anyway, using Signal still doesn't fully work, but now my issue is that the program crashes when trying to make a call, and I don't see anything specific to indicate that this is a microG problem.

Capturing a logcat when Signal crashes would be the next step.

FWIW, I've updated Signal from 4.6.0 to 4.6.1 since I last had a signal call, but I had no issue with either voice only or video calling using Signal with microG.

**Comment by ale5000-git** [comment]
@miketv-s: As n76 said it would be usefull a new logcat during the crash.

**Comment by miketv-s** [comment]
Logcat... OK. Do I want to filter that on something? 
It spews 17000 lines in a few seconds of runtime.

This bit looks relevant.
```
00.486	4221  4221 E AndroidRuntime: FATAL EXCEPTION: main
00.486	4221  4221 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4221
00.486	4221  4221 E AndroidRuntime: Theme: themes:{}
00.486	4221  4221 E AndroidRuntime: java.lang.RuntimeException: Unable to find any matching EGL config
00.486	4221  4221 E AndroidRuntime:		at org.webrtc.EglBase14.getEglConfig(EglBase14.java:236)
00.486	4221  4221 E AndroidRuntime:		at org.webrtc.EglBase14.<init>(EglBase14.java:57)
00.486	4221  4221 E AndroidRuntime:		at org.webrtc.EglBase.create(EglBase.java:86)
00.486	4221  4221 E AndroidRuntime:		at org.webrtc.EglBase.create(EglBase.java:93)
00.486	4221  4221 E AndroidRuntime:		at org.thoughtcrime.securesms.service.WebRtcCallService$7.run(WebRtcCallService.java:835)
00.486	4221  4221 E AndroidRuntime:		at org.thoughtcrime.securesms.util.Util$2.run(Util.java:396)
00.486	4221  4221 E AndroidRuntime:		at android.os.Handler.handleCallback(Handler.java:739)
00.486	4221  4221 E AndroidRuntime:		at android.os.Handler.dispatchMessage(Handler.java:95)
00.486	4221  4221 E AndroidRuntime:		at android.os.Looper.loop(Looper.java:148)
00.486	4221  4221 E AndroidRuntime:		at android.app.ActivityThread.main(ActivityThread.java:5461)
00.486	4221  4221 E AndroidRuntime:		at java.lang.reflect.Method.invoke(Native Method)
00.486	4221  4221 E AndroidRuntime:		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
00.486	4221  4221 E AndroidRuntime:	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by mar-v-in** [comment]
@miketv-s this does not look related to microG but a broken graphics configuration on your device. Assuming you use some custom ROM, you might want to report that there.

**Comment by ale5000-git** [comment]
@miketv-s: I suggest to post a full logcat as attachment to see if there is something that may be related to microG.

**Comment by ale5000-git** [comment]
@miketv-s: Any update on this?
