### ISSUE TITLE
DriveNow app crashes

### ISSUE THREAD

**Issue by thrillfall** [microg/android_packages_apps_GmsCore#388]
I want to run the **drivenow app** (com.dn.drivenow) version 4.2.0. on LineageOS (surnia) 20170608 with **microG 0.2.4-92** installed. 
The location is correctly provided by mozilla location provider and works fine also in other maps.

Sadly it crashes every time after a few seconds with the following log:
```
06-11 13:03:08.934  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:08.936  9090  9090 D GmsMapMarkerImpl: New marker m0 with title null @ lat/lng: (52.xxxxxxx,13.xxxxxxx)
06-11 13:03:08.948  9090  9090 D SafeParcel: Unknown field num 13 in com.google.android.gms.maps.model.GroundOverlayOptions, skipping.
06-11 13:03:08.948  9090  9090 D GmsMapImpl: not yet usable: addGroundOverlay
06-11 13:03:09.076  9090  9130 E GAv4    : Successfully bound to service but never got onServiceConnected callback
06-11 13:03:09.224  3734  4981 W GnssLocationProvider: Invalid size of GpsSvStatus found: 0.
06-11 13:03:09.297  3734  4692 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
06-11 13:03:09.298  3734  5509 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@f33533b
06-11 13:03:09.298  9090  9108 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
06-11 13:03:09.312  9090  9090 W FA      : Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
06-11 13:03:10.227  3734  4981 W GnssLocationProvider: Invalid size of GpsSvStatus found: 0.
06-11 13:03:10.271  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.272  9090  9090 D GmsMapMarkerImpl: New marker m1 with title title_city_marker @ lat/lng: (52.xxxxxxxxxxx,13.xxxxxxxxxxx)
06-11 13:03:10.283  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.293  9090  9090 D GmsMapMarkerImpl: New marker m2 with title title_city_marker @ lat/lng: (53.xxxxxxx,9.xxxxxx)
06-11 13:03:10.303  9090  9101 I art     : Background sticky concurrent mark sweep GC freed 29823(2MB) AllocSpace objects, 1(20KB) LOS objects, 4% free, 11MB/12MB, paused 10.124ms total 45.429ms
06-11 13:03:10.304  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.304  9090  9090 D GmsMapMarkerImpl: New marker m3 with title title_city_marker @ lat/lng: (55.xxxxxxxxxxx,12.xxxxxxxxxxx3)
06-11 13:03:10.311  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.312  9090  9090 D GmsMapMarkerImpl: New marker m4 with title title_city_marker @ lat/lng: (50.xxxxxxxxxxx,6.xxxxxxxxxxx38)
06-11 13:03:10.319  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.320  9090  9090 D GmsMapMarkerImpl: New marker m5 with title title_city_marker @ lat/lng: (51.xxxxxxxxxxx2,6.xxxxxxxxxxx676)
06-11 13:03:10.323  3734  4692 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
06-11 13:03:10.324  3734  5509 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@6d89a58
06-11 13:03:10.324  9090  9108 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
06-11 13:03:10.327  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.328  9090  9090 D GmsMapMarkerImpl: New marker m6 with title title_city_marker @ lat/lng: (48.xxxxxxxxxxx1,11.xxxxxxxxxxx4219)
06-11 13:03:10.342  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.342  9090  9090 D GmsMapMarkerImpl: New marker m7 with title title_city_marker @ lat/lng: (48.xxxxxxxxxxx1,16.xxxxxxxxxxx46)
06-11 13:03:10.350  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.350  9090  9090 D GmsMapMarkerImpl: New marker m8 with title title_city_marker @ lat/lng: (50.xxxxxxxxxxx4,4.xxxxxxxxxxx32)
06-11 13:03:10.359  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.360  9090  9090 D GmsMapMarkerImpl: New marker m9 with title title_city_marker @ lat/lng: (59.xxxxxxxxxxx92,18.xxxxxxxxxxx8)
06-11 13:03:10.367  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.367  9090  9090 D GmsMapMarkerImpl: New marker m10 with title title_city_marker @ lat/lng: (45.xxxxxxxxxxx75,9.xxxxxxxxxxx98)
06-11 13:03:10.368  9090  9131 D EventBus: No subscribers registered for event class com.dn.drivenow.event.CarTypesForCityUpdatedEvent
06-11 13:03:10.368  9090  9131 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.g
06-11 13:03:10.369  9090  9164 I Approov : CA3_3052
06-11 13:03:10.379  9090  9164 I Approov : CA3_2012
06-11 13:03:10.379  9090  9164 D SxDnApiClient: https://api2.drive-now.com/%2Fgeodata%2F6099%2F6099_mobile.kml
06-11 13:03:10.382  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.382  9090  9090 D GmsMapMarkerImpl: New marker m11 with title title_city_marker @ lat/lng: (51.xxxxxxxxxxx3,-0.09218800067901611)
06-11 13:03:10.382  9090  9101 I art     : Background sticky concurrent mark sweep GC freed 11021(517KB) AllocSpace objects, 10(260KB) LOS objects, 0% free, 12MB/12MB, paused 5.980ms total 55.521ms

06-11 13:03:10.402  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.402  9090  9090 D GmsMapMarkerImpl: New marker m12 with title title_city_marker @ lat/lng: (60.xxxxxxxxxxx84,24.xxxxxxxxxxx)
06-11 13:03:10.410  9090  9090 W FA      : Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
06-11 13:03:10.411  9090  9090 D GmsMapCamUpdateFactory: newLatLngZoom
06-11 13:03:10.417  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.418  9090  9090 D GmsMapMarkerImpl: New marker m13 with title null @ lat/lng: (52.xxxxxxxxxxx5,13.xxxxxxxxxxx59)
06-11 13:03:10.421  3734  4692 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
06-11 13:03:10.422  3734  5509 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@150b7b1
06-11 13:03:10.422  9090  9108 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
06-11 13:03:10.427  9090  9090 E EventBus: Could not dispatch event: class com.dn.drivenow.event.MapItemsChunkAddEvent to subscribing class class com.dn.drivenow.plugin.map.c
06-11 13:03:10.427  9090  9090 E EventBus: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.google.android.gms.dynamic.zzd.zzF(Unknown Source)
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.google.android.gms.maps.model.Marker.getTag(Unknown Source)
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.dn.drivenow.plugin.map.h.g(SourceFile:132)
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.dn.drivenow.plugin.map.c.a(SourceFile:178)
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.dn.drivenow.plugin.map.c.onEvent(SourceFile:155)
06-11 13:03:10.427  9090  9090 E EventBus: 	at java.lang.reflect.Method.invoke(Native Method)
06-11 13:03:10.427  9090  9090 E EventBus: 	at org.greenrobot.eventbus.c.a(SourceFile:485)
06-11 13:03:10.427  9090  9090 E EventBus: 	at org.greenrobot.eventbus.c.a(SourceFile:479)
06-11 13:03:10.427  9090  9090 E EventBus: 	at org.greenrobot.eventbus.f.handleMessage(SourceFile:67)
06-11 13:03:10.427  9090  9090 E EventBus: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-11 13:03:10.427  9090  9090 E EventBus: 	at android.os.Looper.loop(Looper.java:154)
06-11 13:03:10.427  9090  9090 E EventBus: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-11 13:03:10.427  9090  9090 E EventBus: 	at java.lang.reflect.Method.invoke(Native Method)
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-11 13:03:10.427  9090  9090 E EventBus: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-11 13:03:10.428  9090  9090 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.k
06-11 13:03:10.433  9090  9090 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
06-11 13:03:10.434  9090  9090 D GmsMapMarkerImpl: New marker m14 with title null @ lat/lng: (52.xxxxxxxxxxx5,13.xxxxxxxxxxx3)
06-11 13:03:10.435  9090  9090 D AndroidRuntime: Shutting down VM
06-11 13:03:10.505  9090  9101 I art     : Background partial concurrent mark sweep GC freed 40928(2MB) AllocSpace objects, 11(1760KB) LOS objects, 39% free, 9MB/15MB, paused 7.094ms total 122.160ms
06-11 13:03:10.609  9090  9090 E AndroidRuntime: FATAL EXCEPTION: main
06-11 13:03:10.609  9090  9090 E AndroidRuntime: Process: com.dn.drivenow, PID: 9090
06-11 13:03:10.609  9090  9090 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.google.android.gms.dynamic.zzd.zzF(Unknown Source)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.google.android.gms.maps.model.Marker.getTag(Unknown Source)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.dn.drivenow.plugin.map.h.g(SourceFile:132)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.dn.drivenow.plugin.map.c.a(SourceFile:178)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.dn.drivenow.plugin.map.c.a(SourceFile:44)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.dn.drivenow.plugin.map.c$1.run(SourceFile:92)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-11 13:03:10.609  9090  9090 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-11 13:03:10.612  3734  9022 W ActivityManager:   Force finishing activity com.dn.drivenow/.MainActivity
```

Is that a problem that could be resolved in the gmscore package? I remember running an older version (year ago) of drivenow with gmscore on cyanogenmod.

**Comment by trypt0ph4n** [comment]
I am having the same problem with the newest version of Drivenow. As a workaround I am using an old version of the Drivenow app (Version 3.x), which works fine with microg

**Comment by thrillfall** [comment]
@trypt0ph4n good to hear that i am not the only one. Do you know by any chance what **version code** for the playstore gives me a working Drivenow app (in Yalp)? (currently it is something like 40000 for the latest 4.2.x)

**Comment by trypt0ph4n** [comment]
@thrillfall  I am using 40008.

**Comment by pomarec** [comment]
I have the same kind of issue with "Cityscoot" app (geolocalized french motorbike renting app)
See more info in second logs as well

```
06-24 23:27:23.750 14439 14439 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 112)
06-24 23:27:23.958 13530 13530 I MonoDroid: UNHANDLED EXCEPTION:
06-24 23:27:23.979 13530 13530 I MonoDroid: Java.Lang.RuntimeException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
06-24 23:27:23.979 13530 13530 I MonoDroid:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d37d3a930aac472a83f138ee88346faf>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00068] in <e7a2543fd03c4e3cb2469cbe34eff5ec>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x0000e] in <882c58553193409095de01cd292b13c2>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at Android.Gms.Maps.Model.Marker.get_Tag () [0x00033] in <c55b537435704a81bf3e8b735e842988>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at CityScoot.Controllers.States.OverviewState+<>c__DisplayClass28_0.<GetAbstractMarkerByMarker>b__0 (CityScoot.Controllers.Map.AbstractMarker x) [0x0000e] in <89d0f795542547d7b11b4debeeb6c183>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <d6141eb5c0e84d758a1341dfadd48702>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <d6141eb5c0e84d758a1341dfadd48702>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at CityScoot.Controllers.States.OverviewState.GetAbstractMarkerByMarker (Android.Gms.Maps.Model.Marker marker) [0x00013] in <89d0f795542547d7b11b4debeeb6c183>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at CityScoot.Controllers.States.OverviewState.ClickOnMarker (Android.Gms.Maps.Model.Marker marker) [0x00000] in <89d0f795542547d7b11b4debeeb6c183>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at CityScoot.MainActivity.<initMapEvents>b__138_0 (System.Object sender, Android.Gms.Maps.GoogleMap+MarkerClickEventArgs e) [0x00037] in <89d0f795542547d7b11b4debeeb6c183>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at Android.Gms.Maps.GoogleMap+IOnMarkerClickListenerImplementor.OnMarkerClick (Android.Gms.Maps.Model.Marker marker) [0x00017] in <c55b537435704a81bf3e8b735e842988>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at Android.Gms.Maps.GoogleMap+IOnMarkerClickListenerInvoker.n_OnMarkerClick_Lcom_google_android_gms_maps_model_Marker_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_marker) [0x00011] in <c55b537435704a81bf3e8b735e842988>:0
06-24 23:27:23.979 13530 13530 I MonoDroid:   at (wrapper dynamic-method) System.Object:a2fe3393-9922-4339-9c3e-ea94886eb9b1 (intptr,intptr,intptr)
06-24 23:27:23.979 13530 13530 I MonoDroid:   --- End of managed Java.Lang.RuntimeException stack trace ---
06-24 23:27:23.979 13530 13530 I MonoDroid: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.google.android.gms.dynamic.zzd.zzF(Unknown Source)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.google.android.gms.maps.model.Marker.getTag(Unknown Source)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at mono.com.google.android.gms.maps.GoogleMap_OnMarkerClickListenerImplementor.n_onMarkerClick(Native Method)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at mono.com.google.android.gms.maps.GoogleMap_OnMarkerClickListenerImplementor.onMarkerClick(GoogleMap_OnMarkerClickListenerImplementor.java:30)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.google.android.gms.maps.GoogleMap$2.zza(Unknown Source)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.google.android.gms.maps.internal.zzu$zza.onTransact(Unknown Source)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at android.os.Binder.transact(Binder.java:387)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.google.android.gms.maps.internal.IOnMarkerClickListener$Stub$Proxy.onMarkerClick(IOnMarkerClickListener.java:81)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.microg.gms.maps.GoogleMapImpl.onClick(GoogleMapImpl.java:336)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.microg.gms.maps.markup.MarkerImpl.onClick(MarkerImpl.java:216)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.microg.gms.maps.BackendMap.onItemSingleTapUp(BackendMap.java:217)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.microg.gms.maps.BackendMap.onItemSingleTapUp(BackendMap.java:55)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.layers.marker.ItemizedLayer.onSingleTapUpHelper(ItemizedLayer.java:145)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.layers.marker.ItemizedLayer$1.run(ItemizedLayer.java:155)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.layers.marker.ItemizedLayer.activateSelectedItems(ItemizedLayer.java:237)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.layers.marker.ItemizedLayer.onGesture(ItemizedLayer.java:263)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.map.Layers.handleGesture(Layers.java:205)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.map.Map.handleGesture(Map.java:372)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at org.oscim.android.input.GestureHandler.onSingleTapConfirmed(GestureHandler.java:54)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at android.os.Looper.loop(Looper.java:148)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-24 23:27:23.979 13530 13530 I MonoDroid: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
06-24 23:27:24.277   631   641 I OAM     : [check_file_size:409]/data/hwlogdir/wifi_log/wifi_log_1 log file beyond size=10240Byte, creat new file
06-24 23:27:24.277   631   641 I OAM     : [rename_old_file:114]rename_old_file
06-24 23:27:24.277   631   641 I OAM     :
```


Idk if it's related but it might :

```
06-24 23:26:39.634 14439 15046 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
06-24 23:26:39.634 14439 14605 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@7328d25
06-24 23:26:39.634 13644 13661 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
```

**Comment by goddib** [comment]
Hi everyone, I can confirm that I have this issue, too. When I open the DriveNow app it works fine at first but the app crashes, as soon as I select one of the (correctly displayed) cars on the map - every time. 

Thanks for the tip with using an old version of the DriveNow app - 3.18 works without issues so far.

**Comment by eudoxos** [comment]
Same issue here with 2 bike sharing apps (obike, rekola). this is from obike:

    09-02 17:32:00.429 E/AndroidRuntime(11749): java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference

**Comment by fkoester** [comment]
Same problem here with DriveNow app version 4.7.1 and microG Services Core 0.2.4.

**Comment by RyanTG** [comment]
_(feel free to ignore/delete if this is not on topic)_

I'm an app developer, and am seeing that same `Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.` as well as [some of these](https://github.com/microg/android_packages_apps_GmsCore/issues/157#issuecomment-236437281), and I'm curious to know why this occurs, and what I could do to fix it. Like, if I downgraded `'com.google.android.gms:play-services:10.2.4'` in gradle, could that solve it? Thanks!
