### ISSUE TITLE
Uber crashes with NullPointerException

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#389]
Uber starts, displays world map, then immediately crashes.

```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.ubercab, PID: 11500
E AndroidRuntime: Theme: themes:{}
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IOnMapLoadedCallback.onMapLoaded()' on a null object reference
E AndroidRuntime: 	at org.microg.gms.maps.GoogleMapImpl$2.run(GoogleMapImpl.java:553)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

Full log: https://pastebin.com/ae8JnHWz

**Comment by ale5000-git** [comment]
What version of microG you have installed?

**Comment by Torvin** [comment]
My bad. I should have checked for updates first. I updated microG and now everything works. Sorry!
