### ISSUE TITLE
CityMapper is crashing (device without GPS)

### ISSUE THREAD

**Issue by pihug12** [microg/android_packages_apps_GmsCore#396]
I'm not sure if this issue is GmsCore related.  
CityMapper v6.22 is crashing on my device.

**Logcat:** https://gist.github.com/pihug12/49504ca314ffda96993feb3f5a76098a
"`java.lang.IllegalArgumentException: provider doesn't exist: gps`"

My device doesn't have a GPS chip. But WiFi geolocalisation should work.

- **Device:** Amazon Kindle Fire HD 7" (tate)
- **OS:** CyanogenMod 12.1 (Android 5.1.1)
- **microG Services Core:** 0.2.4-103
- Xposed + FakeGapps module
- FakeStore
- MozillaNlpBackend + NominatimNlpBackend

**CityMapper v6.22:** [ApkPure.com](https://apkpure.com/citymapper-transit-navigation/com.citymapper.app.release/download?from=details%2Fversion&fid=b%2Fapk%2FY29tLmNpdHltYXBwZXIuYXBwLnJlbGVhc2VfMTYwMTJfMWYyODE0NTY&version_code=16012)

![screenshot_2017-07-02-16-08-05](https://user-images.githubusercontent.com/678038/27770758-020333c6-5f45-11e7-80ee-2afa7f1f08da.png)
![screenshot_2017-07-02-16-08-14](https://user-images.githubusercontent.com/678038/27770759-020441a8-5f45-11e7-9631-546a371cd0a7.png)
![screenshot_2017-07-02-16-08-21](https://user-images.githubusercontent.com/678038/27770757-01fbd9aa-5f45-11e7-92a6-e1c71b29beec.png)
![screenshot_2017-07-02-17-03-43](https://user-images.githubusercontent.com/678038/27771100-9384f886-5f48-11e7-8125-8b402687ea90.png)

**Comment by fanoush** [comment]
Same here with Nook HD+ (tablet with no GPS) and aosp_ovation-ota-N2G48H.180212 by amaces. 
microg 0.2.4-108, every checkbox green except the last one. In my case c:geo is crasing
```
02-28 09:35:54.577   428   449 I ActivityManager: Displayed cgeo.geocaching/.MainActivity: +1s337ms
02-28 09:35:54.601  1021  1035 D GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=100, interval=2000, fast
estInterval=250, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListener
s=false, triggerUpdate=true, clients=[], tag='null', hideFromAppOps=false, forceCoarseLocation=false}, listener=null, pendingIntent=null, callback=com.google.android.gms.location.ILocationCallback$Stub$P
roxy@ab712d4, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@ba7cc7d}
02-28 09:35:54.610  1021  1035 D GmsLocProviderReal: gps: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=100, interval=2000, fastestInterval=250, explicitFastestInterval=true,
expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
02-28 09:35:54.610  1021  1035 D GmsLocProviderReal: gps: requesting location updates. minTime=2000 minDistance=0.0
02-28 09:35:54.617  6181  6181 D AndroidRuntime: Shutting down VM
02-28 09:35:54.624  6181  6181 E AndroidRuntime: FATAL EXCEPTION: main
02-28 09:35:54.624  6181  6181 E AndroidRuntime: Process: cgeo.geocaching, PID: 6181
02-28 09:35:54.624  6181  6181 E AndroidRuntime: java.lang.IllegalArgumentException: provider doesn't exist: gps
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1688)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1637)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.location.internal.zzd$7.zza(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.location.internal.zzd$7.zza(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpm$zza.zzb(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpv.zzf(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpv.zzd(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzqa.zzd(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpy.zzd(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.updateRequest(LocationProvider.java:55)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at cgeo.geocaching.playservices.LocationProvider.onConnected(LocationProvider.java:161)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzl.zzo(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpy.zzm(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpw.zzapp(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpw.onConnected(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzqa.onConnected(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.internal.zzpp.onConnected(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzk$1.onConnected(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzd$zzj.zzasd(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzd$zza.zzv(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzd$zze.zzasf(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-28 09:35:54.624  6181  6181 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-28 09:35:54.638   428  5346 W ActivityManager:   Force finishing activity cgeo.geocaching/.MainActivity
02-28 09:35:54.830  6181  6181 I Process : Sending signal. PID: 6181 SIG: 9

```

**Comment by bjmc** [comment]
Citymapper is complaining that I need to update my Google Play Services. Does anyone have suggestions? I can upload more details, if that would help. Can I downgrade to an older version of Citymapper?

**Comment by voidstarstar** [comment]
This is related to #635 due to the line `ProviderInstallerImpl: yep, i should do something with Security here...`

**Comment by ale5000-git** [comment]
@pihug12: Could you please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry?
