### ISSUE TITLE
Android version and UnifiedNlp package is not supported (OxygenOS Beta 12, Android 7.1.1)

### ISSUE THREAD

**Issue by EinsteinXXL** [microg/android_packages_apps_GmsCore#411]
hello,

microG says that the android version and the location provider is not supportet. I used latest nanomod v12 with magsik 13.3 and I also tred installing microG (v0.2.4-103-gd9e86d9) directly into system/priv-app folder, but no changes. What can I do to resolve this or is it a bug in microG/unifiedNlp? My ROM is OxygenOS Beta 12 for the Oneplus 3T with Android 7.1.1. 

![screenshot_20170812-040404](https://user-images.githubusercontent.com/20692649/29236960-7eb4579e-7f14-11e7-880b-7e5cc83bce56.jpg)

**Comment by luckydevil13** [comment]
same issue with version of microg and phone

**Comment by luckydevil13** [comment]
08-17 23:40:40.253  2896  2896 D LocationManager: requestLocationUpdates listener=org.microg.tools.selfcheck.NlpStatusChecks$2@201d836 packageName= com.google.android.gms
08-17 23:40:40.257  2896  2925 V NlpLocationProvider: onSetRequest: ProviderRequest[ON interval=0] by WorkSource{}
08-17 23:40:40.257  2896  2925 V NlpLocationProvider: using autoUpdate=true autoTime=2500
08-17 23:40:44.220  1477  2175 I chatty  : uid=1000(system) LocationThread expire 12 lines
08-17 23:40:44.221  2896  2925 V NlpLocationProvider: onSetRequest: ProviderRequest[OFF] by WorkSource{}
08-17 23:40:44.222  2896  2925 V NlpLocationProvider: using autoUpdate=false autoTime=9223372036854775807
08-17 23:40:45.232  1477  1518 I ActivityManager: START u0 {act=android.settings.LOCATION_SOURCE_SETTINGS flg=0x14000000 cmp=com.android.settings/.Settings$LocationSettingsActivity} from uid 10035 pid 2013 on display 0
08-17 23:40:46.517  3893  3893 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:909 android.content.ContextWrapper.sendBroadcast:427 com.android.settings.location.LocationSettingsBase.setLocationMode:110 com.android.settings.location.LocationSettings.onSwitchChanged:605 com.android.settings.widget.SwitchBar.propagateChecked:244 
08-17 23:40:51.262  3893  3893 D LocationSettings: getCurrentProviderPackageList currentUsingGpsPkgs:[]
08-17 23:40:51.266  3893  3893 D LocationSettings: recentLocationRequests request.uid=10103
08-17 23:40:51.284  3893  3893 I LocationSettingsBase: Location mode has been changed
08-17 23:40:55.862  2896  2896 D LocationManager: requestLocationUpdates listener=org.microg.tools.selfcheck.NlpStatusChecks$2@b13aa5b packageName= com.google.android.gms
08-17 23:40:57.310  4640  4655 I Adreno  : Local Branch                     : 
08-17 23:41:28.674  2896  2896 D LocationManager: requestLocationUpdates listener=org.microg.tools.selfcheck.NlpStatusChecks$2@4675131 packageName= com.google.android.gms
08-17 23:41:34.549  2896  2896 D LocationManager: requestLocationUpdates listener=org.microg.tools.selfcheck.NlpStatusChecks$2@db13532 packageName= com.google.android.gms
08-17 23:41:45.287  4706  4726 I Adreno  : Local Branch                     : 
08-17 23:42:18.351  1477  2175 I chatty  : uid=1000(system) LocationThread expire 2 lines
08-17 23:42:18.464  4706  4711 I art     : Compiler allocated 4MB to compile java.lang.Object com.github.yeriomin.playstoreapi.DocV2.dynamicMethod$1f92504(int, java.lang.Object, java.lang.Object)
08-17 23:42:21.802  2976  4785 W DownloadManager: fallocate() not supported; falling back to ftruncate()
08-17 23:42:46.780  4003  4003 D SubstratumBuilder: Service:com.qualcomm.location.LocationService
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:com.qualcomm.location.izat.IzatService
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:com.qualcomm.location.izatserviceprovider.service.UnifiedLocationService
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:org.microg.nlp.location.LocationServiceV2
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:com.oneplus.oplocationservice.OPLocationService
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:android.hardware.location.GeofenceHardwareService
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:com.qualcomm.location.LBSSystemMonitorService
08-17 23:42:46.781  4003  4003 D SubstratumBuilder: Service:com.qualcomm.location.izatserviceprovider.service.NetworkLocationService
08-17 23:42:46.782  4003  4003 D SubstratumBuilder: Service:com.android.internal.backup.LocalTransportService
08-17 23:42:52.290  4817  4817 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
08-17 23:42:52.293  4817  4817 W System.err: 	at android.location.ILocationManager$Stub$Proxy.sendExtraCommand(ILocationManager.java:1315)
08-17 23:42:52.293  4817  4817 W System.err: 	at android.location.LocationManager.sendExtraCommand(LocationManager.java:2344)
08-17 23:42:52.293  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:276)
08-17 23:42:52.293  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:241)
08-17 23:42:52.519  4817  4939 I Adreno  : Local Branch                     : 
08-17 23:42:53.058  4817  4817 D LocationManager: removeUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName=  net.osmand
08-17 23:42:57.318  4817  4817 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
08-17 23:42:57.319  4817  4817 W System.err: 	at android.location.ILocationManager$Stub$Proxy.sendExtraCommand(ILocationManager.java:1315)
08-17 23:42:57.319  4817  4817 W System.err: 	at android.location.LocationManager.sendExtraCommand(LocationManager.java:2344)
08-17 23:42:57.319  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:276)
08-17 23:42:57.319  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:241)
08-17 23:42:57.554  4817  4817 D LocationManager: removeUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName=  net.osmand
08-17 23:42:57.958  4817  4930 W net.osmand:native: jnigraphics was not loaded in default location
08-17 23:43:00.921  4817  4817 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
08-17 23:43:00.922  4817  4817 W System.err: 	at android.location.ILocationManager$Stub$Proxy.sendExtraCommand(ILocationManager.java:1315)
08-17 23:43:00.922  4817  4817 W System.err: 	at android.location.LocationManager.sendExtraCommand(LocationManager.java:2344)
08-17 23:43:00.922  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:276)
08-17 23:43:00.922  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:241)
08-17 23:43:46.429  4817  4817 D LocationManager: removeUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName=  net.osmand
08-17 23:43:48.866  4817  4817 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
08-17 23:43:48.867  4817  4817 W System.err: 	at android.location.ILocationManager$Stub$Proxy.sendExtraCommand(ILocationManager.java:1315)
08-17 23:43:48.867  4817  4817 W System.err: 	at android.location.LocationManager.sendExtraCommand(LocationManager.java:2344)
08-17 23:43:48.867  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:276)
08-17 23:43:48.867  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:241)
08-17 23:43:48.884  3976  5012 I Adreno  : Local Branch                     : 
08-17 23:44:19.014  2013  2080 D AppTracker: App Event: quick_location
08-17 23:44:19.031  1477  2825 I ActivityManager: START u0 {act=android.settings.LOCATION_SOURCE_SETTINGS flg=0x14000000 cmp=com.android.settings/.Settings$LocationSettingsActivity} from uid 10035 pid 2013 on display 0
08-17 23:44:19.036  2013  2082 V GAV3    : Thread[GAThread,5,main]: Sending hit to store  PATH: https:  PARAMS: sr=1080x1920,  ht=1503002659035,  _u=.ryAAAAAL,  ec=quick_location,  cid=12bacd19-8f3c-4239-a231-41a6f2c60067,  av=0.0.1.170728153022.f1fd8d8,  v=1,  an=Интерфейс системы,  ul=en-us,  t=event,  tid=UA-92966593-4,  ea=1,  aid=com.android.systemui,  el=long,  
08-17 23:44:19.081  4817  4817 D LocationManager: removeUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName=  net.osmand
08-17 23:44:19.189  3893  3893 D LocationSettings: getCurrentProviderPackageList currentUsingGpsPkgs:[]
08-17 23:44:19.191  3893  3893 D LocationSettings: recentLocationRequests request.uid=10103
08-17 23:44:19.200  3893  3893 I LocationSettingsBase: Location mode has been changed
08-17 23:44:19.250  1477  1603 I ActivityManager: Displayed com.android.settings/.Settings$LocationSettingsActivity: +157ms (total +30s838ms)
08-17 23:44:20.826  3893  3893 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:909 android.content.ContextWrapper.sendBroadcast:427 com.android.settings.location.LocationSettingsBase.setLocationMode:110 com.android.settings.location.LocationSettings.onSwitchChanged:607 com.android.settings.widget.SwitchBar.propagateChecked:244 
08-17 23:44:20.840  3893  3893 I LocationSettingsBase: Location mode has been changed
08-17 23:44:20.852  1477  2175 I GnssLocationProvider: WakeLock acquired by sendMessage(2, 0, null)
08-17 23:44:20.854  1477  1477 D GpsNetInitiatedHandler: location enabled :false
08-17 23:44:20.855  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(2, 0, null)
08-17 23:44:20.865  3893  3893 I LocationSettingsBase: Location mode has been changed
08-17 23:44:21.591  3893  3893 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:909 android.content.ContextWrapper.sendBroadcast:427 com.android.settings.location.LocationSettingsBase.setLocationMode:110 com.android.settings.location.LocationSettings.onSwitchChanged:605 com.android.settings.widget.SwitchBar.propagateChecked:244 
08-17 23:44:21.608  3893  3893 I LocationSettingsBase: Location mode has been changed
08-17 23:44:21.614  1477  2175 I GnssLocationProvider: WakeLock acquired by sendMessage(2, 1, null)
08-17 23:44:21.618  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(2, 1, null)
08-17 23:44:21.620  1477  1477 D GpsNetInitiatedHandler: location enabled :true
08-17 23:44:21.628  3893  3893 I LocationSettingsBase: Location mode has been changed
08-17 23:44:24.037  4817  4817 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
08-17 23:44:24.038  4817  4817 W System.err: 	at android.location.ILocationManager$Stub$Proxy.sendExtraCommand(ILocationManager.java:1315)
08-17 23:44:24.038  4817  4817 W System.err: 	at android.location.LocationManager.sendExtraCommand(LocationManager.java:2344)
08-17 23:44:24.038  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:276)
08-17 23:44:24.038  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:241)
08-17 23:44:24.400  4817  4817 D LocationManager: removeUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName=  net.osmand
08-17 23:45:46.152  4817  4817 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
08-17 23:45:46.152  4817  4817 W System.err: 	at android.location.ILocationManager$Stub$Proxy.sendExtraCommand(ILocationManager.java:1315)
08-17 23:45:46.153  4817  4817 W System.err: 	at android.location.LocationManager.sendExtraCommand(LocationManager.java:2344)
08-17 23:45:46.153  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.redownloadAGPS(OsmAndLocationProvider.java:276)
08-17 23:45:46.153  4817  4817 W System.err: 	at net.osmand.plus.OsmAndLocationProvider.resumeAllUpdates(OsmAndLocationProvider.java:241)
08-17 23:45:48.196  2013  2080 D AppTracker: App Event: quick_location
08-17 23:45:48.217  2013  2082 V GAV3    : Thread[GAThread,5,main]: Sending hit to store  PATH: https:  PARAMS: sr=1080x1920,  ht=1503002748216,  _u=.ryAAAAAL,  ec=quick_location,  cid=12bacd19-8f3c-4239-a231-41a6f2c60067,  av=0.0.1.170728153022.f1fd8d8,  v=1,  an=Интерфейс системы,  ul=en-us,  t=event,  tid=UA-92966593-4,  ea=1,  aid=com.android.systemui,  el=full,  
08-17 23:45:48.224  1477  2175 I GnssLocationProvider: WakeLock acquired by sendMessage(2, 0, null)
08-17 23:45:48.229  1477  1477 D GpsNetInitiatedHandler: location enabled :false
08-17 23:45:48.235  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(2, 0, null)
08-17 23:45:53.573  2013  2080 D AppTracker: App Event: quick_location
08-17 23:45:53.599  2013  2082 V GAV3    : Thread[GAThread,5,main]: Sending hit to store  PATH: https:  PARAMS: sr=1080x1920,  ht=1503002753599,  _u=.ryAAAAAL,  ec=quick_location,  cid=12bacd19-8f3c-4239-a231-41a6f2c60067,  av=0.0.1.170728153022.f1fd8d8,  v=1,  an=Интерфейс системы,  ul=en-us,  t=event,  tid=UA-92966593-4,  ea=1,  aid=com.android.systemui,  el=full,  
08-17 23:45:53.604  1477  2175 I GnssLocationProvider: WakeLock acquired by sendMessage(2, 1, null)
08-17 23:45:53.605  1477  1477 D GpsNetInitiatedHandler: location enabled :true
08-17 23:45:53.606  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(2, 1, null)
08-17 23:45:55.048  4817  4817 D LocationManager: removeUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName=  net.osmand
08-17 23:45:56.489  1477  1477 I GnssLocationProvider: WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@5bd50ae)
08-17 23:45:56.494  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@5bd50ae)
08-17 23:45:56.496  1477  1477 I GnssLocationProvider: WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@4c48e4f)
08-17 23:45:56.497  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@4c48e4f)
08-17 23:45:56.599  1477  2825 W GnssLocationProvider: delete_aiding_data
08-17 23:45:56.599  1477  2825 E GnssLocationProvider: deleteAidingData..debugStatus is:false
08-17 23:45:56.599  1477  2825 E GnssLocationProvider: Not in Debug Status, not deleteAidingData
08-17 23:45:56.602  1477  1517 I GnssLocationProvider: WakeLock acquired by sendMessage(5, 0, null)
08-17 23:45:56.602  1477  2175 I GnssLocationProvider: WakeLock acquired by handleInjectNtpTime()
08-17 23:45:56.603  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(5, 0, null)
08-17 23:45:56.603  1477  5088 I GnssLocationProvider: WakeLock acquired by sendMessage(10, 0, null)
08-17 23:45:56.603  1477  5088 I GnssLocationProvider: WakeLock released by handleInjectNtpTime()
08-17 23:45:56.605  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(10, 0, null)
08-17 23:45:56.614  4817  4817 D LocationManager: requestLocationUpdates listener=net.osmand.plus.OsmAndLocationProvider$2@9eda117 packageName= net.osmand
08-17 23:45:56.615  1477  1518 E LocationManagerService: requestLocationUpdates: uid=10017, pid=4817, provider=gps, package=net.osmand listener= android.location.ILocationListener$Stub$Proxy@bd28874 intent= null
08-17 23:45:56.616  1477  1518 I GnssLocationProvider: WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@4b3d612)
08-17 23:45:56.618  4817  4817 D LocationManager: requestLocationUpdates listener=net.osmand.plus.OsmAndLocationProvider$NetworkListener@330879 packageName= net.osmand
08-17 23:45:56.618  1477  2175 I GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@4b3d612)
08-17 23:45:56.619  1477  2903 E LocationManagerService: requestLocationUpdates: uid=10017, pid=4817, provider=passive, package=net.osmand listener= android.location.ILocationListener$Stub$Proxy@80ba93f intent= null
08-17 23:45:56.620  4817  4817 D LocationManager: requestLocationUpdates listener=net.osmand.plus.OsmAndLocationProvider$NetworkListener@8e5a9be packageName= net.osmand
08-17 23:45:56.621  1477  2824 E LocationManagerService: requestLocationUpdates: uid=10017, pid=4817, provider=network, package=net.osmand listener= android.location.ILocationListener$Stub$Proxy@c526755 intent= null
08-17 23:45:56.721  2846  2846 D OPLocationService: GPS navigation start, inject location!
08-17 23:45:56.724  2846  2846 D OPLocationService: injectPostion!!
08-17 23:45:56.724  2846  2846 E OPLocationService: init
08-17 23:45:56.744  2846  2846 E OPLocationService: request location oversea
08-17 23:45:56.748  2846  2846 D LocationManager: requestLocationUpdates listener=com.oneplus.oplocationservice.OPLocationProvider$LocListener@52d7e3b packageName= com.oneplus.oplocationservice
08-17 23:45:56.750  1477  2482 E LocationManagerService: requestLocationUpdates: uid=1000, pid=2846, provider=network, package=com.oneplus.oplocationservice listener= android.location.ILocationListener$Stub$Proxy@5aaa2f8 intent= null
08-17 23:45:56.752  2846  2846 E OPLocationService: needDestroy true
08-17 23:45:57.132  2013  2013 I StatusBarIconView: set mSlot:location icon.visible:true mBlocked:false
08-17 23:45:57.134  2013  2013 I StatusBarIconView: set mSlot:location icon.visible:true mBlocked:false

**Comment by luckydevil13** [comment]
GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms

**Comment by cstich** [comment]
Have you guys tried different location backends yet?

**Comment by ildar** [comment]
Just tried this and that. No difference.
JB CM10.1

**Comment by EinsteinXXL** [comment]
Posted this issue five months ago, but not fixed. :(

**Comment by ale5000-git** [comment]
To all:

"Android version supported" is only an indication and it doesn't really mean nothing important.

"System supports location provider" is an issue with your ROM or an incorrect installation so it cannot rally be fixed here (except rare cases).
Most probably should be reported to the ROM maintainer.

**Comment by ildar** [comment]
Please clarify "System supports location provider" part:
This wiki page: https://github.com/microg/android_packages_apps_GmsCore/wiki
says:
> GmsCore includes the Unified Network Location Provider module
(UnifiedNlp) which handles application calls to Google's network location
provider.

A user expects it to work (as it does on my Android 7/LOS tablet).
If NOT, then could devs please  give some explanations on it or where we
can see the details why it doesn't work. Thanks in advance!

**Comment by ale5000-git** [comment]
@ildar

It works fine for me.
But some ROMs have different configurations and don't bind to microG, there isn't an universal reply as there are many possible problems.

Sometimes there are conflictring packages, if you want you can try my  [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360) that fix most problems automatically.

**Comment by ildar** [comment]
I see two issues here:
1. The cited wiki page implies that the feature is present and should work.
Which is misguiding.
2. The MicroG app only saying if NLP works or not, doesn't give any clue in
case NLP doesn't work.

On the 1st issue: this function isn't properly documented. Besides fixing
the cited page, a separate wiki page is desired, containing following:
1. how to diagnose the problem, find out what gone wrong.
2. What to do, propose workarounds applicable.

With the 2nd issue I'd prefer that MicroG would do some work inplace,
gathering diagnostics or something helping the user to get working NLP.

**Comment by ale5000-git** [comment]
@ildar
The feature is present and should work for most users, it will never work for 100% of users since there are infinite variants of devices and ROMs

You suppose that microG can know the cause of the problem, it isn't like this.
Maybe it can add some diagnostics but an app can't fix a "bug" of the ROM.

I agree that a guide of common errors would be good.

**Comment by ildar** [comment]
Can you point at any solution/workaround? I couldn't find any to start with.

**Comment by ale5000-git** [comment]
There may be multiple causes. Some of them may be:
1) The ROM only allow location services in the /system partition;
2) The ROM doesn't include the app name used by GApps / microG (com.google.android.gms) in the list of location services to bind;
3) There is another location service that conflict with microG;
4) Incorrect installation;
5) Missing permissions.

My microG unofficial installer take care automatically of point 1, 3, 4 and 5.

The manual solutions are
For 1:
- Install microG in the /system partition (easier);
- or Use another ROM without this limitation or re-compile it with this limitation removed;
- or Use a method that patch the ROM without modify it directly like Xposed or Magisk.
For 2:
- Change ROM or re-compile it;
- Patch the framework-res.apk of an already installed ROM (decompile with apktool, manually change the file and recomiple with apktoo);
- or Use a method that patch the ROM without modify it directly like Xposed or Magisk.
For 3:
- Remove the conflicting packages from the /system partition (easier), possible conflicting location services are Qualcomm, AMAP or Baidu;
- or Use a method that patch the ROM without modify it directly like Xposed or Magisk.
For 4:
- Obvious once you know it.
For 5:
- Obvious once you know it.

**Comment by ildar** [comment]
Wow! Thanks a lot!
I'd be happy to also see how 2 and 3 can be detected. Like grepping logcat
for certain messages...

**Comment by ale5000-git** [comment]
For 2 you have to decompile /system/framework/framework-res.apk
You can do it easily on the PC, but it may take a lot of time if done directly on the phone.

For 3 you can just look at know pathes of these location services (they are present often in Chinese ROMs).

**Comment by ale5000-git** [comment]
@ildar: I'm not sure about logcat but it wouldn't be nice doing it in microG since it is outside it scope although it may be created a separate tool to do this.

**Comment by ildar** [comment]
Thanks. I think this knowledge is something precious already. Just need to
put it to wiki. Then later need to think how to develop it into a code.
That's my idea about it.

**Comment by ildar** [comment]
Oh! The right thing to do here is:
чт, 1 мар. 2018 г. в 0:59, ale5000 <notifications@github.com>:

> It is intended.
> On Android < 4.4 you must install LegacyNetworkLocation in addition to
> GmsCore.
>
The app: https://f-droid.org/packages/com.google.android.location/
Should be installed to /system/ . Got it working on JB yesterday.

**Comment by azrdev** [comment]
@ale5000-git  you wrote
> The ROM doesn't include the app name used by GApps / microG (com.google.android.gms) in the list of location services to bind;

and
> Patch the framework-res.apk of an already installed ROM (decompile with apktool, manually change the files and re-compile with apktool) (medium);

Can you tell which file(s) should contain the location service name (where / how)?

Context: I've got an unofficial Resurrection Remix build (Android 7.1, device Samsung Galaxy S3 Mini "golden"), which has everything in "Self-check" covered, apart from "UnifiedNlp is registered in system". This is both with [UnifiedNlp (no GAPPS) from f-droid](https://f-droid.org/en/packages/com.google.android.gms), microG from their f-droid repo, and that microG GmsCore.apk copied to `/system/priv-app`.
