### ISSUE TITLE
Mobike app crashes

### ISSUE THREAD

**Issue by n1zzo** [microg/android_packages_apps_GmsCore#427]
I'm trying to run the mobike app (com.mobike.mobikeapp) version 6.0.0 on LineageOS 20171002 (onyx) with microG version 0.2.4-105-gf289a13-dirty installed.

As soon as the map tries to load some markers, the app crashes with the following log:

```
10-05 14:48:54.634  1490  3435 W GnssLocationProvider: Invalid size of GpsSvStatus found: 0.
10-05 14:48:54.759  1490  3028 D AudioService: Stream muted, skip playback
10-05 14:48:54.769 14432 14432 D GmsMapCamUpdateFactory: newCameraPosition
10-05 14:48:54.867 14432 14443 I art     : Background sticky concurrent mark sweep GC freed 274661(9MB) AllocSpace objects, 28(764KB) LOS objects, 29% free, 23MB/33MB, paused 3.007ms total 102.262ms
10-05 14:48:55.630  1490  3435 W GnssLocationProvider: Invalid size of GpsSvStatus found: 0.
10-05 14:48:56.626  1490  3435 W GnssLocationProvider: Invalid size of GpsSvStatus found: 0.
10-05 14:48:57.032 14432 14432 V AsyncHttpRH: Progress 3848 from 1 (384800%)
10-05 14:48:57.034 14432 14432 V AsyncHttpRH: Progress 3853 from 1 (385300%)
10-05 14:48:57.037 14432 14432 V AsyncHttpRH: Progress 3905 from 1 (390500%)
10-05 14:48:57.038 14432 14432 V AsyncHttpRH: Progress 4248 from 1 (424800%)
10-05 14:48:57.146 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.153 14432 14432 D GmsMapMarkerImpl: New marker m0 with title null @ lat/lng: (45.478141,9.225615)
10-05 14:48:57.163 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.163 14432 14432 D GmsMapMarkerImpl: New marker m1 with title null @ lat/lng: (45.476565,9.22502)
10-05 14:48:57.172 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.172 14432 14432 D GmsMapMarkerImpl: New marker m2 with title null @ lat/lng: (45.476983,9.226688)
10-05 14:48:57.179 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.179 14432 14432 D GmsMapMarkerImpl: New marker m3 with title null @ lat/lng: (45.476948,9.226742)
10-05 14:48:57.185 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.186 14432 14432 D GmsMapMarkerImpl: New marker m4 with title null @ lat/lng: (45.478339,9.226977)
10-05 14:48:57.192 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.193 14432 14432 D GmsMapMarkerImpl: New marker m5 with title null @ lat/lng: (45.478435,9.226967)
10-05 14:48:57.198 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.199 14432 14432 D GmsMapMarkerImpl: New marker m6 with title null @ lat/lng: (45.479123,9.226579)
10-05 14:48:57.205 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.205 14432 14432 D GmsMapMarkerImpl: New marker m7 with title null @ lat/lng: (45.476876,9.227737)
10-05 14:48:57.212 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.212 14432 14432 D GmsMapMarkerImpl: New marker m8 with title null @ lat/lng: (45.477025,9.222795)
10-05 14:48:57.218 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.218 14432 14432 D GmsMapMarkerImpl: New marker m9 with title null @ lat/lng: (45.479154,9.227067)
10-05 14:48:57.225 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.226 14432 14432 D GmsMapMarkerImpl: New marker m10 with title null @ lat/lng: (45.479588,9.224987)
10-05 14:48:57.232 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.232 14432 14432 D GmsMapMarkerImpl: New marker m11 with title null @ lat/lng: (45.479426,9.226616)
10-05 14:48:57.238 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.238 14432 14432 D GmsMapMarkerImpl: New marker m12 with title null @ lat/lng: (45.477408,9.22836)
10-05 14:48:57.242 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.243 14432 14432 D GmsMapMarkerImpl: New marker m13 with title null @ lat/lng: (45.479574,9.226538)
10-05 14:48:57.247 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.247 14432 14432 D GmsMapMarkerImpl: New marker m14 with title null @ lat/lng: (45.479628,9.226482)
10-05 14:48:57.251 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.251 14432 14432 D GmsMapMarkerImpl: New marker m15 with title null @ lat/lng: (45.475648,9.227046)
10-05 14:48:57.255 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.256 14432 14432 D GmsMapMarkerImpl: New marker m16 with title null @ lat/lng: (45.47536,9.226552)
10-05 14:48:57.260 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.260 14432 14432 D GmsMapMarkerImpl: New marker m17 with title null @ lat/lng: (45.479974,9.224657)
10-05 14:48:57.264 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.265 14432 14432 D GmsMapMarkerImpl: New marker m18 with title null @ lat/lng: (45.479222,9.228262)
10-05 14:48:57.269 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.269 14432 14432 D GmsMapMarkerImpl: New marker m19 with title null @ lat/lng: (45.479501,9.228113)
10-05 14:48:57.274 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.275 14432 14432 D GmsMapMarkerImpl: New marker m20 with title null @ lat/lng: (45.4803,9.225199)
10-05 14:48:57.277 14432 14437 I art     : Do full code cache collection, code=246KB, data=251KB
10-05 14:48:57.279 14432 14437 I art     : Starting a blocking GC JitCodeCache
10-05 14:48:57.279 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.279 14432 14437 I art     : After code cache collection, code=211KB, data=195KB
10-05 14:48:57.280 14432 14432 D GmsMapMarkerImpl: New marker m21 with title null @ lat/lng: (45.474997,9.224005)
10-05 14:48:57.284 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.284 14432 14432 D GmsMapMarkerImpl: New marker m22 with title null @ lat/lng: (45.475183,9.227808)
10-05 14:48:57.288 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.288 14432 14432 D GmsMapMarkerImpl: New marker m23 with title null @ lat/lng: (45.479986,9.228308)
10-05 14:48:57.292 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.293 14432 14432 D GmsMapMarkerImpl: New marker m24 with title null @ lat/lng: (45.478684,9.228604)
10-05 14:48:57.297 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.297 14432 14432 D GmsMapMarkerImpl: New marker m25 with title null @ lat/lng: (45.477002,9.229116)
10-05 14:48:57.301 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.301 14432 14432 D GmsMapMarkerImpl: New marker m26 with title null @ lat/lng: (45.479406,9.222208)
10-05 14:48:57.305 14432 14432 D SafeParcel: Unknown field num 15 in com.google.android.gms.maps.model.MarkerOptions, skipping.
10-05 14:48:57.305 14432 14432 D GmsMapMarkerImpl: New marker m27 with title null @ lat/lng: (45.476177,9.221815)
10-05 14:48:57.307 14432 14432 E ClassLoader: java.lang.reflect.InvocationTargetException
10-05 14:48:57.307 14432 14432 D AndroidRuntime: Shutting down VM
10-05 14:48:57.344 14432 14432 E AndroidRuntime: FATAL EXCEPTION: main
10-05 14:48:57.344 14432 14432 E AndroidRuntime: Process: com.mobike.mobikeapp, PID: 14432
10-05 14:48:57.344 14432 14432 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.mobike.mobikeapp.util.t.h(SourceFile:905)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.mobike.mobikeapp.MainActivity.lambda$onMapLoaded$39(SourceFile:2908)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.mobike.mobikeapp.o.a(Unknown Source)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.mobike.mobikeapp.util.t.a(SourceFile:393)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.mobike.mobikeapp.util.v.run(Unknown Source)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-05 14:48:57.344 14432 14432 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-05 14:48:57.349  1490  3192 W ActivityManager: Process com.mobike.mobikeapp has crashed too many times: killing!
10-05 14:48:57.349  1490  3192 W ActivityManager:   Force finishing activity com.mobike.mobikeapp/.MainActivity
10-05 14:48:57.366  1490  3192 E ActivityManager: Found activity ActivityRecord{d5dc28e u0 com.mobike.mobikeapp/.MainActivity t2840 f} in proc activity list using null instead of expected ProcessRecord{fa87463 14432:com.mobike.mobikeapp/u0a17}
10-05 14:48:57.370  1490  3192 I ActivityManager: Killing 14432:com.mobike.mobikeapp/u0a17 (adj 100): crash
10-05 14:48:57.375  1490  3192 D ActivityManager: cleanUpApplicationRecord -- 14432
10-05 14:48:57.378  7155  7155 D baidu_location_service: baidu location service stop ...
10-05 14:48:57.381  1490  1787 I libprocessgroup: Killing pid 14451 in uid 10017 as part of process group 14432
10-05 14:48:57.381  1490  1787 I libprocessgroup: Killing pid 14502 in uid 10017 as part of process group 14432
10-05 14:48:57.396  1490  3840 I GnssLocationProvider: WakeLock acquired by sendMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@69a71b4)
10-05 14:48:57.396  1490  1784 I GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@69a71b4)
10-05 14:48:57.405  5408  5579 D conversations: deleted file /storage/emulated/0/baidu/tempdata/lcvif.dat
10-05 14:48:57.427  1490  1787 I libprocessgroup: Killing pid 14451 in uid 10017 as part of process group 14432
10-05 14:48:57.427  1490  1787 I libprocessgroup: Killing pid 14502 in uid 10017 as part of process group 14432
10-05 14:48:57.441  7155  7155 D baidu_location_service: baidu location service has stoped ...
10-05 14:48:57.455  1490  3194 D GraphicsStats: Buffer count: 7
10-05 14:48:57.456  5576  7028 V NlpLocationProvider: onSetRequest: ProviderRequest[ON interval=+1d0h0m0s0ms] by WorkSource{1000 android}
10-05 14:48:57.456  5576  7028 V NlpLocationProvider: using autoUpdate=true autoTime=86400000
10-05 14:48:57.956  5472  5786 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-05 14:48:57.956  5472  5786 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

I've tried replacing the null MarkerOptions title with an empty string, and the null snippet with an empty string but still the exception remains.
Can this be fixed in gmscore?

**Comment by n1zzo** [comment]
Is there a way to trace all the calls to gmscore APIs?
In this way I could guess more easily where a `null` is returned instead of a `Bundle`.

**Comment by n1zzo** [comment]
Apparently they fixed it themselves,
from version 6.3.0 the app is working without issues.
