### ISSUE TITLE
unable to connect to service: com.google.android.gms.measurement.START

### ISSUE THREAD

**Issue by A-Shahbazi** [microg/android_packages_apps_GmsCore#450]
Here's the relevant part of `adb logcat` output:
```
I/ActivityManager( 1825): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=ir.alobargroup.app.customer/.Splash bnds=[240,408][240,408]} from pid 10831
D/SurfaceFlinger( 1439): screenshot: sw=180, sh=320, minZ=0, maxZ=21010
I/libblt_hw( 1439): Library opened (handle = 1, fd = 30)
D/OpenGLRenderer(10831): Flushing caches (mode 1)
D/OpenGLRenderer(10831): Flushing caches (mode 0)
W/ActivityManager( 1825): Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }: not found
E/GmsClient(11117): unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
W/ActivityManager( 1825): Unbind failed: could not find connection for android.os.BinderProxy@41dba018
I/libblt_hw( 1439): Library opened (handle = 3, fd = 27)
I/libblt_hw( 1439): Library closed (handle = 5, fd = 34)
W/FA      (11117): Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
W/InputManagerService( 1825): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41538328 (uid=10188 pid=10831)
I/ActivityManager( 1825): Displayed ir.alobargroup.app.customer/.Splash: +246ms
I/libblt_hw( 1439): Library closed (handle = 1, fd = 30)
I/libblt_hw( 1439): Library opened (handle = 1, fd = 30)
W/System.err(10404): java.net.UnknownHostException: Unable to resolve host "gw.ivona.com": No address associated with hostname
W/System.err(10404): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:426)
W/System.err(10404): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:242)
W/System.err(10404): 	at java.net.InetAddress.getAllByName(InetAddress.java:220)
W/System.err(10404): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:143)
W/System.err(10404): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/System.err(10404): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/System.err(10404): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
W/System.err(10404): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:580)
W/System.err(10404): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:512)
W/System.err(10404): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:490)
W/System.err(10404): 	at com.ivona.ttslib.e.b(IvonaBackendThread.java:155)
W/System.err(10404): 	at com.ivona.ttslib.e.run(IvonaBackendThread.java:194)
W/System.err(10404): Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/System.err(10404): 	at libcore.io.Posix.getaddrinfo(Native Method)
W/System.err(10404): 	at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:55)
W/System.err(10404): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:411)
W/System.err(10404): 	... 11 more
W/ActivityManager( 1825): Launch timeout has expired, giving up wake lock!
W/ActivityManager( 1825): Activity idle timeout for ActivityRecord{41e14318 ir.alobargroup.app.customer/.Splash}
D/OpenGLRenderer(10831): Flushing caches (mode 1)
D/dalvikvm(10870): GC_EXPLICIT freed 2K, 10% free 9150K/10079K, paused 8ms+4ms
D/SurfaceFlinger( 1439): screenshot: sw=180, sh=320, minZ=0, maxZ=21020
W/ActivityManager( 1825): Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }: not found
E/GmsClient(11117): unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
W/ActivityManager( 1825): Unbind failed: could not find connection for android.os.BinderProxy@415810f0
W/FA      (11117): Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
I/libblt_hw( 1439): Library opened (handle = 5, fd = 35)
W/ActivityManager( 1825): Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }: not found
E/GmsClient(11117): unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
W/ActivityManager( 1825): Unbind failed: could not find connection for android.os.BinderProxy@41efd418
W/FA      (11117): Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
D/OpenGLRenderer(11117): Flushing caches (mode 1)
I/libblt_hw( 1439): Library closed (handle = 3, fd = 27)
I/libblt_hw( 1439): Library closed (handle = 1, fd = 30)
```

**Comment by swiftgeek** [comment]
Gonna add this fragment:
```
12-06 14:45:23.502 11614 11691 E YouTube : Unexpected exception while attempting to get the GCM registration token                                                                                                
12-06 14:45:23.502 11614 11691 E YouTube : java.io.IOException: SERVICE_NOT_AVAILABLE                                                                                                                             
12-06 14:45:23.502 11614 11691 E YouTube :      at mhk.b(Unknown Source)                                                                                                                                          
12-06 14:45:23.502 11614 11691 E YouTube :      at mhk.a(Unknown Source)                                                                                                                                          
12-06 14:45:23.502 11614 11691 E YouTube :      at mhi.a(Unknown Source)                                                                                                                                          
12-06 14:45:23.502 11614 11691 E YouTube :      at oqc.a(SourceFile:5)                                                                                                                                            
12-06 14:45:23.502 11614 11691 E YouTube :      at yls.run(Unknown Source)                                                                                                                                        
12-06 14:45:23.502 11614 11691 E YouTube :      at rmk.run(SourceFile:2)                                                                                                                                       
12-06 14:45:23.502 11614 11691 E YouTube :      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)                                                                                        
12-06 14:45:23.502 11614 11691 E YouTube :      at java.util.concurrent.FutureTask.run(FutureTask.java:237)                                                     
12-06 14:45:23.502 11614 11691 E YouTube :      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)                                                 
12-06 14:45:23.502 11614 11691 E YouTube :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-06 14:45:23.502 11614 11691 E YouTube :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-06 14:45:23.502 11614 11691 E YouTube :      at rok.run(SourceFile:24)
12-06 14:45:23.502 11614 11691 E YouTube :      at java.lang.Thread.run(Thread.java:761)
```

**Comment by tomasz1986** [comment]
This "measurement" thing is basically Google Analytics with a different name. MicroG does not support any analytics related stuff (on purpose), so these kind of errors should be harmless.

**Comment by ale5000-git** [comment]
In my opinion microG should add a dummy functions for this because the apps retry to use this continuously and failing cause additional battery consumption.

**Comment by A-Shahbazi** [comment]
@tomasz1986 
This is not "harmless" because the app doesn't go beyond the splash screen. It shows an error message and asks me to close(leaving no other choice).

**Comment by tomasz1986** [comment]
> @tomasz1986
> This is not "harmless" because the app doesn't go beyond the splash screen. It shows an error message and asks me to close(leaving no other choice).

Well, you had not said that the app does not open at all... I can also see similar messages in my logcat but the apps I use do work normally nevertheless.

**Comment by ale5000-git** [comment]
@tomasz1986: I don't remember exactly but I'm sure that at least one app try to use it infinite times.

**Comment by wojtoo** [comment]
well, this is the problem which most of us have with measurement.
But the problem is when app won't stop call com.google.android.gms.measurement which cause infinite loop. When app stop, it is not a big deal.
The best solution would be as ale5000 said - dummy functions - like fake store or similar.
That would be a comprehensive solution.
Second option what I tried was to make a xposed module which make that app think that measurement service started but for me it was unsuccessful OR add <meta-data android:name="firebase_analytics_collection_deactivated" android:value="true"/>) to android manifest
Third option (most problematic) is to decompile app using apktool and deactivate it in androidmanifest
Since 2.3.1 version it is possible to use apktool d -r -s --force-manifest this is good option only to change manifest file.
All the best for you in 2018 and thanks for this great project

**Comment by logic** [comment]
This appears to affect the Patreon app (`com.patreon.android`) as well now (I've opened an ticket with Patreon about it):

```
01-24 18:20:08.255  4683 11760 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
01-24 18:20:08.256  4683 13281 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@46fa456
01-24 18:20:08.257 14829 14856 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
01-24 18:20:08.300 14829 14829 W FA      : Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
01-24 18:20:08.393  4683  4779 I ActivityManager: Displayed com.patreon.android/.ui.auth.AuthActivity: +146ms (total +248ms)
```

In this case, the problem manifests as an inability to log in.

**Comment by Freeedim** [comment]
It also prevents N26 (neobanking app) to display transfer confirmation toasts, thus preventing any transfer at all.

**Comment by A-Shahbazi** [comment]
I can confirm this is fixed with microG GmsCore `0.2.6.13280`

**Comment by MarkNashat15** [comment]
Check this video and you will get the solution in the best way

https://youtu.be/G6gubdky87M

**Comment by worstenbrood** [comment]
The GmsClient: unable to connect to service: com.google.android.gms.auth.api.signin.service.START on com.google.android.gms happens on the latest v0.2.22.212658 again

**Comment by ale5000-git** [comment]
@worstenbrood: Please test version 0.2.23.214816 and open a separate issue if still needed
