### ISSUE TITLE
java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#464]
Get a crash running [Speed Test app](https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest) with microG 0.2.4-108. The app works properly when running microG 0.2.4-107

This is with Android 7.1.2 (Lineage with microG).

```
01-03 13:02:24.313 22994 22994 D AndroidRuntime: Shutting down VM
01-03 13:02:24.469 22994 22994 E AndroidRuntime: FATAL EXCEPTION: main
01-03 13:02:24.469 22994 22994 E AndroidRuntime: Process: org.zwanoo.android.speedtest, PID: 22994
01-03 13:02:24.469 22994 22994 E AndroidRuntime: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.app.ContextImpl.checkMode(ContextImpl.java:2134)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:349)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.internal.zzbw.a(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.internal.zzbx.a(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.internal.zzby.a(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.zzf.<init>(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.client.zzz.b(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.client.zzz.a(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.internal.client.zzz.zza(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.google.android.gms.ads.doubleclick.PublisherAdView.loadAd(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.ookla.speedtest.bannerad.a.b(SourceFile:381)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.ookla.speedtest.bannerad.a.a(SourceFile:326)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.ookla.speedtest.bannerad.a$1$1.a(SourceFile:309)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.ookla.speedtest.bannerad.a$1$1.a(SourceFile:306)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.ookla.speedtest.nativead.google.d$5.a(SourceFile:153)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.ookla.speedtest.nativead.google.d$5.onReceiveValue(SourceFile:150)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.monet.monetbidder.a$1$1$1.run(Unknown Source)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-03 13:02:24.469 22994 22994 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-03 13:02:24.478  3861  9926 W ActivityManager:   Force finishing activity org.zwanoo.android.speedtest/com.ookla.speedtest.softfacade.MainActivity

```

**Comment by budbay** [comment]
I'm having the same issue since updating to 0.2.4-108, running NitrogenOS android 8.1

**Comment by AnthonyNahas** [comment]
it seems that permissions are not granted

**Comment by Omar1123** [comment]
World-readable files can be a security flaw. So android first deprecated it and then completely removed it. MODE_WORLD_READABLE was deprecated in versions till Android M. But in Android N it is no longer supported and throws SecurityException. So try a different mode. I used Context.MODE_PRIVATE and it worked.
