### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.a.asBinder()' on a null object reference

### ISSUE THREAD

**Issue by jeekajoo** [microg/android_packages_apps_GmsCore#475]
Hi,

`com.paris.velib` is working smoothly except when I click on an element (a bike sharing station) on the map to have details. It crashes:

```
01-22 12:03:44.828   856      7886        ActivityManager  W  Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
01-22 12:03:44.829   856     31447        ActivityManager  W  Unbind failed: could not find connection for android.os.BinderProxy@d2a7e65
01-22 12:03:44.829  17939    18136              GmsClient  E  unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  FATAL EXCEPTION: main
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  Process: com.paris.velib, PID: 17939
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.a.asBinder()' on a null object reference
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.google.android.gms.dynamic.j.a(Unknown Source)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.google.android.gms.maps.model.h.b(Unknown Source)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.paris.velib.views.map.a$5.a(MapFragment.java:401)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.google.android.gms.maps.k.a(Unknown Source)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.google.android.gms.maps.a.n.onTransact(Unknown Source)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at android.os.Binder.transact(Binder.java:499)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.google.android.gms.maps.internal.IOnMarkerClickListener$Stub$Proxy.onMarkerClick(IOnMarkerClickListener.java:81)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.microg.gms.maps.GoogleMapImpl.onClick(GoogleMapImpl.java:336)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.microg.gms.maps.markup.MarkerImpl.onClick(MarkerImpl.java:216)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.microg.gms.maps.BackendMap.onItemSingleTapUp(BackendMap.java:217)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.microg.gms.maps.BackendMap.onItemSingleTapUp(BackendMap.java:55)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.layers.marker.ItemizedLayer.onSingleTapUpHelper(ItemizedLayer.java:148)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.layers.marker.ItemizedLayer$1.run(ItemizedLayer.java:158)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.layers.marker.ItemizedLayer.activateSelectedItems(ItemizedLayer.java:241)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.layers.marker.ItemizedLayer.onGesture(ItemizedLayer.java:267)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.map.Layers.handleGesture(Layers.java:217)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.map.Map.handleGesture(Map.java:412)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at org.oscim.android.input.GestureHandler.onSingleTapConfirmed(GestureHandler.java:80)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:154)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:6171)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
01-22 12:03:44.886  17939    17939         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
01-22 12:03:44.890   856      4023        ActivityManager  W  Force finishing activity com.paris.velib/.views.home.HomeActivity
01-22 12:03:44.897   856      4023            ContextImpl  W  Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.Ap
                                                            pErrors.crashApplicationInner:370 com.android.server.am.AppErrors.crashApplication:305 com.android.server.am.ActivityManagerService
                                                            .handleApplicationCrashInner:13549 com.android.server.am.ActivityManagerService.handleApplicationCrash:13531
01-22 12:03:44.951   856     10677         OpenGLRenderer  I  Initialized EGL, version 1.4
01-22 12:03:44.952   856     10677         OpenGLRenderer  D  Swap behavior 1
01-22 12:03:45.053   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 0.
01-22 12:03:45.053   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 2.
01-22 12:03:45.069   8478     8478             GpsTrailer  D  Received battery info, batteryLeft: 0.5
01-22 12:03:45.069   8478     8478             GpsTrailer  D  Flags is 69, current notset is NotificationSetting [iconId=2130837602, msgId=2131034502, sticky=false, onFlags=69, offFlags=0]
01-22 12:03:45.069   8478     8478             GpsTrailer  D  Flags is 69, current notset is NotificationSetting [iconId=2130837602, msgId=2131034502, sticky=false, onFlags=69, offFlags=0]
01-22 12:03:45.305   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 0.
01-22 12:03:45.305   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 2.
01-22 12:03:45.396   856      896         ActivityManager  W  Activity pause timeout for ActivityRecord{e5baf2c u0 com.paris.velib/.views.home.HomeActivity t20321 f}
01-22 12:03:45.479   4049     4181                 Adreno  I  QUALCOMM build                   : 6818200, *********
01-22 12:03:45.479   4049     4181                 Adreno  I  Build Date                       : 11/18/16
01-22 12:03:45.479   4049     4181                 Adreno  I  OpenGL ES Shader Compiler Version: XE031.09.00.04
01-22 12:03:45.479   4049     4181                 Adreno  I  Local Branch                     : N25
01-22 12:03:45.479   4049     4181                 Adreno  I  Remote Branch                    :
01-22 12:03:45.479   4049     4181                 Adreno  I  Remote Branch                    :
01-22 12:03:45.479   4049     4181                 Adreno  I  Reconstruct Branch               :
01-22 12:03:45.493   4049     4181                    HAL  I  loaded HAL id=gralloc path=/system/lib64/hw/gralloc.msm8992.so hmi=0x0 handle=0x73140a8010
01-22 12:03:45.499   4049     4181         OpenGLRenderer  I  Initialized EGL, version 1.4
01-22 12:03:45.500   4049     4181         OpenGLRenderer  D  Swap behavior 1
01-22 12:03:45.557   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 0.
01-22 12:03:45.557   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 2.
01-22 12:03:45.722   856      3328          LocSvc_ApiV02  E  I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 86 QMI_LOC_EVENT_GNSS_SV_IN
                                                            FO_IND_V02
01-22 12:03:45.722   856      3239             LocSvc_afw  E  I/<=== sv_status_cb - line 1071 20
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5240
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5240
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5240
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5240
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5240
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5240
01-22 12:03:45.723   856      3328          LocSvc_ApiV02  E  I/<--- void globalEventCb(locClientHandleType, uint32_t, const locClientEventIndUnionType, void *) line 86 QMI_LOC_EVENT_POSITION_R
                                                            EPORT_IND_V02
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5210
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5210
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5210
01-22 12:03:45.723   856      3239        LocSvc_eng_nmea  E  I/<=== nmea_cb line 62 0x72ee1f5210
01-22 12:03:45.809   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 0.
01-22 12:03:45.810   589      589             slim_daemon  E  [SLIM] slim_ProviderConvertTimeMt: NULL pointer or invalid filter with provider 1, unable to convert time for service 2.
01-22 12:03:46.003  17939    17969        CrashlyticsCore  I  Crashlytics report upload complete: 5A65C4E50340-0001-4613-69096F66099E
01-22 12:03:46.039   4049     4181         OpenGLRenderer  W  Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

Is there anything we can do to avoid it to crash?

OS: Omnirom 7.1.2
Phone: Nexus 5X (bullhead)
microg version: 0.2.4-108+g464d454d
App tested: `com.paris.velib` (Paris Velib) version 4.0.3

Thanks.
J.

**Comment by jeekajoo** [comment]
`com.paris.velib` version 4.1.0 fixed it.
