### ISSUE TITLE
Maps API Exceptions Runtastic Pro

### ISSUE THREAD

**Issue by lambdaupb** [microg/android_packages_apps_GmsCore#49]
Im not sure if thats because these Apps use an unsupported API or its a bug in this project.
Please close if its not helpful.

Here are some Exceptions I got when running Some Apps:

##### Runtastic Pro
```

10-22 18:23:39.082 23445 23445 E AndroidRuntime: FATAL EXCEPTION: main
10-22 18:23:39.082 23445 23445 E AndroidRuntime: Process: com.runtastic.android.pro2, PID: 23445
10-22 18:23:39.082 23445 23445 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'com.vividsolutions.jts.geom.Geometry org.oscim.layers.vector.geometries.Drawable.getGeometry()' on a null object reference
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at org.oscim.layers.vector.VectorLayer.add(VectorLayer.java:106)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at org.microg.gms.maps.BackendMap.updateDrawableLayer(BackendMap.java:174)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at org.microg.gms.maps.BackendMap.update(BackendMap.java:212)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at org.microg.gms.maps.GoogleMapImpl.update(GoogleMapImpl.java:239)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at org.microg.gms.maps.markup.PolygonImpl.setVisible(PolygonImpl.java:152)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.google.android.gms.maps.model.internal.IPolygonDelegate$Stub.onTransact(IPolygonDelegate.java:168)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:380)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.google.android.gms.maps.model.internal.zzj$zza$zza.setVisible(Unknown Source)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.google.android.gms.maps.model.Polygon.setVisible(Unknown Source)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.runtastic.android.i.b.<init>(BoltPolylineTraceOverlay.java:116)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.runtastic.android.fragments.bolt.BoltMapFragment.initMap(BoltMapFragment.java:473)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.runtastic.android.fragments.bolt.BoltMapFragment.onCreateView(BoltMapFragment.java:280)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.runtastic.android.common.ui.view.VerticalViewPager.b(VerticalViewPager.java:997)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.runtastic.android.common.ui.view.VerticalViewPager.b(VerticalViewPager.java:846)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at com.runtastic.android.common.ui.view.VerticalViewPager.onMeasure(VerticalViewPager.java:1356)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:868)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.View.measure(View.java:17562)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
10-22 18:23:39.082 23445 23445 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:4
```

##### GpsLogger Lite
```
10-22 18:29:29.346 26707 26707 E AndroidRuntime: FATAL EXCEPTION: main
10-22 18:29:29.346 26707 26707 E AndroidRuntime: Process: com.peterhohsy.gpsloggerlite, PID: 26707
10-22 18:29:29.346 26707 26707 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=ACTION_GPS_gpsloggerpro flg=0x10 (has extras) } in com.peterhohsy.gpsloggerlite.MainActivity$CGPSReceiver@4c0bea5
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:877)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5294)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.vividsolutions.jts.geom.Envelope com.vividsolutions.jts.geom.Geometry.getEnvelopeInternal()' on a null object reference
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at org.oscim.layers.vector.VectorLayer.bbox(VectorLayer.java:89)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at org.oscim.layers.vector.VectorLayer.add(VectorLayer.java:106)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at org.microg.gms.maps.BackendMap.updateDrawableLayer(BackendMap.java:174)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at org.microg.gms.maps.BackendMap.add(BackendMap.java:166)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at org.microg.gms.maps.GoogleMapImpl.addPolyline(GoogleMapImpl.java:197)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(IGoogleMapDelegate.java:134)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at org.microg.gms.maps.GoogleMapImpl.onTransact(GoogleMapImpl.java:428)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:380)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$a$a.addPolyline(Unknown Source)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.google.android.gms.maps.GoogleMap.addPolyline(Unknown Source)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.peterhohsy.gpsloggerlite.MainActivity.updateGooglePolyLine(MainActivity.java:1765)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.peterhohsy.gpsloggerlite.MainActivity.onLocationChangeEx(MainActivity.java:1618)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at com.peterhohsy.gpsloggerlite.MainActivity$CGPSReceiver.onReceive(MainActivity.java:2096)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:867)
10-22 18:29:29.346 26707 26707 E AndroidRuntime: 	... 9 more
```

**Comment by lambdaupb** [comment]
Thanks :)

Runtastic Pro now works, - Even though The map view is just completely white.
Which is acceptable.

**Comment by mar-v-in** [comment]
Yes, the Maps API has some terrible rendering glitches, especially when other views overlap. I totally rely on third-parties there as I am not very deep in OpenGL and Graphic coding, so this is unlikely to be fixed soon...
