### ISSUE TITLE
Cannot sign into Google Photos

### ISSUE THREAD

**Issue by apandichi** [microg/android_packages_apps_GmsCore#512]
I have installed microG core and Services Framework. 
I try to sign into Google Photos using my account.
I get a dialog saying "No connection. Couldn't connect to the server"
The logcat output looks something like this:

```
03-29 13:36:27.169 W/AccountManagerService( 1877): caller uid 10187 is different than the authenticator's uid
03-29 13:36:27.179 E/HttpOperation(15890): [getphotossettings] Unexpected exception
03-29 13:36:27.179 E/HttpOperation(15890): java.io.IOException: Cannot obtain authentication token
03-29 13:36:27.179 E/HttpOperation(15890):      at uho.a(PG:84)
03-29 13:36:27.179 E/HttpOperation(15890):      at ugo.o(PG:543)
03-29 13:36:27.179 E/HttpOperation(15890):      at ugj.a(PG:1402)
03-29 13:36:27.179 E/HttpOperation(15890):      at ugo.i(PG:154)
03-29 13:36:27.179 E/HttpOperation(15890):      at jvz.a(PG:103)
03-29 13:36:27.179 E/HttpOperation(15890):      at tae.e(PG:307)
03-29 13:36:27.179 E/HttpOperation(15890):      at tau.run(PG:1321)
03-29 13:36:27.179 E/HttpOperation(15890):      at wey.run(PG:93)
03-29 13:36:27.179 E/HttpOperation(15890):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-29 13:36:27.179 E/HttpOperation(15890):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-29 13:36:27.179 E/HttpOperation(15890):      at java.lang.Thread.run(Thread.java:856)
03-29 13:36:27.179 E/HttpOperation(15890): Caused by: java.lang.SecurityException: caller uid 10187 is different than the authenticator's uid
03-29 13:36:27.179 E/HttpOperation(15890):      at android.os.Parcel.readException(Parcel.java:1327)
03-29 13:36:27.179 E/HttpOperation(15890):      at android.os.Parcel.readException(Parcel.java:1281)
03-29 13:36:27.179 E/HttpOperation(15890):      at qhd.a(Unknown Source)
03-29 13:36:27.179 E/HttpOperation(15890):      at pco.a(Unknown Source)
03-29 13:36:27.179 E/HttpOperation(15890):      at pcn.a(Unknown Source)
03-29 13:36:27.179 E/HttpOperation(15890):      at pcn.b(Unknown Source)
03-29 13:36:27.179 E/HttpOperation(15890):      at pcm.c(Unknown Source)
03-29 13:36:27.179 E/HttpOperation(15890):      at pcm.a(Unknown Source)
03-29 13:36:27.179 E/HttpOperation(15890):      at rss.a(PG:22)
03-29 13:36:27.179 E/HttpOperation(15890):      at uhk.a(PG:3067)
03-29 13:36:27.179 E/HttpOperation(15890):      at uhk.a(PG:1104)
03-29 13:36:27.179 E/HttpOperation(15890):      at uho.a(PG:80)
03-29 13:36:27.179 E/HttpOperation(15890):      ... 10 more
```

Any idea on how to fix this? Thanks!

**Comment by apandichi** [comment]
Here's a better stacktrace, this time for Google Keep

```
04-04 16:39:34.279 W/AccountManagerService( 1847): caller uid 10187 is
different than the authenticator's uid
04-04 16:39:34.279 W/GmsCheckinSvc( 4927): java.lang.SecurityException:
caller uid 10187 is different than the authenticator's uid
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.os.Parcel.readException(Parcel.java:1327)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.os.Parcel.readException(Parcel.java:1281)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.accounts.IAccountManager$Stub$Proxy.getPassword(IAccountManager.java:415)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.accounts.AccountManager.getPassword(AccountManager.java:308)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at org.microg.gms.checkin.CheckinManager.checkin(CheckinManager.java:51)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at org.microg.gms.checkin.CheckinService.onHandleIntent(CheckinService.java:54)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.os.Handler.dispatchMessage(Handler.java:99)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.os.Looper.loop(Looper.java:137)
04-04 16:39:34.279 W/GmsCheckinSvc( 4927):      at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by MOVZX** [comment]
Google Keep is working perfectly.

**Comment by apandichi** [comment]
@MOVZX Good to know that it's working for other people. I'd love to know what I'm missing. 
On my device, several apps are failing with this same message: `caller uid 10187 is different than the authenticator's uid`

**Comment by ArchangeGabriel** [comment]
@apandichi Hum, can you detail what ROM you’re using and what exact step did you follow to install μG? My first guess here would be you forgot to install FakeStore or to give it sigspoof permission.

**Comment by MOVZX** [comment]
@apandichi I'm using this **MicroG Packs**:

https://t.me/NoGooLag/42

All Google apps working except Play Games.

**Comment by ArchangeGabriel** [comment]
[Source](https://github.com/NoGooLag/MicroG_Packs) for anyone like me that cannot see the content from the above link.

This goes far beyond just μG and also comes with several GApps one might not want.

**Comment by apandichi** [comment]
I'm using a rooted stock ICS 4.0.4 ROM. I installed μG and FakeStore using F-Droid.
Signature spoofing is provided by an Xposed framework module.
Thanks for the links, @MOVZX, @ArchangeGabriel, I'll give it a try.
