### ISSUE TITLE
FreedomPop Messaging unable to launch

### ISSUE THREAD

**Issue by bmccoy11** [microg/android_packages_apps_GmsCore#539]
The FreedomPop Messaging app is currently unable to launch with GmsCore due to a required API being unavailable. Is there currently any intention to add this API?

`04-30 11:16:40.603   983  1598 I ActivityManager: Displayed com.freedompop.phone/.ui.login.SplashActivity: +1s330ms
04-30 11:16:40.606  8672  8734 W zygote  : Long monitor contention with owner pool-6-thread-1 (8729) at long com.android.org.conscrypt.NativeCrypto.RSA_generate_key_ex(int, byte[])(NativeCrypto.java:-2) waiters=0 in com.google.firebase.iid.zzs com.google.firebase.iid.zzr.zzp(java.lang.String, java.lang.String, java.lang.String) for 540ms
04-30 11:16:40.633  3654  3705 D GmsServicesProvider: query caller=com.freedompop.phone name=fireperf:dd68745c15485eea795b6a7aa00450ec3c14186c_limits value=null
04-30 11:16:40.641  3654  3654 D GmsClearcutSvc: onBind: Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms }
04-30 11:16:40.654  3654  3729 D GmsServicesProvider: query caller=com.freedompop.phone name=fireperf:6bb3324f756876b0dd8f402fc2986d9793e96cb5_limits value=null
04-30 11:16:40.656  3654  4144 D GmsServicesProvider: query caller=com.freedompop.phone name=fireperf:f00939dc9169e53f04fd8d4219029aa5fd0dd7ab_limits value=null
04-30 11:16:40.667  3654  3705 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
04-30 11:16:40.667  3654  3705 D GmsClearcutSvc: bound by: GetServiceRequest{serviceId=CLEARCUT_LOGGER, gmsVersion=11020000, packageName='com.freedompop.phone', extras=Bundle[{}]}
04-30 11:16:41.892  8672  8745 D /DefaultRequestRunner.java:151: 11:16:41.892 Thread-3 Network request call ended.
04-30 11:16:41.893  8672  8745 D /RequestProgressManager.java:82: 11:16:41.893 Thread-3 Sending progress COMPLETE
04-30 11:16:41.894  8672  8745 D /SpiceServiceListenerNotifier.java:146: 11:16:41.894 Thread-3 Message queue is Handler (android.os.Handler) {73f775e}
04-30 11:16:41.898  8672  8672 V /DefaultRequestListenerNotifier.java:131: 11:16:41.897 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@4368db8
04-30 11:16:41.900  8672  8745 D /SpiceServiceListenerNotifier.java:146: 11:16:41.899 Thread-3 Message queue is Handler (android.os.Handler) {73f775e}
04-30 11:16:41.903  8672  8745 V /RequestProgressManager.java:161: 11:16:41.902 Thread-3 Removing CachedSpiceRequest [requestCacheKey=null, cacheDuration=0, spiceRequest=IdentificationRequestSimSingle{iccid1=89011703278097075173}]  size is 1
04-30 11:16:41.904  8672  8745 D /RequestProgressManager.java:91: 11:16:41.904 Thread-3 Sending all request complete.
04-30 11:16:41.905  8672  8745 V /SpiceService.java:495: 11:16:41.905 Thread-3 Pending requests : 0
04-30 11:16:41.907  8672  8745 D /SpiceServiceListenerNotifier.java:146: 11:16:41.906 Thread-3 Message queue is Handler (android.os.Handler) {73f775e}
04-30 11:16:41.908  8672  8745 D /DefaultRequestRunner.java:295: 11:16:41.908 Thread-3 It tooks 1401 ms to process request CachedSpiceRequest [requestCacheKey=null, cacheDuration=0, spiceRequest=IdentificationRequestSimSingle{iccid1=89011703278097075173}].
04-30 11:16:49.598   403   409 D NetlinkEvent: Unknown ND option type 31                                                04-30 11:16:50.095   983  6789 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found                                                                     04-30 11:16:50.097   983  6785 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@ccefdfb                                                                                                                   04-30 11:16:50.097  8672  8692 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms                                                                                                    04-30 11:16:50.099  8672  8672 W FA      : Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}                                                                                               04-30 11:16:50.102  8672  8692 E FA      : Discarding data. Failed to send event to service`

**Comment by JonnyTech** [comment]
My FreedomPop Messaging app just updated to v23 and fails to register for push notifications. Downgrading to v22 works. Not sure what the problem is.

**Comment by bmccoy11** [comment]
I'm not able to register with push notifications on version 22.00.1068.0202, or the last beta :/

I'm running an Android 8.1 ROM, and MicroG has otherwise been working fine, although I've had some push notification issues with Riot.

**Comment by hockeymikey** [comment]
I have this same issue. So originally was on 2.4-108 and worked fine.  Upgraded to 2.4-111 and then it just stopped working. Got stuck on registering for push notifications. I'm on Android 6.0.1 if that matters.
Here's the error I get:

07-23 13:29:55.432 E//SourceFile:154(4959): 13:29:55.431 Thread-260 An exception occurred during request network execution :retrofit.RetrofitError: 400 Bad Request
07-23 13:29:55.432 E//SourceFile:154(4959): FreedomPopException{error='invalid_request', description='You must provide a pushToken parameter'}
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.freedompop.acl.common.FreedomPopExceptionProvider.get(SourceFile:25)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.freedompop.acl.common.FreedomPopErrorHandler.handleError(SourceFile:24)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at retrofit.RestAdapter$RestHandler.invoke(SourceFile:242)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at $Proxy3.registerPushToken(Unknown Source)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.freedompop.acl.requests.RegisterPushTokenRequest.loadData(SourceFile:40)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.freedompop.acl.requests.RegisterPushTokenRequest.loadData(SourceFile:12)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.freedompop.acl.requests.auth.AuthorizedRequest.loadDataFromNetwork(SourceFile:25)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(SourceFile:48)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(SourceFile:150)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at com.octo.android.robospice.request.DefaultRequestRunner$1.run(SourceFile:217)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at java.lang.Thread.run(Thread.java:818)
07-23 13:29:55.432 E//SourceFile:154(4959): Caused by: retrofit.RetrofitError: 400 Bad Request
07-23 13:29:55.432 E//SourceFile:154(4959): 	at retrofit.RestAdapter$RestHandler.invokeRequest(SourceFile:388)
07-23 13:29:55.432 E//SourceFile:154(4959): 	at retrofit.RestAdapter$RestHandler.invoke(SourceFile:240)
07-23 13:29:55.432 E//SourceFile:154(4959): 	... 13 more

**Comment by chris42** [comment]
Please see #439 and try latest microg update

**Comment by sm4rk0** [comment]
...and close this issue if it's solved, or report your findings.

**Comment by eSavior** [comment]
I applied the suggestion from mar-v-in to "open the system phone app and dial *#*#2432546#*#* to do a manual device registration" and my FreedomPop app v24.01.14950926 successfully registered and started properly on /e/ ROM 0.7 nightly build 2019101126749 for my device (it's a Lineage OS based ROM derived from Android 7.1.2).

**Comment by hockeymikey** [comment]
Freedompop is working for me on my devices. The one is 0.2.9.19420.
