### ISSUE TITLE
Attempt to invoke virtual method isRoaming() on a null object reference

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#560]
I get this at boot:
```
[ 06-17 21:30:50.251  3264: 3598 W/GmsGcmMcsSvc ]
Exception while connecting!
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isRoaming()' on a null object reference
	at org.microg.gms.gcm.GcmPrefs.getNetworkPrefForInfo(GcmPrefs.java:103)
	at org.microg.gms.gcm.McsService.connect(McsService.java:370)
	at org.microg.gms.gcm.McsService.handleMessage(McsService.java:535)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at org.microg.gms.gcm.McsService$HandlerThread.run(McsService.java:152)

[ 06-17 21:30:50.251  3264: 3598 D/GmsGcmMcsSvc ]
Teardown initiated, reason: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isRoaming()' on a null object reference
```

The problem is [here](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/gcm/GcmPrefs.java#L102) but it is caused by the fact that there isn't a null check for the two call of `cm.getActiveNetworkInfo()` [here](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/gcm/McsService.java#L366).

**ConnectivityManager.getActiveNetworkInfo():**
`a NetworkInfo object for the current default network or **null** if no default network is currently active.`

**Comment by ale5000-git** [comment]
Fixed in https://github.com/microg/android_packages_apps_GmsCore/commit/7bbdcac990a8bcf939b8012c642cbe2249e64758
