### ISSUE TITLE
Twitter crashes on startup: "couldn't find "libcrashlytics.so""

### ISSUE THREAD

**Issue by fkoester** [microg/android_packages_apps_GmsCore#586]
I am running a self-build LineageOS for microG 15.1 on Moto G5 Plus (potter) without any special tools like XPrivacy or something. MicroG is on version 0.2.4-111-gf1cdb48.

I installed Twitter 7.56.0.1048 via Yalp Store and it immediately crashes after lauchn with the following exception logged:

```
08-05 19:08:46.918 31805 31805 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.twitter.android-Tc_VgMkIfeomZyT8zmIiMQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.twitter.android-Tc_VgMkIfeomZyT8zmIiMQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libcrashlytics.so"
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.crashlytics.android.ndk.JniNativeApi.<clinit>(Twttr:13)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.crashlytics.android.ndk.g.a(Twttr:19)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.crashlytics.android.ndk.b.a_(Twttr:54)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.g.a(Twttr:44)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.services.concurrency.AsyncTask.a(Twttr:611)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.services.concurrency.c.a(Twttr:43)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.h.p(Twttr:69)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.c.a(Twttr:440)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.c.j(Twttr:384)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.c.d(Twttr:342)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at io.fabric.sdk.android.c.a(Twttr:333)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.twitter.fabric.CrashlyticsErrorLogger.<init>(Twttr:41)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.twitter.android.initialization.ErrorReporterInitializer.a(Twttr:65)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.twitter.android.initialization.ErrorReporterInitializer.a(Twttr:49)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at cfy.a(Twttr:123)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at cfy.a(Twttr:89)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.twitter.app.common.base.BaseApplication.onCreate(Twttr:42)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.twitter.app.common.app.InjectedApplication.onCreate(Twttr:24)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.twitter.app.TwitterApplication.onCreate(Twttr:67)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
08-05 19:08:46.918 31805 31805 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-05 19:08:46.921 15561 27776 W ActivityManager:   Force finishing activity com.twitter.android/.StartActivity
```

**Comment by jeekajoo** [comment]
Same here.
The last twitter version that works is 7.53.0. I'm sticking on it since later versions crash on startup.

**Comment by jeekajoo** [comment]
Tested last twitter version with microg v0.2.5.12879. Still crashing.

**Comment by ale5000-git** [comment]
@fkoester @jeekajoo

I have installed Twitter 7.59.0.1054, logged-in and it works perfectly.
Maybe your data are corrupted, try to uninstall Twitter completely and reinstall it.

**Comment by jeekajoo** [comment]
I already did that (uninstalling Twitter completely and reinstalling it). I'm using Omnirom 7.1.2

**Comment by chilliger** [comment]
Can confirm with latest microg and Twitter

**Comment by chilliger** [comment]
@jeekajoo do have massive system slow downs when using the old Twitter version? This is especially happening on my devices when I open a tweet notifications from the notification panel.

**Comment by voidstarstar** [comment]
I can also confirm this issue.
Twitter 7.62.0.1058
microG 0.2.5.12879

It seemed odd that a crash occurred in 7.56 and 7.62 but not in 7.59.  I thought that perhaps @ale5000-git reported it working due to some other ROM specific reason, so I tried out 7.59 and it worked!  Does Twitter keep enabling/disabling something in their builds?

Possibly related to #208.

[Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/) looks like the same thing that Twitter [acquired in 2013](https://fabric.io/blog/2013/01/28/crashlytics-is-joining-forces-with-twitter).  I haven't seen any other apps that have a Crashlytics related crash, so I wonder if Twitter has some type of special API access.

(I'm also obligated to note the humor of a crash analysis tool being the cause of a crash.)

**Comment by jimbo1qaz** [comment]
Dropbox should use https://medium.com/keepsafe-engineering/relinker-v1-2-is-here-b8f1799e22fe

**Comment by chilliger** [comment]
Is this still happening. Haven't updated Twitter in a while...

**Comment by wjbolles** [comment]
I haven't noticed it anymore.
