### ISSUE TITLE
Google Contacts Crash

### ISSUE THREAD

**Issue by malitech** [microg/android_packages_apps_GmsCore#589]
Hello,
I just removed google apps from stock marshmallow on my nexus 5 and installed microg. I downloaded the unofficial microg to prevent update play services message. The Google Contacts app is not working. It is crashing with this error.

**java.lang.SecurityException: Access denied, missing EXTENDED_ACCESS permission
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at drg.zzb(PG:20)
at dxj.a(PG:43)
at dxn.a(PG:58)
at dqp.zza(PG:3)
at djc.zzb(PG:14)
at dge.b(PG:37)
at dge.a(PG:25)
at dhb.a(PG:78)
at dgt.a(PG:293)
at amm.a(PG:6)
at dgt.a(PG:487)
at dgh.g(PG:133)
at dgh.a(PG:74)
at dhb.a(PG:51)
at djm.a(PG:6)
at dlu.a(PG:18)
at dlm.a(PG:21)
at dlp.handleMessage(PG:62)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)**

All other apps are working. What can I do? In gmail, sometimes, I get "Gmail is having trouble with Google Play Services. Please try again."

I added my google account. When I open Accounts > Google > "Settings has stopped" crash.

Please help me. Thank you!

**Comment by ildar** [comment]
Related: https://github.com/microg/android_packages_apps_GmsCore/issues/144

**Comment by ildar** [comment]
+ probably related: https://github.com/thermatk/FakeGApps/issues/30

**Comment by ildar** [comment]
might also be related: https://github.com/microg/android_packages_apps_GmsCore/issues/154

**Comment by voidstarstar** [comment]
Also related: https://github.com/microg/android_packages_apps_GmsCore/issues/606
