### ISSUE TITLE
Google Voice Crash

### ISSUE THREAD

**Issue by robsee** [microg/android_packages_apps_GmsCore#598]
On a brand new compile of microg in 8.1 or 9.0 (tried with LineageOS and AOSP) with a fresh userdata partition on a pixel2xl, Google Voice will crash every time I open it, if I have a google account setup. The crash resembles the following depending on what version of GVoice you are using:
08-29 00:17:04.562  3230  3230 E AndroidRuntime: Process: com.google.android.apps.googlevoice, PID: 3230
08-29 00:17:04.562  3230  3230 E AndroidRuntime: java.lang.RuntimeException: ghv: jsu: <string of letters and numbers unique to the user>/photo.jpg
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at hph.a(PG:10)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at hor.a(PG:43)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at hoj.a(PG:47)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at hon.a(PG:29)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at hlx.a(PG:9)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at imf.a(PG:54)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at ahq.a(PG:155)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at agb.a(PG:25)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at afy.a(PG:644)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at afy.a(PG:628)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at afy.c(PG:301)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.D(PG:1386)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.onMeasure(PG:965)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.support.v7.widget.CardView.onMeasure(PG:36)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.View.measure(View.java:23169)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2719)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1856)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-29 00:17:04.562  3230  3230 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

This field is the URL of the users avatar. I was able to bypass the crash by going in as root into the /data/data/com.google.android.gms/databases directroy, and editing the pluscontacts.db by running the following commands:
sqlite3 pluscontacts.db
update owners set avatar='';
.quit

The URL in the avatar field directly matches the string in the backtrace.

My best theory is that maybe GVoice wants a fully formed URL (https://....) instead of just the path, but I haven't researched it any further. Nulling the avatar field in the database lets me get past the issue. If I reinstall GApps any time soon, I will see what data it stores for the avatar.

**Comment by robsee** [comment]
This line has what looks like a path. Exact path removed since it is user specific: 08-29 00:17:04.562 3230 3230 E AndroidRuntime: java.lang.RuntimeException: ghv: jsu: (bunch of characters)/photo.jpg

**Comment by ale5000-git** [comment]
Please verify that you have microG GmsCore 0.2.5.12879 installed.

**Comment by voidstarstar** [comment]
I can confirm that changing the URL fixes this issue!  I set it to the properly formed URL for the photo instead of a blank entry.

I also had to fix the URL in `/data/data/com.google.android.apps.googlevoice/shared_prefs/accounts.xml`, but this might only be an issue if Google Voice is installed prior to modifying the database.

Google Voice no longer crashes after making the above changes, but a default avatar seems to be used.  I see the default avatar in Hangouts as well.  I doubt anyone will care much this as long as the basic functionality is working, but it's worth a mention that something still might not be right.  It may also just be a cache issue that will resolve itself.
