### ISSUE TITLE
Deezer: crash on app launch

### ISSUE THREAD

**Issue by gumida** [microg/android_packages_apps_GmsCore#636]
Hello,
I'm new to the microG-world so I hope I'm doing this right :smiley: 

- Android 8.1
- microgG 0.2.6.13280
- Deezer was being freshly installed from the appstore
- First launch, instantly crashed/stopped working. It's the same everytime the app gets started.

Logcat:
```
<<< log_count = 15 >>>
[10-09 12:00:15.261 1032:5775 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=deezer.android.app/com.deezer.android.ui.activity.LauncherActivity (has extras)} from uid 10197

[10-09 12:00:15.498 1032:5775 I/ActivityManager]
Start proc 14405:deezer.android.app/u0a190 for activity deezer.android.app/com.deezer.android.ui.activity.LauncherActivity

[10-09 12:00:16.233 14405:14421 I/FA]
To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app deezer.android.app

[10-09 12:00:16.453 14405:14405 I/chatty]
uid=10190(deezer.android.app) identical 9 lines

[10-09 12:00:16.862 1032:15879 I/ActivityManager]
START u0 {flg=0x10008000 cmp=deezer.android.app/com.deezer.android.ui.activity.LoginPageActivity (has extras)} from uid 10190

[10-09 12:00:16.913 2118:4675 D/GmsMeasureBrokerSvc]
bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12211000, packageName='deezer.android.app', extras=Bundle[{}]}

[10-09 12:00:17.054 461:461 D/SurfaceFlinger]
duplicate layer name: changing Splash Screen deezer.android.app to Splash Screen deezer.android.app#1

[10-09 12:00:17.520 1032:6104 W/ActivityManager]
Duplicate finish request for ActivityRecord{cf72094 u0 deezer.android.app/com.deezer.android.ui.activity.LauncherActivity t561 f}

[10-09 12:00:18.332 14405:14405 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: deezer.android.app, PID: 14405
java.lang.RuntimeException: Unable to create service com.google.android.gms.cast.framework.ReconnectionService: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.cast.framework.zzr.a()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.cast.framework.zzr.a()' on a null object reference
	at com.google.android.gms.cast.framework.ReconnectionService.onCreate(Unknown Source:1000)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
	... 8 more

[10-09 12:00:18.485 1032:1165 W/ActivityManager]
  Force finishing activity deezer.android.app/com.deezer.android.ui.activity.LoginPageActivity

[10-09 12:00:18.541 1032:1066 I/ActivityManager]
Showing crash dialog for package deezer.android.app u0

[10-09 12:00:19.012 1032:1065 W/ActivityManager]
Activity pause timeout for ActivityRecord{798dbbf u0 deezer.android.app/com.deezer.android.ui.activity.LoginPageActivity t561 f}

[10-09 12:00:20.377 1032:1165 W/ActivityManager]
  Force finishing activity deezer.android.app/com.deezer.android.ui.activity.LoginPageActivity

[10-09 12:00:20.490 1032:1165 W/ActivityManager]
  Force finishing activity deezer.android.app/com.deezer.android.ui.activity.LauncherActivity

[10-09 12:00:20.592 1032:1165 I/ActivityManager]
Killing 14405:deezer.android.app/u0a190 (adj 0): crash
```

**Comment by Nanolx** [comment]
This and #634 are actually the same. Both apps seems to crash when they try to invoke the Cast framework. @armills is currently working on improving microG's cast bindings, as seen in #555
