### ISSUE TITLE
Duolingo crashes on startup

### ISSUE THREAD

**Issue by jpellegrini** [microg/android_packages_apps_GmsCore#651]
Hello,

Duolingo (com.duolingo) crashes at startup. I am using OmniROM 8.1.0, with MicroG 0.2.6.14366 (installed as Magisk module).

Below is a transcript of the log.

J.

```
11-02 12:07:20.213  2238 15791 I ActivityManager: Start proc 29336:com.duolingo/u0a264 for activity com.duolingo/.app.LoginActivity
11-02 12:07:20.216  1902  1936 I Magisk  : proc_monitor: com.duolingo
11-02 12:07:20.371  2238 15348 W ActivityManager: Slow operation: 98ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
11-02 12:07:20.565 29336 29336 I MultiDex: VM with version 2.1.0 has multidex support
11-02 12:07:20.565 29336 29336 I MultiDex: Installing application
11-02 12:07:20.565 29336 29336 I MultiDex: VM has multidex support, MultiDex support library is disabled.
11-02 12:07:20.589 29336 29336 D AndroidRuntime: Shutting down VM
11-02 12:07:20.593 29336 29336 E AndroidRuntime: FATAL EXCEPTION: main
11-02 12:07:20.593 29336 29336 E AndroidRuntime: Process: com.duolingo, PID: 29336
11-02 12:07:20.593 29336 29336 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.crashlytics.android.CrashlyticsInitProvider: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080153
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6247)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5810)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5727)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6499)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080153
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:261)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.content.res.Resources.getResourcePackageName(Resources.java:1949)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at io.fabric.sdk.android.services.common.CommonUtils.n(CommonUtils.java:767)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at io.fabric.sdk.android.services.common.CommonUtils.a(CommonUtils.java:517)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at io.fabric.sdk.android.services.common.CommonUtils.a(CommonUtils.java:498)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at io.fabric.sdk.android.services.common.m.a(FirebaseInfo.java:52)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at com.crashlytics.android.CrashlyticsInitProvider.onCreate(CrashlyticsInitProvider.java:1073)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6244)
11-02 12:07:20.593 29336 29336 E AndroidRuntime: 	... 10 more
11-02 12:07:20.598  2238  3607 W ActivityManager:   Force finishing activity com.duolingo/.app.LoginActivity
11-02 12:07:20.609  2238  2293 I ActivityManager: Showing crash dialog for package com.duolingo u0

```

**Comment by jpellegrini** [comment]
Reinstalled MicroG, and then a new version of Duolingo was available, and I also upgraded it. Now it works.

**Comment by Ember2528** [comment]
Probably best to close this issue then
