### ISSUE TITLE
App severeweather not working when gmscore microg is installed (appcrash)

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#66]
hi,

the App 
https://play.google.com/store/apps/details?id=de.mdiener.unwetter.gm
erließ on Google play services and gcm. it opens when Sig fake is missing and shows a button with link to original gms in play store. with sig fake properly Installed, microg gcm working with Google account, the app immediately crashes. I am then taken to a message Google play store crashed subsequently  and no crash details are shown. can you help me?
platform is a5.1.1 on cm12.1 build 29-12-2015. newest sww13 build installed. previous also did not work.

**Comment by bonanza123** [comment]
catlog please.

**Comment by Catfriend1** [comment]
Is this right? Got this from android terminal emulator googling "how to catlog".


[ 12-31 08:16:20.148 23072:23072 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: de.mdiener.unwetter.gm, PID: 23072
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.mdiener.unwetter.gm/de.mdiener.unwetter.gm.UnwetterActivity}: java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by: java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
	at com.google.android.gms.common.internal.zzu.zzb(Unknown Source)
	at com.google.android.gms.maps.model.LatLngBounds.<init>(Unknown Source)
	at com.google.android.gms.maps.model.zzd.zzeO(Unknown Source)
	at com.google.android.gms.maps.model.zzd.createFromParcel(Unknown Source)
	at com.google.android.gms.common.internal.safeparcel.zza.zza(Unknown Source)
	at com.google.android.gms.maps.model.zzo.zzeZ(Unknown Source)
	at com.google.android.gms.maps.internal.IProjectionDelegate$zza$zza.getVisibleRegion(Unknown Source)
	at com.google.android.gms.maps.Projection.getVisibleRegion(Unknown Source)
	at de.mdiener.unwetter.gm.UnwetterActivity.calculateCurrentBounds(Unknown Source)
	at de.mdiener.unwetter.gm.UnwetterActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more


[ 12-31 08:16:22.841 18952:18952 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.vending, PID: 18952
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.vending/com.google.android.finsky.activities.AppCrashProxy}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
	at android.app.Activity.startActivityForResult(Activity.java:3745)
	at android.app.Activity.startActivityForResult(Activity.java:3706)
	at android.app.Activity.startActivity(Activity.java:4016)
	at android.app.Activity.startActivity(Activity.java:3984)
	at com.google.android.finsky.activities.AppCrashProxy.onCreate(AppCrashProxy.java:91)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more


[ 12-31 08:16:42.624 23214:23214 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: de.mdiener.unwetter.gm, PID: 23214
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.mdiener.unwetter.gm/de.mdiener.unwetter.gm.UnwetterActivity}: java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by: java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
	at com.google.android.gms.common.internal.zzu.zzb(Unknown Source)
	at com.google.android.gms.maps.model.LatLngBounds.<init>(Unknown Source)
	at com.google.android.gms.maps.model.zzd.zzeO(Unknown Source)
	at com.google.android.gms.maps.model.zzd.createFromParcel(Unknown Source)
	at com.google.android.gms.common.internal.safeparcel.zza.zza(Unknown Source)
	at com.google.android.gms.maps.model.zzo.zzeZ(Unknown Source)
	at com.google.android.gms.maps.internal.IProjectionDelegate$zza$zza.getVisibleRegion(Unknown Source)
	at com.google.android.gms.maps.Projection.getVisibleRegion(Unknown Source)
	at de.mdiener.unwetter.gm.UnwetterActivity.calculateCurrentBounds(Unknown Source)
	at de.mdiener.unwetter.gm.UnwetterActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more


[ 12-31 08:16:44.856 23115:23115 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.vending, PID: 23115
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.vending/com.google.android.finsky.activities.AppCrashProxy}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
	at android.app.Activity.startActivityForResult(Activity.java:3745)
	at android.app.Activity.startActivityForResult(Activity.java:3706)
	at android.app.Activity.startActivity(Activity.java:4016)
	at android.app.Activity.startActivity(Activity.java:3984)
	at com.google.android.finsky.activities.AppCrashProxy.onCreate(AppCrashProxy.java:91)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more


[ 12-31 08:16:49.107 23268:23268 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: de.mdiener.unwetter.gm, PID: 23268
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.mdiener.unwetter.gm/de.mdiener.unwetter.gm.UnwetterActivity}: java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by: java.lang.IllegalArgumentException: southern latitude exceeds northern latitude (NaN > NaN)
	at com.google.android.gms.common.internal.zzu.zzb(Unknown Source)
	at com.google.android.gms.maps.model.LatLngBounds.<init>(Unknown Source)
	at com.google.android.gms.maps.model.zzd.zzeO(Unknown Source)
	at com.google.android.gms.maps.model.zzd.createFromParcel(Unknown Source)
	at com.google.android.gms.common.internal.safeparcel.zza.zza(Unknown Source)
	at com.google.android.gms.maps.model.zzo.zzeZ(Unknown Source)
	at com.google.android.gms.maps.internal.IProjectionDelegate$zza$zza.getVisibleRegion(Unknown Source)
	at com.google.android.gms.maps.Projection.getVisibleRegion(Unknown Source)
	at de.mdiener.unwetter.gm.UnwetterActivity.calculateCurrentBounds(Unknown Source)
	at de.mdiener.unwetter.gm.UnwetterActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more


[ 12-31 08:16:52.227 23301:23301 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.vending, PID: 23301
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.vending/com.google.android.finsky.activities.AppCrashProxy}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.APP_ERROR flg=0x10000000 pkg=com.google.android.gms (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
	at android.app.Activity.startActivityForResult(Activity.java:3745)
	at android.app.Activity.startActivityForResult(Activity.java:3706)
	at android.app.Activity.startActivity(Activity.java:4016)
	at android.app.Activity.startActivity(Activity.java:3984)
	at com.google.android.finsky.activities.AppCrashProxy.onCreate(AppCrashProxy.java:91)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more

**Comment by bonanza123** [comment]
Better use something like catlog (the app from fdroid) and upload the log as Gist at github. This is usually easier to read

**Comment by Catfriend1** [comment]
Fixed, newest sww build Form today works fine.

**Comment by ghost** [comment]
please delete issue
