### ISSUE TITLE
Chrome does not register to gcm anymore 

### ISSUE THREAD

**Issue by GRBurst** [microg/android_packages_apps_GmsCore#676]
Hey,

I am facing the issue that Chrome does not register to gcm for some time now, although it did before.

It seems to be related to an issue with the sender id.

Here is the related logcat output:

```
**GmsGcmRegisterSvc** 
onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
```

```
**GmsHttpFormClient** 
-- Request --
X-GOOG.USER_AID=3557875368816913745&device=3557875368816913745&app=com.android.chrome&appid=d-fambNGVew&cert=38918a453d07199354f8b19af05ec6562ced5788&app_ver=353811002&app_ver_name=70.0.3538.110&gmsv=13280000&scope=*&osv=27&sender=BDd3_hVL9fZi9Ybo2UUzA284WG5FZR30_95YeZJsiApwXKpNcF1rRPF3foIiBHXRdJI2Qhumhf6_LFTeZaNndIo&subtype=BDd3_hVL9fZi9Ybo2UUzA284WG5FZR30_95YeZJsiApwXKpNcF1rRPF3foIiBHXRdJI2Qhumhf6_LFTeZaNndIo
```

```
**GmsGcmRegisterMgr** 
java.io.IOException: Error=INVALID_SENDER
	at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:90)
	at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:187)
	at java.lang.Thread.run(Thread.java:764)
```

I get this result in all apps that try to register for web push notification, e.g.

https://gauntface.github.io/simple-push-demo/

This however works with Firefox, but sadly ff still misses several other features of web push... 

Kind regards

**Comment by ale5000-git** [comment]
Could you please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry?

**Comment by GRBurst** [comment]
> Could you please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry?

Happy to hear from you! I will try it asap. Does it differ from the official `v0.2.8.17785` release?

**Comment by patrickdrd** [comment]
I've tested the page and it works on me with the build from here:
https://microg.org/dl/GmsCore-v0.2.8.17785-2-8a0010a.apk

however there are still issues with chrome pushes:
https://github.com/microg/android_packages_apps_GmsCore/issues/668

subscribing to this page:
https://tests.peter.sh/push-message-generator/
still doesn't work

**Comment by ale5000-git** [comment]
@GRBurst: The build 0.2.8.17785-**4** (note the 4) include all changes after the latest release.

@patrickdrd: You have an older build.

**Comment by patrickdrd** [comment]
are these builds uploaded somewhere? 
I wasn't informed that there was an update, 
as I understand these builds should be nightlies,
I usually update through the stable channel,
but I made an exception because I've had this crash with chrome after 0.2.8 was released

**Comment by ale5000-git** [comment]
No, they aren't anywhere, they are only linked on issues here by mar-v-in when needed.
But I keep a copy in my repo: https://github.com/micro5k/microg-unofficial-installer/tree/master/zip-content/files/variants/priv-app

Although it is a nightlies currently it is more stable than the last release.

**Comment by GRBurst** [comment]
I still cannot register for push with Chrome or chromium while it is working with Firefox. I will send you a log output later
