### ISSUE TITLE
Background start not allowed: service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms

### ISSUE THREAD

**Issue by daviddean99** [microg/android_packages_apps_GmsCore#677]
Android 8.1
MicroG: 0.2.6.13280-dirty

I've successfully installed MicroG in Android 8.1 and most apps are working perfectly.

But several apps are crashing on startup with the error below:

```
AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) }: app is in background uid UidRecord{b092f7c u0a80 TRNB idle change:idle|uncached procs:1 seq(0,0,0)}
AndroidRuntime:        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
AndroidRuntime:        at android.app.ContextImpl.startService(ContextImpl.java:1477)
AndroidRuntime:        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
AndroidRuntime:        at com.google.firebase.iid.h.b(Unknown Source:5000)
AndroidRuntime:        at com.google.firebase.iid.h.a(Unknown Source:0)
AndroidRuntime:        at com.google.firebase.iid.f.b(Unknown Source:4000)
AndroidRuntime:        at com.google.firebase.iid.FirebaseInstanceId.e(Unknown Source:2000)
AndroidRuntime:        at com.google.firebase.iid.FirebaseInstanceIdService.d(Unknown Source:21)
AndroidRuntime:        at com.google.firebase.iid.FirebaseInstanceIdService.b(Unknown Source:1000)
AndroidRuntime:        at com.google.firebase.iid.d.run(Unknown Source:4)
AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
```

I found that by uninstalling and reinstalling the app the problem goes away. But when I reboot the device the same error starts happening again until I uninstall/reinstall the app.

Any suggestions on how to fix this issue permanently?

Thanks.

**Comment by HanteIsHante** [comment]
I also encountered this problem.  [StackOverFlow](https://stackoverflow.com/questions/53954114/fatal-exception-java-lang-securityexception-without-permission-com-google-andro).
But at the same time I don't know how to fix it.
