### ISSUE TITLE
Lyft crashes when you hit the "get started" button upon fresh install of app

### ISSUE THREAD

**Issue by Riamse** [microg/android_packages_apps_GmsCore#689]
```
01-16 22:11:59.599  6923  6923 I Bugsnag : Saved unsent payload to disk (/data/user/0/me.lyft.android/cache/bugsnag-errors/[removed].json) 
01-16 22:11:59.600  6923  6969 I Bugsnag : Sending 1 saved error(s) to Bugsnag
01-16 22:11:59.611  6923  6923 E AndroidRuntime: FATAL EXCEPTION: main
01-16 22:11:59.611  6923  6923 E AndroidRuntime: Process: me.lyft.android, PID: 6923
01-16 22:11:59.611  6923  6923 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle null
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResultInner(Activity.java:4845)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResult(Activity.java:4812)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(SourceFile:796)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResult(Activity.java:4779)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(SourceFile:781)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.googleaccount.GoogleAccountService.a(SourceFile:10088)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.landing.ui.AbstractLoginViewController.onAttach(SourceFile:3235)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.landing.ui.passenger.PassengerLoginViewController.onAttach(SourceFile:60)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.scoop.ViewController.attach(SourceFile:23)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.scoop.ViewControllerBinding.onViewAttachedToWindow(SourceFile:20)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:18358)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4865)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4805)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4778)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.scoop.ScreenTransition$1.a(SourceFile:16)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.scoop.rendering.controller.LayoutViewControllerRenderer$LayoutViewControllerBindings.a(SourceFile:99)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.scoop.ScreenLayoutContainer.d(SourceFile:89)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.android.scoop.ScreenLayoutContainer.a(SourceFile:60)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at me.lyft.android.ui.MainActivity$2.accept(SourceFile:532)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at me.lyft.android.ui.MainActivity$2.accept(SourceFile:499)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(SourceFile:63)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(SourceFile:2201)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(SourceFile:119)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: Caused by: com.lyft.rxdebug.RxStackTraceCaptureException: Bound observable threw an error. Call-site stacktrace captured.
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.rxdebug.RxDebugErrors.a(SourceFile:8)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.rxdebug.init.-$$Lambda$zIzHITFhQwQgHYc-kGd4Qmy1-XE.apply(Unknown Source:2)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.rx.RxErrors.a(SourceFile:17)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at com.lyft.rx.RxErrors.a(SourceFile:12)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at me.lyft.android.rx.RxBinder.bindStream(SourceFile:96)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at me.lyft.android.rx.RxUIBinder.bindStream(SourceFile:66)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at me.lyft.android.ui.MainActivity.onCreate(SourceFile:245)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	... 5 more
01-16 22:11:59.611  6923  6923 E AndroidRuntime: Caused by: com.lyft.common.StacktraceCallsiteException
01-16 22:11:59.611  6923  6923 E AndroidRuntime: 	at me.lyft.android.ui.MainActivity.onCreate(SourceFile:245)
01-16 22:11:59.613  1181  2955 W ActivityManager:   Force finishing activity me.lyft.android/.ui.MainActivity
01-16 22:11:59.616  1181  1196 I ActivityManager: Showing crash dialog for package me.lyft.android u0
```

I thought it might be because my phone isn't signed in to a Google account, so I tried to sign in, but it still crashes.

**Comment by Riamse** [comment]
This is what's supposed to happen when you press "get started".
![lyft-expected-output](https://user-images.githubusercontent.com/2367611/51361476-c4b96380-1a84-11e9-988e-2ae3065d0e94.jpg)
