### ISSUE TITLE
Unable to connect to bike app

### ISSUE THREAD

**Issue by StephanDufour** [microg/android_packages_apps_GmsCore#745]
Hi,

the app starts fine, it can geolocate me but when I try to connect with my account I just got a generic message on the app saying that something went wrong. Yet no crash.

Here are the logs:

`4-04 13:29:14.104  6648  6709 D OkHttp  : <-- 200 OK https://api.cyclocity.fr/contracts/lyon/accounts/removedemail (593ms)
04-04 13:29:14.104  6648  6709 D OkHttp  : Date: Thu, 04 Apr 2019 11:29:14 GMT
04-04 13:29:14.104  6648  6709 D OkHttp  : Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
04-04 13:29:14.104  6648  6709 D OkHttp  : Content-Type: application/vnd.account.v1+json
04-04 13:29:14.104  6648  6709 D OkHttp  : Content-Length: 668
04-04 13:29:14.104  6648  6709 D OkHttp  : Set-Cookie: dtCookie==3=srv=1=sn=removed=perc=100000=ol=0=mul=1; Path=/; Domain=.cyclocity.fr
04-04 13:29:14.104  6648  6709 D OkHttp  : Keep-Alive: timeout=15, max=50
04-04 13:29:14.104  6648  6709 D OkHttp  : Connection: Keep-Alive
04-04 13:29:14.108  6648  6709 D OkHttp  : {personalinforemoved}
04-04 13:29:14.108  6648  6709 D OkHttp  : <-- END HTTP (668-byte body)
04-04 13:29:14.115  2109  2151 I Xposed  : FakeGApps: returning fake signature to com.jcdecaux.vls.lyon
04-04 13:29:14.117  2109  2991 I Xposed  : FakeGApps: returning fake signature to com.jcdecaux.vls.lyon
04-04 13:29:14.125  2109  3719 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.config.START pkg=com.google.android.gms } U=0: not found
04-04 13:29:14.126  2109  6373 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@92cea8b
04-04 13:29:14.126  6648  6704 E GmsClient: unable to connect to service: com.google.android.gms.config.START on com.google.android.gms
04-04 13:29:14.137  6648  6648 W FirebaseRemoteConfig: IPC failure: 17:API: Config.API is not available on this device.
04-04 13:29:14.138  6648  6648 W FirebaseRemoteConfig: IPC failure: 17:API: Config.API is not available on this device.
04-04 13:29:14.140  4355  4374 D GmsClearcutLogSvcImpl: log: LogEventParcelable[1, PlayLoggerContext[1, package=com.jcdecaux.vls.lyon, packageVersionCode=10500, logSource=-1, uploadAccount=null, loggingId=-1, logAndroidId=false, logSourceName=FIREPERF, isAnonymous=true, qosTier=0], LogEventBytes: CIPX8MCeLTKOAgppCicxOjUwOTg5OTQwNjA1NTphbmRyb2lkOmVkMjMxODU3ZjQ4NzYyYjUSC2Q5aFMwRnB0NWZFGi8KFWNvbS5qY2RlY2F1eC52bHMubHlvbhIPMS4wLjAuMjI1MDUzMjU2GgUxLjUuMCgBGqABCkRodHRwczovL2FwaS5jeWNsb2NpdHkuZnIvY29udHJhY3RzL2x5b24vYWNjb3VudHMvc2R1Zm91cjc1QGdtYWlsLmNvbRABIJwFKMgBMh9hcHBsaWNhdGlvbi92bmQuYWNjb3VudC52MStqc29uOJCegfCqtuECUOSXJmoiCiBhMDAwYTUxMTI5NjM0MjRmOTY1ZjZhNTI5ZWRiYzZjMXjAcIgBhIAI, AddPhenotypeExperimentTokens: true]
04-04 13:29:14.177  6648  6648 W System.err: kotlin.TypeCastException: null cannot be cast to non-null type android.accounts.Account
04-04 13:29:14.178  6648  6648 W System.err:    at com.jcdecaux.vls.app.SignInActivity.t(SignInActivity.kt:267)
04-04 13:29:14.178  6648  6648 W System.err:    at com.jcdecaux.vls.app.SignInActivity.b(SignInActivity.kt:40)
04-04 13:29:14.178  6648  6648 W System.err:    at com.jcdecaux.vls.app.SignInActivity$q.a(SignInActivity.kt:199)
04-04 13:29:14.178  6648  6648 W System.err:    at com.jcdecaux.vls.app.SignInActivity$q.b(SignInActivity.kt:40)
04-04 13:29:14.178  6648  6648 W System.err:    at io.reactivex.d.d.k.b_(LambdaObserver.java:63)
04-04 13:29:14.178  6648  6648 W System.err:    at io.reactivex.d.e.e.m$a.b_(ObservableDoFinally.java:80)
04-04 13:29:14.178  6648  6648 W System.err:    at io.reactivex.d.d.h.b_(DisposableLambdaObserver.java:58)
04-04 13:29:14.178  6648  6648 W System.err:    at io.reactivex.d.e.e.am$a.g(ObservableObserveOn.java:201)
04-04 13:29:14.178  6648  6648 W System.err:    at io.reactivex.d.e.e.am$a.run(ObservableObserveOn.java:255)
04-04 13:29:14.178  6648  6648 W System.err:    at io.reactivex.a.b.b$b.run(HandlerScheduler.java:119)
04-04 13:29:14.178  6648  6648 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
04-04 13:29:14.178  6648  6648 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
04-04 13:29:14.178  6648  6648 W System.err:    at android.os.Looper.loop(Looper.java:154)
04-04 13:29:14.178  6648  6648 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6128)
04-04 13:29:14.178  6648  6648 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-04 13:29:14.178  6648  6648 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-04 13:29:14.178  6648  6648 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-04 13:29:14.178  6648  6648 W System.err:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)`

**Comment by XVicarious** [comment]
I can confirm the same error is thrown for DoorDash when you go to your bag/basket/cart/whatever, and it just loads infinitely.

Maybe something has to be done like was done for the AnalyticsService.
