### ISSUE TITLE
Feature Request: Google Voice voip call compatibility

### ISSUE THREAD

**Issue by tb-303** [microg/android_packages_apps_GmsCore#776]
It would be great to have this functionality via gmscore! Here is a logcat *:E when attempting to call using microg:

`E/dalvikvm( 8587): Could not find class 'android.view.accessibility.AccessibilityNodeInfo$AccessibilityAction', referenced from method com.google.android.apps.voice.conversationlist.CallItemView.onInitializeAccessibilityNodeInfo
E/native  ( 8587): birdsong_native.cc:71 Voice call manager not found for account network_conditions_dummy_account_key
E/LegacyVoipPlaceCallHand( 8587): Place VoIP call failed
E/LegacyVoipPlaceCallHand( 8587): android.accounts.NetworkErrorException: Can't get auth token.
E/LegacyVoipPlaceCallHand( 8587):       at nar.call(PG:23)
E/LegacyVoipPlaceCallHand( 8587):       at nme.call(PG:3)
E/LegacyVoipPlaceCallHand( 8587):       at oei.b(PG:4)
E/LegacyVoipPlaceCallHand( 8587):       at odi.run(PG:5)
E/LegacyVoipPlaceCallHand( 8587):       at oeg.run(PG:9)
E/LegacyVoipPlaceCallHand( 8587):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/LegacyVoipPlaceCallHand( 8587):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/LegacyVoipPlaceCallHand( 8587):       at mfi.run(PG:5)
E/LegacyVoipPlaceCallHand( 8587):       at java.lang.Thread.run(Thread.java:841)
E/LegacyVoipPlaceCallHand( 8587): Caused by: java.io.IOException: Service unavailable.
E/LegacyVoipPlaceCallHand( 8587):       at hyd.a(PG:28)
E/LegacyVoipPlaceCallHand( 8587):       at hyn.a(PG:4)
E/LegacyVoipPlaceCallHand( 8587):       at hyd.a(PG:37)
E/LegacyVoipPlaceCallHand( 8587):       at jhh.a(PG:21)
E/LegacyVoipPlaceCallHand( 8587):       at nar.call(PG:7)
E/LegacyVoipPlaceCallHand( 8587):       ... 8 more
E/LegacyVoipPlaceCallHand( 8587): Place VoIP call failed
E/LegacyVoipPlaceCallHand( 8587): android.accounts.NetworkErrorException: Can't get auth token.
E/LegacyVoipPlaceCallHand( 8587):       at nar.call(PG:23)
E/LegacyVoipPlaceCallHand( 8587):       at nme.call(PG:3)
E/LegacyVoipPlaceCallHand( 8587):       at oei.b(PG:4)
E/LegacyVoipPlaceCallHand( 8587):       at odi.run(PG:5)
E/LegacyVoipPlaceCallHand( 8587):       at oeg.run(PG:9)
E/LegacyVoipPlaceCallHand( 8587):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/LegacyVoipPlaceCallHand( 8587):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/LegacyVoipPlaceCallHand( 8587):       at mfi.run(PG:5)
E/LegacyVoipPlaceCallHand( 8587):       at java.lang.Thread.run(Thread.java:841)
E/LegacyVoipPlaceCallHand( 8587): Caused by: java.io.IOException: Service unavailable.
E/LegacyVoipPlaceCallHand( 8587):       at hyd.a(PG:28)
E/LegacyVoipPlaceCallHand( 8587):       at hyn.a(PG:4)
E/LegacyVoipPlaceCallHand( 8587):       at hyd.a(PG:37)
E/LegacyVoipPlaceCallHand( 8587):       at jhh.a(PG:21)
E/LegacyVoipPlaceCallHand( 8587):       at nar.call(PG:7)
E/LegacyVoipPlaceCallHand( 8587):       ... 8 more
E/Term    ( 9820): onCreate
E/libpjsip( 2544): 11:11:31.062 tlsc0x6315cd2c  TLS connect() error: Connection refused [code=120111]
`

**Comment by EwonRael** [comment]
Has there been any update or progress on this?
