### ISSUE TITLE
SafetyNetHelperSAMPLE: ApiException[14]

### ISSUE THREAD

**Issue by mwberry** [microg/android_packages_apps_GmsCore#780]
I've installed LineageOS 14.1 w/ MicroG from the MicroG download site [1] and installed that on my Verizon LG V20. I'd like to use some applications that required SafetyNet, so I learned that I'd have to install DroidGuardHelper (via F-Droid), make it a system app (via the Yalp store & SuperSU), and enable SafetyNet in the MicroG settings. I've done those things and currently, when I run SafetyNet Test it fails. 

DroidGuardHelper Version: 0.1.0-10-gf64bf69

I see the following in `logcat`:

```
05-13 20:47:22.228  4089  4089 D c       : apkCertificateDigests:[FJZqNb3u3c9XbWF4NmmpNkUzP/q2q9IW+5LyS/P86/s=]
05-13 20:47:22.251  4089  4089 D c       : apkDigest:rNsOECUMDZI28aZ8dM+d80CL94qZzk25t8u2+yGWW7g=
05-13 20:47:22.251  4089  4089 V c       : running SafetyNet.API Test
05-13 20:47:22.299  1856  3093 I ActivityManager: Start proc 4539:com.google.android.gms.unstable/u0a93 for service org.microg.gms.droidguard/.RemoteDroidGuardService
05-13 20:47:22.315  3232  3247 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@6293e8a, 16
05-13 20:47:22.356  4539  4539 I art     : Starting a blocking GC AddRemoveAppImageSpace
05-13 20:47:22.356  4539  4539 W System  : ClassLoader referenced unknown path: /system/priv-app/org.microg.gms.droidguard/lib/arm64
05-13 20:47:22.358  3232  3244 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@959dcfb, 16
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: java.lang.NoSuchFieldException: BUILD
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 	at java.lang.Class.getField(Class.java:1549)
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.DroidguardHelper.createSystemInfoPair(DroidguardHelper.java:169)
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.DroidguardHelper.getSystemInfo(DroidguardHelper.java:117)
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:64)
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
05-13 20:47:22.397  4539  4555 W GmsDroidguardHelper: 	at java.lang.Thread.run(Thread.java:761)
05-13 20:47:22.402  4539  4555 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-13 20:47:22.413  4539  4555 D GmsDroidguardHelper: -- Request --
05-13 20:47:22.413  4539  4555 D GmsDroidguardHelper: DGRequest{usage=DGUsage{type=attest, packageName=com.google.android.gms}, info=[KeyValuePair{key=BUILD, val=unknown}, KeyValuePair{key=BOARD, val=MSM8996}, KeyValuePair{key=BOOTLOADER, val=unknown}, KeyValuePair{key=BRAND, val=lge}, KeyValuePair{key=CPU_ABI, val=arm64-v8a}, KeyValuePair{key=CPU_ABI2, val=}, KeyValuePair{key=DEVICE, val=vs995}, KeyValuePair{key=DISPLAY, val=lineage_vs995-userdebug 7.1.2 NJH47F 20190303 dev-keys}, KeyValuePair{key=FINGERPRINT, val=lge/elsa_vzw/elsa:7.0/NRD90M/1628409164d39:user/release-keys}, KeyValuePair{key=HARDWARE, val=qcom}, KeyValuePair{key=HOST, val=ee676dcbf5a0}, KeyValuePair{key=ID, val=NJH47F}, KeyValuePair{key=MANUFACTURER, val=LGE}, KeyValuePair{key=MODEL, val=LG-VS995}, KeyValuePair{key=PRODUCT, val=elsa_vzw_us}, KeyValuePair{key=RADIO, val=unknown}, KeyValuePair{key=SERIAL, val=LGVS995xxxxxxxx}, KeyValuePair{key=TAGS, val=dev-keys}, KeyValuePair{key=TIME, val=1551643193000}, KeyValuePair{key=TYPE, val=user}, KeyValuePair{key=USER, val=root}, KeyValuePair{key=CODENAME, val=REL}, KeyValuePair{key=INCREMENTAL, val=765d6d7149}, KeyValuePair{key=RELEASE, val=7.1.2}, KeyValuePair{key=SDK, val=25}, KeyValuePair{key=SDK_INT, val=25}], versionNamePrefix=9.6.83 (430-, isGoogleCn=false, enableInlineVm=true, cached=[ByteString[size=20 md5=03d24cde019d581711b7d6a8e2e50d85]], currentVersion=3, arch=aarch64}
05-13 20:47:22.589  4539  4555 D GmsDroidguardHelper: Using cached file from /data/user/0/org.microg.gms.droidguard/app_dg_cache/a5c1de40796a02c71a5309b7ef7fc66244f71fa3/the.apk
05-13 20:47:22.604  4539  4555 E AndroidRuntime: FATAL EXCEPTION: Thread-2
05-13 20:47:22.604  4539  4555 E AndroidRuntime: Process: com.google.android.gms.unstable, PID: 4539
05-13 20:47:22.604  4539  4555 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/org.microg.gms.droidguard/org.microg.gms.droidguard.apk"],nativeLibraryDirectories=[/system/priv-app/org.microg.gms.droidguard/lib/arm64, /system/fake-libs64, /system/priv-app/org.microg.gms.droidguard/org.microg.gms.droidguard.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]] couldn't find "libarthook_native.so"
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at de.larma.arthook.Native.<clinit>(Native.java:22)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at de.larma.arthook.Native.is64Bit(Native.java:45)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at de.larma.arthook.ArtHook.<clinit>(ArtHook.java:46)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at de.larma.arthook.ArtHook.hook(ArtHook.java:75)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at org.microg.gms.droidguard.SysHook.activate(SysHook.java:52)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:91)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
05-13 20:47:22.604  4539  4555 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)

```

From some reading, I understand that DroidGuardHelper is designed to run Google's proprietary DroidGuard binary in a sandbox. Could it be the case that the process of converting DroidGuardHelper from a user application to a system application failed to pull all required libraries into the sandbox?

```
0|vs995:/ $ find / -name 'libarthook_native.so' 2>/dev/null                                                                                                                                                                                                 
1|vs995:/ $ 
```

Or is it the case that Google has added a new dependency and DroidGuardHelper now needs to change to bundle it?

[1] lineage-14.1-20190303-microG-vs995.zip

**Comment by mwberry** [comment]
```
vs995:/ $ unzip -l /system/priv-app/org.microg.gms.droidguard/org.microg.gms.droidguard.apk                                                                                                                                                                   
Archive:  /system/priv-app/org.microg.gms.droidguard/org.microg.gms.droidguard.apk
  Length      Date    Time    Name
---------  ---------- -----   ----
     2072  1980-00-00 00:00   AndroidManifest.xml
     1163  1980-00-00 00:00   META-INF/CERT.RSA
     1303  1980-00-00 00:00   META-INF/CERT.SF
     1241  1980-00-00 00:00   META-INF/MANIFEST.MF
   303176  1980-00-00 00:00   classes.dex
     9688  1980-00-00 00:00   lib/arm64-v8a/libarthook_native.so
    13520  1980-00-00 00:00   lib/armeabi-v7a/libarthook_native.so
    17608  1980-00-00 00:00   lib/armeabi/libarthook_native.so
     1920  1980-00-00 00:00   res/mipmap-hdpi-v4/ic_core_service_app.png
     1427  1980-00-00 00:00   res/mipmap-mdpi-v4/ic_core_service_app.png
     2535  1980-00-00 00:00   res/mipmap-xhdpi-v4/ic_core_service_app.png
     3696  1980-00-00 00:00   res/mipmap-xxhdpi-v4/ic_core_service_app.png
     5258  1980-00-00 00:00   res/mipmap-xxxhdpi-v4/ic_core_service_app.png
     1392  1980-00-00 00:00   resources.arsc
---------                     -------
   365999                     14 files
```

**Comment by mwberry** [comment]
```
vs995:/ $ cat /proc/cpuinfo                                                                                                                                                                                                                                   
Processor	: AArch64 Processor rev 2 (aarch64)
processor	: 0
BogoMIPS	: 38.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x211
CPU revision	: 2

processor	: 1
BogoMIPS	: 38.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x211
CPU revision	: 2

processor	: 2
BogoMIPS	: 38.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x205
CPU revision	: 2

processor	: 3
BogoMIPS	: 38.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x205
CPU revision	: 2

Revision	: 000c
Hardware	: Qualcomm Technologies, Inc MSM8996
```

**Comment by mwberry** [comment]
Sure seems like `/system/priv-app/org.microg.gms.droidguard/org.microg.gms.droidguard.apk!/lib/arm64-v8a` has a copy of `libarthook_native.so` in it, so I don't know what the issue is.

**Comment by mwberry** [comment]
So I deleted the cached droidguard download from `/data/user/0/org.microg.gms.droidguard` and then resinstalled DroidGuardHelper to be extra sure. I now get a different error.

```
05-13 21:58:09.000  5111  5111 D SafetyNetHelperSAMPLE: SafetyNet start request
05-13 21:58:09.002  5111  5111 D SafetyNetHelper: apkCertificateDigests:[MZNsDhz8VAJMmFxPPso38ZRvZE6r7VIyzUqypkakG8E=]
05-13 21:58:09.002  5111  5111 V SafetyNetHelper: running SafetyNet.API Test
05-13 21:58:09.037  5603  5639 D GmsDroidguardHelper: -- Request --
05-13 21:58:09.037  5603  5639 D GmsDroidguardHelper: DGRequest{usage=DGUsage{type=attest, packageName=com.google.android.gms}, info=[KeyValuePair{key=BOARD, val=MSM8996}, KeyValuePair{key=BOOTLOADER, val=unknown}, KeyValuePair{key=BRAND, val=lge}, KeyValuePair{key=CPU_ABI, val=arm64-v8a}, KeyValuePair{key=CPU_ABI2, val=}, KeyValuePair{key=DEVICE, val=vs995}, KeyValuePair{key=DISPLAY, val=lineage_vs995-userdebug 7.1.2 NJH47F 20190303 dev-keys}, KeyValuePair{key=FINGERPRINT, val=lge/elsa_vzw/elsa:7.0/NRD90M/1628409164d39:user/release-keys}, KeyValuePair{key=HARDWARE, val=qcom}, KeyValuePair{key=HOST, val=ee676dcbf5a0}, KeyValuePair{key=ID, val=NJH47F}, KeyValuePair{key=MANUFACTURER, val=LGE}, KeyValuePair{key=MODEL, val=LG-VS995}, KeyValuePair{key=PRODUCT, val=elsa_vzw_us}, KeyValuePair{key=RADIO, val=unknown}, KeyValuePair{key=SERIAL, val=LGVS995xxxxxxxx}, KeyValuePair{key=TAGS, val=dev-keys}, KeyValuePair{key=TIME, val=1551643193000}, KeyValuePair{key=TYPE, val=user}, KeyValuePair{key=USER, val=root}, KeyValuePair{key=CODENAME, val=REL}, KeyValuePair{key=INCREMENTAL, val=765d6d7149}, KeyValuePair{key=RELEASE, val=7.1.2}, KeyValuePair{key=SDK, val=25}, KeyValuePair{key=SDK_INT, val=25}], versionNamePrefix=10.0.84 (430-, isGoogleCn=false, enableInlineVm=true, cached=[ByteString[size=20 md5=03d24cde019d581711b7d6a8e2e50d85]], currentVersion=3, arch=aarch64}
05-13 21:58:09.125  5603  5639 D GmsDroidguardHelper: Using cached file from /data/user/0/org.microg.gms.droidguard/app_dg_cache/a5c1de40796a02c71a5309b7ef7fc66244f71fa3/the.apk
05-13 21:58:09.275  5603  5639 D GmsDroidguardHelper: c -> com.google.android.gms
05-13 21:58:09.311  5639  5639 W Thread-3: type=1400 audit(0.0:56401): avc: denied { read } for name="/" dev="tmpfs" ino=4997 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0
05-13 21:58:39.031  5111  5111 E SafetyNetHelperSAMPLE: ApiException[14] 14: 
05-13 21:58:39.353  5603  5639 W art     : Thread suspension timed out: 13
05-13 21:58:43.676  3936  3936 I UpdateChecker: Started
05-13 21:58:43.696  3936  5643 I NativeHttpClientAdapter: Requesting https://android.clients.google.com/fdfe/toc
```

**Comment by mwberry** [comment]
After reading through https://github.com/microg/android_packages_apps_GmsCore/issues/181 I figured it would be worth noting that I have no Xposed and no Magisk. I did install SuperSU in order to be able to make DroidGuardHelper a system app, but I ran a "Full unroot" so I no longer have root, yet the `ApiException[14]` issue persists.

**Comment by Nanolx** [comment]
You're posting this in the wrong project. RemoteDroidGuard is here: https://github.com/microg/android_packages_apps_RemoteDroidGuard

Also a fix for SafetyNet attestations is already pull requested, but not (yet) merged: https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19

Attestation is working here.

**Comment by Nanolx** [comment]
/should/ be fixed now with @ThibG pull request now merged by @mar-v-in see:

https://github.com/microg/android_packages_apps_RemoteDroidGuard/commits/master

As I said I've already been using an inofficial build before (including the afforementioned commits) and it works as expected).

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19
