### ISSUE TITLE
App crash with new mapbox

### ISSUE THREAD

**Issue by Vavun** [microg/android_packages_apps_GmsCore#800]
App  https://play.google.com/store/apps/details?id=gts.dozor_city

```
06-02 12:51:30.103 I/ActivityManager( 1306): Start proc 3693:gts.dozor_city/u0a180 for activity gts.dozor_city/.MainActivity
06-02 12:51:30.240 W/WindowManager( 1306): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@67578bd
06-02 12:51:30.251 D/gts.dozor_city( 3693): initializeSession
06-02 12:51:30.251 D/gts.dozor_city( 3693): HTTPHelper started
06-02 12:51:30.306 D/gts.dozor_city( 3693): initializeGUIElements
06-02 12:51:30.317 E/GooglePlayServicesUtil( 3693): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
06-02 12:51:30.324 I/zzy ( 3693): Making Creator dynamically
06-02 12:51:30.341 I/zygote64( 3693): The ClassLoaderContext is a special shared library.
06-02 12:51:30.349 D/GmsMapCreator( 3693): initV2
06-02 12:51:30.355 D/AndroidRuntime( 3693): Shutting down VM
06-02 12:51:30.356 E/AndroidRuntime( 3693): FATAL EXCEPTION: main
06-02 12:51:30.356 E/AndroidRuntime( 3693): Process: gts.dozor_city, PID: 3693
06-02 12:51:30.356 E/AndroidRuntime( 3693): java.lang.RuntimeException: Unable to start activity ComponentInfo{gts.dozor_city/gts.dozor_city.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.os.Handler.dispatchMessage(Handler.java:106)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.os.Looper.loop(Looper.java:164)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.ActivityThread.main(ActivityThread.java:6494)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at java.lang.reflect.Method.invoke(Native Method)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-02 12:51:30.356 E/AndroidRuntime( 3693): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
06-02 12:51:30.356 E/AndroidRuntime( 3693): at org.microg.gms.maps.mapbox.MapFragmentImpl.onCreateView(Unknown Source:12)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.maps.internal.IMapFragmentDelegate$Stub.onTransact(IMapFragmentDelegate.java:105)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at org.microg.gms.maps.mapbox.MapFragmentImpl.onTransact(MapFragment.kt:88)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.os.Binder.transact(Binder.java:627)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.maps.internal.IMapFragmentDelegate$zza$zza.onCreateView(Unknown Source:46)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.maps.MapFragment$zza.onCreateView(Unknown Source:10)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.dynamic.zza$4.zzb(Unknown Source:19)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.dynamic.zza.zza(Unknown Source:6)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.dynamic.zza.onCreateView(Unknown Source:18)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at com.google.android.gms.maps.MapFragment.onCreateView(Unknown Source:2)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.Fragment.performCreateView(Fragment.java:2508)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.Activity.performCreate(Activity.java:7015)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.Activity.performCreate(Activity.java:7000)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
06-02 12:51:30.356 E/AndroidRuntime( 3693): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
06-02 12:51:30.356 E/AndroidRuntime( 3693): ... 9 more
06-02 12:51:30.359 W/ActivityManager( 1306): Force finishing activity gts.dozor_city/.MainActivity
06-02 12:51:30.368 I/ActivityManager( 1306): Showing crash dialog for package gts.dozor_city u0
```

Also there is
`06-02 12:51:30.317 E/GooglePlayServicesUtil( 3693): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.`
But everything OK, all components are in their place and selfcheck also OK

**Comment by ildar** [comment]
+ https://play.google.com/store/apps/details?id=citybus.guidejet.com , map
fails to show.

**Comment by mar-v-in** [comment]
@Vavun can you try again with 73fd85a8c7ff2762dd615f3a5caa9d9f1db2b6f5

**Comment by Vavun** [comment]
@mar-v-in thanks, it looks like this crash issue been fixed. (*But there is no map so I can't be completely sure that there is no other problems)
Also special thanks to @Nanolx for helping me with this build

I love you guys :)

**Comment by ildar** [comment]
@mar-v-in , would you please reopen and check the citybus.guidejet.com ? It
still fails to show the map with mapbox.
VTM version 0.2.8 and earlier works great.
Thanks!

**Comment by ildar** [comment]
[citybus.adb.logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3834879/1.txt)

**Comment by ildar** [comment]
Please reopen.
I just checked with the newest version. Same exception.

**Comment by mar-v-in** [comment]
@ildar can you open a new issue for this and provide a logcat with current version?
