### ISSUE TITLE
Add com.google.apps.subscriptions.red to known_google_apps (G One).

### ISSUE THREAD

**Issue by oldosfan** [microg/android_packages_apps_GmsCore#806]
Google One requests the EXTENDED_ACCESS permission only available by default to Google-made applications; Here's a logcat of the crash (LoS for µG 16.0, latest microG installed from F-Droid):

```
2019-06-03 08:21:51.124 29861-29881/com.google.android.apps.subscriptions.red E/jpa: Got more than one input Future failure. Logging failures after the first
    java.lang.SecurityException: Access denied, missing EXTENDED_ACCESS permission
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at bgc.b(PG:15)
        at ehj.a(PG:9)
        at eho.a(PG:41)
        at ehy.a(PG:6)
        at dki.b(PG:6)
        at dle.b(PG:14)
        at dle.a(PG:3)
        at dlv.a(PG:18)
        at dls.a(PG:41)
        at ehv.a(PG:2)
        at exx.a(PG:7)
        at hpn.a(Unknown Source:3)
        at hzk.a(Unknown Source:1)
        at hyi.a(PG:5)
        at hyg.a(Unknown Source:1)
        at jpp.a(PG:6)
        at joy.a(PG:5)
        at joz.run(PG:17)
        at jrt.run(PG:3)
        at hyz.run(PG:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at hxb.run(PG:5)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by Nanolx** [comment]
See #799
