### ISSUE TITLE
Google Maps crash with mapbox

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#808]
After upgrading to mapbox Google Maps started to crash with `SecurityException: UID [10097] is not related to packageName [com.google.android.apps.maps]` when I pressed the "show current location" button. I reinstalled Google Maps and now it doesn't start at all:

```


                            Process com.google.android.apps.maps created for activity com.google.android.apps.maps/com.google.android.maps.MapsActivity
                            PID: 29886   UID:    GIDs: 

               zygote64  I  Deoptimizing com.google.common.d.gl com.google.common.d.gl.a(int, java.lang.Object[]) due to JIT inline cache
                 Adreno  I  QUALCOMM build                   : dceea4a, Iedf7298c8c
                         I  Build Date                       : 02/19/18
                         I  OpenGL ES Shader Compiler Version: EV031.22.00.01
                         I  Local Branch                     :
                         I  Remote Branch                    :
                         I  Remote Branch                    :
                         I  Reconstruct Branch               :
                         I  PFP: 0x005ff087, ME: 0x005ff063
               zygote64  I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
                         I  Deoptimizing java.lang.Object com.google.common.d.oj.a(java.lang.Object[], int, int, int) due to JIT inline cache
                         I  The ClassLoaderContext is a special shared library.
  GmsDynamiteLoaderImpl  D  unimplemented Method: getModuleVersion for com.google.android.gms.cronet_dynamite
                         D  unimplemented Method: getModuleVersion for providerinstaller
                         D  unimplemented Method: getModuleVersion for com.google.android.gms.cronet_dynamite
   GmsProviderInstaller  D  Provider installer invoked for com.google.android.apps.maps
               zygote64  I  Compiler allocated 5MB to compile com.google.android.apps.gmm.base.y.b com.google.android.apps.gmm.base.app.bc.gv()
  NetworkSecurityConfig  D  No Network Security Config specified, using platform default
           NativeCrypto  V  Registering org/conscrypt/NativeCrypto's 284 native methods...
   GmsProviderInstaller  D  SSL provider installed
               zygote64  I  Do partial code cache collection, code=28KB, data=28KB
                         I  After code cache collection, code=23KB, data=26KB
                         I  Increasing code cache capacity to 128KB
                         I  Do partial code cache collection, code=62KB, data=50KB
                         I  After code cache collection, code=62KB, data=50KB
                         I  Increasing code cache capacity to 256KB
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
         AndroidRuntime  E  FATAL EXCEPTION: Sensors
                         E  Process: com.google.android.apps.maps, PID: 29886
                         E  android.database.sqlite.SQLiteException: unknown error (code 14): Could not open database
                         E  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
                         E  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                         E  	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                         E  	at android.content.ContentResolver.query(ContentResolver.java:754)
                         E  	at android.content.ContentResolver.query(ContentResolver.java:704)
                         E  	at android.content.ContentResolver.query(ContentResolver.java:662)
                         E  	at com.google.android.f.e.a(PG:94)
                         E  	at com.google.android.f.e.a(PG:22)
                         E  	at com.google.android.apps.gmm.l.a.a(PG:205)
                         E  	at com.google.android.apps.gmm.l.a.b(PG:76)
                         E  	at com.google.android.apps.gmm.location.g.a(PG:15)
                         E  	at com.google.android.apps.gmm.shared.h.k.b(PG:17)
                         E  	at com.google.android.apps.gmm.shared.h.h.b(PG:128)
                         E  	at com.google.android.apps.gmm.shared.h.q.run(PG:1)
                         E  	at android.os.Handler.handleCallback(Handler.java:790)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.os.HandlerThread.run(HandlerThread.java:65)
             System.err  W  android.database.sqlite.SQLiteException: tname=Sensors - unknown error (code 14): Could not open database
                         W  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
                         W  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                         W  	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                         W  	at android.content.ContentResolver.query(ContentResolver.java:754)
                         W  	at android.content.ContentResolver.query(ContentResolver.java:704)
                         W  	at android.content.ContentResolver.query(ContentResolver.java:662)
                         W  	at com.google.android.f.e.a(PG:94)
                         W  	at com.google.android.f.e.a(PG:22)
                         W  	at com.google.android.apps.gmm.l.a.a(PG:205)
                         W  	at com.google.android.apps.gmm.l.a.b(PG:76)
                         W  	at com.google.android.apps.gmm.location.g.a(PG:15)
                         W  	at com.google.android.apps.gmm.shared.h.k.b(PG:17)
                         W  	at com.google.android.apps.gmm.shared.h.h.b(PG:128)
                         W  	at com.google.android.apps.gmm.shared.h.q.run(PG:1)
                         W  	at android.os.Handler.handleCallback(Handler.java:790)
                         W  	at android.os.Handler.dispatchMessage(Handler.java:99)
                         W  	at android.os.Looper.loop(Looper.java:164)
                         W  	at android.os.HandlerThread.run(HandlerThread.java:65)
               zygote64  I  Deoptimizing java.lang.Object com.google.common.d.oj.a(java.lang.Object, java.lang.Object[], int, int, java.lang.Object) due to JIT inline cache
                         I  Deoptimizing int android.support.v4.h.v.a(java.lang.Object, int) due to JIT inline cache
         OpenGLRenderer  D  HWUI GL Pipeline
               zygote64  I  Do full code cache collection, code=103KB, data=116KB
                         I  After code cache collection, code=81KB, data=50KB
                         I  Do partial code cache collection, code=81KB, data=63KB
                         I  After code cache collection, code=81KB, data=63KB
                         I  Increasing code cache capacity to 512KB
                         I  Compiler allocated 5MB to compile void com.google.android.apps.gmm.base.layout.MainLayout.onMeasure(int, int)
                         I  Compiler allocated 5MB to compile void com.google.ag.dq.a(java.lang.Object, com.google.ag.ec, com.google.ag.az)
                         I  Do full code cache collection, code=251KB, data=141KB
                         I  After code cache collection, code=200KB, data=99KB
                         I  Do partial code cache collection, code=238KB, data=126KB
                         I  After code cache collection, code=236KB, data=126KB
                         I  Increasing code cache capacity to 1024KB
                         I  Compiler allocated 4MB to compile void com.google.ag.dq.a(java.lang.Object, com.google.ag.fz)
```

**Comment by Nanolx** [comment]
The location picker is currently disabled so that's likely the cause for the crash.

The issue that Maps works on first installation, but not on a re-installation isn't new at all, I remember that someone™, somewhere™ posted a work-around, maybe I can find it.

**Comment by Nanolx** [comment]
Figured it out: you need to remove your Google Account and then re-add it. Maps will start working again. Seems related to Google Auth Token.

**Comment by Torvin** [comment]
@Nanolx thank you, I don't have a google account, but removing those 2 dirs helped. Maps are still crashing on location pick, but at least now they open

I noticed that I lost all microG settings after all these manipulations. I had to re-enable location backends and turn GCM on. And now it says 0 apps are registered and the state is 'disconnected'. I cannot make any app to re-register by removing its `com.google.android.gms.appid.xml` like I used to before. Should I open a separate issue about that? Here's what Whatsapp says after removing the appid and restarting it:

```

                            Process com.google.android.apps.maps created for activity com.google.android.apps.maps/com.google.android.maps.MapsActivity
                            PID: 25322   UID:    GIDs: 

                 Adreno  I  QUALCOMM build                   : dceea4a, Iedf7298c8c
                         I  Build Date                       : 02/19/18
                         I  OpenGL ES Shader Compiler Version: EV031.22.00.01
                         I  Local Branch                     :
                         I  Remote Branch                    :
                         I  Remote Branch                    :
                         I  Reconstruct Branch               :
                         I  PFP: 0x005ff087, ME: 0x005ff063
               zygote64  I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
                         I  The ClassLoaderContext is a special shared library.
  GmsDynamiteLoaderImpl  D  unimplemented Method: getModuleVersion for com.google.android.gms.cronet_dynamite
                         D  unimplemented Method: getModuleVersion for providerinstaller
   GmsProviderInstaller  D  Provider installer invoked for com.google.android.apps.maps
  GmsDynamiteLoaderImpl  D  unimplemented Method: getModuleVersion for com.google.android.gms.cronet_dynamite
           NativeCrypto  V  Registering org/conscrypt/NativeCrypto's 284 native methods...
  NetworkSecurityConfig  D  No Network Security Config specified, using platform default
   GmsProviderInstaller  D  SSL provider installed
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
         OpenGLRenderer  D  HWUI GL Pipeline
                         I  Initialized EGL, version 1.4
                         D  Swap behavior 2
               zygote64  I  Background concurrent copying GC freed 114455(5MB) AllocSpace objects, 40(2MB) LOS objects, 50% free, 21MB/42MB, paused 927us total 156.432ms
                         I  Do partial code cache collection, code=8KB, data=30KB
                         I  After code cache collection, code=8KB, data=30KB
                         I  Increasing code cache capacity to 128KB
                    NFC  V  this device does not have NFC support
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.google.android.apps.maps, PID: 25322
                         E  java.lang.SecurityException: UID [10097] is not related to packageName [com.google.android.apps.maps]
                         E  	at android.os.Parcel.readException(Parcel.java:2013)
                         E  	at android.os.Parcel.readException(Parcel.java:1959)
                         E  	at com.google.android.a.b.b(PG:15)
                         E  	at com.google.android.gms.location.internal.ab.a(PG:39)
                         E  	at com.google.android.gms.location.internal.at.a(PG:7)
                         E  	at com.google.android.gms.common.api.internal.p.b(PG:7)
                         E  	at com.google.android.gms.common.api.internal.ak.b(PG:16)
                         E  	at com.google.android.gms.common.api.internal.bg.b(PG:21)
                         E  	at com.google.android.gms.common.api.internal.ay.b(PG:32)
                         E  	at com.google.android.gms.common.api.internal.ay.a(PG:218)
                         E  	at com.google.android.gms.common.api.internal.am.g(PG:92)
                         E  	at com.google.android.gms.common.api.internal.am.a(PG:69)
                         E  	at com.google.android.gms.common.api.internal.bg.a(PG:60)
                         E  	at com.google.android.gms.common.api.internal.y.a(PG:5)
                         E  	at com.google.android.gms.common.internal.ab.a(PG:3)
                         E  	at com.google.android.gms.common.internal.l.a(PG:18)
                         E  	at com.google.android.gms.common.internal.e.a(PG:12)
                         E  	at com.google.android.gms.common.internal.f.handleMessage(PG:54)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         E  	at com.google.android.gms.e.a.b.c.a(PG:5)
                         E  	at com.google.android.gms.e.a.b.c.dispatchMessage(PG:4)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E  	at java.lang.reflect.Method.invoke(Native Method)
                         E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
             System.err  W  java.lang.SecurityException: tname=main - UID [10097] is not related to packageName [com.google.android.apps.maps]
                         W  	at android.os.Parcel.readException(Parcel.java:2013)
                         W  	at android.os.Parcel.readException(Parcel.java:1959)
                         W  	at com.google.android.a.b.b(PG:15)
                         W  	at com.google.android.gms.location.internal.ab.a(PG:39)
                         W  	at com.google.android.gms.location.internal.at.a(PG:7)
                         W  	at com.google.android.gms.common.api.internal.p.b(PG:7)
                         W  	at com.google.android.gms.common.api.internal.ak.b(PG:16)
                         W  	at com.google.android.gms.common.api.internal.bg.b(PG:21)
                         W  	at com.google.android.gms.common.api.internal.ay.b(PG:32)
                         W  	at com.google.android.gms.common.api.internal.ay.a(PG:218)
                         W  	at com.google.android.gms.common.api.internal.am.g(PG:92)
                         W  	at com.google.android.gms.common.api.internal.am.a(PG:69)
                         W  	at com.google.android.gms.common.api.internal.bg.a(PG:60)
                         W  	at com.google.android.gms.common.api.internal.y.a(PG:5)
                         W  	at com.google.android.gms.common.internal.ab.a(PG:3)
                         W  	at com.google.android.gms.common.internal.l.a(PG:18)
                         W  	at com.google.android.gms.common.internal.e.a(PG:12)
                         W  	at com.google.android.gms.common.internal.f.handleMessage(PG:54)
                         W  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         W  	at com.google.android.gms.e.a.b.c.a(PG:5)
                         W  	at com.google.android.gms.e.a.b.c.dispatchMessage(PG:4)
                         W  	at android.os.Looper.loop(Looper.java:164)
                         W  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         W  	at java.lang.reflect.Method.invoke(Native Method)
                         W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.google.android.apps.maps, PID: 28191
                         E  java.lang.SecurityException: UID [10097] is not related to packageName [com.google.android.apps.maps]
                         E  	at android.os.Parcel.readException(Parcel.java:2013)
                         E  	at android.os.Parcel.readException(Parcel.java:1959)
                         E  	at com.google.android.a.b.b(PG:15)
                         E  	at com.google.android.gms.location.internal.ab.a(PG:39)
                         E  	at com.google.android.gms.location.internal.at.a(PG:7)
                         E  	at com.google.android.gms.common.api.internal.p.b(PG:7)
                         E  	at com.google.android.gms.common.api.internal.ak.b(PG:16)
                         E  	at com.google.android.gms.common.api.internal.bg.b(PG:21)
                         E  	at com.google.android.gms.common.api.internal.ay.b(PG:32)
                         E  	at com.google.android.gms.common.api.internal.ay.a(PG:218)
                         E  	at com.google.android.gms.common.api.internal.am.g(PG:92)
                         E  	at com.google.android.gms.common.api.internal.am.a(PG:69)
                         E  	at com.google.android.gms.common.api.internal.bg.a(PG:60)
                         E  	at com.google.android.gms.common.api.internal.y.a(PG:5)
                         E  	at com.google.android.gms.common.internal.ab.a(PG:3)
                         E  	at com.google.android.gms.common.internal.l.a(PG:18)
                         E  	at com.google.android.gms.common.internal.e.a(PG:12)
                         E  	at com.google.android.gms.common.internal.f.handleMessage(PG:54)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         E  	at com.google.android.gms.e.a.b.c.a(PG:5)
                         E  	at com.google.android.gms.e.a.b.c.dispatchMessage(PG:4)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E  	at java.lang.reflect.Method.invoke(Native Method)
                         E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
             System.err  W  java.lang.SecurityException: tname=main - UID [10097] is not related to packageName [com.google.android.apps.maps]
                         W  	at android.os.Parcel.readException(Parcel.java:2013)
                         W  	at android.os.Parcel.readException(Parcel.java:1959)
                         W  	at com.google.android.a.b.b(PG:15)
                         W  	at com.google.android.gms.location.internal.ab.a(PG:39)
                         W  	at com.google.android.gms.location.internal.at.a(PG:7)
                         W  	at com.google.android.gms.common.api.internal.p.b(PG:7)
                         W  	at com.google.android.gms.common.api.internal.ak.b(PG:16)
                         W  	at com.google.android.gms.common.api.internal.bg.b(PG:21)
                         W  	at com.google.android.gms.common.api.internal.ay.b(PG:32)
                         W  	at com.google.android.gms.common.api.internal.ay.a(PG:218)
                         W  	at com.google.android.gms.common.api.internal.am.g(PG:92)
                         W  	at com.google.android.gms.common.api.internal.am.a(PG:69)
                         W  	at com.google.android.gms.common.api.internal.bg.a(PG:60)
                         W  	at com.google.android.gms.common.api.internal.y.a(PG:5)
                         W  	at com.google.android.gms.common.internal.ab.a(PG:3)
                         W  	at com.google.android.gms.common.internal.l.a(PG:18)
                         W  	at com.google.android.gms.common.internal.e.a(PG:12)
                         W  	at com.google.android.gms.common.internal.f.handleMessage(PG:54)
                         W  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         W  	at com.google.android.gms.e.a.b.c.a(PG:5)
                         W  	at com.google.android.gms.e.a.b.c.dispatchMessage(PG:4)
                         W  	at android.os.Looper.loop(Looper.java:164)
                         W  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         W  	at java.lang.reflect.Method.invoke(Native Method)
                         W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

                            Process com.google.android.apps.maps created for activity com.google.android.apps.maps/com.google.android.maps.MapsActivity
                            PID: 29886   UID:    GIDs: 

               zygote64  I  Deoptimizing com.google.common.d.gl com.google.common.d.gl.a(int, java.lang.Object[]) due to JIT inline cache
                 Adreno  I  QUALCOMM build                   : dceea4a, Iedf7298c8c
                         I  Build Date                       : 02/19/18
                         I  OpenGL ES Shader Compiler Version: EV031.22.00.01
                         I  Local Branch                     :
                         I  Remote Branch                    :
                         I  Remote Branch                    :
                         I  Reconstruct Branch               :
                         I  PFP: 0x005ff087, ME: 0x005ff063
               zygote64  I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
                         I  Deoptimizing java.lang.Object com.google.common.d.oj.a(java.lang.Object[], int, int, int) due to JIT inline cache
                         I  The ClassLoaderContext is a special shared library.
  GmsDynamiteLoaderImpl  D  unimplemented Method: getModuleVersion for com.google.android.gms.cronet_dynamite
                         D  unimplemented Method: getModuleVersion for providerinstaller
                         D  unimplemented Method: getModuleVersion for com.google.android.gms.cronet_dynamite
   GmsProviderInstaller  D  Provider installer invoked for com.google.android.apps.maps
               zygote64  I  Compiler allocated 5MB to compile com.google.android.apps.gmm.base.y.b com.google.android.apps.gmm.base.app.bc.gv()
  NetworkSecurityConfig  D  No Network Security Config specified, using platform default
           NativeCrypto  V  Registering org/conscrypt/NativeCrypto's 284 native methods...
   GmsProviderInstaller  D  SSL provider installed
               zygote64  I  Do partial code cache collection, code=28KB, data=28KB
                         I  After code cache collection, code=23KB, data=26KB
                         I  Increasing code cache capacity to 128KB
                         I  Do partial code cache collection, code=62KB, data=50KB
                         I  After code cache collection, code=62KB, data=50KB
                         I  Increasing code cache capacity to 256KB
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
         AndroidRuntime  E  FATAL EXCEPTION: Sensors
                         E  Process: com.google.android.apps.maps, PID: 29886
                         E  android.database.sqlite.SQLiteException: unknown error (code 14): Could not open database
                         E  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
                         E  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                         E  	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                         E  	at android.content.ContentResolver.query(ContentResolver.java:754)
                         E  	at android.content.ContentResolver.query(ContentResolver.java:704)
                         E  	at android.content.ContentResolver.query(ContentResolver.java:662)
                         E  	at com.google.android.f.e.a(PG:94)
                         E  	at com.google.android.f.e.a(PG:22)
                         E  	at com.google.android.apps.gmm.l.a.a(PG:205)
                         E  	at com.google.android.apps.gmm.l.a.b(PG:76)
                         E  	at com.google.android.apps.gmm.location.g.a(PG:15)
                         E  	at com.google.android.apps.gmm.shared.h.k.b(PG:17)
                         E  	at com.google.android.apps.gmm.shared.h.h.b(PG:128)
                         E  	at com.google.android.apps.gmm.shared.h.q.run(PG:1)
                         E  	at android.os.Handler.handleCallback(Handler.java:790)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.os.HandlerThread.run(HandlerThread.java:65)
             System.err  W  android.database.sqlite.SQLiteException: tname=Sensors - unknown error (code 14): Could not open database
                         W  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
                         W  	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                         W  	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                         W  	at android.content.ContentResolver.query(ContentResolver.java:754)
                         W  	at android.content.ContentResolver.query(ContentResolver.java:704)
                         W  	at android.content.ContentResolver.query(ContentResolver.java:662)
                         W  	at com.google.android.f.e.a(PG:94)
                         W  	at com.google.android.f.e.a(PG:22)
                         W  	at com.google.android.apps.gmm.l.a.a(PG:205)
                         W  	at com.google.android.apps.gmm.l.a.b(PG:76)
                         W  	at com.google.android.apps.gmm.location.g.a(PG:15)
                         W  	at com.google.android.apps.gmm.shared.h.k.b(PG:17)
                         W  	at com.google.android.apps.gmm.shared.h.h.b(PG:128)
                         W  	at com.google.android.apps.gmm.shared.h.q.run(PG:1)
                         W  	at android.os.Handler.handleCallback(Handler.java:790)
                         W  	at android.os.Handler.dispatchMessage(Handler.java:99)
                         W  	at android.os.Looper.loop(Looper.java:164)
                         W  	at android.os.HandlerThread.run(HandlerThread.java:65)
               zygote64  I  Deoptimizing java.lang.Object com.google.common.d.oj.a(java.lang.Object, java.lang.Object[], int, int, java.lang.Object) due to JIT inline cache
                         I  Deoptimizing int android.support.v4.h.v.a(java.lang.Object, int) due to JIT inline cache
         OpenGLRenderer  D  HWUI GL Pipeline
               zygote64  I  Do full code cache collection, code=103KB, data=116KB
                         I  After code cache collection, code=81KB, data=50KB
                         I  Do partial code cache collection, code=81KB, data=63KB
                         I  After code cache collection, code=81KB, data=63KB
                         I  Increasing code cache capacity to 512KB
                         I  Compiler allocated 5MB to compile void com.google.android.apps.gmm.base.layout.MainLayout.onMeasure(int, int)
                         I  Compiler allocated 5MB to compile void com.google.ag.dq.a(java.lang.Object, com.google.ag.ec, com.google.ag.az)
                         I  Do full code cache collection, code=251KB, data=141KB
                         I  After code cache collection, code=200KB, data=99KB
                         I  Do partial code cache collection, code=238KB, data=126KB
                         I  After code cache collection, code=236KB, data=126KB
                         I  Increasing code cache capacity to 1024KB
                         I  Compiler allocated 4MB to compile void com.google.ag.dq.a(java.lang.Object, com.google.ag.fz)

                            Process com.whatsapp created for activity com.whatsapp/.Main
                            PID: 8421   UID:    GIDs: 

               MultiDex  I  VM with version 2.1.0 has multidex support
                         I  Installing application
                         I  VM has multidex support, MultiDex support library is disabled.
SigquitBasedANRDetector  D  Registered
         ActivityThread  D  Loading provider com.whatsapp.provider.contact: com.whatsapp.contact.ContactProvider
               zygote64  W  Class d.f.w.g failed lock verification and will run slower.
                         W  Common causes for lock verification issues are non-optimized dex code
                         W  and incorrect proguard optimizations.
            FirebaseApp  D  com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
                         D  com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
   FirebaseInitProvider  I  FirebaseApp initialization successful
                     FA  I  Collection disabled with firebase_analytics_collection_deactivated=1
                         I  App measurement is starting up, version: 11910
                         I  To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
                         I  To enable faster debug mode event logging run:
                         I    adb shell setprop debug.firebase.analytics.app com.whatsapp
               zygote64  W  Class d.f.b.c failed lock verification and will run slower.
                         W  Class d.f.Z.Qa failed lock verification and will run slower.
  NetworkSecurityConfig  D  Using Network Security Config from resource network_security_config debugBuild: false
                  Event  D  No subscribers registered for event class d.f.C.c
                         D  No subscribers registered for event class e.a.a.h
                         D  No subscribers registered for event class d.f.C.c
                         D  No subscribers registered for event class e.a.a.h
  AppCompatViewInflater  I  app:theme is now deprecated. Please move to using android:theme instead.
                    NFC  V  this device does not have NFC support
         OpenGLRenderer  D  HWUI GL Pipeline
                 Adreno  I  QUALCOMM build                   : dceea4a, Iedf7298c8c
                         I  Build Date                       : 02/19/18
                         I  OpenGL ES Shader Compiler Version: EV031.22.00.01
                         I  Local Branch                     :
                         I  Remote Branch                    :
                         I  Remote Branch                    :
                         I  Reconstruct Branch               :
                         I  PFP: 0x005ff087, ME: 0x005ff063
               zygote64  I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
         OpenGLRenderer  I  Initialized EGL, version 1.4
                         D  Swap behavior 2
               zygote64  I  Method exceeds compiler instruction limit: 29726 in int com.whatsapp.emoji.EmojiDescriptor.getDescriptor(com.whatsapp.emoji.EmojiDescriptor$b)
                         W  Long monitor contention with owner pool-1-thread-1 (8459) at long com.android.org.conscrypt.NativeCrypto.RSA_generate_key_ex(int, byte[])(NativeCrypto.java:-2) waiters=0 in java.security.KeyPair d.e.b.a.z.f(java.lang.String) for 525ms
           RecyclerView  E  No adapter attached; skipping layout
               zygote64  I  Do partial code cache collection, code=2912B, data=30KB
                         I  After code cache collection, code=2912B, data=30KB
                         I  Increasing code cache capacity to 128KB
     FirebaseInstanceId  E  Token retrieval failed: SERVICE_NOT_AVAILABLE
 SpannableStringBuilder  E  SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
                         E  SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
                         E  SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
                         E  SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

```

**Comment by ravilov** [comment]
Hello,

Just stumbled upon this looking for answers to my other issues, I was just wondering - why is the location picker disabled?

Thanks.

**Comment by Torvin** [comment]
None of the apps are showing. Not even 'non-registered' ones:

![Screenshot_20190604-230821_microG_Services_Core](https://user-images.githubusercontent.com/3890785/58874845-fc683580-871d-11e9-99b2-e1176d214369.png)

Re-installing apps doesn't help either

**Comment by Nanolx** [comment]
@ravilov because mar-v-in is currently re-writing the Maps support in microG, and in the current state it's not working, so it was disabled to prevent crashes.

@Torvin if your device is rooted, try the following command on-device as root:

`find /data/data/*/shared_prefs -name com.google.android.gms.*.xml -delete`

this will reset all GMS connections from the apps, if you afterwards start them again, they should register. If not, please provide a logcat **in a new issue**, because this is not related to the Maps crash.

**Comment by ravilov** [comment]
Gotcha, thanks.

**Comment by Torvin** [comment]
@Nanolx done #814, thanks

Should I keep this issue open with regards to the Maps crash? Also I've noticed that some public transport apps that I use show Saarbrucken (Germany) as the default map location. I don't even leave in Germany. Is this expected because of the disabled location picker? Or should I file a bug about this?

**Comment by Torvin** [comment]
Stopped crashing after updating to `0.2.8.17785-mapbox`
