### ISSUE TITLE
Mapbox broke map api calls completly

### ISSUE THREAD

**Issue by kusznier** [microg/android_packages_apps_GmsCore#812]
Hi, 
On my Huawei p20 gallery crashes with following error. 
Also, any map api request ends up with empty map screen like (uber, Lime, and others)
I have newest microg update.

2019-06-04 11:58:48,ERROR,Gallery2_Common_CrashHandler ,Fatal  Gallery uncaughtException.Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IUiSettingsDelegate.setZoomControlsEnabled(boolean)' on a null object reference

**Comment by kusznier** [comment]
Same thing on second device mi5 with different system

**Comment by oldosfan** [comment]
Please post the entire Logcat, not just the first line of the stack

**Comment by kusznier** [comment]
06-05 09:40:06.670 27554 27554 D GmsMultiArchLoader: Loading mapbox-gl from /data/user/0/com.android.gallery3d/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so
06-05 09:40:06.783 27554 27554 D AndroidRuntime: Shutting down VM
06-05 09:40:06.793 27554 27554 E AndroidRuntime: FATAL EXCEPTION: main
06-05 09:40:06.793 27554 27554 E AndroidRuntime: Process: com.android.gallery3d, PID: 27554
06-05 09:40:06.793 27554 27554 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IUiSettingsDelegate.setZoomControlsEnabled(boolean)' on a null object reference
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at com.google.android.gms.maps.UiSettings.setZoomControlsEnabled(Unknown Source:2)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at com.huawei.gallery.map.photomore.GoogleFragment.onViewCreated(GoogleFragment.java:52)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1432)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7470)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
06-05 09:40:06.793 27554 27554 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
06-05 09:40:06.793 27554 27554 E Gallery2_Common_CrashHandler : Fatal  Gallery uncaughtException.Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IUiSettingsDelegate.setZoomControlsEnabled(boolean)' on a null object reference

**Comment by oldosfan** [comment]
There should be more than just the first exception of the logcat
