### ISSUE TITLE
Jodel app crashes on initial setup

### ISSUE THREAD

**Issue by Eerovil** [microg/android_packages_apps_GmsCore#820]
Using latest NanoDroid version from f-droid. No nlp installed.

```06-06 09:30:01.718 D/GmsLocManagerSvc(3362): onBind: Intent { act=com.google.android.location.internal.GoogleLocationManagerService.START pkg=com.google.android.gms }
06-06 09:30:01.772 D/SafeParcel(3362): Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-06 09:30:01.772 D/SafeParcel(3362): Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-06 09:30:01.772 D/SafeParcel(3362): Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-06 09:30:01.773 D/GmsLocManagerSvc(3362): bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=12451000, packageName='com.tellm.android.app', extras=Bundle[{client_name=locationServices}]}
06-06 09:30:01.821 D/SafeParcel(3362): Unknown field num 3 in com.google.android.gms.location.LocationSettingsRequest, skipping.
06-06 09:30:01.821 D/GmsLocManagerSvcImpl(3362): requestLocationSettingsDialog: com.google.android.gms.location.LocationSettingsRequest@88f9672
06-06 09:30:02.247 W/zygote  (16093): Long monitor contention with owner firebase-iid-executor (16112) at long com.android.org.conscrypt.NativeCrypto.RSA_generate_key_ex(int, byte[])(NativeCrypto.java:-2) waiters=0 in com.google.firebase.iid.zzax com.google.firebase.iid.zzaw.ˊॱ(java.lang.String, java.lang.String, java.lang.String) for 2.745s
06-06 09:30:02.252 W/ActivityManager(1581): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=16093, uid=10113 requires com.google.android.c2dm.permission.RECEIVE
06-06 09:30:02.253 E/AndroidRuntime(16093): FATAL EXCEPTION: firebase-iid-executor
06-06 09:30:02.253 E/AndroidRuntime(16093): Process: com.tellm.android.app, PID: 16093
06-06 09:30:02.253 E/AndroidRuntime(16093): java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1623)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at android.app.ContextImpl.bindService(ContextImpl.java:1557)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.android.gms.common.stats.ConnectionTracker.ˏ(Unknown Source:22)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.android.gms.common.stats.ConnectionTracker.ˊ(Unknown Source:24)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.firebase.iid.zzad.ˏ(Unknown Source:17)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.firebase.iid.zzab.ˋ(Unknown Source:15)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.firebase.iid.zzab.ˏ(Unknown Source:12)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.firebase.iid.zzat.ˉ(Unknown Source:80)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.firebase.iid.zzr.ˏ(Unknown Source:73)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at com.google.firebase.iid.zzs.run(Unknown Source:6)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-06 09:30:02.253 E/AndroidRuntime(16093): 	at java.lang.Thread.run(Thread.java:764)
06-06 09:30:02.262 I/FA      (16093): Tag Manager is not found and thus will not be used
06-06 09:30:02.334 D/SafeParcel(3362): Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-06 09:30:02.334 D/SafeParcel(3362): Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-06 09:30:02.334 D/SafeParcel(3362): Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-06 09:30:02.334 D/GmsMeasureBrokerSvc(3362): bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='com.tellm.android.app', extras=Bundle[{}]}
06-06 09:30:02.340 W/ActivityManager(1581):   Force finishing activity com.tellm.android.app/com.jodelapp.jodelandroidv3.view.Launcher
06-06 09:30:02.361 I/BranchSDK(16093): returned {"session_id":"665067199391771215","identity_id":"665067199396263434","link":"https://shared.jodel.com/a/key_live_jcESXFnKwxb53gafuWSRFijozto4BLB5?%24identity_id=665067199396263434","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":true}","device_fingerprint_id":"665067199350088477"}
06-06 09:30:02.364 I/ActivityManager(1581): Showing crash dialog for package com.tellm.android.app u0
06-06 09:30:02.406 D/GmsMeasureSvcImpl(3362): onTransact [unknown]: 4, android.os.Parcel@4b049d5, 16
06-06 09:30:02.414 I/OpenGLRenderer(1581): Initialized EGL, version 1.4
06-06 09:30:02.414 D/OpenGLRenderer(1581): Swap behavior 2
06-06 09:30:02.423 D/GmsMeasureSvcImpl(3362): onTransact [unknown]: 1, android.os.Parcel@767a931, 16
06-06 09:30:02.423 D/GmsMeasureSvcImpl(3362): onTransact [unknown]: 11, android.os.Parcel@4b049d5, 16
06-06 09:30:02.428 D/GmsMeasureSvcImpl(3362): onTransact [unknown]: 10, android.os.Parcel@767a931, 16
06-06 09:30:02.430 D/GmsMeasureSvcImpl(3362): onTransact [unknown]: 10, android.os.Parcel@4b049d5, 16
06-06 09:30:02.468 D/GmsMeasureSvcImpl(3362): onTransact [unknown]: 1, android.os.Parcel@767a931, 16
06-06 09:30:02.485 D/        (1160): DpmQmiMgr installListenFilters```

**Comment by Nanolx** [comment]
I think I know what the issue is. A new build is up.

**Comment by Eerovil** [comment]
@Nanolx Thanks. This might be a dumb question, but what do you mean by "build is up"? Where is it? I see you have made a commit in the nanolx-new branch and I could very well build it myself, but then Play Store and GmsCore would have differing keys.

I also tried making a NanoDroid microG snapshot package, but it doesn't have that latest commit

**Comment by Nanolx** [comment]
https://www.nanolx.org/fdroid/repo

Am 6. Juni 2019 11:56:57 MESZ schrieb Eerovil <notifications@github.com>:
>@Nanolx Thanks. This might be a dumb question, but what do you mean by
>"build is up"? Where is it? I see you have made a commit in the
>nanolx-new branch and I could very well build it myself, but then Play
>Store and GmsCore would have differing keys.
>
>I also tried making a NanoDroid microG snapshot package, but it doesn't
>have that latest commit
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/820#issuecomment-499430197

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Eerovil** [comment]
Right, it's in the repo. I'll try to download it there.

Right now there seems to be a problem with the GmsCore app not being visible in f-droid after installing NanoDroid, but I don't know if it's just a temporary bug. Someone else on Telegram also had the same problem. Oh well, I'll try to figure something out!

**Comment by Nanolx** [comment]
It shows up as uNlp, it's a known bug in F-Droid.

Am 6. Juni 2019 12:05:50 MESZ schrieb Eerovil <notifications@github.com>:
>Right, it's in the repo. I'll try to download it there.
>
>Right now there seems to be a problem with the GmsCore app not being
>visible in f-droid after installing NanoDroid, but I don't know if it's
>just a temporary bug. Someone else on Telegram also had the same
>problem. Oh well, I'll try to figure something out!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/820#issuecomment-499433096

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
