### ISSUE TITLE
Revolut crashes on [microG v0.2.7.17455][Logcat included]

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [microg/android_packages_apps_GmsCore#823]
A clean Revolut install crashes after launching.

```
time: 1559831650456
msg: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0802e7
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.revolut.revolut/com.revolut.ui.login.pin.LoginActivity}: android.content.res.Resources$NotFoundException: Drawable com.revolut.revolut:drawable/layer_list_splash_background with resource ID #0x7f080563
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6745)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.revolut.revolut:drawable/layer_list_splash_background with resource ID #0x7f080563
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/layer_list_splash_background.xml from drawable resource ID #0x7f080563
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
	at android.content.res.Resources.getDrawable(Resources.java:827)
	at android.content.Context.getDrawable(Context.java:635)
	at android.support.v4.content.ContextCompat.getDrawable(Unknown Source:6)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(Unknown Source:16)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(Unknown Source:24)
	at android.support.v7.app.c.<init>(Unknown Source:61)
	at android.support.v7.app.AppCompatDelegate.a(Unknown Source:6)
	at android.support.v7.app.a.getDelegate(Unknown Source:4)
	at android.support.v7.app.a.onCreate(Unknown Source:0)
	at com.revolut.retail.core.c.a.onCreate(Unknown Source:0)
	at com.revolut.ui.activity.b.onCreate(Unknown Source:0)
	at com.revolut.ui.login.pin.LoginActivity.onCreate(Unknown Source:34)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6745)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0802e7
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0802e7
	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:255)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:785)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
	at android.content.res.Resources.loadDrawable(Resources.java:897)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:382)
	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:261)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:194)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
	at android.content.res.Resources.getDrawable(Resources.java:827)
	at android.content.Context.getDrawable(Context.java:635)
	at android.support.v4.content.ContextCompat.getDrawable(Unknown Source:6)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(Unknown Source:16)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(Unknown Source:24)
	at android.support.v7.app.c.<init>(Unknown Source:61)
	at android.support.v7.app.AppCompatDelegate.a(Unknown Source:6)
	at android.support.v7.app.a.getDelegate(Unknown Source:4)
	at android.support.v7.app.a.onCreate(Unknown Source:0)
	at com.revolut.retail.core.c.a.onCreate(Unknown Source:0)
	at com.revolut.ui.activity.b.onCreate(Unknown Source:0)
	at com.revolut.ui.login.pin.LoginActivity.onCreate(Unknown Source:34)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6745)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by oldosfan** [comment]
This is a. bug with Revolut

**Comment by voxitme** [comment]
Here I don't have any crash on OnePlus6 liquidremix 10.0.8-20190514 (Pie) with microG v0.2.7.17455-mapbox

**Comment by mar-v-in** [comment]
This seems unrelated to microG. From the error message I guess you only installed the base part of a split apk and not the resolution dependent resources.

**Comment by cRaZy-bisCuiT** [comment]
Could you please let me know what you do mean by "not the resolution dependent resources"? I installed the APK from Google Play Store using Aurora Store do download it.

**Comment by mar-v-in** [comment]
Split APKs consist of multiple files. I just checked for Revolut and it consists of 4 files: base, architecture-dependent, language-dependent and resolution-dependent.  To correctly install the app, you'd need to download and install all 4 parts at once. Android for some reason allows to install only the base of a split APK, which usually causes the app to directly crash after launch with a log as the one you provided.

As far as I know, Yalp and Aurora store do support downloading split APK including all the parts required to install it. However, if not installed as a system app, they will not be able to install split APK correctly, neither is it possible to manually do so by selecting the downloaded file from a file explorer. Split APKs can only be installed by specifically crafted system apps (like the original Google Play Store) and manually through `adb`.

**Comment by cRaZy-bisCuiT** [comment]
Interesting. They seem to have changed there APK then. It was working in the past without any issues. I'll try with giving root/system permissions to Aurora.

**Comment by cRaZy-bisCuiTs** [comment]
Actually it was the split apk reason and unrelated to MicroG. Thanks!

SAI fixed the issue for me.
