### ISSUE TITLE
Crash on mapbox from worker thread in Uber

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#832]
When I press 'Request Uber' it crashes with the following:

```
06-09 22:31:12.014  4739  4739 W System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Inferred subscribe point: aeom.accept(:1063747)
06-09 22:31:12.014  4739  4739 W System.err: 	at com.ubercab.rx2.java.stackelementtagging.TaggingObserver.onError(:276671)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.a(:135985)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.e(:136002)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(:136060)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.android.schedulers.AsyncHandlerScheduler$ScheduledRunnable.run(:285788)
06-09 22:31:12.014  4739  4739 W System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
06-09 22:31:12.014  4739  4739 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-09 22:31:12.014  4739  4739 W System.err: 	at android.os.Looper.loop(Looper.java:164)
06-09 22:31:12.014  4739  4739 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-09 22:31:12.014  4739  4739 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-09 22:31:12.014  4739  4739 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-09 22:31:12.014  4739  4739 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-09 22:31:12.014  4739  4739 W System.err: Caused by: com.mapbox.mapboxsdk.exceptions.CalledFromWorkerThreadException: Map interactions should happen on the UI thread. Method invoked from wrong thread is pixelForLatLng.
06-09 22:31:12.014  4739  4739 W System.err: 	at com.mapbox.mapboxsdk.maps.NativeMapView.checkState(NativeMapView.java:113)
06-09 22:31:12.014  4739  4739 W System.err: 	at com.mapbox.mapboxsdk.maps.NativeMapView.pixelForLatLng(NativeMapView.java:659)
06-09 22:31:12.014  4739  4739 W System.err: 	at com.mapbox.mapboxsdk.maps.Projection.toScreenLocation(Projection.java:257)
06-09 22:31:12.014  4739  4739 W System.err: 	at org.microg.gms.maps.mapbox.ProjectionImpl.toScreenLocation(Projection.kt:37)
06-09 22:31:12.014  4739  4739 W System.err: 	at com.google.android.gms.maps.internal.IProjectionDelegate$Stub.onTransact(IProjectionDelegate.java:72)
06-09 22:31:12.014  4739  4739 W System.err: 	at android.os.Binder.transact(Binder.java:627)
06-09 22:31:12.014  4739  4739 W System.err: 	at dvv.a(Unknown Source:7)
06-09 22:31:12.014  4739  4739 W System.err: 	at ecl.a(Unknown Source:8)
06-09 22:31:12.014  4739  4739 W System.err: 	at ebr.a(Unknown Source:2)
06-09 22:31:12.014  4739  4739 W System.err: 	at hif.toScreenLocation(:122401)
06-09 22:31:12.014  4739  4739 W System.err: 	at aeop.apply(:1063766)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(:135727)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.e(:136007)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(:136060)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(:140477)
06-09 22:31:12.014  4739  4739 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(:140460)
06-09 22:31:12.015  4739  4739 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-09 22:31:12.015  4739  4739 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
06-09 22:31:12.015  4739  4739 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
06-09 22:31:12.015  4739  4739 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-09 22:31:12.015  4739  4739 W System.err: 	at -$$Lambda$gvu$VCSYyzcX1Z4p8g4sB0tJFRQC-4I.run(Unknown Source:7)
06-09 22:31:12.015  4739  4739 W System.err: 	at java.lang.Thread.run(Thread.java:764)
```

It successfuly requests an uber though, and shows that driver is on their way after restarting the app.

**Comment by mar-v-in** [comment]
According to https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap,
> Similar to a View object, a GoogleMap can only be read and modified from the Android UI thread. Calling GoogleMap methods from another thread will result in an exception.

However this rule isn't enforced in Google API for any call to methods on a Projection, whereas in MapBox it isn't enforced for the call to `getProjection()`, but for calls to methods on a Projection.

**Comment by mar-v-in** [comment]
Related upstream issue: mapbox/mapbox-gl-native#14881

**Comment by oldosfan** [comment]
@mar-v-in thank's for clarifying this behaviour. I'd like to think this is Google being lax with enforcement.

Might have to wait for Mapbox though

**Comment by Torvin** [comment]
Doesn't crash anymore after updating to 0.2.8.17785-mapbox.
