### ISSUE TITLE
Transit doesn't show buses on the map

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#833]
Transit (`com.thetransitapp.droid`) definitely works better now in mapbox version. But I still can't see bus routes and I cant see buses on the map. 

I ran the app and picked a route. No routes/buses are displayed on the map:

```

                            Process com.thetransitapp.droid created for activity com.thetransitapp.droid/.shared.activity.SplashActivity
                            PID: 3720   UID:    GIDs: 

               MultiDex  I  VM with version 2.1.0 has multidex support
                         I  Installing application
                         I  VM has multidex support, MultiDex support library is disabled.
            FirebaseApp  D  com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
                         D  com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
   FirebaseInitProvider  I  FirebaseApp initialization successful
                     FA  I  App measurement is starting up, version: 12451
                         I  To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
                         I  To enable faster debug mode event logging run:
                         I    adb shell setprop debug.firebase.analytics.app com.thetransitapp.droid
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
         libcrashlytics  D  Initializing libcrashlytics version 2.0.5
                         D  Initializing native crash handling successful.
        CrashlyticsCore  I  Initializing Crashlytics 2.6.4.27
  NetworkSecurityConfig  D  No Network Security Config specified, using platform default
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
                     FA  I  Tag Manager is not found and thus will not be used
         OpenGLRenderer  D  HWUI GL Pipeline
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
                 Adreno  I  QUALCOMM build                   : dceea4a, Iedf7298c8c
                         I  Build Date                       : 02/19/18
                         I  OpenGL ES Shader Compiler Version: EV031.22.00.01
                         I  Local Branch                     :
                         I  Remote Branch                    :
                         I  Remote Branch                    :
                         I  Reconstruct Branch               :
                         I  PFP: 0x005ff087, ME: 0x005ff063
               zygote64  I  android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
         OpenGLRenderer  I  Initialized EGL, version 1.4
                         D  Swap behavior 2
               EventBus  D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
                         D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
                         D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
                         D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
                         D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
        CrashlyticsCore  W  No minidump data found in directory /data/user/0/com.thetransitapp.droid/files/.Fabric/com.crashlytics.sdk.android.crashlytics-ndk/native/1559970301793
                      t  I  Making Creator dynamically
         DynamiteModule  W  Failed to retrieve remote module version.
               zygote64  I  The ClassLoaderContext is a special shared library.
         DynamiteModule  W  IDynamite loader version < 2, falling back to getModuleVersion2
  GmsDynamiteLoaderImpl  D  unimplemented Method: getModuleVersion for com.google.android.gms.maps_dynamite
         DynamiteModule  W  Local module descriptor class for com.google.android.gms.maps_dynamite not found.
                         I  Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:0
                      t  E  Failed to load maps module, use legacy
                         E  com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
                         E  	at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:8)
                         E  	at com.google.android.gms.maps.a.t.c(Unknown Source:4)
                         E  	at com.google.android.gms.maps.a.t.b(Unknown Source:5)
                         E  	at com.google.android.gms.maps.a.t.a(Unknown Source:24)
                         E  	at com.google.android.gms.maps.d.a(Unknown Source:15)
                         E  	at com.google.android.gms.maps.h$b.i(Unknown Source:16)
                         E  	at com.google.android.gms.maps.h$b.a(Unknown Source:2)
                         E  	at com.google.android.gms.dynamic.a.a(Unknown Source:18)
                         E  	at com.google.android.gms.dynamic.a.a(Unknown Source:22)
                         E  	at com.google.android.gms.maps.h.onCreate(Unknown Source:5)
                         E  	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
                         E  	at androidx.fragment.app.h.a(FragmentManager.java:1418)
                         E  	at androidx.fragment.app.m.a(FragmentTransition.java:1195)
                         E  	at androidx.fragment.app.m.a(FragmentTransition.java:1078)
                         E  	at androidx.fragment.app.m.a(FragmentTransition.java:117)
                         E  	at androidx.fragment.app.h.a(FragmentManager.java:2408)
                         E  	at androidx.fragment.app.h.b(FragmentManager.java:2366)
                         E  	at androidx.fragment.app.h.i(FragmentManager.java:2273)
                         E  	at androidx.fragment.app.h$1.run(FragmentManager.java:733)
                         E  	at android.os.Handler.handleCallback(Handler.java:790)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E  	at java.lang.reflect.Method.invoke(Native Method)
                         E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
          GmsMapCreator  D  initV2
     GmsMultiArchLoader  D  Loading mapbox-gl from /data/user/0/com.thetransitapp.droid/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so
            ContextImpl  W  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
         GmsMapFragment  D  onTransact [unknown]: 15, android.os.Parcel@2a152d4, 0
  Mbgl-EGLConfigChooser  I  In emulator: false
                   Mbgl  I  {GLThread 506}[General]: GPU Identifier: Adreno (TM) 512
       Mbgl-HttpRequest  D  [HTTP] Request with response = 304: Not Modified
                         D  [HTTP] Request with response = 304: Not Modified
                         D  [HTTP] Request with response = 304: Not Modified
                         V  [HTTP] Request was successful (code = 200).
                         D  [HTTP] Request with response = 304: Not Modified
         GmsMapFragment  D  onTransact [unknown]: 16, android.os.Parcel@6e10876, 0
       Mbgl-HttpRequest  D  [HTTP] Request with response = 304: Not Modified
                         I  Request failed due to a connection error: Socket closed
                   Mbgl  W  {ransitapp.droid}[General]: Source 'mapbox-android-fill-source' is in use, cannot remove
                         W  {ransitapp.droid}[General]: Source 'mapbox-android-circle-source' is in use, cannot remove
                         W  {ransitapp.droid}[General]: Source 'mapbox-android-symbol-source' is in use, cannot remove
                         W  {ransitapp.droid}[General]: Source 'mapbox-android-line-source' is in use, cannot remove
        CrashlyticsCore  I  Crashlytics report upload complete: 5CFB41FD032A-0001-052A-AF0B34918E3A
               EventBus  D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
                         D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
                         D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
           RecyclerView  E  No adapter attached; skipping layout
               EventBus  D  No subscribers registered for event class com.thetransitapp.droid.shared.events.BannerEventBus$c
                         D  No subscribers registered for event class org.greenrobot.eventbus.f
           RecyclerView  E  No adapter attached; skipping layout
         GmsMapFragment  D  onTransact [unknown]: 15, android.os.Parcel@6e10876, 0
  Mbgl-EGLConfigChooser  I  In emulator: false
       Mbgl-HttpRequest  D  [HTTP] Request with response = 304: Not Modified
               EventBus  W  Subscriber to unregister was not registered before: class com.thetransitapp.droid.shared.activity.TransitActivity
         GmsMapFragment  D  onTransact [unknown]: 16, android.os.Parcel@6e10876, 0

                            Process com.thetransitapp.droid (PID: 3720) ended
```

**Comment by Torvin** [comment]
After updating to `0.2.8.17785-mapbox` I can see busses now, but not the bus routes

**Comment by Wangstaboi** [comment]
I find busses don't always show up, sometimes they'll be present and sometimes they won't.

**Comment by cedricr** [comment]
Still not working with /e/os 1.19, microg v0.3.0.233515

**Comment by Velocifyer** [comment]
Still not working

**Comment by ale5000-git** [comment]
Do you have the same issue with microG v0.3.9?

**Comment by Velocifyer** [comment]
> Do you have the same issue with microG v0.3.9?

Yes, but now random stores apear on the map witch doesnt happen with google play services

**Comment by Velocifyer** [comment]
Actually I can see busses when I have the route selected but I can't see bus routes

**Comment by Velocifyer** [comment]
Transit app says

> Unfortunately, if you don't use Google Play services on your phone, the map layer on Transit may not work correctly.
>
>At the moment we don't plan to provide support for phones without Play Services.

**Comment by TheSofter** [comment]
> Actually I can see busses when I have the route selected but I can't see bus routes

I have the same issue : https://community.e.foundation/t/display-issue-in-the-transit-app-com-thetransitapp-droid/79254

**Comment by Pandapip1** [comment]
```
❯ grep unimplemented transit-failure.log 
02-10 02:48:02.386 30136 30136 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.maps_core_dynamite
02-10 02:48:02.730 30136 30136 D GmsMapAbstract: unimplemented Method: setBuildingsEnabled
02-10 02:48:02.730 30136 30136 D GmsMapAbstract: unimplemented Method: setIndoorEnabled
02-10 02:48:02.731 30136 30136 D GmsMapsUi: unimplemented Method: setMyLocationButtonEnabled
02-10 02:48:02.731 30136 30136 D GmsMapsUi: unimplemented Method: setMapToolbarEnabled
02-10 02:48:02.731 30136 30136 D GmsMapsUi: unimplemented Method: setScrollGesturesEnabledDuringRotateOrZoom
02-10 02:48:02.740 30136 30318 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.tflite_dynamite
02-10 02:48:03.626 30136 30136 D GmsMap  : unimplemented Method: addTileOverlay
02-10 02:48:04.156 30136 30136 D GmsMap  : unimplemented Method: addTileOverlay
02-10 02:48:04.463 30136 30136 D GmsMapAbstract: unimplemented Method: setBuildingsEnabled
02-10 02:48:04.463 30136 30136 D GmsMapAbstract: unimplemented Method: setIndoorEnabled
02-10 02:48:04.499 30136 30136 D GmsMapsUi: unimplemented Method: setMyLocationButtonEnabled
02-10 02:48:04.499 30136 30136 D GmsMapsUi: unimplemented Method: setMapToolbarEnabled
02-10 02:48:04.499 30136 30136 D GmsMapsUi: unimplemented Method: setScrollGesturesEnabledDuringRotateOrZoom
02-10 02:48:04.732 30136 30136 D GmsMap  : unimplemented Method: addTileOverlay
02-10 02:50:54.170 30136 30728 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.tflite_dynamite
02-10 02:51:13.196 30836 30836 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.maps_core_dynamite
02-10 02:51:13.530 30836 30836 D GmsMapAbstract: unimplemented Method: setBuildingsEnabled
02-10 02:51:13.530 30836 30836 D GmsMapAbstract: unimplemented Method: setIndoorEnabled
02-10 02:51:13.532 30836 30836 D GmsMapsUi: unimplemented Method: setMyLocationButtonEnabled
02-10 02:51:13.532 30836 30836 D GmsMapsUi: unimplemented Method: setMapToolbarEnabled
02-10 02:51:13.532 30836 30836 D GmsMapsUi: unimplemented Method: setScrollGesturesEnabledDuringRotateOrZoom
02-10 02:51:13.571 30836 31031 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.tflite_dynamite
02-10 02:51:14.450 30836 30836 D GmsMap  : unimplemented Method: addTileOverlay
02-10 02:51:14.914 30836 30836 D GmsMap  : unimplemented Method: addTileOverlay
02-10 02:51:15.180 30836 30836 D GmsMapAbstract: unimplemented Method: setBuildingsEnabled
02-10 02:51:15.180 30836 30836 D GmsMapAbstract: unimplemented Method: setIndoorEnabled
02-10 02:51:15.180 30836 30836 D GmsMapsUi: unimplemented Method: setMyLocationButtonEnabled
02-10 02:51:15.180 30836 30836 D GmsMapsUi: unimplemented Method: setMapToolbarEnabled
02-10 02:51:15.180 30836 30836 D GmsMapsUi: unimplemented Method: setScrollGesturesEnabledDuringRotateOrZoom
02-10 02:51:15.501 30836 30836 D GmsMap  : unimplemented Method: addTileOverlay

❯ grep "Unknown field id" transit-failure.log
02-10 02:48:02.090  4277  8865 D SafeParcel: Unknown field id 4 in com.google.android.gms.common.Feature, skipping.
...
02-10 02:48:02.635 30136 30136 D SafeParcel: Unknown field id 23 in com.google.android.gms.maps.GoogleMapOptions, skipping.
...
02-10 02:48:04.600 30136 30136 D SafeParcel: Unknown field id 17 in com.google.android.gms.maps.model.MarkerOptions, skipping.
02-10 02:48:04.600 30136 30136 D SafeParcel: Unknown field id 18 in com.google.android.gms.maps.model.MarkerOptions, skipping.
02-10 02:48:04.600 30136 30136 D SafeParcel: Unknown field id 19 in com.google.android.gms.maps.model.MarkerOptions, skipping.
02-10 02:48:04.600 30136 30136 D SafeParcel: Unknown field id 21 in com.google.android.gms.maps.model.MarkerOptions, skipping.
...
```

A few other potentially noteworthy entries.

This gets repeated a few times:

```
02-10 02:48:04.454 30136 30136 W Resources: Drawable com.google.android.gms:drawable/maplibre_user_icon_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
02-10 02:48:04.454 30136 30136 W Resources: java.lang.RuntimeException
02-10 02:48:04.454 30136 30136 W Resources: 	at android.content.res.Resources.getDrawable(Resources.java:928)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:183)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:169)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LayerBitmapProvider.generateShadowBitmap(LayerBitmapProvider.java:30)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.styleBitmaps(LocationLayerController.java:162)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.applyStyle(LocationLayerController.java:98)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.initializeComponents(LocationLayerController.java:79)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LocationLayerController.<init>(LocationLayerController.java:72)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LocationComponent.initialize(LocationComponent.java:1092)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.location.LocationComponent.activateLocationComponent(LocationComponent.java:250)
02-10 02:48:04.454 30136 30136 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap$lambda$58(GoogleMap.kt:787)
02-10 02:48:04.454 30136 30136 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.$r8$lambda$cX0y-H2SH4CZt1TXY-dFHLjbrxI(Unknown Source:0)
02-10 02:48:04.454 30136 30136 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl$$ExternalSyntheticLambda3.onStyleLoaded(Unknown Source:4)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.maps.MapboxMap.getStyle(MapboxMap.java:120)
02-10 02:48:04.454 30136 30136 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap(GoogleMap.kt:698)
02-10 02:48:04.454 30136 30136 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.$r8$lambda$SopKtjQYYLh9Z4xMPOlCv4DMlsk(Unknown Source:0)
02-10 02:48:04.454 30136 30136 W Resources: 	at org.microg.gms.maps.mapbox.GoogleMapImpl$$ExternalSyntheticLambda6.onMapReady(Unknown Source:2)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1322)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1308)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:203)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:65)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:355)
02-10 02:48:04.454 30136 30136 W Resources: 	at android.os.Handler.handleCallback(Handler.java:991)
02-10 02:48:04.454 30136 30136 W Resources: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-10 02:48:04.454 30136 30136 W Resources: 	at android.os.Looper.loopOnce(Looper.java:232)
02-10 02:48:04.454 30136 30136 W Resources: 	at android.os.Looper.loop(Looper.java:317)
02-10 02:48:04.454 30136 30136 W Resources: 	at android.app.ActivityThread.main(ActivityThread.java:8934)
02-10 02:48:04.454 30136 30136 W Resources: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
02-10 02:48:04.454 30136 30136 W Resources: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

This is spammed constantly while the app is in use:

```
GmsCameraUpdate: newLatLngBounds
```
