### ISSUE TITLE
crash with Null Reference for Polygon

### ISSUE THREAD

**Issue by thrillfall** [microg/android_packages_apps_GmsCore#835]
I know @mar-v-in is in the making of the new maps implementation but i just want to contribute even if ze might already know about this.
crashing app: com.trafi.whitelabel.bvg (v1.0.1) 
gmscore version: 0.2.7.17455-beta-80
on lineageos a3y17lte

when i run the quite new app Jelbi (public and private transportation) it crashes when i select one of the offered vehicles from a list. Displaying markers seems to work fine so far.

This is the stacktrace when i click on a vehicle from a list

```
06-13 08:18:28.248 24390 24390 D SafeParcel: Unknown field num 8 in com.google.android.gms.maps.model.PolylineOptions, skipping.
06-13 08:18:28.248 24390 24390 D SafeParcel: Unknown field num 9 in com.google.android.gms.maps.model.PolylineOptions, skipping.
06-13 08:18:28.248 24390 24390 D SafeParcel: Unknown field num 10 in com.google.android.gms.maps.model.PolylineOptions, skipping.
06-13 08:18:28.248 24390 24390 D SafeParcel: Unknown field num 11 in com.google.android.gms.maps.model.PolylineOptions, skipping.
06-13 08:18:28.248 24390 24390 D SafeParcel: Unknown field num 12 in com.google.android.gms.maps.model.PolylineOptions, skipping.
06-13 08:18:28.747 24390 24390 D SafeParcel: Unknown field num 10 in com.google.android.gms.maps.model.PolygonOptions, skipping.
06-13 08:18:28.747 24390 24390 D SafeParcel: Unknown field num 11 in com.google.android.gms.maps.model.PolygonOptions, skipping.
06-13 08:18:28.747 24390 24390 D GmsMap  : unimplemented Method: addPolygon
06-13 08:18:28.748 24390 24390 D AndroidRuntime: Shutting down VM
06-13 08:18:28.749 24390 24390 E AndroidRuntime: FATAL EXCEPTION: main
06-13 08:18:28.749 24390 24390 E AndroidRuntime: Process: com.trafi.whitelabel.bvg, PID: 24390
06-13 08:18:28.749 24390 24390 E AndroidRuntime: java.lang.NullPointerException: null reference
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.a(SourceFile:1)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.google.android.gms.maps.model.Polygon.<init>(Unknown Source:3)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.google.android.gms.maps.GoogleMap.a(Unknown Source:8)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.google.GoogleMapProvider.a(SourceFile:18)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.MapView.a(SourceFile:37)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.AnnotationManager.a(SourceFile:42)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.AnnotationManager.a(SourceFile:2)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.e.a(SourceFile:2)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.e.a(SourceFile:1)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.trafi.map.b.run(SourceFile:1)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-13 08:18:28.749 24390 24390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by thrillfall** [comment]
Thank you @mar-v-in. The latest release (v0.2.8.17785) fixed the issue.
