### ISSUE TITLE
MapBox variant crashes when using QuickMap

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#839]
It is possible that this is fixed by https://github.com/microg/android_packages_apps_GmsCore/commit/73fd85a8c7ff2762dd615f3a5caa9d9f1db2b6f5

But just in case it is a different issue, I am getting a crash when using QuickMap. App opens okay (but with map in wrong location). If selecting an area of interest via pull down (e.g. Los Angeles) the app will crash.

OS: LineageOS 14.1 for microG
microG version: GmsCore-v0.2.7.17455-mapbox.apk
Application: https://play.google.com/store/apps/details?id=gov.caltrans.quickmap

```
06-15 16:50:56.449  5570  5588 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
06-15 16:50:56.449  5570  5588 D GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=11020000, packageName='gov.caltrans.quickmap', extras=Bundle[{client_name=locationServices}]}
06-15 16:50:56.568  3003  3421 I ActivityManager: Displayed gov.caltrans.quickmap/.MapsActivity: +798ms
06-15 16:50:56.695 10005 10005 D AndroidRuntime: Shutting down VM
06-15 16:50:56.699 10005 10005 E AndroidRuntime: FATAL EXCEPTION: main
06-15 16:50:56.699 10005 10005 E AndroidRuntime: Process: gov.caltrans.quickmap, PID: 10005
06-15 16:50:56.699 10005 10005 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(boolean)' on a null object reference
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at gov.caltrans.quickmap.MapsActivity.zoomToLocation(MapsActivity.java:931)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at gov.caltrans.quickmap.MapsActivity.onConnected(MapsActivity.java:1313)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzac.zzn(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.internal.zzbcp.zzm(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.internal.zzbcd.zzpY(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.internal.zzbcd.onConnected(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.internal.zzbcx.onConnected(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.internal.zzbbi.onConnected(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzaa.onConnected(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzn.zzrj(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.common.internal.zze.zzs(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzi.zzrk(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-15 16:50:56.699 10005 10005 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-15 16:50:56.704  3003  4857 W ActivityManager:   Force finishing activity gov.caltrans.quickmap/.MapsActivity

```

**Comment by paulbauriegel** [comment]
@n76 Besides the disaligned map it works on my phone :-)

Android: 9
microG version: GmsCore-v0.2.7.17455-mapbox-dirty https://github.com/microg/android_packages_apps_GmsCore/commit/73fd85a8c7ff2762dd615f3a5caa9d9f1db2b6f5

![LA](https://user-images.githubusercontent.com/20282916/60399236-d9387680-9b61-11e9-984e-59c5b7eb7949.jpg)

**Comment by n76** [comment]
@paulbauriegel Odd. I just tried it again and QuickMap still crashes when I use the MapBox variant. It does not crash if using the non-MapBox variant.

Your screen shot looks different than on my phone with respect to the location of options, location, etc. controls. Mine closely resembles the screen shot I see for the app when using Aurora to view Play Store apps. What version of QuickMap do you have? (Mine is 2.9.6 installed on a LineageOS with microG).

**Comment by paulbauriegel** [comment]
@n76 I was using a much older version of QuickMap (1.4...). The current version app is now crashing with the exception your log already shows. 
Yes I did build MicroG myself including the newest patches, but apparently that did not help.

**Comment by paulbauriegel** [comment]
Error-Logs from the new version:
[logcat_07-04-2019_11-21-02.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3358662/logcat_07-04-2019_11-21-02.txt)
