### ISSUE TITLE
Bus app crashes when trying to tap on a bus stop

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#852]
```
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.dyancat.bus, PID: 30664
                         E  java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.b.b.asBinder()' on a null object reference
                         E  	at com.google.android.gms.b.d.a(Unknown Source:9)
                         E  	at com.google.android.gms.maps.model.f.f(Unknown Source:6)
                         E  	at com.dyancat.bus.ui.map.realtime.e.a(Unknown Source:5)
                         E  	at com.google.android.gms.maps.m.a(Unknown Source:7)
                         E  	at com.google.android.gms.maps.a.n.a(Unknown Source:11)
                         E  	at com.google.android.gms.internal.g.d.onTransact(Unknown Source:22)
                         E  	at android.os.Binder.transact(Binder.java:627)
                         E  	at com.google.android.gms.maps.internal.IOnMarkerClickListener$Stub$Proxy.onMarkerClick(IOnMarkerClickListener.java:85)
                         E  	at org.microg.gms.maps.mapbox.GoogleMapImpl$initMap$1$$special$$inlined$let$lambda$1.onAnnotationClick(GoogleMap.kt:389)
                         E  	at org.microg.gms.maps.mapbox.GoogleMapImpl$initMap$1$$special$$inlined$let$lambda$1.onAnnotationClick(GoogleMap.kt:389)
                         E  	at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver.onMapClick(AnnotationManager.java:372)
                         E  	at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:936)
                         E  	at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:347)
                         E  	at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
                         E  	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E  	at java.lang.reflect.Method.invoke(Native Method)
                         E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
      UncaughtException  E  java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.b.b.asBinder()' on a null object reference
                         E  	at com.google.android.gms.b.d.a(Unknown Source:9)
                         E  	at com.google.android.gms.maps.model.f.f(Unknown Source:6)
                         E  	at com.dyancat.bus.ui.map.realtime.e.a(Unknown Source:5)
                         E  	at com.google.android.gms.maps.m.a(Unknown Source:7)
                         E  	at com.google.android.gms.maps.a.n.a(Unknown Source:11)
                         E  	at com.google.android.gms.internal.g.d.onTransact(Unknown Source:22)
                         E  	at android.os.Binder.transact(Binder.java:627)
                         E  	at com.google.android.gms.maps.internal.IOnMarkerClickListener$Stub$Proxy.onMarkerClick(IOnMarkerClickListener.java:85)
                         E  	at org.microg.gms.maps.mapbox.GoogleMapImpl$initMap$1$$special$$inlined$let$lambda$1.onAnnotationClick(GoogleMap.kt:389)
                         E  	at org.microg.gms.maps.mapbox.GoogleMapImpl$initMap$1$$special$$inlined$let$lambda$1.onAnnotationClick(GoogleMap.kt:389)
                         E  	at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver.onMapClick(AnnotationManager.java:372)
                         E  	at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:936)
                         E  	at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:347)
                         E  	at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
                         E  	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E  	at java.lang.reflect.Method.invoke(Native Method)
                         E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Torvin** [comment]
Doesn't crash anymore after updating to `0.2.8.17785-mapbox`, now nothing happens at all. I cannot pick a bus stop on the map.
