### ISSUE TITLE
Bolt crashes immediately after startup

### ISSUE THREAD

**Issue by isthisme** [microg/android_packages_apps_GmsCore#858]
I'm trying to use a taxi app called Bolt but after startup it crashes a few seconds later.  I'm currently using this rom version: 16.0-20190625-microG-oneplus3.  I've inserted a logcat below:

`[07-01 18:20:14.953 3936:3936 E/v]
Failed to load maps module, use legacy
com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:29)
	at com.google.android.gms.maps.a.v.c(Unknown Source:2)
	at com.google.android.gms.maps.a.v.b(Unknown Source:2)
	at com.google.android.gms.maps.a.v.a(Unknown Source:5)
	at com.google.android.gms.maps.d.a(Unknown Source:4)
	at com.google.android.gms.maps.SupportMapFragment$b.i(Unknown Source:2)
	at com.google.android.gms.maps.SupportMapFragment$b.a(Unknown Source:2)
	at com.google.android.gms.dynamic.a.a(Unknown Source:12)
	at com.google.android.gms.dynamic.a.a(Unknown Source:13)
	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source:9)
	at androidx.fragment.app.Fragment.onInflate(Fragment.java:4)
	at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManager.java:25)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at ee.mtakso.client.view.a.l.inflate(BoltLayoutInflater.kt:1)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at ee.mtakso.client.view.common.map.TaxifyMapFragment.onCreateView(TaxifyMapFragment.java:1)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:6)
	at androidx.fragment.app.FragmentManagerImpl.a(FragmentManager.java:226)
	at androidx.fragment.app.FragmentManagerImpl.h(FragmentManager.java:6)
	at androidx.fragment.app.FragmentManagerImpl.a(FragmentManager.java:327)
	at androidx.fragment.app.a.f(BackStackRecord.java:25)
	at androidx.fragment.app.FragmentManagerImpl.a(FragmentManager.java:456)
	at androidx.fragment.app.FragmentManagerImpl.b(FragmentManager.java:78)
	at androidx.fragment.app.FragmentManagerImpl.c(FragmentManager.java:47)
	at androidx.fragment.app.FragmentManagerImpl.r(FragmentManager.java:4)
	at androidx.fragment.app.k.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

`

By the way you can find the app here: https://play.google.com/store/apps/details?id=ee.mtakso.client

**Comment by mar-v-in** [comment]
A `DynamiteModule$LoadingException` being logged is usually not going to cause any issues. Please provide more logs. If the application crashes, there are message logged right after a line saying "FATAL EXCEPTION" containing the actually relevant details.

**Comment by isthisme** [comment]
The only fatal I can find from the apo is this:
`Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 20852 (e.mtakso.client), pid 20852 (e.mtakso.client)`

**Comment by Eerovil** [comment]
I tried the Bolt app (`ee.mtakso.client`), no problems launching (didn't try to register my phone number though).

**Comment by isthisme** [comment]
@Eerovil I should have specified I can get through the registration but the app crashes afterwards when it begins actually looking for taxis.

**Comment by chlarsen** [comment]
Exactly my problem, too. Once registered, and trying to access location data, it goes belly-up. 
No problems with others, like Grab, Uber,...

**Comment by rfvermut** [comment]
I'm having similar error:

```
E/AndroidRuntime(24452): FATAL EXCEPTION: main
E/AndroidRuntime(24452): Process: ee.mtakso.client, PID: 24452
E/AndroidRuntime(24452): java.util.ConcurrentModificationException
E/AndroidRuntime(24452):     at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap(GoogleMap.kt:540)
E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl.access$initMap(GoogleMap.kt:61)
E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:459)
E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:61)
E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapKt$sam$com_mapbox_mapboxsdk_maps_OnMapReadyCallback$0.onMapReady(GoogleMap.kt)
E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1154)
E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1140)
E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:205)
E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:62)
E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:320)
E/AndroidRuntime(24452):     at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(24452):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(24452):     at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(24452):     at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(24452):     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24452):     at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(24452):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
E/AndroidRuntime(24452):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
E/AndroidRuntime(24452):     at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(21329):   Force finishing activity ee.mtakso.client/.view.orderflow.OrderFlowActivity

```

**Comment by tempte** [comment]
ROM Lineage 17.1 (Android 10), microG services 0.2.11.202414, Bolt (ee.mtakso.client) ver. CA.6.03

Bolt app starts, sign in also works, but then it shows "Enable location services" dialog and after choosing "Turn on location services" (everything was turned on even before the dialog) - notifies that "Bolt won`t run without Google Play services, which are not supported by your device." So no map opens as the app can`t catch location.
