### ISSUE TITLE
Crash of MOIA app when setting manual address

### ISSUE THREAD

**Issue by chris42** [microg/android_packages_apps_GmsCore#869]
I just tested 0.2.8.17785-mapbox (official from website) with MOIA.
App starts up fine and map is displayed. However when entering an address to start while location is disabled, MOIA crashes.
It looks similar to #835, however this seems to look for Polyline.
I found two exceptions in the log.

The final crash:
```
07-05 15:44:27.041 10145 10145 D AndroidRuntime: Shutting down VM
07-05 15:44:27.042 10145 10145 E AndroidRuntime: FATAL EXCEPTION: main
07-05 15:44:27.042 10145 10145 E AndroidRuntime: Process: io.moia.neptune, PID: 10145
07-05 15:44:27.042 10145 10145 E AndroidRuntime: java.lang.NullPointerException: null reference
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.a(Unknown Source:1)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.android.gms.maps.model.Polyline.<init>(Unknown Source:2)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.android.gms.maps.GoogleMap.a(Unknown Source:8)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.Renderer.a(Renderer.java:98)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.Renderer.a(Renderer.java:52)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.Renderer.a(Renderer.java:33)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.geojson.GeoJsonRenderer.a(GeoJsonRenderer.java:1)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.geojson.GeoJsonRenderer.e(GeoJsonRenderer.java:4)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.Layer.a(Layer.java:3)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.google.maps.android.data.geojson.GeoJsonLayer.c(GeoJsonLayer.java:1)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at io.moia.neptune.common.map.MapHelper.b(MapHelper.java:27)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at io.moia.neptune.trip.booking.fragment.TripBookingFragment.b(TripBookingFragment.java:9)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at io.moia.neptune.trip.booking.fragment.TripBookingFragment.onViewStateRestored(TripBookingFragment.java:13)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:5)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.a(FragmentManager.java:242)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.i(FragmentManager.java:6)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.a(FragmentManager.java:329)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.a.b(BackStackRecord.java:31)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.a(FragmentManager.java:442)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.b(FragmentManager.java:68)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.c(FragmentManager.java:52)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.n.p(FragmentManager.java:8)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at androidx.fragment.app.h.run(FragmentManager.java:1)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-05 15:44:27.042 10145 10145 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

A bit before there is another exception in the logs, but it seems not to crash the app. Maybe not connected, but nevertheless:
```
07-05 15:44:14.733 10145 10145 I zzbz    : Making Creator dynamically
07-05 15:44:14.745  2803  2815 D GmsChimeraSpoof: query: content://com.google.android.gms.chimera/api_force_staging/com.google.android.gms.maps_dynamite
07-05 15:44:14.747 10145 10145 W DynamiteModule: Failed to retrieve remote module version.
07-05 15:44:14.763 10145 10145 I io.moia.neptun: The ClassLoaderContext is a special shared library.
07-05 15:44:14.773 10145 10145 W DynamiteModule: IDynamite loader version < 2, falling back to getModuleVersion2
07-05 15:44:14.774 10145 10145 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for com.google.android.gms.maps_dynamite
07-05 15:44:14.776 10145 10145 W DynamiteModule: Local module descriptor class for com.google.android.gms.maps_dynamite not found.
07-05 15:44:14.776 10145 10145 I DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:0
07-05 15:44:14.777 10145 10145 E zzbz    : Failed to load maps module, use legacy
07-05 15:44:14.777 10145 10145 E zzbz    : com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:29)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.internal.zzbz.c(Unknown Source:2)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.internal.zzbz.b(Unknown Source:2)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.internal.zzbz.a(Unknown Source:5)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.MapsInitializer.a(Unknown Source:4)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.SupportMapFragment$b.h(Unknown Source:2)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.SupportMapFragment$b.a(Unknown Source:2)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.a(Unknown Source:11)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.a(Unknown Source:12)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source:9)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.Fragment.onInflate(Fragment.java:4)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.onCreateView(FragmentManager.java:25)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:963)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.databinding.DataBindingUtil.a(DataBindingUtil.java:3)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.databinding.DataBindingUtil.a(DataBindingUtil.java:1)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at io.moia.neptune.trip.booking.fragment.TripBookingFragment.onCreateView(TripBookingFragment.java:1)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:6)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.a(FragmentManager.java:228)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.i(FragmentManager.java:6)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.a(FragmentManager.java:329)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.a.g(BackStackRecord.java:24)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.a(FragmentManager.java:444)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.b(FragmentManager.java:68)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.c(FragmentManager.java:52)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.p(FragmentManager.java:8)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.e(FragmentManager.java:15)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.n.f(FragmentManager.java:7)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.FragmentController.a(FragmentController.java:6)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:5)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.Activity.performStart(Activity.java:7165)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.os.Looper.loop(Looper.java:193)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at java.lang.reflect.Method.invoke(Native Method)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-05 15:44:14.777 10145 10145 E zzbz    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-05 15:44:14.784 10145 10145 D GmsMapCreator: initV2
07-05 15:44:14.800 10145 10145 D GmsMapFragment: onInflate: lat/lng: (0.0,0.0)
07-05 15:44:14.802 10145 10145 D GmsMapFragment: onCreate: lat/lng: (0.0,0.0)
07-05 15:44:14.818 10145 10145 D GmsMultiArchLoader: Loading mapbox-gl from /data/user/0/io.moia.neptune/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so
07-05 15:44:14.849 10145 10145 D GmsMapFragment: onCreateView: lat/lng: (0.0,0.0)
```

**Comment by ale5000-git** [comment]
Could you please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry?

**Comment by chris42** [comment]
Nope, no change. I get the same exception on polyline as above.

**Comment by chris42** [comment]
Just tried 0.2.9.19420 and Moia still crashes. However checking the logs it does not seem to be the polyline anymore, but something with geocoding, etc.
Will wait to investigate further until the overall unifiednlp crashes #964

**Comment by chris42** [comment]
The polyline error is gone, however the app is still crashing (see log). It happens when you try to manually set an address in the app.
[moia_log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3776086/moia_log.txt)

Using location services, it does not crash, but wasn't able to test a full ride yet.

**Comment by ale5000-git** [comment]
It may not fix your problem but the version 0.2.9 is bugged, update to 0.2.10

**Comment by chris42** [comment]
Already did, still crashing...

**Comment by chris42** [comment]
For some reason the newest version of MOIA (v20.5.201.2005201) seems to work now. The crash on selecting a manual address is gone.
