### ISSUE TITLE
[Mapbox] Starbucks app crashes

### ISSUE THREAD

**Issue by benwaffle** [microg/android_packages_apps_GmsCore#870]
Reproduce:
1. Open starbucks
2. Go to stores
3. Wait a few seconds 

```
FATAL EXCEPTION: androidmapsapi-ula-1
Process: com.starbucks.mobilecard, PID: 18881
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] com.google.android.gms.common.internal.CertData.getBytes()' on a null object reference
	at com.google.android.gms.common.GoogleCertificatesImpl.isGoogleOrPlatformSigned(GoogleCertificatesImpl.java:58)
	at com.google.android.gms.common.internal.IGoogleCertificatesApi$Stub.onTransact(IGoogleCertificatesApi.java:98)
	at android.os.Binder.transact(Binder.java:667)
	at com.google.android.m4b.maps.c.a.a(:10)
	at com.google.android.m4b.maps.m.au.a(:6)
	at com.google.android.m4b.maps.h.i.a(:30)
	at com.google.android.m4b.maps.h.i.a(:22)
	at com.google.android.m4b.maps.h.u.a(:34)
	at com.google.android.m4b.maps.h.u.a(:19)
	at com.google.android.m4b.maps.bo.ep.a(:110)
	at com.google.android.m4b.maps.bo.et.a(:4)
	at com.google.android.m4b.maps.bo.er.run(:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by CircuitSerialKiller** [comment]
I'm having this error in the latest 7/3/2019 v0.2.8.17785 with microGGoogleQuickSearchBox  (using offline only):
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] com.google.android.gms.common.internal.CertData.getBytes()' on a null object reference

**Comment by ale5000-git** [comment]
This is one of the problems fixed after the release.
Please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry.

**Comment by CircuitSerialKiller** [comment]
@ale5000-git. I'm going to be setting up a new phone hopefully this weekend just for testing. 
BTW thanks a ton for your contributions to this project!

Slightly off topic, but quick question that may help others:
I have been recompiling googlequicksearchbox (need it for voice recognition) to remove Internet permissions so I could ensure it's not sending speech data to the cloud. I see that with newer versions of microG that googlequicksearchbox crashes, even older versions, with missing EXTENDED_ACCESS permissions. I'm guessing this is due to microG's signature validation for EXTENDED_ACCESS  permissions discussed [here ](https://github.com/microg/android_packages_apps_GmsCore/issues/144) and code [here](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java#L48), but I'm not sure what changed in the latest version that I wasn't having an issue before. 

With the updated build above, would I still end up with googlequicksearchbox crashing even with the original googlequicksearchbox apk since I don't see the signature for it in the KNOWN_GOOGLE_PACKAGES HashMap?
