### ISSUE TITLE
Crash for inability to open database

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#876]
microG should handle this case:

```
 07-07 21:30:44.069  8394: 8394 W/ContextImpl ]
Failed to ensure /data/user/0/com.google.android.gms/databases: mkdir failed: ENOENT (No such file or directory)

[ 07-07 21:30:44.069  8394: 8394 E/SQLiteLog ]
(14) cannot open file at line 32460 of [69906880ce]


[ 07-07 21:30:44.069  8394: 8394 E/SQLiteLog ]
(14) os_unix.c:32460: (2) open(/data/user/0/com.google.android.gms/databases/gcmstatus) - 


[ 07-07 21:30:44.072  8394: 8394 E/SQLiteDatabase ]
Failed to open database '/data/user/0/com.google.android.gms/databases/gcmstatus'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
	at org.microg.gms.gcm.GcmDatabase.getAppList(GcmDatabase.java:116)
	at org.microg.gms.ui.GcmFragment.updateContent(GcmFragment.java:151)
	at org.microg.gms.ui.GcmFragment.onCreatePreferencesFix(GcmFragment.java:83)
	at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:62)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

[ 07-07 21:30:44.073  8394: 8394 D/AndroidRuntime ]
Shutting down VM

[ 07-07 21:30:44.075  8394: 8394 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 8394
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.GcmFragment$AsActivity}: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
	at org.microg.gms.gcm.GcmDatabase.getAppList(GcmDatabase.java:116)
	at org.microg.gms.ui.GcmFragment.updateContent(GcmFragment.java:151)
	at org.microg.gms.ui.GcmFragment.onCreatePreferencesFix(GcmFragment.java:83)
	at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:62)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
	... 9 more

[ 07-07 21:30:44.085  2365: 2921 W/ActivityManager ]
  Force finishing activity com.google.android.gms/org.microg.gms.ui.GcmFragment$AsActivity

[ 07-07 21:30:44.093  2365: 2921 W/ActivityManager ]
  Force finishing activity com.google.android.gms/org.microg.gms.ui.SettingsActivity
```

**Comment by mar-v-in** [comment]
Not sure if this is really something to be handled by microG. The issue is directly in the first line:
```
Failed to ensure /data/user/0/com.google.android.gms/databases: mkdir failed: ENOENT (No such file or directory)
```
This should really never happen: the only way for ENOENT is that `/data/user/0/com.google.android.gms` does not exist. This directory is created by the OS automatically and it being not present will cause tons of issues. We cannot just create that directory from microG itself, as that would require root access.

How did you reach that error?

**Comment by ale5000-git** [comment]
To completely reset the data I have manually deleted them, then reset them again inside Android settings and killed the app.
I have supposed that they were recreated when the app was run again but if it isn't supposed to be like this then it is fine.

**Comment by ildar** [comment]
It's recreated on reboot only
