### ISSUE TITLE
Apps crash with IllegalArgumentException: cipherSuite TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 is not supported in OkHttp

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#877]
After updating to `0.2.8.17785-mapbox` several apps started to crash with `cipherSuite TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 is not supported`. Here is an example from Uber:

```
         AndroidRuntime  E  FATAL EXCEPTION: OkHttp Dispatcher
                         E  Process: com.ubercab, PID: 24686
                         E  java.lang.IllegalArgumentException: cipherSuite TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 is not supported.
                         E      at org.conscrypt.NativeCrypto.checkEnabledCipherSuites(NativeCrypto.java:1082)
                         E      at org.conscrypt.SSLParametersImpl.setEnabledCipherSuites(SSLParametersImpl.java:221)
                         E      at org.conscrypt.ConscryptFileDescriptorSocket.setEnabledCipherSuites(ConscryptFileDescriptorSocket.java:730)
                         E      at okhttp3.ConnectionSpec.apply(ConnectionSpec.java:158)
                         E      at okhttp3.OkHttpClient$1.apply(OkHttpClient.java:180)
                         E      at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:79)
                         E      at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:312)
                         E      at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)                         E      at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
                         E      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
                         E      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
                         E      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
                         E      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                         E      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                         E      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                         E      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
                         E      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
                         E      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                         E      at java.lang.Thread.run(Thread.java:764)

```

Same happens to AccuWeather:

```
         AndroidRuntime  E  FATAL EXCEPTION: OkHttp Dispatcher
                         E  Process: com.accuweather.android, PID: 25496
                         E  java.lang.IllegalArgumentException: cipherSuite TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 is not supported.
                         E      at org.conscrypt.NativeCrypto.checkEnabledCipherSuites(NativeCrypto.java:1082)
                         E      at org.conscrypt.SSLParametersImpl.setEnabledCipherSuites(SSLParametersImpl.java:221)
                         E      at org.conscrypt.ConscryptFileDescriptorSocket.setEnabledCipherSuites(ConscryptFileDescriptorSocket.java:730)
                         E      at okhttp3.ConnectionSpec.apply(ConnectionSpec.java:158)
                         E      at okhttp3.OkHttpClient$1.apply(OkHttpClient.java:180)
                         E      at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:79)
                         E      at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:312)
                         E      at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
                         E      at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
                         E      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
                         E      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
                         E      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
                         E      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                         E      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                         E      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                         E      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
                         E      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
                         E      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                         E      at java.lang.Thread.run(Thread.java:764)
```

**Comment by benwaffle** [comment]
fixed in https://github.com/microg/android_packages_apps_GmsCore/issues/863

**Comment by Torvin** [comment]
Thank you! Sorry, couldn't find that issue for some reason
