### ISSUE TITLE
GmsAuthProvider: Not granting access to

### ISSUE THREAD

**Issue by ibleedbinari** [microg/android_packages_apps_GmsCore#89]
Using: Google Classroom, Google Fit
Tested on: GmsCore 0.2.0 Nightly

Multiple Google apps appear to be getting denied access to Google accounts. The log line appears to be coming from microG stating that they were denied access.

Logcat: [logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/120767/logcat.txt)

**Comment by ibleedbinari** [comment]
For Google Fit:
```
02-07 11:20:51.421 W/GmsAuthProvider(23647): Not granting access to [com.google.android.apps.fitness], signature: 24bb24c05e47e0aefa68a58a766179d9b613a600

02-07 11:20:51.428 E/AndroidRuntime(7137): FATAL EXCEPTION: main
02-07 11:20:51.428 E/AndroidRuntime(7137): Process: com.google.android.apps.fitness, PID: 7137
02-07 11:20:51.428 E/AndroidRuntime(7137): java.lang.SecurityException: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.os.Parcel.readException(Parcel.java:1620)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.content.ContentProviderClient.call(ContentProviderClient.java:437)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at aou.c(Unknown Source)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at aou.b(Unknown Source)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.google.android.libraries.gcoreclient.auth.impl.GcoreGoogleAuthUtilImpl.a(PG:39)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.google.android.apps.fitness.account.FitnessAccountManager.c(PG:173)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.google.android.apps.fitness.welcome.selectuser.SelectUserFragment.b(PG:103)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.google.android.apps.fitness.welcome.selectuser.SelectUserFragment.n(PG:212)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at fd.a(PG:8005)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at fd.a(PG:1248)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at ek.run(PG:738)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at fd.g(PG:1613)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at fd.b(PG:570)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at fo.a(PG:163)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.support.v4.view.ViewPager.c(PG:1106)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.support.v4.view.ViewPager.c(PG:952)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.support.v4.view.ViewPager.onMeasure(PG:1474)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.View.measure(View.java:18797)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(PG:135)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.View.measure(View.java:18797)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.View.measure(View.java:18797)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.View.measure(View.java:18797)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.View.measure(View.java:18797)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.View.measure(View.java:18797)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.os.Handler.handleCallback(Handler.java:739)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.os.Looper.loop(Looper.java:148)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at android.app.ActivityThread.main(ActivityThread.java:5466)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at java.lang.reflect.Method.invoke(Native Method)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-07 11:20:51.428 E/AndroidRuntime(7137): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by mar-v-in** [comment]
Is this an Android 6.0 system. If so, please grant Contacts permission to the apps (required to read account list) in system settings.

**Comment by ibleedbinari** [comment]
This is an Android 6.0 system. microG already has "Contacts", but neither app (Classroom nor Fit) request "Contacts", so I cannot grant it to them.

**Comment by ibleedbinari** [comment]
I can confirm or works now. Thanks!

**Comment by TheInitializer** [comment]
This seems to still not be working with Google Classroom on Android 9.0 and microG Services Core 0.2.6-13280-dirty.

**Comment by DevPre24** [comment]
This is still an issue on microG Services Core 0.2.6-14797-dirty113.

**Comment by PorygonZRocks** [comment]
Version [3.5.212.04](https://www.apkmirror.com/apk/google-inc/classroom/classroom-3-5-212-04-release/) of Classroom works for me, but nothing newer. I'm guessing maybe they changed something in the app after that point and it's no longer compatible?
