### ISSUE TITLE
[Mapbox] Eurail/Interrail Rail Planner app crashes

### ISSUE THREAD

**Issue by johannesneyer** [microg/android_packages_apps_GmsCore#894]
v0.2.8.17785-mapbox

to reproduce:
1. open app
2. search for connection
3. click on one of the results

I get the same error on another local train app (oebb scotty).

```
[07-17 13:02:10.455 10428:10428 D/GmsMultiArchLoader]
Loading mapbox-gl from /data/user/0/org.eurail.railplanner/cache/.gmscore/lib/armeabi/libmapbox-gl.so

[07-17 13:02:10.457 10428:10428 E/Mbgl-LibraryLoader]
Failed to load native shared library.
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/org.eurail.railplanner/cache/.gmscore/lib/armeabi/libmapbox-gl.so" not found
	at java.lang.Runtime.load0(Runtime.java:928)
	at java.lang.System.load(System.java:1633)
	at org.microg.gms.maps.mapbox.utils.MultiArchLoader.load(MultiArchLoader.kt:48)
	at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
	at org.microg.gms.maps.mapbox.GoogleMapImpl.<init>(GoogleMap.kt:103)
	at org.microg.gms.maps.mapbox.MapViewImpl.onCreate(MapView.kt:37)
	at com.google.android.gms.maps.internal.IMapViewDelegate$Stub.onTransact(IMapViewDelegate.java:64)
	at org.microg.gms.maps.mapbox.MapViewImpl.onTransact(MapView.kt:59)
	at android.os.Binder.transact(Binder.java:667)
	at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
	at com.google.android.gms.maps.internal.zzk.onCreate(Unknown Source:17)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source:8)
	at com.google.android.gms.dynamic.zac.zaa(Unknown Source:3)
	at com.google.android.gms.dynamic.zaa.onDelegateCreated(Unknown Source:4)
	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source:16)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(Unknown Source:18)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source:22)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source:26)
	at nl.elastique.eurail.ui.map.SimpleTravelMapFragment.onCreateView(SimpleTravelMapFragment.java:77)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:168)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23190)

[07-17 13:02:10.460 10428:10428 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: org.eurail.railplanner, PID: 10428
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
	at org.microg.gms.maps.mapbox.GoogleMapImpl.<init>(GoogleMap.kt:103)
	at org.microg.gms.maps.mapbox.MapViewImpl.onCreate(MapView.kt:37)
	at com.google.android.gms.maps.internal.IMapViewDelegate$Stub.onTransact(IMapViewDelegate.java:64)
	at org.microg.gms.maps.mapbox.MapViewImpl.onTransact(MapView.kt:59)
	at android.os.Binder.transact(Binder.java:667)
	at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
	at com.google.android.gms.maps.internal.zzk.onCreate(Unknown Source:17)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source:8)
	at com.google.android.gms.dynamic.zac.zaa(Unknown Source:3)
	at com.google.android.gms.dynamic.zaa.onDelegateCreated(Unknown Source:4)
	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source:16)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(Unknown Source:18)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source:22)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source:26)
	at nl.elastique.eurail.ui.map.SimpleTravelMapFragment.onCreateView(SimpleTravelMapFragment.java:77)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:168)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23190)
```

**Comment by ale5000-git** [comment]
This is one of the problem fixed after the release.
Please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry.

**Comment by johannesneyer** [comment]
Ah cool works, thanks.
