### ISSUE TITLE
Problem creating org.conscrypt.OpenSSLSocketFactoryImpl (conscrypt?)

### ISSUE THREAD

**Issue by rfvermut** [microg/android_packages_apps_GmsCore#901]
Short version:

```
D/dalvikvm(20305): newInstance failed: Lorg/conscrypt/OpenSSLSocketFactoryImpl; not accessible to Ljavax/net/ssl/SSLSocketFactory;
E/System  (20305): Problem creating org.conscrypt.OpenSSLSocketFactoryImpl
E/System  (20305): java.lang.IllegalAccessException: access to class not allowed
E/System  (20305):   at java.lang.Class.newInstanceImpl(Native Method)
E/System  (20305):   at java.lang.Class.newInstance(Class.java:1208)
E/System  (20305):   at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:56)
E/System  (20305):   at javax.net.ssl.HttpsURLConnection$NoPreloadHolder.<clinit>(HttpsURLConnection.java:114)
E/System  (20305):   at javax.net.ssl.HttpsURLConnection.setDefaultSSLSocketFactory(HttpsURLConnection.java:154)
E/System  (20305):   at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(ProviderInstallerImpl.java:48)
E/System  (20305):   at java.lang.reflect.Method.invokeNative(Native Method)
E/System  (20305):   at java.lang.reflect.Method.invoke(Method.java:515)
E/System  (20305):   at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
E/System  (20305):   at ee.cyber.smartid.SmartIdService.b(SmartIdService.java:728)
E/System  (20305):   at ee.cyber.smartid.SmartIdService.createRequestClient(SmartIdService.java:683)
E/System  (20305):   at ee.cyber.smartid.network.SmartIdAPI.<init>(SmartIdAPI.java:196)
E/System  (20305):   at ee.cyber.smartid.network.SmartIdAPI.createNewInstance(SmartIdAPI.java:171)
E/System  (20305):   at ee.cyber.smartid.SmartIdService$1.run(SmartIdService.java:932)
E/System  (20305):   at java.lang.Thread.run(Thread.java:841)
D/GmsProviderInstaller(20305): SSL provider installed
```

-----
Full logs:

```
D/ProcessState(25245): getContextObject - ALIEN_ID=[alien]
I/AlienService(21329): startApp () className = com.smart_id/com.stagnationlab.sk.MainActivity
I/AlienService(21329): startApp with intent : Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=com.smart_id/com.stagnationlab.sk.MainActivity }
I/AlienService(21329): startApp with intent : send msg!
I/AlienService(21329): handleStartApp()
D/FakeHome(21489): onPause
I/AlienService(21329): showAlienWindow()
W/WindowManager(21329): Token{e760b068 ActivityRecord{e760af08 u0 com.smart_id/com.stagnationlab.sk.MainActivity t22}} failed creating starting window
W/WindowManager(21329): java.lang.RuntimeException: Binary XML file line #31: You must supply a layout_height attribute.
W/WindowManager(21329):      at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
W/WindowManager(21329):      at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5949)
W/WindowManager(21329):      at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6117)
W/WindowManager(21329):      at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1831)
W/WindowManager(21329):      at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1743)
W/WindowManager(21329):      at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
W/WindowManager(21329):      at android.view.LayoutInflater.rInflate(LayoutInflater.java:757)
W/WindowManager(21329):      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
W/WindowManager(21329):      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
W/WindowManager(21329):      at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
W/WindowManager(21329):      at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3022)
W/WindowManager(21329):      at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085)
W/WindowManager(21329):      at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
W/WindowManager(21329):      at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1716)
W/WindowManager(21329):      at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7198)
W/WindowManager(21329):      at android.os.Handler.dispatchMessage(Handler.java:102)
W/WindowManager(21329):      at android.os.Looper.loop(Looper.java:136)
W/WindowManager(21329):      at android.os.HandlerThread.run(HandlerThread.java:61)
I/AlienService(21329): handleShowAlienWindow() surfaceId = 18,packageName = com.smart_id,appTitle = Smart-ID
I/AlienServiceJNI(21329): showAlienWindow surfaceId = 18
D/WLAlienRuntime(21329): showAlienWindow, mAlienState = 3 -- package=com.smart_id, title=Smart-ID
D/WLAlienSurface(21329): alien_leave_power_save_mode
D/AlienSensor(21329): ......activate 0......
D/IAlienSensorService(21329): ......activate start......
I/ActivityManager(21329): START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.smart_id/com.stagnationlab.sk.MainActivity} from pid 21329
D/ActivityManager(21329): Set surfaceId of task { TaskRecord{e763e0e8 #22 surfaceId = 0 A=com.smart_id U=0 sz=0} } to 18
D/ActivityManager(21329): getTopRunningSurface() r = ActivityRecord{e760af08 u0 com.smart_id/com.stagnationlab.sk.MainActivity t22}
D/ActivityManager(21329): getPackageNameOfTopRunningSurface() r = ActivityRecord{e760af08 u0 com.smart_id/com.stagnationlab.sk.MainActivity t22}
D/ActivityManager(21329): getAppNameOfTopRunningSurface() r = ActivityRecord{e760af08 u0 com.smart_id/com.stagnationlab.sk.MainActivity t22}
D/IAlienSensorService(21184): ......ACTIVATE start......
D/AlienSensorService(21184): ......activate......
D/IAlienSensorService(21184): ......ACTIVATE end......
D/AlienSensorService(21184): ......activate 0 accelerometer......
D/IAlienSensorService(21329): ......activate end......
D/AlienPowerManagerInterface(21329): alienPMEnableWakeLocks -> true
D/WLAlienRuntime(21329): finishStateChange enter
D/AlienRuntime(21329): WLAlienRuntimeExt::createSurface
D/WLAlienSurface(21329): WLAlienSurface ( 1080 x 1920 )
D/AlienRuntime(21329): WLAlienRuntimeExt::getAlienManager
D/WLAlienRuntime(21329): Surface created. Leave GPS power save mode.
D/AlienGps(21329): setPowerSavingMode enabled=0
D/WLAlienRuntime(21329): finishStateChange exit
D/WLAlienSurface(21329): onFullscreen(), mId(18), mSurfaceState = 0
D/WLAlienSurface(21329): alien_leave_power_save_mode
D/AlienSensor(21329): ......activate 0......
D/IAlienSensorService(21329): ......activate start......
D/IAlienSensorService(21184): ......ACTIVATE start......
D/AlienSensorService(21184): ......activate......
D/IAlienSensorService(21184): ......ACTIVATE end......
D/AlienSensorService(21184): ......activate 0 accelerometer......
D/IAlienSensorService(21329): ......activate end......
D/AlienPowerManagerInterface(21329): alienPMEnableWakeLocks -> true
D/WLAlienSurface(21329): setState, mId = 18, 0 -> 5
I/ActivityManager(21329): Start proc com.smart_id for activity com.smart_id/com.stagnationlab.sk.MainActivity: pid=25255 uid=10053 gids={50053, 3003}
D/alien_init(21147): Set process(pid = 25082) score_adj as [1000]
D/ProcessState(25255): getContextObject - ALIEN_ID=[alien]
D/FakeHome(21489): onStop
D/alien_init(21147): Set process(pid = 25255) score_adj as [35]
D/dalvikvm(21176): GC_EXPLICIT freed 41K, 1% free 16710K/16788K, paused 1ms+2ms, total 21ms
I/MultiDex(25255): VM with version 1.6.0 does not have multidex support
I/MultiDex(25255): install
I/MultiDex(25255): MultiDexExtractor.load(/data/app/com.smart_id-2.apk, false)
I/MultiDex(25255): loading existing secondary dex files
D/dalvikvm(21176): GC_EXPLICIT freed <1K, 1% free 16710K/16788K, paused 1ms+2ms, total 16ms
I/MultiDex(25255): load found 1 secondary dex files
I/MultiDex(25255): install done
D/dalvikvm(21176): GC_EXPLICIT freed <1K, 1% free 16710K/16788K, paused 1ms+2ms, total 16ms
D/dalvikvm(25255): GC_CONCURRENT freed 282K, 2% free 16868K/17184K, paused 2ms+2ms, total 18ms
D/XWalkLib(25255): Init embedded mode
D/XWalkLib(25255): [App Version] build:22.52.561.4, api:7, min_api:7
D/XWalkLib(25255): [Lib Version] build:22.52.561.4, api:7, min_api:5
D/dalvikvm(25255): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
W/dalvikvm(25255): VFY: unable to resolve static field 412 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm(25255): VFY: replacing opcode 0x62 at 0x0004
D/XWalkLib(25255): Crosswalk download mode: false
D/XWalkLib(25255): XWalk core version matched
D/dalvikvm(25255): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
W/dalvikvm(25255): VFY: unable to resolve static field 412 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm(25255): VFY: replacing opcode 0x62 at 0x0004
D/dalvikvm(25255): Trying to load lib /data/app-lib/com.smart_id-2/libxwalkcore.so 0xe6eb55f0
D/dalvikvm(25255): GC_CONCURRENT freed 336K, 3% free 16977K/17348K, paused 4ms+3ms, total 17ms
D/dalvikvm(25255): Added shared lib /data/app-lib/com.smart_id-2/libxwalkcore.so 0xe6eb55f0
I/dalvikvm(25255): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zze.zzs
W/dalvikvm(25255): VFY: unable to resolve virtual method 813: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm(25255): VFY: replacing opcode 0x6e at 0x001b
D/dalvikvm(25255): Trying to load lib /data/app-lib/com.smart_id-2/libxwalkdummy.so 0xe6eb55f0
D/dalvikvm(25255): Added shared lib /data/app-lib/com.smart_id-2/libxwalkdummy.so 0xe6eb55f0
D/dalvikvm(25255): No JNI_OnLoad found in /data/app-lib/com.smart_id-2/libxwalkdummy.so 0xe6eb55f0, skipping init
D/GmsProviderInstaller(25255): Provider installer invoked for com.smart_id
I/cr_LibraryLoader(25255): Time to load native libraries: 1 ms (timestamps 5066-5067)
I/cr_LibraryLoader(25255): Expected native library version number "", actual native library version number ""
D/XWalkLib(25255): Native library is built for ARM
E/dalvikvm(25255): Could not find class 'javax.net.ssl.SNIServerName', referenced from method org.conscrypt.Platform.getSniHostnameFromParams
W/dalvikvm(25255): VFY: unable to resolve check-cast 3424 (Ljavax/net/ssl/SNIServerName;) in Lorg/conscrypt/Platform;
D/dalvikvm(25255): VFY: replacing opcode 0x1f at 0x0025
E/dalvikvm(25255): Could not find class 'javax.net.ssl.SNIHostName', referenced from method org.conscrypt.Platform.setParametersSniHostname
W/dalvikvm(25255): VFY: unable to resolve new-instance 3423 (Ljavax/net/ssl/SNIHostName;) in Lorg/conscrypt/Platform;
D/dalvikvm(25255): VFY: replacing opcode 0x22 at 0x0024
E/dalvikvm(25255): Could not find class 'javax.net.ssl.SNIHostName', referenced from method org.conscrypt.Platform.setParametersSniHostname
W/dalvikvm(25255): VFY: unable to resolve new-instance 3423 (Ljavax/net/ssl/SNIHostName;) in Lorg/conscrypt/Platform;
D/dalvikvm(25255): VFY: replacing opcode 0x22 at 0x0024
W/dalvikvm(25255): Unable to resolve superclass of Lorg/conscrypt/Java7ExtendedSSLSession; (3414)
W/dalvikvm(25255): Link of class 'Lorg/conscrypt/Java7ExtendedSSLSession;' failed
W/dalvikvm(25255): Unable to resolve superclass of Lorg/conscrypt/Java8ExtendedSSLSession; (4261)
W/dalvikvm(25255): Link of class 'Lorg/conscrypt/Java8ExtendedSSLSession;' failed
E/dalvikvm(25255): Could not find class 'org.conscrypt.Java8ExtendedSSLSession', referenced from method org.conscrypt.Platform.wrapSSLSession
W/dalvikvm(25255): VFY: unable to resolve new-instance 4266 (Lorg/conscrypt/Java8ExtendedSSLSession;) in Lorg/conscrypt/Platform;
D/dalvikvm(25255): VFY: replacing opcode 0x22 at 0x0006
D/dalvikvm(25255): DexOpt: unable to opt direct call 0x5bde at 0x2a in Lorg/conscrypt/Platform;.setParametersSniHostname
D/dalvikvm(25255): DexOpt: unable to opt direct call 0x5bde at 0x2a in Lorg/conscrypt/Platform;.setParametersSniHostname
W/dalvikvm(25255): Unable to resolve superclass of Lorg/conscrypt/Java7ExtendedSSLSession; (3414)
W/dalvikvm(25255): Link of class 'Lorg/conscrypt/Java7ExtendedSSLSession;' failed
W/dalvikvm(25255): Unable to resolve superclass of Lorg/conscrypt/Java8ExtendedSSLSession; (4261)
W/dalvikvm(25255): Link of class 'Lorg/conscrypt/Java8ExtendedSSLSession;' failed
D/dalvikvm(25255): DexOpt: unable to opt direct call 0x7581 at 0x08 in Lorg/conscrypt/Platform;.wrapSSLSession
D/dalvikvm(25255): Trying to load lib /data/app-lib/com.google.android.gms-1/libconscrypt_jni.so 0xe6eb9d30
D/dalvikvm(25255): Added shared lib /data/app-lib/com.google.android.gms-1/libconscrypt_jni.so 0xe6eb9d30
V/NativeCrypto(25255): Registering org/conscrypt/NativeCrypto's 284 native methods...
D/dalvikvm(25255): GC_CONCURRENT freed 318K, 3% free 17172K/17524K, paused 2ms+2ms, total 16ms
D/dalvikvm(25255): WAIT_FOR_CONCURRENT_GC blocked 7ms
D/dalvikvm(25255): newInstance failed: Lorg/conscrypt/OpenSSLSocketFactoryImpl; not accessible to Ljavax/net/ssl/SSLSocketFactory;
E/System  (25255): Problem creating org.conscrypt.OpenSSLSocketFactoryImpl
E/System  (25255): java.lang.IllegalAccessException: access to class not allowed
E/System  (25255):   at java.lang.Class.newInstanceImpl(Native Method)
E/System  (25255):   at java.lang.Class.newInstance(Class.java:1208)
E/System  (25255):   at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:56)
E/System  (25255):   at javax.net.ssl.HttpsURLConnection$NoPreloadHolder.<clinit>(HttpsURLConnection.java:114)
E/System  (25255):   at javax.net.ssl.HttpsURLConnection.setDefaultSSLSocketFactory(HttpsURLConnection.java:154)
E/System  (25255):   at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(ProviderInstallerImpl.java:118)
E/System  (25255):   at java.lang.reflect.Method.invokeNative(Native Method)
E/System  (25255):   at java.lang.reflect.Method.invoke(Method.java:515)
E/System  (25255):   at com.google.android.gms.security.ProviderInstaller.installIfNeeded(Unknown Source)
E/System  (25255):   at ee.cyber.smartid.SmartIdService.b(SmartIdService.java:728)
E/System  (25255):   at ee.cyber.smartid.SmartIdService.createRequestClient(SmartIdService.java:683)
E/System  (25255):   at ee.cyber.smartid.network.SmartIdAPI.<init>(SmartIdAPI.java:196)
E/System  (25255):   at ee.cyber.smartid.network.SmartIdAPI.createNewInstance(SmartIdAPI.java:171)
E/System  (25255):   at ee.cyber.smartid.SmartIdService$1.run(SmartIdService.java:932)
E/System  (25255):   at java.lang.Thread.run(Thread.java:841)
D/GmsProviderInstaller(25255): SSL provider installed
D/dalvikvm(25255): GC_CONCURRENT freed 337K, 3% free 17328K/17704K, paused 2ms+2ms, total 17ms
D/alien_init(21147): Set process(pid = 25082) score_adj as [35]
D/GmsSafetyNetClientSvc(25082): onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
I/ActivityManager(21329): Waited long enough for: ServiceRecord{e7610630 u0 com.skype.raider/com.google.firebase.iid.FirebaseInstanceIdService}
```

**Comment by ale5000-git** [comment]
Which build of microG GmsCore are you using?

[This build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) contains a fix for Conscrypt.
If you aren't using this build I suggest to update and retry, in case the problem was already fixed.

**Comment by rfvermut** [comment]
I tested it on current f-droid version which was `0.2.8.17785-mapbox`, added on 7/3/2019. 
@ale5000-git it is the one or I should manually download the apk above?

**Comment by ale5000-git** [comment]
It is only in the nightly build on this link: https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk

**Comment by rfvermut** [comment]
Nope. Same error. Sailfish, Xperia X, Android 4.4.

**Comment by ale5000-git** [comment]
These error is strange: `D/dalvikvm(25255): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS`.

Have you tried to clean the Dalvik Cache from the recovery?

**Comment by mar-v-in** [comment]
I think this might be a problem of Sailfish Alien Runtime (which is not exactly the same as Android 4.4), but would need to further investigate and see if this is reproducible on normal Android 4.4.

This shouldn't crash the app though (does it?), it only means that it does not use the Conscrypt provided by microG, but the SSL implementation shipped with Alien/your OS. If you see connectivity problems in that app (again, not crashes), this might be the cause.

**Comment by rfvermut** [comment]
Thanks for reply.
It doesn't crash, but it's a security related app and next screen I get is "sorry, technical error" because I believe it really needs TLS 1.2+ to proceed.

**Comment by rfvermut** [comment]
It's a problem in Jolla phone which used Android 4.4. I moved to Xperia XA2 with Android8 and problem obviously disappeared.
