### ISSUE TITLE
App: DJI Mimo 

### ISSUE THREAD

**Issue by Kerberus35** [microg/android_packages_apps_GmsCore#905]
Hi

Thanks for the awesome work on microg. Allmost everything works flawlessly, a very impressive feat, meaning this is a very good daily driver, with total control over the OS.

Except for one app in my collection: DJI Mimo, a camera app to connect to the Osmo Pocket and act as a screen. 

The app starts correctly but displays "Update failed. Check Network Connection". Restore of a previous working TitaniumBackup appdata file does not fix the issue.

These seem to be the problem:

07-26 22:02:47.576 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:02:47.577  1322 27666 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:02:47.577 29417 29417 E LicenseChecker: Could not bind to service.

LOGCAT:

`
07-26 22:01:26.398 29417 29417 E DJI-MIMO: java.lang.NoSuchFieldException: No field mLastSrvView in class Landroid/view/inputmethod/InputMethodManager; (declaration of 'android.view.inputmethod.InputMethodManager' appears in /system/framework/framework.jar!classes2.dex)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at java.lang.Class.getDeclaredField(Native Method)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at dji.libs.d.v.b(SourceFile:117)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at dji.libs.d.v.a(SourceFile:29)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at dji.libs.d.v$1.onActivityDestroyed(SourceFile:69)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.Application.dispatchActivityDestroyed(Application.java:276)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.Activity.onDestroy(Activity.java:2003)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.support.v4.app.FragmentActivity.onDestroy(SourceFile:382)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at dji.base.ui.base.FitScreenActivity.onDestroy(SourceFile:162)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at com.bangcle.andjni.JniLib.cV(Native Method)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at dji.mimo.main.DJISplashActivity.onDestroy(Unknown Source:15)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.Activity.performDestroy(Activity.java:7403)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4481)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.os.Looper.loop(Looper.java:193)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-26 22:01:26.398 29417 29417 E DJI-MIMO: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-26 22:01:26.438   932 23326 D         : DpmDfsTracker::dfsIndCb callback
07-26 22:01:26.650  2523  2713 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
07-26 22:01:26.650  2523  2523 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
07-26 22:01:26.704  1322  2505 D AlarmManagerService: Kernel timezone updated to -120 minutes west of GMT
07-26 22:01:26.722  2544  2544 D ServiceStateProvider: subId=1
07-26 22:01:26.813   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
07-26 22:01:26.813   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
07-26 22:01:26.813   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
07-26 22:01:26.813   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
07-26 22:01:31.441 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:31.442  1322  2833 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:31.442 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:33.706  1322  1322 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
07-26 22:01:34.480  3709 17532 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-26 22:01:34.480  3709 17532 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-26 22:01:34.480  3709 17532 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-26 22:01:34.480  3709 17532 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='dji.mimo', extras=Bundle[{}]}
07-26 22:01:34.506  3709 17532 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@8db5f90, 16
07-26 22:01:37.314 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:37.315  1322  2942 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:37.316 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:38.842 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:38.843  1322  2833 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:38.843 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:39.147 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:39.148 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:39.654 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:39.148  1322  2833 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:39.655  1322  2942 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:39.655 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:40.066 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:40.068  1322  2833 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:40.068 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:40.640 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:40.641  1322  2942 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:40.641 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:41.312 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:01:41.314 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:01:41.314  1322  2942 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:01:45.456  1322  1322 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
07-26 22:01:56.370  2523  2713 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
07-26 22:01:56.371  2523  2523 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
07-26 22:01:56.423  1322  1586 D AlarmManagerService: Kernel timezone updated to -120 minutes west of GMT
07-26 22:01:56.454  2544  2544 D ServiceStateProvider: subId=1
07-26 22:02:01.259   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
07-26 22:02:01.259   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
07-26 22:02:01.259   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
07-26 22:02:01.259   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
07-26 22:02:01.556  2523  2713 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
07-26 22:02:01.556  2523  2523 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
07-26 22:02:01.588  1322  1586 D AlarmManagerService: Kernel timezone updated to -120 minutes west of GMT
07-26 22:02:01.601  2544  2544 D ServiceStateProvider: subId=1
07-26 22:02:07.007   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
07-26 22:02:07.007   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
07-26 22:02:07.007   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
07-26 22:02:07.007   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
07-26 22:02:11.459 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:02:11.460  1322 27666 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:02:11.460 29417 29417 E LicenseChecker: Could not bind to service.
07-26 22:02:14.986  2283  2304 I ndroid.systemu: Background concurrent copying GC freed 257524(11MB) AllocSpace objects, 0(0B) LOS objects, 58% free, 8MB/20MB, paused 153us total 133.893ms
07-26 22:02:17.207 31767 31799 W ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
07-26 22:02:18.166   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
07-26 22:02:18.166   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
07-26 22:02:18.166   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
07-26 22:02:18.166   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
07-26 22:02:21.073   934  1086 I ThermalEngine: Monitor : quiet_therm = 34, msm_therm = 35, ufs_therm = -40, battery_therm = 331,current_now = -380000 
07-26 22:02:23.117  2523  2713 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
07-26 22:02:23.119  2523  2523 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
07-26 22:02:23.163  1322 27666 D AlarmManagerService: Kernel timezone updated to -120 minutes west of GMT
07-26 22:02:23.189  2544  2544 D ServiceStateProvider: subId=1
07-26 22:02:23.367   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
07-26 22:02:23.368   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
07-26 22:02:23.368   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
07-26 22:02:23.368   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
07-26 22:02:28.568   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'INTERFACE' not found
07-26 22:02:28.568   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'STATE' not found
07-26 22:02:28.568   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
07-26 22:02:28.568   672   687 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
07-26 22:02:40.689  2523  2713 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
07-26 22:02:40.690  2523  2523 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
07-26 22:02:40.740  1322 27666 D AlarmManagerService: Kernel timezone updated to -120 minutes west of GMT
07-26 22:02:40.756  2544  2544 D ServiceStateProvider: subId=1
07-26 22:02:47.576 29417 29417 I LicenseChecker: Binding to licensing service.
07-26 22:02:47.577  1322 27666 W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
07-26 22:02:47.577 29417 29417 E LicenseChecker: Could not bind to service.

`

Any input how to fix this?

**Comment by xcore995** [comment]
Do you have Play Store installed?

**Comment by Kerberus35** [comment]
This was with FakeStore installed, i try to run without google code. 

I installed the play store like this:

The playstore runs. However the DJI error remains. New LogCat:

```
07-28 14:40:07.374  1324  2866 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=dji.mimo/.main.DJISplashActivity (has extras)} from uid 10098
07-28 14:40:07.378  1324  2866 W system_server: resources.arsc in APK '/data/app/dji.mimo-oM-leI5RzVPHO2kLYh1prQ==/base.apk' is compressed.
07-28 14:40:07.419  7568  7568 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@606cf58
07-28 14:40:07.426  1324  2866 W ActivityManager: Request to remove task ignored for non-existent task 3798
07-28 14:40:07.430  3576  7898 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-28 14:40:07.430  3576  7898 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-28 14:40:07.430  3576  7898 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-28 14:40:07.430  3576  7898 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='com.teslacoilsw.launcher', extras=Bundle[{}]}
07-28 14:40:07.431  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@cf8b0c9, 16
07-28 14:40:07.530  3576  7898 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-28 14:40:07.530  3576  7898 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-28 14:40:07.530  3576  7898 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-28 14:40:07.530  3576  7898 D GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='dji.mimo', extras=Bundle[{}]}
07-28 14:40:07.538  1324  1349 I ActivityManager: Displayed dji.mimo/.main.DJISplashActivity: +157ms
07-28 14:40:07.544  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@41ee8d0, 16
07-28 14:40:07.545  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@cf8b0c9, 16
07-28 14:40:08.998  1324  8080 I ActivityManager: START u0 {cmp=dji.mimo/dji.assets.obb.ObbDownloadActivity (has extras)} from uid 10143
07-28 14:40:09.010  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@41ee8d0, 16
07-28 14:40:09.014  7568  7568 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f9cd9b8
07-28 14:40:09.047  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@cf8b0c9, 16
07-28 14:40:09.057  7568  7568 I LicenseChecker: Binding to licensing service.
07-28 14:40:09.058  1324  8080 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.android.vending/com.google.android.finsky.services.LicensingService} from pid=7568, uid=10143 requires com.android.vending.CHECK_LICENSE
07-28 14:40:09.067  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@41ee8d0, 16
07-28 14:40:09.069  3576  7898 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@cf8b0c9, 16
07-28 14:40:09.526  7568  7568 E DJI-MIMO: java.lang.NoSuchFieldException: No field mLastSrvView in class Landroid/view/inputmethod/InputMethodManager; (declaration of 'android.view.inputmethod.InputMethodManager' appears in /system/framework/framework.jar!classes2.dex)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at java.lang.Class.getDeclaredField(Native Method)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at dji.libs.d.v.b(SourceFile:117)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at dji.libs.d.v.a(SourceFile:29)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at dji.libs.d.v$1.onActivityDestroyed(SourceFile:69)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.Application.dispatchActivityDestroyed(Application.java:276)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.Activity.onDestroy(Activity.java:2003)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.support.v4.app.FragmentActivity.onDestroy(SourceFile:382)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at dji.base.ui.base.FitScreenActivity.onDestroy(SourceFile:162)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at com.bangcle.andjni.JniLib.cV(Native Method)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at dji.mimo.main.DJISplashActivity.onDestroy(Unknown Source:15)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.Activity.performDestroy(Activity.java:7403)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4481)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.os.Looper.loop(Looper.java:193)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at java.lang.reflect.Method.invoke(Native Method)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-28 14:40:09.526  7568  7568 E DJI-MIMO: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-28 14:40:12.600  7568  7568 I LicenseChecker: Binding to licensing service.
07-28 14:40:12.601  1324  5978 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.android.vending/com.google.android.finsky.services.LicensingService} from pid=7568, uid=10143 requires com.android.vending.CHECK_LICENSE

```

**Comment by fenik** [comment]
I think the main reason the Mimo app does call the license check service is, that it tries to load additional resources via OBB (?), which is not supported by any alternative Play store besides the official one and MicroG itself. Although, this is just a wild guess, so please correct me if I'm wrong here.

Anyways, I was having similiar issues with some of the DJI apps and found that if you sideload the official APKs from their website (https://www.dji.com/downloads/djiapp), everything seems to work perfectly fine.

**Comment by ale5000-git** [comment]
@Kerberus35

This main problem "Binding to licensing service" should be already fixed, try the latest version of FakeStore please: https://github.com/microg/FakeStore/releases

Instead for the problem `java.lang.NoSuchFieldException: No field mLastSrvView in class Landroid/view/inputmethod/InputMethodManager` I don't know.

Update both microG GmsCore and FakeStore and retry please.
