### ISSUE TITLE
OneDrive crashes

### ISSUE THREAD

**Issue by samantohermes** [microg/android_packages_apps_GmsCore#909]
> AndroidRuntime
FATAL EXCEPTION: main
Process: com.microsoft.skydrive, PID: 13210
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
	at com.microsoft.skydrive.iap.BaseOffice365PlansFragment.getProductInfo(SourceFile:133)
	at com.microsoft.skydrive.iap.InAppPurchaseFreFragment.onMAMCreateView(SourceFile:121)
	at com.microsoft.intune.mam.client.app.offline.OfflineFragmentBehavior.onCreateView(SourceFile:161)
	at com.microsoft.intune.mam.client.support.v4.app.MAMFragment.onCreateView(SourceFile:107)
	at android.support.v4.app.k.performCreateView(SourceFile:2346)
	at android.support.v4.app.q.a(SourceFile:1428)
	at android.support.v4.app.q.f(SourceFile:1759)
	at android.support.v4.app.q.a(SourceFile:1827)
	at android.support.v4.app.e.h(SourceFile:797)
	at android.support.v4.app.q.b(SourceFile:2596)
	at android.support.v4.app.q.a(SourceFile:2383)
	at android.support.v4.app.q.b(SourceFile:2338)
	at android.support.v4.app.q.i(SourceFile:2245)
	at android.support.v4.app.q.f(SourceFile:3248)
	at android.support.v4.app.q.q(SourceFile:3200)
	at android.support.v4.app.n.f(SourceFile:195)
	at android.support.v4.app.l.onStart(SourceFile:597)
	at android.support.v7.app.e.onStart(SourceFile:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7165)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by samantohermes** [comment]
???

**Comment by samantohermes** [comment]
Suddenly works again
