### ISSUE TITLE
Chrooma Keyboard Crash-Loops

### ISSUE THREAD

**Issue by timea-techgirl** [microg/android_packages_apps_GmsCore#918]
Chrooma keyboard keeps crashing continuously as it's unable to register with play services. Hope this can be fixed.

```
Process: com.gamelounge.chroomakeyboard
Flags: 0x38d8be44
Package: com.gamelounge.chroomakeyboard v20828 (helium-4.7.6)
Build: Android/aosp_hammerhead_fp/hammerhead:6.0/MRA58K/7.6.8:user/release-keys

java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1332)
	at android.app.ContextImpl.bindService(ContextImpl.java:1296)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:614)
	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source)
	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source)
	at com.google.firebase.iid.zzae.zzb(Unknown Source)
	at com.google.firebase.iid.zzac.zza(Unknown Source)
	at com.google.firebase.iid.zzac.zzb(Unknown Source)
	at com.google.firebase.iid.zzau.zzc(Unknown Source)
	at com.google.firebase.iid.zzs.zza(Unknown Source)
	at com.google.firebase.iid.zzr.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by timeakesmarky** [comment]
Tried a different ROM with the same crash.
```
Process: com.gamelounge.chroomakeyboard
Flags: 0x38d8be44
Package: com.gamelounge.chroomakeyboard v20830 (helium-4.7.8)
Build: google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys

java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1322)
	at android.app.ContextImpl.bindService(ContextImpl.java:1286)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source)
	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source)
	at com.google.firebase.iid.zzae.zzb(Unknown Source)
	at com.google.firebase.iid.zzac.zza(Unknown Source)
	at com.google.firebase.iid.zzac.zzb(Unknown Source)
	at com.google.firebase.iid.zzau.zzc(Unknown Source)
	at com.google.firebase.iid.zzs.zza(Unknown Source)
	at com.google.firebase.iid.zzr.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```
