### ISSUE TITLE
Allmost all apps crash after installing μG

### ISSUE THREAD

**Issue by ArchangeGabriel** [microg/android_packages_apps_GmsCore#924]
I’ve recently re-installed μG on my phone and for the first time enabled GCM because of N26 requiring it to work properly. N26 works fine after setting everything up, but…

Allmost all my (proprietary) applications are crashing. I would guess every that depends on GSF or GCM. The issue seems to be always the same:

```
08-11 13:46:52.708 29462 29484 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 13:46:52.708 29462 29484 E AndroidRuntime: Process: com.radiofrance.radio.franceinter.android, PID: 29462
08-11 13:46:52.708 29462 29484 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:22)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:24)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.firebase.iid.zzad.zzb(Unknown Source:17)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zza(Unknown Source:15)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zzb(Unknown Source:12)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.firebase.iid.zzat.zzc(Unknown Source:80)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.firebase.iid.zzr.zza(Unknown Source:73)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at com.google.firebase.iid.zzs.run(Unknown Source:6)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 13:46:52.708 29462 29484 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 13:46:52.711  1305  2826 W ActivityManager:   Force finishing activity com.radiofrance.radio.franceinter.android/.ui.activity.StarterActivity


08-11 13:55:46.887 30399 30423 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 13:55:46.887 30399 30423 E AndroidRuntime: Process: com.Slack, PID: 30399
08-11 13:55:46.887 30399 30423 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza$58d5677d(Unknown Source:22)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:24)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at com.google.firebase.iid.zzad.zzb(Unknown Source:17)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zza(Unknown Source:16)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at com.google.firebase.iid.zzat.zzc(Unknown Source:1013)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at com.google.firebase.iid.zzs.run(Unknown Source:1078)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 13:55:46.887 30399 30423 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)


08-11 13:56:38.253  1305 13312 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=30447, uid=10171 requires com.google.android.c2dm.permission.RECEIVE
08-11 13:56:38.255 30447 30499 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 13:56:38.255 30447 30499 E AndroidRuntime: Process: com.google.android.apps.maps, PID: 30447
08-11 13:56:38.255 30447 30499 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at bdfj.a(PG:14)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at bdfj.b(PG:15)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at brnq.a(PG:9)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at brnn.a(PG:13)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at brng.run(Unknown Source:5)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 13:56:38.255 30447 30499 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 13:56:38.279  1305 13312 W ActivityManager:   Force finishing activity com.google.android.apps.maps/com.google.android.maps.MapsActivity

08-11 13:59:58.837  1305 25983 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=31258, uid=10146 requires com.google.android.c2dm.permission.RECEIVE
08-11 13:59:58.838 31258 31282 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 13:59:58.838 31258 31282 E AndroidRuntime: Process: com.capitainetrain.android, PID: 31258
08-11 13:59:58.838 31258 31282 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:29)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:6)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:13)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.firebase.iid.g.a(Unknown Source:17)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.firebase.iid.e.a(Unknown Source:15)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.firebase.iid.e.b(Unknown Source:12)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.firebase.iid.w.a(Unknown Source:80)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.firebase.iid.au.a(Unknown Source:73)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at com.google.firebase.iid.av.run(Unknown Source:6)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 13:59:58.838 31258 31282 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 13:59:58.842  1305 25983 W ActivityManager:   Force finishing activity com.capitainetrain.android/.HomeActivity

08-11 14:01:35.574  1305  6416 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=32330, uid=10145 requires com.google.android.c2dm.permission.RECEIVE
08-11 14:01:35.575 32330 32379 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 14:01:35.575 32330 32379 E AndroidRuntime: Process: com.sncf.fusion:A4SService, PID: 32330
08-11 14:01:35.575 32330 32379 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(SourceFile:22)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(SourceFile:24)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.firebase.iid.zzad.zzb(SourceFile:17)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zza(SourceFile:15)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zzb(SourceFile:12)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.firebase.iid.zzat.zzc(SourceFile:80)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.firebase.iid.zzr.zza(SourceFile:73)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at com.google.firebase.iid.zzs.run(Unknown Source:6)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 14:01:35.575 32330 32379 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: Stack trace: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(SourceFile:22)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(SourceFile:24)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.firebase.iid.zzad.zzb(SourceFile:17)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.firebase.iid.zzab.zza(SourceFile:15)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.firebase.iid.zzab.zzb(SourceFile:12)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.firebase.iid.zzat.zzc(SourceFile:80)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.firebase.iid.zzr.zza(SourceFile:73)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at com.google.firebase.iid.zzs.run(Unknown Source:6)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 14:01:35.575 32330 32379 E CrashLogHandler: 	at java.lang.Thread.run(Thread.java:764)


08-11 14:03:27.736  1305 12460 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.orange.mysosh/.MySoshActivity bnds=[24,1415][230,1748] (has extras)} from uid 10106
08-11 14:03:27.755  1305  1339 I ActivityManager: Start proc 1559:com.orange.mysosh/u0a147 for activity com.orange.mysosh/.MySoshActivity
08-11 14:03:27.826  1305  4313 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=1559, uid=10147 requires com.google.android.c2dm.permission.RECEIVE
08-11 14:03:27.827  1559  1596 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 14:03:27.827  1559  1596 E AndroidRuntime: Process: com.orange.mysosh, PID: 1559
08-11 14:03:27.827  1559  1596 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:22)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:24)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.firebase.iid.zzad.zzb(Unknown Source:17)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zza(Unknown Source:15)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zzb(Unknown Source:12)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.firebase.iid.zzat.zzc(Unknown Source:80)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.firebase.iid.zzr.zza(Unknown Source:73)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at com.google.firebase.iid.zzs.run(Unknown Source:6)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 14:03:27.827  1559  1596 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 14:03:27.828  1305  1339 I ActivityManager: Start proc 1590:com.orange.mysosh:equalone/u0a147 for service com.orange.mysosh/com.v3d.equalcore.inpc.server.EQualOneService
08-11 14:03:27.829  1305 14429 W ActivityManager:   Force finishing activity com.orange.mysosh/.MySoshActivity
08-11 14:03:27.833  1305  1337 I ActivityManager: Showing crash dialog for package com.orange.mysosh u0



08-11 14:04:42.809  2140  2170 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 14:04:42.809  2140  2170 E AndroidRuntime: Process: com.applidium.vianavigo, PID: 2140
08-11 14:04:42.809  2140  2170 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.zza(Unknown Source:22)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.android.gms.common.stats.ConnectionTracker.bindService(Unknown Source:24)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.firebase.iid.zzad.zzb(Unknown Source:17)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zza(Unknown Source:15)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.firebase.iid.zzab.zzb(Unknown Source:12)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.firebase.iid.zzat.zzc(Unknown Source:80)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.firebase.iid.zzr.zza(Unknown Source:73)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at com.google.firebase.iid.zzs.run(Unknown Source:6)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 14:04:42.809  2140  2170 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 14:04:42.811  1305  2372 W ActivityManager:   Force finishing activity com.applidium.vianavigo/com.is.android.views._start.StartFlowActivity


08-11 14:05:43.863  1305 15144 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=2655, uid=10140 requires com.google.android.c2dm.permission.RECEIVE
08-11 14:05:43.864  2655  2691 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
08-11 14:05:43.864  2655  2691 E AndroidRuntime: Process: com.fabernovel.ratp, PID: 2655
08-11 14:05:43.864  2655  2691 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.android.gms.common.b.a.a(Unknown Source:10)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.android.gms.common.b.a.a(Unknown Source:11)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.firebase.iid.h.a(Unknown Source:17)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.firebase.iid.f.a(Unknown Source:9)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.firebase.iid.f.b(Unknown Source:1)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.firebase.iid.w.a(Unknown Source:60)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.firebase.iid.V.a(Unknown Source:35)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at com.google.firebase.iid.U.run(Unknown Source:6)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 14:05:43.864  2655  2691 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-11 14:05:43.866  1305 21035 W ActivityManager:   Force finishing activity com.fabernovel.ratp/fr.ratp.app.android.splashscreen.ui.SplashScreenActivity
```

I’m available to do debugging if required. Should I try as a first step to re-install microG without GCM/GSF and see if applications work in this case?

**Comment by mar-v-in** [comment]
You need to reinstall all apps installed before microG, so that they can be granted the required permission.

**Comment by ArchangeGabriel** [comment]
OK, I thought this was necessary for GCM to work for those applications (which I don’t want), not for them to actually work. Re-installing did the job, many thanks!

**Comment by ArchangeGabriel** [comment]
Well, I did backup every crashing app, uninstalled them, re-installed them, restored and voilà!

Updating is not enough. However, I’m worried about your mention of GApps. You must not have GApps installed for μG to work.

**Comment by gersh0m** [comment]
Thank you!

Unfortunately I saw the version without GApps pre-installed ( openkiring project ) only when was too late...
I folewed the  the instructions to install micro-G also in case of pre installed Gapps.
I think I better reinstall everything again...
