### ISSUE TITLE
Can't signin with YouTube TV (Android 7.1.2)  missing GET_ACCOUNTS or EXTENDED_ACCESS permission

### ISSUE THREAD

**Issue by Pengchengistaken** [microg/android_packages_apps_GmsCore#926]
Google account is signed in, but when click on sign in from Youtube TV, nothing happens.
Below is logcat:

clientId=android.media.AudioManager@d55ef0dev.cobalt.media.CobaltMediaSession@b66bc69
08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-15 14:49:04.004  4845  4867 D GmsFeedbackSvc: bound by: GetServiceRequest{serviceId=FEEDBACK, gmsVersion=13280000, packageName='com.google.android.youtube.tv', extras=Bundle[{}]}
08-15 14:49:04.770  4845  4858 D GmsAuthProvider: Call from com.google.android.youtube.tv
08-15 14:49:04.775  4845  4858 W GmsAuthProvider: Not granting extended access to [com.google.android.youtube.tv], signature: 61226bdb57cc32c8a2a9ef71f7bc9548e95dcc0b
08-15 14:49:04.776  4845  4858 E DatabaseUtils: Writing exception to parcel
08-15 14:49:04.776  4845  4858 E DatabaseUtils: java.lang.SecurityException: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at org.microg.gms.auth.AccountContentProvider.call(AccountContentProvider.java:65)
08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.content.ContentProvider$Transport.call(ContentProvider.java:400)
08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:565)
08-15 14:49:04.777  5293  5758 E starboard: Error getting signed-in account
08-15 14:49:04.777  5293  5758 E starboard: android.os.RemoteException: Accounts ContentProvider failed: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
08-15 14:49:04.777  5293  5758 E starboard:     at bbp.b(SourceFile:23)
08-15 14:49:04.777  5293  5758 E starboard:     at bpo.a(SourceFile:3)
08-15 14:49:04.777  5293  5758 E starboard:     at bpp.a(SourceFile:13)
08-15 14:49:04.777  5293  5758 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.c(SourceFile:25)
08-15 14:49:04.777  5293  5758 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.authorizeUser(SourceFile:7)

**Comment by mar-v-in** [comment]
Did you grant contacts permission to the app through the system permission settings?

**Comment by Pengchengistaken** [comment]
> Did you grant contacts permission to the app through the system permission settings?

yes. i run 
```
pm grant com.google.android.youtube.tv android.permission.GET_ACCOUNTS
```
But it says
```
Operation not allowed: java.lang.SecurityException: Package com.google.android.youtube.tv has not requested permission android.permission.GET_ACCOUNTS
```

thx.

**Comment by Pengchengistaken** [comment]
I found a similar issue #144 
Is there a workaround/fixed for my issue?

**Comment by sharljimhtsin** [comment]
it seems that i hit the bug too,i install the latest youtube vanced (14.21.54 ) &  MicroG - For YouTube 14.21.54 and up (0.2.6.17455).

after logined in successful, it hangs up on prepare the account data activity.

help plz.

**Comment by Pengchengistaken** [comment]
I downloaded the source code, added YouTube TV signature, the GET_ACCOUNTS issue is gone.
```
static {
        KNOWN_GOOGLE_PACKAGES = new HashMap<>();
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.classroom", "46f6c8987311e131f4f558d8e0ae145bebab6da3");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.inbox", "aa87ce1260c008d801197bb4ecea4ab8929da246");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.playconsole", "d6c35e55b481aefddd74152ca7254332739a81d6");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.travel.onthego", "0cbe08032217d45e61c0bc72f294395ee9ecb5d5");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.tycho", "01b844184e360686aa98b48eb16e05c76d4a72ad");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.youtube.tv", "61226bdb57cc32c8a2a9ef71f7bc9548e95dcc0b");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.contacts", "ee3e2b5d95365c5a1ccc2d8dfe48d94eb33b3ebe");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.wearable.app", "a197f9212f2fed64f0ff9c2a4edf24b9c8801c8c");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.youtube.music", "afb0fed5eeaebdd86f56a97742f4b6b33ef59875");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.vr.home", "fc1edc68f7e3e4963c998e95fc38f3de8d1bfc96");
        KNOWN_GOOGLE_PACKAGES.put("com.google.vr.cyclops", "188c5ca3863fa121216157a5baa80755ceda70ab");
        KNOWN_GOOGLE_PACKAGES.put("com.waze", "35b438fe1bc69d975dc8702dc16ab69ebf65f26f");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.wellbeing", "4ebdd02380f1fa0b6741491f0af35625dba76e9f");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.village.boond", "48e7985b8f901df335b5d5223579c81618431c7b");
        KNOWN_GOOGLE_PACKAGES.put("com.google.android.apps.subscriptions.red", "de8304ace744ae4c4e05887a27a790815e610ff0");
    }
```
But, it comes another issue, YouTube TV is still not signed in. Looks like problem in authentication with google.

```
08-19 12:32:08.762 13341 13414 I starboard: Prepare to resume
08-19 12:32:08.775 13341 13341 I starboard_media: Media focus: none
08-19 12:32:08.776  4357  4372 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10035/13341 clientId=android.media.AudioManager@17e6e97dev.cobalt.media.CobaltMediaSession@8514884
08-19 12:32:08.804 13321 13334 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-19 12:32:08.804 13321 13334 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-19 12:32:08.805 13321 13334 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
08-19 12:32:08.805 13321 13334 D GmsFeedbackSvc: bound by: GetServiceRequest{serviceId=FEEDBACK, gmsVersion=13280000, packageName='com.google.android.youtube.tv', extras=Bundle[{}]}
08-19 12:32:08.825 13483 13483 I art     : Starting a blocking GC Explicit
08-19 12:32:08.874 13483 13483 I art     : Explicit concurrent mark sweep GC freed 2524(141KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 2MB/3MB, paused 404us total 44.982ms
08-19 12:32:08.876 13483 13483 I art     : Starting a blocking GC Explicit
08-19 12:32:08.919 13483 13483 I art     : Explicit concurrent mark sweep GC freed 5620(248KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 2MB/3MB, paused 654us total 42.098ms
08-19 12:32:09.022 13321 13776 D GmsAuthProvider: Call from com.google.android.youtube.tv
08-19 12:32:09.047 13321 13334 D GmsAuthManagerSvc: clearToken: token:null extras:Bundle[{androidPackageName=com.google.android.youtube.tv, clientPackageName=com.google.android.youtube.tv}]
08-19 12:32:09.047 13341 13450 W Auth    : [GoogleAuthUtil] GoogleAuthUtil
08-19 12:32:09.048 13341 13450 E starboard: Error getting OAuth token
08-19 12:32:09.048 13341 13450 E starboard: java.io.IOException: Service unavailable.
08-19 12:32:09.048 13341 13450 E starboard:     at afh.a(SourceFile:29)
08-19 12:32:09.048 13341 13450 E starboard:     at afp.a(SourceFile:4)
08-19 12:32:09.048 13341 13450 E starboard:     at afh.a(SourceFile:38)
08-19 12:32:09.048 13341 13450 E starboard:     at bbq.a(SourceFile:30)
08-19 12:32:09.048 13341 13450 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.c(SourceFile:32)
08-19 12:32:09.048 13341 13450 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.authorizeUser(SourceFile:7)
```

additional test:
YouTube for mobile is OK to login.
YouTube for TV is NG to login.

Any help is appreciated.

**Comment by MrDodojo** [comment]
> it seems that i hit the bug too,i install the latest youtube vanced (14.21.54 ) & MicroG - For YouTube 14.21.54 and up (0.2.6.17455).
> 
> after logined in successful, it hangs up on prepare the account data activity.
> 
> help plz.

YouTube Vanced isn't made for TV. If you have any issues with the Non-Root version you should Disable 2FA if you have that enabled, I guess something is wrong with MicroG, MicroG4Vanced or Vanced itself that doesn't handle 2FA in some usecases

**Comment by MrDodojo** [comment]
> Google account is signed in, but when click on sign in from Youtube TV, nothing happens.
> Below is logcat:
> 
> ```
> clientId=android.media.AudioManager@d55ef0dev.cobalt.media.CobaltMediaSession@b66bc69
> 08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
> 08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
> 08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
> 08-15 14:49:04.004  4845  4867 D GmsFeedbackSvc: bound by: GetServiceRequest{serviceId=FEEDBACK, gmsVersion=13280000, packageName='com.google.android.youtube.tv', extras=Bundle[{}]}
> 08-15 14:49:04.770  4845  4858 D GmsAuthProvider: Call from com.google.android.youtube.tv
> 08-15 14:49:04.775  4845  4858 W GmsAuthProvider: Not granting extended access to [com.google.android.youtube.tv], signature: 61226bdb57cc32c8a2a9ef71f7bc9548e95dcc0b
> 08-15 14:49:04.776  4845  4858 E DatabaseUtils: Writing exception to parcel
> 08-15 14:49:04.776  4845  4858 E DatabaseUtils: java.lang.SecurityException: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
> 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at org.microg.gms.auth.AccountContentProvider.call(AccountContentProvider.java:65)
> 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.content.ContentProvider$Transport.call(ContentProvider.java:400)
> 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
> 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:565)
> 08-15 14:49:04.777  5293  5758 E starboard: Error getting signed-in account
> 08-15 14:49:04.777  5293  5758 E starboard: android.os.RemoteException: Accounts ContentProvider failed: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
> 08-15 14:49:04.777  5293  5758 E starboard:     at bbp.b(SourceFile:23)
> 08-15 14:49:04.777  5293  5758 E starboard:     at bpo.a(SourceFile:3)
> 08-15 14:49:04.777  5293  5758 E starboard:     at bpp.a(SourceFile:13)
> 08-15 14:49:04.777  5293  5758 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.c(SourceFile:25)
> 08-15 14:49:04.777  5293  5758 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.authorizeUser(SourceFile:7)
> ```

It's stock youtube right?

**Comment by Pengchengistaken** [comment]
> > Google account is signed in, but when click on sign in from Youtube TV, nothing happens.
> > Below is logcat:
> > ```
> > clientId=android.media.AudioManager@d55ef0dev.cobalt.media.CobaltMediaSession@b66bc69
> > 08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
> > 08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
> > 08-15 14:49:04.003  4845  4867 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
> > 08-15 14:49:04.004  4845  4867 D GmsFeedbackSvc: bound by: GetServiceRequest{serviceId=FEEDBACK, gmsVersion=13280000, packageName='com.google.android.youtube.tv', extras=Bundle[{}]}
> > 08-15 14:49:04.770  4845  4858 D GmsAuthProvider: Call from com.google.android.youtube.tv
> > 08-15 14:49:04.775  4845  4858 W GmsAuthProvider: Not granting extended access to [com.google.android.youtube.tv], signature: 61226bdb57cc32c8a2a9ef71f7bc9548e95dcc0b
> > 08-15 14:49:04.776  4845  4858 E DatabaseUtils: Writing exception to parcel
> > 08-15 14:49:04.776  4845  4858 E DatabaseUtils: java.lang.SecurityException: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
> > 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at org.microg.gms.auth.AccountContentProvider.call(AccountContentProvider.java:65)
> > 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.content.ContentProvider$Transport.call(ContentProvider.java:400)
> > 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
> > 08-15 14:49:04.776  4845  4858 E DatabaseUtils:         at android.os.Binder.execTransact(Binder.java:565)
> > 08-15 14:49:04.777  5293  5758 E starboard: Error getting signed-in account
> > 08-15 14:49:04.777  5293  5758 E starboard: android.os.RemoteException: Accounts ContentProvider failed: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
> > 08-15 14:49:04.777  5293  5758 E starboard:     at bbp.b(SourceFile:23)
> > 08-15 14:49:04.777  5293  5758 E starboard:     at bpo.a(SourceFile:3)
> > 08-15 14:49:04.777  5293  5758 E starboard:     at bpp.a(SourceFile:13)
> > 08-15 14:49:04.777  5293  5758 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.c(SourceFile:25)
> > 08-15 14:49:04.777  5293  5758 E starboard:     at com.google.android.libraries.youtube.tv.account.TvUserAuthorizer.authorizeUser(SourceFile:7)
> > ```
> 
> It's stock youtube right?

Yes it is. i'm using: https://www.apkmirror.com/apk/google-inc/youtube-for-android-tv-android-tv/youtube-for-android-tv-android-tv-2-07-02-release/

**Comment by Pengchengistaken** [comment]
more background:
i am rom developer, building AOSP 7.1.2, patched signature spoofing.

**Comment by gyk001** [comment]
same problem， 
Google account is signed in, but when click on sign in from Youtube TV, nothing happens.

**Comment by ale5000-git** [comment]
I have downloaded the first version and the last version of YouTube TV from apkmirror and they both request `android.permission.GET_ACCOUNTS`.

@Pengchengistaken: Is it possible that you have a modded version?
