### ISSUE TITLE
emulator image does not boot

### ISSUE THREAD

**Issue by YtvwlD** [microg/android_packages_apps_GmsCore#937]
I'm trying to run the provided Android emulator image.
Because my CPU sadly doesn't have SSSE3 support, I disabled hardware acceleration.

The emulator does not boot properly because the system server crashes repeatedly.

The first crash has only happened once on first boot, I guess it is irrelevant:

```
--------- beginning of crash
09-07 10:16:43.198  1152  1152 F libc    : Fatal signal 5 (SIGTRAP), code 2 in tid 1152 (system_server)
09-07 10:16:43.441   946   946 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-07 10:16:43.442   946   946 F DEBUG   : Build fingerprint: 'Android/aosp_x86/generic_x86:6.0.1/MOB30M/marvin06151802:eng/test-keys'
09-07 10:16:43.442   946   946 F DEBUG   : Revision: '0'
09-07 10:16:43.442   946   946 F DEBUG   : ABI: 'x86'
09-07 10:16:43.447   946   946 F DEBUG   : pid: 1152, tid: 1152, name: system_server  >>> system_server <<<
09-07 10:16:43.449   946   946 F DEBUG   : signal 5 (SIGTRAP), code 2 (TRAP_TRACE), fault addr 0x480
09-07 10:16:43.750   946   946 F DEBUG   :     eax 4c285901  ebx 0000003f  ecx 0000003b  edx 00000004
09-07 10:16:43.751   946   946 F DEBUG   :     esi bf84bf20  edi ab6c5d40
09-07 10:16:43.751   946   946 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000007  xss 0000007b
09-07 10:16:43.752   946   946 F DEBUG   :     eip b67527c4  ebp a9dbb900  esp bf84bf00  flags d2e83f2a
09-07 10:16:43.818   946   946 F DEBUG   : 
09-07 10:16:43.818   946   946 F DEBUG   : backtrace:
09-07 10:16:43.820   946   946 F DEBUG   :     #00 pc 0002d7c4  /system/lib/libcrypto.so
09-07 10:16:43.821   946   946 F DEBUG   :     #01 pc 5fc19070  <unknown>
```

This one is repeated:

```
9-07 10:20:36.910  1624  1624 E System  : ******************************************
09-07 10:20:36.927  1624  1624 E System  : ************ Failure starting system services
09-07 10:20:36.927  1624  1624 E System  : java.lang.RuntimeException: There must be one required installer
09-07 10:20:36.927  1624  1624 E System  :      at com.android.server.pm.PackageManagerService.getRequiredInstallerLPr(PackageManagerService.java:2425)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2331)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:1767)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:366)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.server.SystemServer.run(SystemServer.java:268)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.server.SystemServer.main(SystemServer.java:168)
09-07 10:20:36.927  1624  1624 E System  :      at java.lang.reflect.Method.invoke(Native Method)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-07 10:20:36.927  1624  1624 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-07 10:20:36.934  1624  1624 D AndroidRuntime: Shutting down VM
09-07 10:20:36.937  1624  1624 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
09-07 10:20:36.937  1624  1624 E AndroidRuntime: java.lang.RuntimeException: There must be one required installer
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.getRequiredInstallerLPr(PackageManagerService.java:2425)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2331)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:1767)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:366)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:268)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:168)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-07 10:20:36.937  1624  1624 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-07 10:20:36.960  1624  1624 E AndroidRuntime: Error reporting crash
09-07 10:20:36.960  1624  1624 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference
09-07 10:20:36.960  1624  1624 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
09-07 10:20:36.960  1624  1624 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
09-07 10:20:36.960  1624  1624 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

Looking at [the code](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/marshmallow-mr3-release/services/core/java/com/android/server/pm/PackageManagerService.java#2399), I guess there's an installer missing?

`pm` also doesn't work.

```
root@generic_x86:/ # pm list
Error: Could not access the Package Manager.  Is the system running?
```

It might be my setup, I can try this with a newer CPU in a few days. 

Edit: This does work on a newer CPU.

**Comment by mar-v-in** [comment]
There is a new emulator image using Android 10.0 / x86_64. Can you verify if the issue still exists with that image?

**Comment by YtvwlD** [comment]
It still doesn't seem to come up, but I also don't get a understandable error.

```
10-27 20:07:28.006  2562  2606 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.bg
10-27 20:07:28.006  2562  2606 E AndroidRuntime: java.lang.IllegalStateException: Wait for admin data timed out.
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at com.android.internal.util.ConcurrentUtils.waitForCountDownNoInterrupt(ConcurrentUtils.java:108)
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at com.android.server.usage.AppStandbyController.waitForAdminData(AppStandbyController.java:1312)
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at com.android.server.usage.AppStandbyController.access$300(AppStandbyController.java:125)
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at com.android.server.usage.AppStandbyController$AppStandbyHandler.handleMessage(AppStandbyController.java:1731)
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
10-27 20:07:28.006  2562  2606 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
10-27 20:04:58.382  1651  1803 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.fg
10-27 20:04:58.382  1651  1803 E AndroidRuntime: java.lang.IllegalStateException: Error granting/upgrading runtime permissions
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at com.android.server.policy.PermissionPolicyService.lambda$grantOrUpgradeDefaultRuntimePermissionsIfNeeded$0(PermissionPolicyService.java:299)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at com.android.server.policy.-$$Lambda$PermissionPolicyService$8D9Zbki65ND_Q20M-Trexl6cHcQ.accept(Unknown Source:4)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at android.permission.PermissionControllerManager$PendingGrantOrUpgradeDefaultRuntimePermissionsRequest.onTimeout(PermissionControllerManager.java:1212)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at android.permission.PermissionControllerManager$PendingGrantOrUpgradeDefaultRuntimePermissionsRequest.onTimeout(PermissionControllerManager.java:1185)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at com.android.internal.infra.AbstractRemoteService$PendingRequest.lambda$new$0$AbstractRemoteService$PendingRequest(AbstractRemoteService.java:654)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at com.android.internal.infra.-$$Lambda$AbstractRemoteService$PendingRequest$IBoaBGXZQEXJr69u3aJF-LCJ42Y.run(Unknown Source:4)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
10-27 20:04:58.382  1651  1803 E AndroidRuntime:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

I guess the main reason is that the whole system starts too slow:

```
10-27 19:57:32.943  1694  1878 W ServiceManager: Service package_native didn't start. Returning NULL
```

But that message occurs relatively early in the boot process and not before the services die. I'll try this with a more modern CPU.

**Comment by YtvwlD** [comment]
So, both the old and the new image boot on my laptop and don't boot on my desktop. So I don't think the image is at fault.
