### ISSUE TITLE
Postfinance app crashes on startup: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad

### ISSUE THREAD

**Issue by anjanoelle** [microg/android_packages_apps_GmsCore#946]
Hello everyone,

immediately on opening the "Postfinance"-app, it crashes, giving me the following error:

```
09-22 10:08:45.361 10193 10193 E AndroidRuntime: Process: ch.postfinance.android, PID: 10193
09-22 10:08:45.361 10193 10193 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/ch.postfinance.android-X-Lfc94AdgpjcpOvXQvzSA==/lib/arm64/libmfjava.so": -110
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at ch.postfinance.core.CurrentActivityHandlingApp.<clinit>(Unknown Source:2)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1102)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-22 10:08:45.361 10193 10193 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Please let me know if I can provide you with any further information or if there is a fix I'm overlooking.

Cheers

**Comment by bachi76** [comment]
Same happens here, HTC U11, orig ROM, not rooted. Must be a postfinance app version issue - it worked just fine before. Let's stress their support!

**Comment by callmemagnus** [comment]
I don't use microG.

I also have this problem with lineageos and opengapps.

**Comment by erenustun** [comment]
> 
> 
> I don't use microG.
> 
> I also have this problem with lineageos and opengapps.

I'm also on lineageos. Did you find any solutions to your problem back then?

**Comment by bachi76** [comment]
Actually I found the problem cause. In my case, it was the app "_Automate_" and _one add-on app that could give Automate SU-perms_ (don't remember the exact name). Havig that app (that required device management permissions) on my phone was enough for the PF app crash on start-up - even when the device was not rooted! The mere presence of the su-giving companion app to Automate triggered the PF rooting check.

And, btw, I discussed this with the Postfinance app manager, and he confirmed that a) they bought the SU-check from a third-party provider and b) that they on purpose let the Postfinance app crash without proper error msg. if the root checker was triggered - it was a security concern that I not really understood.

So: **Deinstall Automate + companion apps. Maybe uninstall other apps with the Device Management permission.** For me, the Postfinance app worked again after that (and ever since).

Hope this can help someone.

**Comment by SangeloDev** [comment]
> Havig that app (that required device management permissions) on my phone was enough for the PF app crash on start-up - even when the device was not rooted!

Where can I find the device management permissions of an Android app?

**Comment by AndreKoepke** [comment]
I managed to get it work. I needed these steps with LineageOS 19:

1. Install Magisk
2. Enable "Zygisk" (Settings -> Magisk -> Zygisk)
3. Enforce denial list (maybe it's called something different. In German it's "Verweigerungsliste")
4. Put Postfinance into the denial list.
5. Hide Magisk-App (Settings -> App -> Hide Magisk-App)
6. If this is not enough, then try this too. https://community.e.foundation/t/postfinance-app-crashes/6716/38

I think, that this ticket can be closed. It has nothing to with MicroG.
