### ISSUE TITLE
Lyft app crashes due to 32/64-bit issues

### ISSUE THREAD

**Issue by gm23** [microg/android_packages_apps_GmsCore#95]
I am trying to get Lyft running with GmsCore. After I Needle'd my ROM and rebooted, everything is fine---for example, UnifiedNlp works without a hitch---but Lyft is crashing on startup:

```
E/AndroidRuntime(10738): FATAL EXCEPTION: main
E/AndroidRuntime(10738): Process: me.lyft.android, PID: 10738
E/AndroidRuntime(10738): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.gms-1/lib/arm64/libvtm-jni.so" is 64-bit instead of 32-bit
E/AndroidRuntime(10738):        at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(10738):        at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(10738):        at org.oscim.android.MapView.<clinit>(MapView.java:52)
E/AndroidRuntime(10738):        at org.microg.gms.maps.BackendMap.<init>(BackendMap.java:60)
E/AndroidRuntime(10738):        at org.microg.gms.maps.GoogleMapImpl.<init>(GoogleMapImpl.java:131)
E/AndroidRuntime(10738):        at org.microg.gms.maps.MapViewImpl.myMap(MapViewImpl.java:50)
E/AndroidRuntime(10738):        at org.microg.gms.maps.MapViewImpl.getView(MapViewImpl.java:103)
E/AndroidRuntime(10738):        at com.google.android.gms.maps.internal.IMapViewDelegate$Stub.onTransact(IMapViewDelegate.java:119)
E/AndroidRuntime(10738):        at org.microg.gms.maps.MapViewImpl.onTransact(MapViewImpl.java:113)
E/AndroidRuntime(10738):        at android.os.Binder.transact(Binder.java:380)
E/AndroidRuntime(10738):        at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.getView(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.dynamic.zza.zza(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
E/AndroidRuntime(10738):        at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
E/AndroidRuntime(10738):        at me.lyft.android.ui.MainActivity.onCreate(MainActivity.java:164)
E/AndroidRuntime(10738):        at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(10738):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(10738):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime(10738):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime(10738):        at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(10738):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(10738):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10738):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10738):        at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(10738):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10738):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10738):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(10738):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```
I am rather unexperienced with the Android and GmsCore ecosystem, but it seems that Lyft first loads some 32-bit libraries (libcardioDecider.so, libopencv_core.so, etc.), and it then tries to load the libvtm-jni.so, but only finds a 64-bit version of it. As 32-bit and 64-bit libraries cannot be loaded concurrently, the application raises an exception. 

The question would be if and how to provide an 32-bit version of the GmsCore libraries, and if and how these could be provided side-by-side with 64-bit libraries.

**Comment by gm23** [comment]
The Uber app shows the same behavior, which the same exception. Both use `loadLibrary` to load the `libvtm-jni.so`. Thus I am currently wondering if I have set up everything correctly, as I only have an `arm64`, but no `arm` folder in my `/data/app/com.google.android.gms-1/lib/` directory.

**Comment by gm23** [comment]
Just a quick reply: When I push the `armeabi-v7a` .so-files into the `arm64` directory (thus overwriting the 64 bit binaries with 32 bit ones), Uber is working, however Lyft is still complaining ("Lyft is having trouble with Google Play services. If the problem persists, please contact the developer for assistance.")

I should have noted earlier that this is on Android 6.0.1, and thus probably highly related to #97.

**Comment by gm23** [comment]
Great work! For future reference: With the currently nightly build (at the time of writing that is BUILD_71_2016-02-28_13-50) both Uber and Lyft now work without a hitch!

**Comment by bfwrtaglead** [comment]
@gm23 See #207 for workarounds for selecting a destination address.
