### ISSUE TITLE
Zero - Fasting Tracker does not work

### ISSUE THREAD

**Issue by omyno** [microg/android_packages_apps_GmsCore#951]
Device: Xiaomi Mi Mix 2
GCM: Connected

Upon logging in at Zero, nothing happens and the following error is logged:

```
[10-10 21:45:13.720 25806:25917 E/Zero - UALib]
Push registration failed.
com.urbanairship.push.PushProvider$RegistrationException: FCM registration failed.
	at com.urbanairship.push.fcm.FcmPushProvider.getRegistrationToken(FcmPushProvider.java:75)
	at com.urbanairship.push.PushManagerJobHandler.onUpdatePushRegistration(PushManagerJobHandler.java:198)
	at com.urbanairship.push.PushManagerJobHandler.performJob(PushManagerJobHandler.java:116)
	at com.urbanairship.push.PushManager.onPerformJob(PushManager.java:349)
	at com.urbanairship.job.Job$1.run(Job.java:90)
	at com.urbanairship.util.SerialExecutor$1.run(SerialExecutor.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.0:67)
	at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.0:80)
	at com.google.firebase.iid.zzp.then(com.google.firebase:firebase-iid@@20.0.0:4)
	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	... 1 more
```

**Comment by mar-v-in** [comment]
This should be fixed in c3bfb63f27c116d21ba7b2b87629e36573d4a59e
