### ISSUE TITLE
Doesn't checkin because of 'invalid device'.

### ISSUE THREAD

**Issue by ettavolt** [microg/android_packages_apps_GmsCore#953]
Here are request and response:
```
10-12 13:56:34.171  4419  4438 D GmsCheckinClient: -- Request --
10-12 13:56:34.171  4419  4438 D GmsCheckinClient: CheckinRequest{androidId=0, digest=1-929a0dca0eee55513280171a8585da7dcd3700f8, checkin=Checkin{build=Build{fingerprint=Doogee/lineage_T6pro
/T6pro:7.1.2/NJH47F/c48213a34f:userdebug/release-keys, hardware=mt6735, brand=Umidigi, radio=MOLY.LR9.W1444.MD.LWTG.MP.V79.P35, 2017/05/06 15:21, bootloader=unknown, clientId=android-google,
 time=1537560166, device=UMI Diamond, sdkVersion=25, model=UMI Diamond, manufacturer=Umidigi, product=lineage_UMI Diamond, otaInstalled=false}, lastCheckinMs=0, event=[Event{tag=event_log_st
art, timeMs=1570877794151}], stat=[], requestedGroup=[], cellOperator=26207, simOperator=26207, roaming=mobile-notroaming, userNumber=0}, locale=ru_RU, loggingId=<skip>, macAddr
ess=[<skip>], meid=<skip>, accountCookie=[], timeZone=Europe/Moscow, version=3, otaCert=[71Q6Rn2DDZl1zPDVaaeEHItd], serial=008741287512907F, deviceConfiguration=DeviceConfig{t
ouchScreen=3, keyboardType=1, navigation=1, screenLayout=2, hasHardKeyboard=false, hasFiveWayNavigation=false, densityDpi=320, glEsVersion=196609, sharedLibrary=[android.ext.services, androi
d.ext.shared, android.test.runner, com.android.future.usb.accessory, com.android.location.provider, com.android.media.remotedisplay, com.android.mediadrm.signer, com.google.android.maps, com
.google.android.media.effects, com.google.widevine.software.drm, javax.obex, org.apache.http.legacy, org.cyanogenmod.hardware, org.cyanogenmod.platform], availableFeature=[android.hardware.a
udio.low_latency, android.hardware.audio.output, android.hardware.bluetooth, android.hardware.bluetooth_le, android.hardware.camera, android.hardware.camera.any, android.hardware.camera.auto
focus, android.hardware.camera.flash, android.hardware.camera.front, android.hardware.faketouch, android.hardware.location, android.hardware.location.gps, android.hardware.location.network, 
android.hardware.microphone, android.hardware.screen.landscape, android.hardware.screen.portrait, android.hardware.sensor.accelerometer, android.hardware.sensor.compass, android.hardware.sen
sor.gyroscope, android.hardware.sensor.light, android.hardware.sensor.proximity, android.hardware.telephony, android.hardware.telephony.gsm, android.hardware.touchscreen, android.hardware.to
uchscreen.multitouch, android.hardware.touchscreen.multitouch.distinct, android.hardware.touchscreen.multitouch.jazzhand, android.hardware.usb.accessory, android.hardware.usb.host, android.h
ardware.wifi, android.hardware.wifi.direct, android.software.app_widgets, android.software.backup, android.software.connectionservice, android.software.device_admin, android.software.home_sc
reen, android.software.input_methods, android.software.live_wallpaper, android.software.managed_users, android.software.midi, android.software.print, android.software.sip, android.software.s
ip.voip, android.software.voice_recognizers, android.software.webview, com.cyanogenmod.android, com.google.android.feature.GOOGLE_BUILD, com.google.android.feature.GOOGLE_EXPERIENCE, com.vip
er.android, org.cyanogenmod.appsuggest, org.cyanogenmod.audio, org.cyanogenmod.hardware, org.cyanogenmod.livedisplay, org.cyanogenmod.livelockscreen, org.cyanogenmod.partner, org.cyanogenmod
.performance, org.cyanogenmod.profiles, org.cyanogenmod.statusbar, org.cyanogenmod.telephony, org.cyanogenmod.weather, projekt.substratum.theme], nativePlatform=[arm64-v8a, armeabi-v7a, arme
abi], widthPixels=720, heightPixels=1280, locale=[af, af_ZA, am, am_ET, ar, ar_EG, ar_XB, as, ast_ES, az, az_AZ, be, be_BY, bg, bg_BG, bn, bn_BD, bs, bs_BA, ca, ca_ES, cs, cs_CZ, da, da_DK, 
de, de_AT, de_CH, de_DE, de_LI, el, el_GR, en, en_AU, en_CA, en_GB, en_IN, en_NZ, en_SG, en_US, en_XA, en_XC, eo, es, es_ES, es_US, et, et_EE, eu, eu_ES, fa, fa_IR, fi, fi_FI, fil, fil_PH, f
r, fr_BE, fr_CA, fr_CH, fr_FR, gl, gl_ES, gu, gu_IN, he, hi, hi_IN, hr, hr_HR, hu, hu_HU, hy, hy_AM, in, in_ID, is, is_IS, it, it_CH, it_IT, iw, iw_IL, ja, ja_JP, ka, ka_GE, kk, kk_KZ, km, k
m_KH, kn, kn_IN, ko, ko_KR, ku, ky, ky_KG, lb, lo, lo_LA, lt, lt_LT, lv, lv_LV, mk, mk_MK, ml, m
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: 
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: java.io.IOException: invalid hardware identifier: "UMI Diamond" is not a valid device
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at org.microg.gms.checkin.CheckinClient.request(CheckinClient.java:70)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at org.microg.gms.checkin.CheckinManager.checkin(CheckinManager.java:64)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at org.microg.gms.checkin.CheckinService.onHandleIntent(CheckinService.java:59)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at android.os.Handler.dispatchMessage(Handler.java:102)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at android.os.Looper.loop(Looper.java:153)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc:         at android.os.HandlerThread.run(HandlerThread.java:61)
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: Caused by: java.io.IOException: <HTML>
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: <HEAD>
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: <TITLE>invalid hardware identifier: &quot;UMI Diamond&quot; is not a valid device</TITLE>
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: </HEAD>
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: <H1>invalid hardware identifier: &quot;UMI Diamond&quot; is not a valid device</H1>
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: <H2>Error 400</H2>
10-12 13:56:34.667  4419  4438 W GmsCheckinSvc: </BODY>
```

I'm running a firmware built for Doogee T6 Pro and modified for this UMI Diamond. Neither of these listed as [certified](https://support.google.com/googleplay/answer/1727131?hl=en). Also, this model actually has 6753, not 6735 (this is props problem).
I've tried to edit '/system/build.props' directly, changing just the build fingerprint, but it failed to boot.
Still, should I try this direction (maybe with the help of [some Magisk module](https://forum.xda-developers.com/apps/magisk/module-magiskhide-props-config-t3789228)), or I be better finding something newer?
Looks like #90 could be of assistance too.
This all happenned after I noticed some instability of the messages and flashed a new version 0.2.8.17785-mapbox from esteemed Nanolx.

**Comment by mar-v-in** [comment]
I guess the issue is that you changed Build.DEVICE to "UMI Diamond", but Build.DEVICE is supposed to be a lower-case string without any spaces, thus formal requirements are not met, which is probably checked on the Google side during checkin.

**Comment by ettavolt** [comment]
I think it's simpler for me to try microg build with hardcoded values. I'll update this once I get some working values. Maybe I should use some of [original ones](http://specdevice.com/showspec.php?id=a0e8-fee1-ffff-ffffb4e318ab).

**Comment by ettavolt** [comment]
I've hardcoded original DEVICE, MODEL and PRODUCT and it works now.
Better to fix build.props, of course. Who knows what other app will check these.

**Comment by ettavolt** [comment]
Turns out, I could have just edited build.prop directly on system partition after remount,rw. For some reason copying of prepared version through TWRP didn't work (permission, most likely).
