### ISSUE TITLE
de.hafas.android.db (DB Navigator) crashes on startup

### ISSUE THREAD

**Issue by derhagen** [microg/android_packages_apps_GmsCore#972]
The app "DB Navigator" crashes on startup.
LineageOS 16.0
microG Services Core 0.2.9.19420

logcat shows the following errors:
```
cr_SBApiBridge: Failed to init handler: throw with null exception
VideoCapabilities: Unrecognized profile 4 for video/hevc
VideoCapabilities: Unrecognized profile 2130706433 for video/avc
VideoCapabilities: Unrecognized profile 2130706434 for video/avc
SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
GmsMeasureBrokerSvc: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='de.hafas.android.db', extras=Bundle[{}]}
VideoCapabilities: Unsupported profile 4 for video/mp4v-es
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: de.hafas.android.db, PID: 31834
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.hafas.android.db/de.hafas.main.HafasApp}: android.view.InflateException: Binary XML file line #41: Binary XML file line #1: Error inflating class com.google.android.material.navigation.NavigationView
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #41: Binary XML file line #1: Error inflating class com.google.android.material.navigation.NavigationView
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class com.google.android.material.navigation.NavigationView
AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:965)
AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
AndroidRuntime: 	at de.bahn.dbnav.ui.a.c.setContentView(BaseHomeActivity.java:243)
AndroidRuntime: 	at de.bahn.dbnav.ui.a.b.onCreate(BaseActivity.java:159)
AndroidRuntime: 	at de.bahn.dbnav.ui.a.c.onCreate(BaseHomeActivity.java:66)
AndroidRuntime: 	at de.hafas.app.c.onCreate(HafasBaseApp.java:1410)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class ImageView
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class ImageView
AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f0805fc
AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0805fc
AndroidRuntime: 	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:255)
AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:785)
AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:897)
AndroidRuntime: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:189)
AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:172)
AndroidRuntime: 	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
AndroidRuntime: 	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
AndroidRuntime: 	at androidx.appcompat.app.h.a(AppCompatDelegateImpl.java:1266)
AndroidRuntime: 	at androidx.appcompat.app.h.onCreateView(AppCompatDelegateImpl.java:1316)
AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
AndroidRuntime: 	at com.google.android.material.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:207)
AndroidRuntime: 	at com.google.android.material.navigation.NavigationView.inflateHeaderView(NavigationView.java:281)
AndroidRuntime: 	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:193)
AndroidRuntime: 	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:104)
AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:965)
AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
AndroidRuntime: 	at de.bahn.dbnav.ui.a.c.setContentView(BaseHomeActivity.java:243)
AndroidRuntime: 	at de.bahn.dbnav.ui.a.b.onCreate(BaseActivity.java:159)
AndroidRuntime: 	at de.bahn.dbnav.ui.a.c.onCreate(BaseHomeActivity.java:66)
AndroidRuntime: 	at de.hafas.app.c.onCreate(HafasBaseApp.java:1410)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by chris42** [comment]
Try this release [https://microg.org/dl/GmsCore-v0.2.9.19420-5-cfc90b4.apk](https://microg.org/dl/GmsCore-v0.2.9.19420-5-cfc90b4.apk)
I have DB Navigator and it works without problems.
Marvin is working on a new release for the above version.

**Comment by derhagen** [comment]
@chris42 which version of DB Navigator are you using? It broke for me when upgrading from 19.08.p03.00 to 19.10.p03.02

I will try the new version when it's released.

**Comment by drrossum** [comment]
* on Friday, 2019-11-01 03:57 -0700, Hagen <notifications@github.com> wrote:

> @chris42 which version of DB Navigator are you using? It broke for me when upgrading from 19.08.p03.00 to 19.10.p03.02

Why don't you keep using the version that worked?

**Comment by derhagen** [comment]
Well, that works for me for now, but I does not solve the general problem for other users or when the old app might not be supported any more.

**Comment by mar-v-in** [comment]
I don't have any issues with `19.10.p03.02`

**Comment by derhagen** [comment]
@mar-v-in thank you for explaining that. Since  `19.10.p03.02` they ship a split apk. I didn't notice that because I used Yalp to download and install. Manually downloading and installing the apks with SAI Split APK installer resolved the problem.
