### ISSUE TITLE
Unable to select enterprise Google account in apps

### ISSUE THREAD

**Issue by MrDrMcCoy** [microg/android_packages_apps_GmsCore#981]
I am having an issue getting my work Google account to appear in Hangouts Meet and other apps (Hangouts Meet is the one I care most about). 

From the [screenshots here](https://imgur.com/a/aWDUji9), you can see that I have three Google accounts successfully registered. One is a personal Google account, one is a Google apps for domain account attached to one of my personal domains, and the third is an enterprise account from my employer. When launching Hangouts Meet and other apps that want to attach to a Google account, the two personal accounts appear in the list and work, but the enterprise account is not an option.

Are there any known issues with apps using enterprise Google accounts? I'm not sure what information is useful to you in this regard, but am happy to share more details within reason. The only thing I can think of is that they normally request to manage the device and might be blocking something for devices that aren't enrolled, but I'm not sure if that's correct or relevant.

My device is a Sony Xperia XA2 running Lineage MicroG dated 11/21/2019.

**Comment by ale5000-git** [comment]
Hi, it would be nice if you post a logcat.

**Comment by MrDrMcCoy** [comment]
Hey @ale5000-git 

Here's the Logcat: https://pastebin.com/raw/cn3Q0E9c

These are the steps I took:
- Remove enterprise account
- Force stop Hangouts Meet and clear its cache
- Clear logcat
- Launch Hangouts Meet
- Add enterprise account through the dialogue
- When complete, the app stopped (not crashed or hung) showing this: https://imgur.com/a/arLKaah
- Pressed back to exit without making selection
- Reopened Hangouts Meet, and the account selection dialogue continues to omit the enterprise account as before.

The Logcat output didn't look super helpful to my eyes. Did I miss something?

**Comment by ale5000-git** [comment]
I think many things are missing, you logcat is too short, try to:
- clear logcat
- remove and add account 3 times and take logcat of all of this

**Comment by MrDrMcCoy** [comment]
Hey, sorry for the delay. I have a better logcat here: https://pastebin.com/BvGs8Ujg

I'd wager this is the culprit, though you would know better:
```
java.io.IOException: Error=DeviceManagementRequired
	at org.microg.gms.common.HttpFormClient.request(Unknown Source:344)
	at org.microg.gms.auth.AuthRequest.getResponse(Unknown Source:4)
	at org.microg.gms.auth.AuthManager.requestAuth(Unknown Source:150)
	at org.microg.gms.auth.AuthManagerServiceImpl.getToken(Unknown Source:135)
	at org.microg.gms.auth.AuthManagerServiceImpl.getTokenWithAccount(Unknown Source:2)
	at com.google.android.auth.IAuthManagerService$Stub.onTransact(Unknown Source:68)
	at org.microg.gms.auth.AuthManagerServiceImpl.onTransact(Unknown Source:0)
	at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by MrDrMcCoy** [comment]
Hey @ale5000-git, does my guess at `Error=DeviceManagementRequired` seem right to you as being the cause here? If so, how difficult is that to spoof?

**Comment by daocaorenGithub** [comment]
hi@MrDrMcCoy，Did you finally solve this problem?
> Hey @ale5000-git, does my guess at `Error=DeviceManagementRequired` seem right to you as being the cause here? If so, how difficult is that to spoof?

**Comment by MrDrMcCoy** [comment]
@daocaorenGithub I have no idea whether this is still an issue. I have since switched to Graphene OS and am using its sandboxed Google Play instead of MicroG.

**Comment by daocaorenGithub** [comment]
> @daocaorenGithub I have no idea whether this is still an issue. I have since switched to Graphene OS and am using its sandboxed Google Play instead of MicroG.

thanks for your reply
