### ISSUE TITLE
Share Now App does crash (logcat attached) works with stock gapps

### ISSUE THREAD

**Issue by TheB1gG** [microg/android_packages_apps_GmsCore#988]
Hi,
I have the problem that the Share Now App does crash because of some gms.maps stuff, I talked with their devs and they said that it is caused by some Polygon forms which microg is not able to handle.
Here the logcat
`2019-12-10 11:08:34.874 32722-32722/com.car2go E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.car2go, PID: 32722
    java.lang.RuntimeException: Unable to resume activity {com.car2go/com.car2go.activity.MainActivity}: java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3823)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3855)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1)
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at org.microg.gms.maps.mapbox.model.PolygonImpl.setHoles(Unknown Source:302)
        at com.google.android.gms.maps.model.internal.IPolygonDelegate$Stub.onTransact(Unknown Source:256)
        at org.microg.gms.maps.mapbox.model.PolygonImpl.onTransact(Unknown Source:0)
        at android.os.Binder.transact(Binder.java:667)
        at com.google.android.gms.internal.maps.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
        at com.google.android.gms.internal.maps.zzy.setHoles(Unknown Source:8)
        at com.google.android.gms.maps.model.Polygon.setHoles(Unknown Source:2)
        at com.car2go.maps.google.adapter.PolygonAdapter.setHoles(PolygonAdapter.java:1)
        at com.car2go.map.t0.h.b(SpecialZoneLayer.java:24)
        at com.car2go.map.t0.h.a(SpecialZoneLayer.java:10)
        at com.car2go.map.t0.f.a(PolygonLayers.java:7)
        at com.car2go.map.MapView.onResume(MapView.java:6)
        at com.car2go.activity.MainActivity.onResume(MainActivity.java:4)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7300)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3815)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3855) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6724) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
Thanks for help

**Comment by chris42** [comment]
It is probably similar to #869. You'll need to wait until it is implemented.
Alternatively try the vtm version, but not sure if that helps.

**Comment by TheB1gG** [comment]
Thank you for your reply @chris42 I don't know what the vtm version is, can you point me to it so i can try if that works?

**Comment by chris42** [comment]
You find it in the [release section for Gmsore](https://github.com/microg/android_packages_apps_GmsCore/releases). It uses the old vtm implementation for maps. The regular version now uses mapbox and is still missing a few things.

**Comment by TheB1gG** [comment]
@chris42 Really thank you for bringing some insight to me. Sadly the vtm version just displays a white page instead of a map to me. So i will have to wait i guess.

**Comment by fynngodau** [comment]
Hi, thanks for opening this issue. It seems that the problem is no longer present as of today, as the map in the Share Now app you mentioned can be opened without any crashes or major issues.
