### ISSUE TITLE
urbansportsclub crashes

### ISSUE THREAD

**Issue by raidwas** [microg/android_packages_apps_GmsCore#989]
Running the latest release of lineagos (16.0) for microg (0.2.10.19420). When starting the app it first runs for a short while (also rendering the map) and then crashes.
For reference I attach the whole logcat of the app process, since it contains several error messages and I'm not sure which ones are the important ones for you:
`12-11 11:36:40.635 E/FirebaseInstanceId(20846): Token retrieval failed: SERVICE_NOT_AVAILABLE
12-11 11:46:11.990 W/ActivityThread(20846): handleWindowVisibility: no activity for token android.os.BinderProxy@b2dd685
12-11 11:46:12.097 I/FA      (20846): Tag Manager is not found and thus will not be used
12-11 11:46:12.097 D/OpenGLRenderer(20846): Skia GL Pipeline
12-11 11:46:12.130 I/Adreno  (20846): QUALCOMM build                   : 365e321, I294de8bafa
12-11 11:46:12.130 I/Adreno  (20846): Build Date                       : 01/08/19
12-11 11:46:12.130 I/Adreno  (20846): OpenGL ES Shader Compiler Version: EV031.25.03.02
12-11 11:46:12.130 I/Adreno  (20846): Local Branch                     : 
12-11 11:46:12.130 I/Adreno  (20846): Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.5.R1.09.00.00.464.040
12-11 11:46:12.130 I/Adreno  (20846): Remote Branch                    : NONE
12-11 11:46:12.130 I/Adreno  (20846): Reconstruct Branch               : NOTHING
12-11 11:46:12.130 I/Adreno  (20846): Build Config                     : S L 6.0.7 AArch64
12-11 11:46:12.130 D/vndksupport(20846): Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
12-11 11:46:12.134 I/Adreno  (20846): PFP: 0x005ff110, ME: 0x005ff066
12-11 11:46:12.138 I/ConfigStore(20846): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
12-11 11:46:12.139 I/ConfigStore(20846): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
12-11 11:46:12.139 I/OpenGLRenderer(20846): Initialized EGL, version 1.4
12-11 11:46:12.139 D/OpenGLRenderer(20846): Swap behavior 2
12-11 11:46:12.152 D/vndksupport(20846): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
12-11 11:46:12.153 D/vndksupport(20846): Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
12-11 11:46:12.503 W/ActivityThread(20846): handleWindowVisibility: no activity for token android.os.BinderProxy@36ccbb4
12-11 11:46:12.560 D/dagger.android.support(20846): An injector for com.urbansportsclub.main.venues.VenuesFragment was found in com.urbansportsclub.main.MainActivity
12-11 11:46:12.596 I/u       (20846): Making Creator dynamically
12-11 11:46:12.599 W/DynamiteModule(20846): Failed to retrieve remote module version.
12-11 11:46:12.607 I/urbansportsclu(20846): The ClassLoaderContext is a special shared library.
12-11 11:46:12.608 W/urbansportsclu(20846): Insufficient pre-allocated space to mmap vdex.
12-11 11:46:12.612 W/DynamiteModule(20846): IDynamite loader version < 2, falling back to getModuleVersion2
12-11 11:46:12.612 D/GmsDynamiteLoaderImpl(20846): unimplemented Method: getModuleVersion for com.google.android.gms.maps_dynamite
12-11 11:46:12.613 W/DynamiteModule(20846): Local module descriptor class for com.google.android.gms.maps_dynamite not found.
12-11 11:46:12.613 I/DynamiteModule(20846): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:0
12-11 11:46:12.614 E/u       (20846): Failed to load maps module, use legacy
12-11 11:46:12.614 E/u       (20846): com.google.android.gms.dynamite.DynamiteModule$a: No acceptable module found. Local version is 0 and remote version is 0.
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.dynamite.DynamiteModule.a(SourceFile:29)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.i.u.c(Unknown Source:4)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.i.u.b(Unknown Source:5)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.i.u.a(Unknown Source:24)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.d.a(Unknown Source:15)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.g$b.i(Unknown Source:16)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.g$b.a(Unknown Source:2)
12-11 11:46:12.614 E/u       (20846): 	at b.c.a.a.b.a.a(SourceFile:12)
12-11 11:46:12.614 E/u       (20846): 	at b.c.a.a.b.a.a(SourceFile:13)
12-11 11:46:12.614 E/u       (20846): 	at com.google.android.gms.maps.g.onInflate(Unknown Source:44)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.Fragment.onInflate(SourceFile:4)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentManagerImpl.onCreateView(SourceFile:25)
12-11 11:46:12.614 E/u       (20846): 	at co.lokalise.android.sdk.core.LokaliseLayoutInflater$WrapperFactory2.onCreateView(SourceFile:7)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
12-11 11:46:12.614 E/u       (20846): 	at co.lokalise.android.sdk.core.LokaliseLayoutInflater.inflate(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
12-11 11:46:12.614 E/u       (20846): 	at com.urbansportsclub.main.venues.VenuesFragment.onCreateView(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.Fragment.performCreateView(SourceFile:6)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentManagerImpl.ensureInflatedFragmentView(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:53)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:142)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentManagerImpl.addFragment(SourceFile:14)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentManagerImpl.onCreateView(SourceFile:26)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentController.onCreateView(SourceFile:1)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(SourceFile:1)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v4.app.FragmentActivity.onCreateView(SourceFile:1)
12-11 11:46:12.614 E/u       (20846): 	at co.lokalise.android.sdk.core.LokaliseLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
12-11 11:46:12.614 E/u       (20846): 	at co.lokalise.android.sdk.core.LokaliseLayoutInflater.inflate(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
12-11 11:46:12.614 E/u       (20846): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(SourceFile:9)
12-11 11:46:12.614 E/u       (20846): 	at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:1)
12-11 11:46:12.614 E/u       (20846): 	at android.databinding.f.a(SourceFile:9)
12-11 11:46:12.614 E/u       (20846): 	at android.databinding.f.a(SourceFile:8)
12-11 11:46:12.614 E/u       (20846): 	at com.urbansportsclub.main.k6.a(SourceFile:5)
12-11 11:46:12.614 E/u       (20846): 	at com.urbansportsclub.main.MainActivity.c(SourceFile:6)
12-11 11:46:12.614 E/u       (20846): 	at com.urbansportsclub.main.p1.a(Unknown Source:4)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.k0$a.onNext(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.k0$a.onNext(SourceFile:3)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.z1$b.onNext(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.k0$a.onNext(SourceFile:3)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.q2$a.run(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.o1.subscribeActual(SourceFile:3)
12-11 11:46:12.614 E/u       (20846): 	at d.b.l.subscribe(SourceFile:14)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.k0.subscribeActual(SourceFile:1)
12-11 11:46:12.614 E/u       (20846): 	at d.b.l.subscribe(SourceFile:14)
12-11 11:46:12.614 E/u       (20846): 	at d.b.c0.e.c.z1.a(SourceFile:10)
12-11 11:46:12.614 E/u       (20846): 	at d.b.d0.a.a(SourceFile:2)
12-11 11:46:12.614 E/u       (20846): 	at com.urbansportsclub.main.MainActivity.onCreate(SourceFile:245)
12-11 11:46:12.614 E/u       (20846): 	at android.app.Activity.performCreate(Activity.java:7144)
12-11 11:46:12.614 E/u       (20846): 	at android.app.Activity.performCreate(Activity.java:7135)
12-11 11:46:12.614 E/u       (20846): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
12-11 11:46:12.614 E/u       (20846): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
12-11 11:46:12.614 E/u       (20846): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
12-11 11:46:12.614 E/u       (20846): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
12-11 11:46:12.614 E/u       (20846): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
12-11 11:46:12.614 E/u       (20846): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
12-11 11:46:12.614 E/u       (20846): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
12-11 11:46:12.614 E/u       (20846): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-11 11:46:12.614 E/u       (20846): 	at android.os.Looper.loop(Looper.java:193)
12-11 11:46:12.614 E/u       (20846): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-11 11:46:12.614 E/u       (20846): 	at java.lang.reflect.Method.invoke(Native Method)
12-11 11:46:12.614 E/u       (20846): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-11 11:46:12.614 E/u       (20846): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-11 11:46:12.615 D/GmsMapCreator(20846): initV2 12451000
12-11 11:46:12.620 D/dagger.android.support(20846): An injector for com.urbansportsclub.main.venues.VenuesMapFragment was found in com.urbansportsclub.main.venues.VenuesFragment
12-11 11:46:12.633 D/GmsMultiArchLoader(20846): Loading native mapbox-gl
12-11 11:46:12.650 D/GmsMapFragment(20846): onCreateView: lat/lng: (0.0,0.0)
12-11 11:46:12.651 D/GmsMap  (20846): create
12-11 11:46:12.677 D/GmsMap  (20846): Delay callback invocation, as map is not yet initialized
12-11 11:46:12.705 D/dagger.android.support(20846): An injector for com.urbansportsclub.main.venues.VenuesListFragment was found in com.urbansportsclub.main.venues.VenuesFragment
12-11 11:46:12.787 D/dagger.android.support(20846): An injector for com.urbansportsclub.main.courses.CoursesFragment was found in com.urbansportsclub.main.MainActivity
12-11 11:46:12.805 I/AppCompatViewInflater(20846): app:theme is now deprecated. Please move to using android:theme instead.
12-11 11:46:12.870 D/dagger.android.support(20846): An injector for com.urbansportsclub.main.bookings.BookingsFragment was found in com.urbansportsclub.main.MainActivity
12-11 11:46:12.890 I/AppCompatViewInflater(20846): app:theme is now deprecated. Please move to using android:theme instead.
12-11 11:46:13.040 W/System  (20846): ClassLoader referenced unknown path: 
12-11 11:46:13.096 E/RecyclerView(20846): No adapter attached; skipping layout
12-11 11:46:13.155 I/Mbgl-EGLConfigChooser(20846): In emulator: false
12-11 11:46:13.161 I/Mbgl    (20846): {GLThread 461}[General]: GPU Identifier: Adreno (TM) 530
12-11 11:46:13.204 V/Mbgl-ConnectivityReceiver(20846): connected - true
12-11 11:46:13.280 D/GmsMapBitmap(20846): registerMap
12-11 11:46:13.282 D/GmsMap  (20846): Invoking 1 callbacks delayed, as map is initialized
12-11 11:46:13.348 D/GmsMapsUi(20846): unimplemented Method: setMapToolbarEnabled
12-11 11:46:13.349 D/GmsMap  (20846): unimplemented Method: setOnInfoWindowClickListener
12-11 11:46:13.573 D/Mbgl-HttpRequest(20846): [HTTP] Request with response = 304: Not Modified
12-11 11:46:13.670 D/Mbgl-HttpRequest(20846): [HTTP] Request with response = 304: Not Modified
12-11 11:46:13.751 D/Mbgl-HttpRequest(20846): [HTTP] Request with response = 304: Not Modified
12-11 11:46:14.084 D/GmsMap  (20846): unimplemented Method: setMyLocationEnabled
12-11 11:46:14.088 I/Choreographer(20846): Skipped 43 frames!  The application may be doing too much work on its main thread.
12-11 11:46:14.130 I/OpenGLRenderer(20846): Davey! duration=763ms; Flags=1, IntendedVsync=12909638596428, Vsync=12910355263066, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=12910360793406, AnimationStart=12910360833979, PerformTraversalsStart=12910366694240, DrawStart=12910390456899, SyncQueued=12910391784295, SyncStart=12910391856534, IssueDrawCommandsStart=12910392040076, SwapBuffers=12910400762785, FrameCompleted=12910401901900, DequeueBufferDuration=2324000, QueueBufferDuration=492000, 
12-11 11:46:14.161 I/urbansportsclu(20846): Background concurrent copying GC freed 88746(5MB) AllocSpace objects, 33(660KB) LOS objects, 49% free, 15MB/30MB, paused 206us total 161.612ms
12-11 11:46:14.759 W/System.err(20846): d.b.a0.d: length=62; index=62
12-11 11:46:14.759 W/System.err(20846): 	at d.b.c0.b.a$f0.a(SourceFile:2)
12-11 11:46:14.759 W/System.err(20846): 	at d.b.c0.b.a$f0.a(SourceFile:1)
12-11 11:46:14.759 W/System.err(20846): 	at d.b.c0.d.q.onError(SourceFile:3)
12-11 11:46:14.759 W/System.err(20846): 	at d.b.c0.d.q.onNext(SourceFile:5)
12-11 11:46:14.759 W/System.err(20846): 	at d.b.c0.e.c.w1$a.b(SourceFile:8)
12-11 11:46:14.759 W/System.err(20846): 	at d.b.c0.e.c.w1$a.run(SourceFile:3)
12-11 11:46:14.759 W/System.err(20846): 	at d.b.y.b.b$b.run(SourceFile:1)
12-11 11:46:14.759 W/System.err(20846): 	at android.os.Handler.handleCallback(Handler.java:873)
12-11 11:46:14.759 W/System.err(20846): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 11:46:14.759 W/System.err(20846): 	at android.os.Looper.loop(Looper.java:193)
12-11 11:46:14.759 W/System.err(20846): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-11 11:46:14.759 W/System.err(20846): 	at java.lang.reflect.Method.invoke(Native Method)
12-11 11:46:14.759 W/System.err(20846): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-11 11:46:14.759 W/System.err(20846): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-11 11:46:14.760 W/System.err(20846): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=62; index=62
12-11 11:46:14.760 W/System.err(20846): 	at a.b.c.f.f.a(Unknown Source:9)
12-11 11:46:14.760 W/System.err(20846): 	at org.microg.gms.maps.mapbox.GoogleMapImpl.clear(Unknown Source:16)
12-11 11:46:14.760 W/System.err(20846): 	at org.microg.gms.maps.mapbox.GoogleMapImpl.clear(Unknown Source:25)
12-11 11:46:14.760 W/System.err(20846): 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(Unknown Source:817)
12-11 11:46:14.760 W/System.err(20846): 	at org.microg.gms.maps.mapbox.GoogleMapImpl.onTransact(Unknown Source:0)
12-11 11:46:14.760 W/System.err(20846): 	at android.os.Binder.transact(Binder.java:667)
12-11 11:46:14.760 W/System.err(20846): 	at b.c.a.a.c.f.a.b(Unknown Source:7)
12-11 11:46:14.760 W/System.err(20846): 	at com.google.android.gms.maps.i.x.clear(Unknown Source:6)
12-11 11:46:14.760 W/System.err(20846): 	at com.google.android.gms.maps.c.a(Unknown Source:2)
12-11 11:46:14.760 W/System.err(20846): 	at com.urbansportsclub.main.venues.VenuesMapFragment.a(SourceFile:45)
12-11 11:46:14.760 W/System.err(20846): 	at com.urbansportsclub.main.venues.f4.a(Unknown Source:4)
12-11 11:46:14.760 W/System.err(20846): 	at d.b.c0.d.q.onNext(SourceFile:2)
12-11 11:46:14.760 W/System.err(20846): 	... 10 more
12-11 11:46:15.658 I/CrashlyticsCore(20846): Crashlytics report upload complete: 5DF0B1DB0381-0001-516E-24B243132CD2
12-11 11:46:17.088 E/GAv4    (20846): Successfully bound to service but never got onServiceConnected callback
12-11 11:46:17.414 E/AndroidRuntime(20846): FATAL EXCEPTION: main
12-11 11:46:17.414 E/AndroidRuntime(20846): Process: com.urbansportsclub, PID: 20846
12-11 11:46:17.414 E/AndroidRuntime(20846): d.b.a0.d: length=62; index=62
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.b.a$f0.a(SourceFile:2)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.b.a$f0.a(SourceFile:1)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.d.q.onError(SourceFile:3)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.d.q.onNext(SourceFile:5)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.e.c.w1$a.b(SourceFile:8)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.e.c.w1$a.run(SourceFile:3)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.y.b.b$b.run(SourceFile:1)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at android.os.Handler.handleCallback(Handler.java:873)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at android.os.Looper.loop(Looper.java:193)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at java.lang.reflect.Method.invoke(Native Method)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-11 11:46:17.414 E/AndroidRuntime(20846): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=62; index=62
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at a.b.c.f.f.a(Unknown Source:9)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at org.microg.gms.maps.mapbox.GoogleMapImpl.clear(Unknown Source:16)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at org.microg.gms.maps.mapbox.GoogleMapImpl.clear(Unknown Source:25)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$Stub.onTransact(Unknown Source:817)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at org.microg.gms.maps.mapbox.GoogleMapImpl.onTransact(Unknown Source:0)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at android.os.Binder.transact(Binder.java:667)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at b.c.a.a.c.f.a.b(Unknown Source:7)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.google.android.gms.maps.i.x.clear(Unknown Source:6)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.google.android.gms.maps.c.a(Unknown Source:2)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.urbansportsclub.main.venues.VenuesMapFragment.a(SourceFile:45)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at com.urbansportsclub.main.venues.f4.a(Unknown Source:4)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	at d.b.c0.d.q.onNext(SourceFile:2)
12-11 11:46:17.414 E/AndroidRuntime(20846): 	... 10 more
12-11 11:46:17.454 I/Process (20846): Sending signal. PID: 20846 SIG: 9
`

Oh and the app worked before but I'm not sure if I updated it or if I updated the system (so I'm not sure if its a regression of microg or a change in the app)..

**Comment by dynobo** [comment]
Same issue here: Same Version, same crash, seemed to be working fine 2 weeks ago. Happy to help with testing...

**Comment by bisam** [comment]
Not a fix but a workaround: Install the Beta of the urban sports club app. Works fine again

**Comment by dynobo** [comment]
Thx for the hint! I can confirm: Urban Sports Club Beta (available as a seperate App) seems to work stable so far.
