### ISSUE TITLE
Google maps service doesn't working

### ISSUE THREAD

**Issue by ofskymohsen** [microg/android_packages_apps_GmsCore#996]
I installed a simple app using google maps service, But map doesn't display in map fragment, In Logcat this error exists:

```
2019-12-28 14:48:11.751 7699-7699/com.example.mapdemo E/zzbz: Failed to load maps module, use legacy
    com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source:299)
        at com.google.android.gms.maps.internal.zzbz.zzeb(Unknown Source:4)
        at com.google.android.gms.maps.internal.zzbz.zzea(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzbz.zzdz(Unknown Source:23)
        at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source:15)
        at com.google.android.gms.maps.SupportMapFragment$zzb.zzaxs(Unknown Source:16)
        at com.google.android.gms.maps.SupportMapFragment$zzb.zza(Unknown Source:2)
        at com.google.android.gms.dynamic.zza.zza(Unknown Source:48)
        at com.google.android.gms.dynamic.zza.onInflate(Unknown Source:5)
        at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source:44)
        at android.support.v4.app.Fragment.onInflate(Fragment.java:1208)
        at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3697)
        at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
        at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:350)
        at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39)
        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.example.mapdemo.BasicMapDemoActivity.onCreate(BasicMapDemoActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

In microg self-check page, all checks is passed. How can I solve this problem?

**Comment by emv412** [comment]
Same happening to me while using the VTM version. File tilecache.db which is storing downloaded tiles stays empty, most likely because it tries to fetch tiles from opensciencemap.org, which seems to be down. I'm trying to resolve this issue by replacing the server in code, but I don't know how to do it.

You can use the Mapbox version which does not have this issue.

**Comment by ofskymohsen** [comment]
Mapbox map doesn't displayed too. It seems both opensciencemap and mapbox servers are down.

**Comment by herrdeh** [comment]
In my prior setup, google maps worked.
But after a reinstall (maps v 11.149.0101; microG 0.2.27.223616; LineageOS v.21-20241019-nightly-sargo) it opens google maps, but does not display any map.

Maybe due to misconfiguration, hints would be appraciated.

**Comment by herrdeh** [comment]
Happened to find that after installing microG fake store (now called [microG companion](https://microg.org/fdroid/repo/com.android.vending-83700037.apk), map appears at g**gl maps app.

Don't know why - but HTH somebody.
